### ISSUE TITLE
Having problem flashing the eMMC on the CM3

### ISSUE THREAD

**Issue by huyuanrong** [raspberrypi/documentation#1002]
Hi there, quite new in general to this.

I tried to follow the documentation for [Linux ](https://www.raspberrypi.org/documentation/hardware/computemodule/cm-emmc-flashing.md) and also copied the Raspbian Lite image file into the /usbboot folder.

However, after doing all the steps stated in the documentation (I may have done something wrong, not sure), it doesn't boot when I try to plug it into an external display (The USB_SLAVE port is not connected, only POWER_IN and HDMI port). I then tried to flash the module on Windows 10, but the eMMC does not get recognized as a flash drive after running rpiboot, it only gets recognized as "BCM2710 Boot" 
![image](https://user-images.githubusercontent.com/31068480/47157706-82b14200-d31c-11e8-872a-e0689897af89.png)
 
Would appreciate any help with what I could do to either reset or reflash the board, thanks!

EDIT: I'm using the CM3 with the CMIO V3 Board

**Comment by JamesH65** [comment]
I think for a technical question like this your best bet is to try posting on the forums. If it turns out there is an issue with the documentation, please ask for this issue to be reopened.
