### ISSUE TITLE
4G modem + RPI autoconnect failure with network manager

### ISSUE THREAD

**Issue by LAMU11** [raspberrypi/documentation#1014]
Dear fellow RPI users,
I could imagine many other RPI owners also struggle with this issue, and hope for your support for resolving a time consuming issue related to securing automated reconnection of a 4G/3G usb-modem connectivity with RPI Zero (w) in combination with network manager.

Issue:
Initial connection and configuration is seamless. However, upon reboot (e.g. regular scheduled in crontab), the usb-modem+ RPI fails to connect to the internet, though the connection is configured for auto connecting.
After a reboot, the connection is not automatically re-established as configured. Upon manual connecting to the internet with command:

sudo nmcli c up 4G

RPI simply reports reports a connection failure. The modem however flashes a LED, indicating ready for connection.

Question
How to ensure reliable auto connect of modem and 4G internet connectivity upon reboot without having to physically un- and replug modem to RPI?

Hardware used:
1) 4G usb modem (Huawei e3276 dongle, VendorID =12d1 ; productID = 1506)
2) Raspberry Pi Zero W,
3) usb cable, and
3) sim card

Configuration in RPI:

1) Raspbian Stretch with desktop installed, updated and upgraded,

2) latest version of network manager installed,

3) 4G usb modem connected to RPI,

4) a new connection named 4G is created with the following command:
sudo nmcli c add con-name "4G" type gsm ifname "*" apn "internet"

5) Connection is configured for automatical reconnection to the internet with the following command:
sudo nmcli c mod 4G connection.autoconnect yes

6) The RPI+Huawei e3276 immeditely connects and all work fine until a reboot takes place.

Investigated issues so far
A) usb reset with usb_modeswitch command:
Unplugging the modem hardware enables reconnection when re-installing the modem. Consequently a reset of the usb port could maybe do this trick with the command:

sudo usb_modeswitch -R -v 0x12d1 -p 0x1506

Unfortunately not. Resetting the usb port does not re-establish internet connection. After reboot, only unplugging 4G modem will re-establish connection with command:

sudo nmcli c up 4G

B) Modem recognition memory card vs. modem
At all times, RPI recognizes the modem device. When connecting the modem to RPI, a prompt suggests connecting to the modem as memory card. With command:

sudo mmcli -L

lists a Huawei E3276 modem s number 0 or 1 (some times on port cdc-wdm0 and some times on port ttyUSB1). At all times, the modem is registered as vendorID = 12d1 and productID = 1506 (Huawei 3276 in recognized as modem instead of memory card)

C) Reloading connection configuration
Followiung a reboot where the modem does not connect to internet, reload of connection configuration was tried with the command:

sudo nmcli c reload id 4G

..followed by:

sudo nmcli c up 4G

..with no success however.

**Comment by JamesH65** [comment]
This is not a documentation issues so this is completely the wrong place to ask the question. It is better asked on the forum.

https://www.raspberrypi.org/forums
