### ISSUE TITLE
How to get raspberrypi kernel header of version 4.14.71-v7+ ?

### ISSUE THREAD

**Issue by northeusunshine** [raspberrypi/documentation#1026]
I installed kernel header with apt-get, but the header version provided by github is 4.14.79+( my kernel version is 4.14.71-v7+).There was error when insmod insert helloworld driver into kerel.

Qestion: how can I find and install kernel header of 4.14.71-v7+?
Thanks!

**Comment by JamesH65** [comment]
This issue tracker is for problems with the Raspbery Pi documentation repo. For technical support questions please use the forums.

**Comment by lurch** [comment]
...and see if this helps https://github.com/raspberrypi/firmware/issues/63

**Comment by wandercn** [comment]
sudo apt install raspberrypi-kernel raspberrypi-kernel-headers raspberrypi-bootloader
