### ISSUE TITLE
documentation/hardware/raspberrypi/bootmodes/msd.md incorrectly states only Pi 3 can use USB MSD boot

### ISSUE THREAD

**Issue by andrum99** [raspberrypi/documentation#1029]
The official documentation at documentation/msd.md incorrectly states only Pi 3 can boot from a USB mass storage device. I'm guessing it just hasn't been updated since other 2837-based Pi's came out. The fix is to explain that the Pi 2 B Model 1.2, Pi 3 B and Pi 3 B+ can do MSD boot, but the rest of the range cannot.

Also bear in mind that MSD boot is currently blocked on the 2837-based Pi 3 A+, since the OTP bits are set such that it goes into USB host mode.

**Comment by JamesH65** [comment]
Are you referrring to hardware/raspberrypi/bootmodes/msd.md? Because that refers to both the 3 and 3+, the only bit missing is the v1.2 Model 2 I believe?

**Comment by JamesH65** [comment]
Ah, I see you have sentin a PR, I'll move to that.

**Comment by andrum99** [comment]
Sorry - I got the address of the page wrong - github obviously shortened it. The page I'm referring to is documentation/hardware/raspberrypi/bootmodes/msd.md. It is directly linked to from documentation/faqs/README.md - that page has no mention of the fact that only some Pi models support MSD booting.

Yes PR is #1030 

HTH

**Comment by JamesH65** [comment]
Merged so closing.
