### ISSUE TITLE
Missing File???

### ISSUE THREAD

**Issue by AsherGomez** [raspberrypi/documentation#1031]
I can't seem to find the `.brd` files for the compute module.
If they aren't there could y'all upload them?
>Thanks!

**Comment by JamesH65** [comment]
I pressume BRD is an Eagle file? In which case we do not have or provide those.

**Comment by AsherGomez** [comment]
Can they be provided?

**Comment by JamesH65** [comment]
No, we do not publish full schematics or PCB design files.

**Comment by AsherGomez** [comment]
Thanks.
