### ISSUE TITLE
Typo in CM datasheet

### ISSUE THREAD

**Issue by em-er-es** [raspberrypi/documentation#1040]
Release 2, Page 5: "hwardware"

**Comment by lurch** [comment]
"Release 2, Page 5" of what exactly? Could you point to a URL?

**Comment by em-er-es** [comment]
The datasheet for Raspberry Pi Compute Modules, release 2: [rpi_DATA_CM_2p0.pdf](https://www.raspberrypi.org/documentation/hardware/computemodule/datasheets/rpi_DATA_CM_2p0.pdf) from [CM documentation page](https://www.raspberrypi.org/documentation/hardware/computemodule/datasheet.md).

**Comment by JamesH65** [comment]
OK, can see the issue, will need to find out who is responsible for that document - it's not part of the easily fixed docs repo in github.

@jimbojr This is for you I think.

**Comment by lurch** [comment]
I just spotted that Table 4 on Page 13 also says "GPIO28-27 I/O Supply Voltage" which I suspect should be "GPIO28-45 I/O Supply Voltage" :slightly_smiling_face:

**Comment by JamesH65** [comment]
@dp111 Are you now the goto guy for CM (older ones) datasheet mods? Is this error still present?

**Comment by dp111** [comment]
@JamesH65  not me I'm afraid for older datasheets

**Comment by lurch** [comment]
Probably still @jimbojr then.

**Comment by aallan** [comment]
It's probably my job to figure out who has the source text for these and then take ownership.

**Comment by aallan** [comment]
Fixed.
