### ISSUE TITLE
Raspi-config outdated

### ISSUE THREAD

**Issue by Perdex** [raspberrypi/documentation#1041]
The textual explanation of the [raspi-config.md](https://github.com/raspberrypi/documentation/blob/master/configuration/raspi-config.md) has completely different options than the screenshot right above the text. I believe that the options in text are from an old version and the screenshot from a newer version, or vice versa. Both versions should be explained in the text.

**Comment by JamesH65** [comment]
It's the image that is out of date. I will grab a new one.

Thanks.

**Comment by JamesH65** [comment]
Should now be updated in github, along with some minor textual changes to the page. Will be live on website in an hour or so.

Thanks.
