### ISSUE TITLE
Ruby install commands out of date

### ISSUE THREAD

**Issue by mitchpehora** [raspberrypi/documentation#1043]
https://www.raspberrypi.org/documentation/linux/software/ruby.md
https://github.com/raspberrypi/documentation/blob/master/linux/software/ruby.md

The command listed provides the below error. 

![image](https://user-images.githubusercontent.com/19673759/49879322-b928ac00-fdf7-11e8-8721-e9bd8cdb6910.png)

As of Sept 21/18, Ruby can be installed using the following, as per [this link:](https://linuxize.com/post/how-to-install-ruby-on-debian-9/l)
`sudo apt update`
`sudo apt install ruby-full`

**Comment by JamesH65** [comment]
Thanks for the heads up. I didn't even know we had Ruby install instructions...!

**Comment by bennuttall** [comment]
Thanks :+1:

**Comment by mitchpehora** [comment]
You're welcome. I believe this does provide a proper install, however I'm having issues with the gem (rmate) I've downloaded. Likely an issue specific to me, I'm making progress with troubleshooting.
