### ISSUE TITLE
config.txt conditional for 3 A+

### ISSUE THREAD

**Issue by burtyb** [raspberrypi/documentation#1046]
Is there a conditional filter for the 3 A+ hardware as I couldn't spot on in the documentation?

**Comment by JamesH65** [comment]
No, conditional filters apply to the version not the model, so the 3A+ is covered by the [pi3+] flag i.e. same category as the 3B+. So the docs are correct as far as they go. I might add some clarification text inthere somewhere so will leave this open for the moment,.

**Comment by JamesH65** [comment]
See #1047

**Comment by JamesH65** [comment]
Fixed by #1047
