### ISSUE TITLE
Raspberry Pi 3 A+ Schematics

### ISSUE THREAD

**Issue by nullr0ute** [raspberrypi/documentation#1049]
It would be useful to add the reduced schematics, similar to the 3B and the 3B+ to the docs here:

https://www.raspberrypi.org/documentation/hardware/raspberrypi/schematics/README.md

It would also be useful to have the pinouts and connections to the WiFi/BT module as part of that, there's been issues/regressions upstream recently and the way that module is connected to the rest of the SoC would be useful to have as public docs. (an updated 3B/3B+/ZeroW with that details would be nice too)

**Comment by JamesH65** [comment]
@Roger-Thornton Are these in the pipeline?

**Comment by lurch** [comment]
IIRC when the WiFi/BT module was asked about before (or maybe it was something else), somebody pointed to https://github.com/raspberrypi/documentation/blob/master/configuration/pin-configuration.md#sample-device-tree-source-file ?

**Comment by nullr0ute** [comment]
The problem with the device tree is that there's been issues with it in the past, which depending on how the code is (built in vs modular) the issues may appear differently, see the recent upstream WiFi regression. There was a regression that wasn't seen on Raspbian because of the way the it deals with it vs a generic distribution, hence my request of actual schematics as to how things are physically connected up.

**Comment by JamesH65** [comment]
@Roger-Thornton Are we likely to produce 3A+ schematics at some point?

**Comment by JamesH65** [comment]
Uploaded to githuib, should appear here https://www.raspberrypi.org/documentation/hardware/raspberrypi/schematics/README.md soon.
