### ISSUE TITLE
raspbian/updating.md: additional information and third-party solutions

### ISSUE THREAD

**Issue by mirzak** [raspberrypi/documentation#1050]
I have a suggested update of the of the rasbpian [updating.md](https://github.com/raspberrypi/documentation/blob/master/raspbian/updating.md) file and I wanted to get some feedback before trying to send a PR.

I have created a draft which is available [here](https://github.com/mirzak/documentation/commits/updating-raspbian). 

The goal of the update to bring a bit more awareness regarding importance of software updates but also provide some alternatives that are available as open-source projects. Currently I have added mender.io which supports Raspbian out of the box.

I am affiliated with the Mender project, but I also have a history of involvement in software updates on Linux in general and I have written several articles on the topic ([article1](https://mkrak.org/2017/11/18/updating-embedded-linux-devices-part-0/), [article2](https://mkrak.org/2018/01/10/updating-embedded-linux-devices-part1/)) covering several projects.

I am looking forward to get your feedback and would happily work on this if you deem it something of interest to the greater Raspberry Pi community.

**Comment by JamesH65** [comment]
@ghollingworth @LizUpton What's our current policy for changes such as this?

**Comment by ghollingworth** [comment]
I'm happy pulling this in, agree with the warnings over CVE and the mender link will be useful to industrial users of the Pi.

Gordon

**Comment by JamesH65** [comment]
OK, @mirzak can you submit your final draft as a pull request please. I'll review it then pass it on to our copy editing team for final polish, then it can be merged.

**Comment by mirzak** [comment]
Thank you for the feedback, I will continue working on this then and you can expect a pull request mid next week.

**Comment by mirzak** [comment]
@JamesH65, I created the pull-request as agreed. Wondering if you had any time to look at it?

**Comment by JamesH65** [comment]
Thanks for the reminder. Read it, seems OK, now pushed to our copy edit team. Usually takes between one and two weeks to get to the top of their work list, so should go online after that. Thanks!

**Comment by mirzak** [comment]
@JamesH65, any update on the progress of copy edit team?

**Comment by JamesH65** [comment]
I usually batch up and then submit in a chunk. This one has been submitted and is due by end of next week, as the editors are pretty busy at the moment.

**Comment by mirzak** [comment]
Checking if there are any updates?

**Comment by JamesH65** [comment]
We've had a lot of illness in the comms team, and our copy editor has moved from Trading to Foundation so having trouble getting the CE's through at the moment. Hopefully get some movement soon.

**Comment by lurch** [comment]
Closing, as #1062 has been merged.
