### ISSUE TITLE
Need a summary page for the HW and model differences

### ISSUE THREAD

**Issue by JamesH65** [raspberrypi/documentation#106]
I've not found a summary page describing the HW differences over the four models - I've knocked something up here...do you think its OK?

https://github.com/JamesH65/documentation/blob/master/hardware/raspberrypi/models/README.md

James

**Comment by lurch** [comment]
I guess http://www.raspberrypi.org/documentation/hardware/raspberrypi/models/specs.md means this issue can be closed?
