### ISSUE TITLE
access-point.md  patch

### ISSUE THREAD

**Issue by malessandrini** [raspberrypi/documentation#1078]
Hi,
in "configuration/wireless/access-point.md", when setting dhcpcd.conf for static ip address on wlan0, it does not work for me as is, it seems it needs at least the following:
```
interface wlan0
static ip_address=192.168.4.1/24
static routers=192.168.4.1
static domain_name_servers=192.168.4.1
nohook wpa_supplicant
```

Thanks
Michele Alessandrini

**Comment by JamesH65** [comment]
I suspect that whole document need revamping for the latest Raspbian. I think there might be some PR's waiting to go through on this page, but will leave this open as it is something that needs looking at.  Thanks for the report.

**Comment by XECDesign** [comment]
Could you please provide a bit more information? In what way does it not work?

After hostapd starts, what's the output of
```
ip addr show wlan0
ip route
sudo journalctl -u dhcpcd
```

**Comment by malessandrini** [comment]
It did not work because wlan0 was not assigned the given IP address, so all the remaining tools depending on it did not work. Currently I don't have a Raspberry 3 any more, so I can't connect to it via ethernet leaving wlan0 unconfigured. Anyway it was a fresh installation or Raspbian Strecth Lite.

**Comment by XECDesign** [comment]
While updating the docs, I tried the example as is and the IP was set as expected. Without exact output, it's hard to diagnose what went wrong in your case.

**Comment by malessandrini** [comment]
I'm sorry, that's strange, I'll try to test it again as soon as possible. Thanks for now.

**Comment by XECDesign** [comment]
If you do, please use this version https://github.com/XECDesign/documentation/blob/wifi-ap-update/configuration/wireless/access-point.md (sent as a PR)

**Comment by JamesH65** [comment]
I believe the changes to the page over the last year  will have taken this in to account.
