### ISSUE TITLE
Multilingual documentation(not programming language)

### ISSUE THREAD

**Issue by danyang685** [raspberrypi/documentation#1082]
Is there any plan to build multilingual documentation for other language speakers? like Chinese, Japanese, Korean, Russian and so on? I found it hard for me to read English fast enough but the machine translation can not satisfy me.

**Comment by bennuttall** [comment]
We have a [translation programme](rpf.io/translate), but it currently only covers our learning resources. I've let the translation manager aware of this issue.

**Comment by JamesH65** [comment]
No plans for Multilanguage support for the documentation at this stage.
