### ISSUE TITLE
Add missing sdtv_mode for 240p output to documentation

### ISSUE THREAD

**Issue by jeroenjacobs1205** [raspberrypi/documentation#1091]
Hi,

The following values are also accepted in "sdtv_mode", but they are not listed on the documentation page at https://www.raspberrypi.org/documentation/configuration/config-txt/video.md.

sdtv_mode=16 (for progressive scan NTSC)
sdtv_mode=18 (for progressive scan PAL)

Those modes are documented in this issue: https://github.com/raspberrypi/firmware/issues/683

**Comment by lurch** [comment]
That issue also links to https://github.com/raspberrypi/firmware/issues/811 which seems to add additional sdtv_mode values as well?
