### ISSUE TITLE
Description of switching to a different username is not complete

### ISSUE THREAD

**Issue by KimSJ** [raspberrypi/documentation#1101]
Your description of how to create a usable username other than pi (in  documentation/configuration/security.md) is not complete. The new user will have a very limited set of groups! To rectify that, the following bash command works well:

```
for i in `grep -E "(:|,)pi(:|,|$)" /etc/group|cut -f1 -d:` ; do
	sudo addgroup <new_username> $i
done
```
Obviously this should be run before you delete the pi user!

**Comment by JamesH65** [comment]
Interesting idea. WIll talk about in Monday in the office.

**Comment by lurch** [comment]
Related to #1092 ?

**Comment by lurch** [comment]
@KimSJ #1092 has now been merged - does it adequately address your concerns?

**Comment by JamesH65** [comment]
I believe this has been fixed by the merge mentioned,
