### ISSUE TITLE
Missing documentation for Revision a22083

### ISSUE THREAD

**Issue by matteobogo** [raspberrypi/documentation#1108]
Hello,
Recently i have received a new Raspberry Pi 3 Model B v1.3 with Revision Code: a22083.
I didn't find any info about it in the official documentation.
![WP_20190322_19_04_39_Rich](https://user-images.githubusercontent.com/8475090/54843909-cfd37e80-4cd5-11e9-8045-f77ac261116f.jpg)
![WP_20190322_19_12_56_Rich](https://user-images.githubusercontent.com/8475090/54845289-4a51cd80-4cd9-11e9-94d4-6a2ddfa9698c.jpg)
![WP_20190322_19_10_36_Rich (2)](https://user-images.githubusercontent.com/8475090/54844249-b54dd500-4cd6-11e9-93b2-eed53d5a30bc.jpg)

**Comment by bennuttall** [comment]
Thanks, it's a Pi 3B manufactured by Embest. I've added it to the table: https://github.com/raspberrypi/documentation/blob/master/hardware/raspberrypi/revision-codes/README.md
