### ISSUE TITLE
Missing documentation for Revision 900061 

### ISSUE THREAD

**Issue by matteobogo** [raspberrypi/documentation#1110]
Hello,
I have another suggestion for updating the documentation of revision codes. :)

Raspberry Pi Compute Module RPI-CM v1.1 with Revision: 900061 "Made in the UK".
![WP_20190315_21_56_25_Rich](https://user-images.githubusercontent.com/8475090/54916481-e9eda680-4ef9-11e9-830d-bdf805c3a972.jpg)
![WP_20190325_12_23_00_Rich (2)](https://user-images.githubusercontent.com/8475090/54916556-11dd0a00-4efa-11e9-87fd-bd1b2c3e82a5.jpg)
![WP_20190325_12_23_00_Rich (3)](https://user-images.githubusercontent.com/8475090/54916562-13a6cd80-4efa-11e9-928c-c7cc72376292.jpg)

Hope it helps.
Cheers

**Comment by bennuttall** [comment]
Thanks, added: https://github.com/raspberrypi/documentation/blob/master/hardware/raspberrypi/revision-codes/README.md
