### ISSUE TITLE
Running Retro Pie and Emulation Station

### ISSUE THREAD

**Issue by crystalmmeridia** [raspberrypi/documentation#1130]
Running with Raspberry Pi 3B. In Emulation Station I went to the Retro Pie options to download themes for the background and I hit the download all by accident not knowing it would max out the memory. So first thing I did was uninstall those themes. First thing I noticed was all the details in the meta data for Snes and sega sg 1000 disappeared. In command line it said it couldn’t parse the xml files for those game sets. 

Second thing. I stupidly typed reset in command line. For a couple power cycling on and off, the pi couldn’t save my basic settings like theme and screensaver etc. then Snes and sg-1000 and the Retro pie options completely disappeared. They were replaced by Turbograffix 16, Atari Lynx and Kodi. Which I haven’t even seen before nor has it been advertised for before. So I really want to erase my whole Raspberry Pi and I can’t figure out how. If someone can help me that would save my day. I still have my Retro Pie micro as so I can start from scratch. Oh please and thank you 🙏🏻

**Comment by JamesH65** [comment]
This is the Pi documentation repo for reporting problems with the documentation. You really need to post your question on the Raspberry Pi forums, it won't get answered here.
