### ISSUE TITLE
TFTP folder update due to package bug(s)

### ISSUE THREAD

**Issue by Kasperx** [raspberrypi/documentation#1135]
Hi

I would like to correct this doc for usage of the tftp-package du to a known bug. Unfortunately I didn't save the link to that discription, but the solution is pretty easy :)
The tftp-package only reads the folder "/srv/tftp" with access rights for user "nobody" and groud "nogroup", maybe also someone else :)
So one solution might be to create a symlink from "/srv/tftp" to your folder "/tftpboot" (with similar rights) or to use the other folder from beginning on.

Regards
Kasperx

**Comment by Kasperx** [comment]
Sry, forgot.
You can see the client (tftp-client) wanting to read files from the folder "/srv/tftp" in the debug output, discriped in your docs. It doesn't care on the edited config-file.

**Comment by JamesH65** [comment]
Can you provide a link to the page you believe is incorrect?

**Comment by Kasperx** [comment]
Yes -> [docu](https://github.com/raspberrypi/documentation/blob/master/hardware/raspberrypi/bootmodes/net_tutorial.md)
![image](https://user-images.githubusercontent.com/10506030/57519463-a02b1500-731b-11e9-872b-a88de7941f37.png)

**Comment by JamesH65** [comment]
Thanks for that, but I'm a bit confused as to how this could ever have worked given the apparent bug. Do you have a link to the tftp-package bug report?

**Comment by lurch** [comment]
Perhaps @Kasperx is using a different TFTP server than the one that `net_tutorial.md` was originally written for? :man_shrugging:

**Comment by Kasperx** [comment]
@lurch I installed a tftp server with `sudo apt install tftpd` with verion=0.17-18 on raspbian 9.
@JamesH65 I don't know if the process discriped in docu ever worked  :( In my test it didn't, only with symbolic link or other folder.
Perhapt just the link from website to docu is wrong ?
[Website](https://www.raspberrypi.org/documentation/hardware/raspberrypi/bootmodes/net_tutorial.md)

**Comment by Kasperx** [comment]
I came to that solution by visiting this [post](https://thwack.solarwinds.com/thread/16628).
Somewhere here...
![image](https://user-images.githubusercontent.com/10506030/57609287-d90ef800-756e-11e9-9044-8a755b30a709.png)

And of course the log file with `tail -f /var/log/daemon.lo` (shown in docu) shows nice terminal message with asked folder, where the created folder is NOT the one asked :( No matter what the config file says... (Screenshot coming later)
