### ISSUE TITLE
FAQ Tables on mobile horizontal scrolling

### ISSUE THREAD

**Issue by bepvte** [raspberrypi/documentation#1140]
![Screenshot_20190511-121003_Firefox Beta](https://user-images.githubusercontent.com/8226605/57572265-50c21300-7407-11e9-86db-b4c36b97cda5.png)

**Comment by JamesH65** [comment]
Although this does look odd, you can still scroll sideways to see the table, so flagging this as a won't fix as its works well enough, and the likelihood of it getting any sort of attention from the webteam is minimal.
