### ISSUE TITLE
Missing documentation of the Clock Manager

### ISSUE THREAD

**Issue by ptesarik** [raspberrypi/documentation#1146]
The whole register block at VPU address 0x7e101000 is undocumented, except a few registers related to General Purpose Clock control. Some information can be inferred from the Linux clock driver, but there is no proper documentation of the hardware registers and their use. A diagram of the available clock sources (and possible hierarchies) would be also very helpful.

**Comment by ghollingworth** [comment]
As before, we aided Eric Anholt in developing a driver but cannot provide you with Broadcom's documentation.
