### ISSUE TITLE
Missing documentation of the hardware RNG

### ISSUE THREAD

**Issue by ptesarik** [raspberrypi/documentation#1148]
The hardware random number generator (registers at VPU address 0x7e104000) is not documented. In particular, it's not clear what feeds the entropy pool in this RNG, or if it is some sort of pseudo-random generator, why it needs a warm-up and if the values read from the data registers can be considered cryptographically strong.

**Comment by ghollingworth** [comment]
Cannot provide

**Comment by ptesarik** [comment]
Hm… Since hardware RNG was not mentioned by Broadcom on a product brief for any of their embedded multimedia applications processor, for any serious applications, we should assume there is no hardware RNG on the chip.

Thanks!

**Comment by JamesH65** [comment]
Assumption is wrong, there is a hardware RNG on the chip.

**Comment by ghollingworth** [comment]
Yes, it uses quantum tunnelling through a band gap

**Comment by ptesarik** [comment]
> Yes, it uses quantum tunnelling through a band gap

Then it shouldn't be trusted, because attackers will simply inject quantum-coupled particles into it, controlling them trough the other end of the pairs.

You made my day. :laughing:

**Comment by ptesarik** [comment]
Forgot to say. Thank you for the answers. This has helped clear up some doubts.
