### ISSUE TITLE
Network booted system lost USB functionality

### ISSUE THREAD

**Issue by chunky** [raspberrypi/documentation#1157]
Recently, I lost USB functionality on a network-booted pi. Eventually I traced the issue to a filesystem change in /boot during a normal package upgrade, when /boot hadn't been mounted. So, the files in /boot weren't in sync with the rest of the system.

I have put in a pull request suggesting mounting the TFTP boot partition back into the live system:
https://github.com/raspberrypi/documentation/pull/1156

**Comment by JamesH65** [comment]
Closing, PR is merged.
