### ISSUE TITLE
Raspberry Pi Camera Module - advice to use rpi-update needs caution adding? https://www.raspberrypi.org/documentation/raspbian/applications/camera.md

### ISSUE THREAD

**Issue by DeeJay** [raspberrypi/documentation#1158]
> "If you've checked all the above issues and the Camera Module is still not working, you may need to upgrade the firmware on the Raspberry Pi. Use the following command to get the very latest (but experimental) firmware:
> 
> sudo rpi-update"

Perhaps needs a 'health warning' that this experimental firmware might render the installed OS unstable? Discussion in this forum thread suggests that rpi-update is deprecated in almost all circumstances - [https://www.raspberrypi.org/forums/viewtopic.php?f=28&t=241977](url)

**Comment by JamesH65** [comment]
I've just taken a look at this, I'm not sure. It does say experimental, and it's a last resort IIF you camera isn't working.

**Comment by JamesH65** [comment]
OK, I decided just to remove that and subsequent paragraph.
