### ISSUE TITLE
Raspbian 'Updating' doc potentially misleading?

### ISSUE THREAD

**Issue by DeeJay** [raspberrypi/documentation#1190]
Re: [https://www.raspberrypi.org/documentation/raspbian/updating.md](https://www.raspberrypi.org/documentation/raspbian/updating.md)

>  Generally speaking, doing this regularly will keep your installation up to date, in that it will be equivalent to the latest released image available from raspberrypi.org/downloads.

Could be interpreted as meaning that a Stretch Installation can be converted to Buster just by using update+upgrade. (Which is not the case.)

**Comment by JamesH65** [comment]
I've updated the page.
