### ISSUE TITLE
Kernel building instructions are not updated to rpi4

### ISSUE THREAD

**Issue by SirDifferential** [raspberrypi/documentation#1193]
Currently the kernel building instructions aren't up to date with the new raspberry pi 4. The page in question is this: https://github.com/raspberrypi/documentation/blob/master/linux/kernel/building.md

The changes that are required are:

* `KERNEL=kernel` must be changed to `KERNEL=kernel7l` on rpi 4
* `bcm2709_defconfig` must be changed to `bcm2711_defconfig` on rpi 4

I haven't looked at the crosscompiling section.

**Comment by JamesH65** [comment]
This has been updated.
