### ISSUE TITLE
Unzip link broken

### ISSUE THREAD

**Issue by rafaelalvespereira** [raspberrypi/documentation#1198]
Hi, the link to UnZip in 
documentation/installation/installing-images/README.md  is broken.

**Comment by lurch** [comment]
@JamesH65 I noticed this a while ago, but forgot to say anything at the time. Looks like http://www.info-zip.org/ is now non-functional, and nobody has ever bothered to fix it :confused: 
Looks like either http://infozip.sourceforge.net/UnZip.html or https://linux.die.net/man/1/unzip are valid replacements though, depending on what is desired.

**Comment by JamesH65** [comment]
Fixed. Used the die.net link.
