### ISSUE TITLE
Add troubleshooting for slow mouse updates

### ISSUE THREAD

**Issue by asb** [raspberrypi/documentation#121]
A small number of users might experience a slow/laggy mouse with more recent kernel updates (mostly wireless mice have the issue). See https://github.com/raspberrypi/linux/issues/642 for a full discussion of the problem. The fix is to add usbhid.mousepoll=0 to /boot/cmdline.txt, though I expect to add an option to do this for you to raspi-config's advanced option section shortly.

**Comment by ebenupton** [comment]
@asb - did you add this option? @popcornmix - should we remove this for ARMv7

**Comment by JamesH65** [comment]
@popcornmix @pelwell I remember this from ages ago (think I came up with the mousepoll thing!) and apparently this is still there according to the linked issue. Should we add this to the documentation?

**Comment by pelwell** [comment]
Of course - make it so.

**Comment by JamesH65** [comment]
I've submitted a PR to add a page describing the kernel command line, #523, which covers this. Once that PR is accepted I will close this.

**Comment by JamesH65** [comment]
#523 now merged.
