### ISSUE TITLE
Change instances of stretch to buster in installation/update docs

### ISSUE THREAD

**Issue by rossbar** [raspberrypi/documentation#1215]
There are two files in the installation instructions that refer to images of Debian stretch:

 - [installation/installing-images/mac.md](https://github.com/raspberrypi/documentation/blob/master/installation/installing-images/mac.md)
 - [installation/installing-images/linux.md](https://github.com/raspberrypi/documentation/blob/master/installation/installing-images/linux.md)

According to the Raspbian downloads page as well as the [Raspbian version history](https://en.wikipedia.org/wiki/Raspbian), the most current images are Debian Buster rather than Stretch. I suggest changing the instances of stretch to buster in the above-listed files (I have done so in a fork and am happy to PR the changes).

Additionally, there is a section in `raspbian/updating.md` that specifically addresses updating from Jessie to Stretch. Just wanted to call your attention to that in case you wanted to update the section or add an additional one for Stretch -> Buster.

**Comment by lurch** [comment]
See #1221
