### ISSUE TITLE
Etcher requires zenity on Linux 

### ISSUE THREAD

**Issue by alexlemaire** [raspberrypi/documentation#1225]
## Issue :boom: 

Was unable to flash the latest [Raspbian Buster Lite image](https://www.raspberrypi.org/downloads/raspbian/) on my SD card with [balenaEtcher](https://www.balena.io/etcher/).

_Following the installation documentation [here](https://www.raspberrypi.org/documentation/installation/installing-images/README.md)._

## Steps to reproduce :computer: 

1. Download and extract balenaEtcher appImage on a Linux machine
2. Download the latest Raspbian Buster Lite image from the official website
3. Start balenaEtcher
4. Select the Raspbian Buster Lite image archive and your SD device and try to "Flash!"
5. Enter your password in the SUDO prompt

This should then throw an error where something unexpected seem to happen when trying to flash.

## Fix :wrench: 

After some Googling ([see here](https://linuxhint.com/install_etcher_linux/)), I realized that the system needs to have _zenity_ installed to be able to flash an SD card via balenaEtcher.

## Update request :question: 

Would be nice to **include a note about that for Linux users** to avoid troubles for them.

I would gladly fork and open a pull request to handle this if this issue is approved! :+1:

**Comment by JamesH65** [comment]
Feel free to provide a pull request. I would suggest saying that zenity _might_ need to be installed if not present

**Comment by lurch** [comment]
I think this might count as an Etcher problem, rather than a Raspberry Pi documentation issue? Try creating an issue [here](https://github.com/balena-io/etcher/issues).

**Comment by alexlemaire** [comment]
Alright, I created a pull request here with the update but will also open an issue on Etcher side so they can get that fixed.
In the meantime I think it may be worth having the note inside of Raspberry Pi documentation just to avoid problems for users. This can be removed as soon as Etcher team found a workaround.

**Comment by JamesH65** [comment]
Change merged. #1230
