### ISSUE TITLE
Problem with URLs ending with brackets

### ISSUE THREAD

**Issue by lurch** [raspberrypi/documentation#1228]
As I mentioned [here](https://github.com/raspberrypi/documentation/pull/1186#issuecomment-512287987) and [here](https://github.com/raspberrypi/documentation/pull/1208#issuecomment-513811950) there's a problem with https://www.raspberrypi.org/documentation/ displaying URLs that end with a `)` character.
Opening an issue so that this doesn't get forgotten about...

**Comment by andrum99** [comment]
According to https://en.wikipedia.org/wiki/Percent-encoding, parentheses are reserved characters in RFC3986 - Uniform Resource Identifier (URI): Generic Syntax. This means they are meant to be escaped. The mapping is:

( -> %28
) -> %29

**Comment by lurch** [comment]
Fixed, see #1278

Thanks @andrum99 :+1:
