### ISSUE TITLE
Access Point IP range issue

### ISSUE THREAD

**Issue by mdmobashir** [raspberrypi/documentation#1229]
So I followed the instruction here "[Setting up a Raspberry Pi as an access point in a standalone network (NAT)](https://www.raspberrypi.org/documentation/configuration/wireless/access-point.md)" and managed to setup RPI as an access point and even share the internet from the eth0 interface. 

I have also setup a static IP for wlan0 (say, 192.168.0.10). 

I wanted to have a range of IP that all the clients connected to the RPI should receive (192.168.0.11 to 192.168.0.30). However, when I connect to over WiFi to RPI, I'm receiving an IP 192.168.2.106. 

Any help on how to fix that issue of getting IP assigned from proper IP range?

I have added this to `/etc/dhcpcd.conf `
```
interface wlan0
static ip_address=192.168.0.10/24
nohook wpa_supplicant
denyinterfaces eth0
```
Also, I have added this to `/etc/dnsmasq.conf`
```
interface=wlan0
dhcp-range=192.168.0.11,192.168.0.30,255.255.255.0,24h
```

**Comment by JamesH65** [comment]
This is not a docs repo problem, and should be asked on the forums.  www.raspberrypi.org/forums
