### ISSUE TITLE
Multi-level lists in docs subtly broken on raspberrypi.org

### ISSUE THREAD

**Issue by andrum99** [raspberrypi/documentation#1251]
(This is one I discovered a while ago but I'm just getting round to adding it as a separate bug).

Documentation pages which contain multi-level lists are currently subtly broken on the official Pi website (raspberrypi.org). The breakage applies only to list items where the indent level is a multiple of 3. In other words indent levels 3, 6, 9 etc are affected. For those indent levels, any list item will be rendered as if it belongs to one below the actual indent level. So level 3 list items are rendered as level 2 list items, level 6 list items as level 5 items, etc.

Compare and contrast the following pages:

https://www.raspberrypi.org/documentation/hardware/raspberrypi/bootmodes/host.md
https://github.com/raspberrypi/documentation/blob/master/hardware/raspberrypi/bootmodes/host.md

Rendered on github, the page shows the correct layout of multi-level lists. On raspberrypi.org it is broken as described above.

Interestingly, github.com seems to know about the possible breakage: if you go into edit mode it  renders 3rd, 6th etc level list items in red - see https://github.com/raspberrypi/documentation/edit/master/hardware/raspberrypi/bootmodes/host.md

**Comment by andrum99** [comment]
Also affected by bug: https://www.raspberrypi.org/documentation/hardware/raspberrypi/bootmodes/net.md

**Comment by andrum99** [comment]
Note that there is nothing wrong with the markdown on these pages, the bug is in whatever is converting the markdown to HTML.

**Comment by andrum99** [comment]
And another one: https://www.raspberrypi.org/documentation/hardware/raspberrypi/bootmodes/bootflow.md

**Comment by lurch** [comment]
@andrum99 I wonder if this might be related to https://github.com/Python-Markdown/markdown/issues/3 ?

**Comment by andrum99** [comment]
> @andrum99 I wonder if this might be related to [Python-Markdown/markdown#3](https://github.com/Python-Markdown/markdown/issues/3) ?

I can't tell from that bug what is actually going from in that case. I've modified one of the wonky pages to apply their suggested fix - make all indents in the markdown 4 spaces instead of 2. Can you possibly have a look @lurch , and it it looks OK push it to master? We'll only know once it appears on raspberrypi.org if it has worked or not.

**Comment by andrum99** [comment]
I suspect it won't help, but that's only based on the fact that github.com's editor still shows the defective lines in red.

**Comment by andrum99** [comment]
OK, that was a useful guess as it was a potentially easy fix to the broken pages. This will need some investigation. How do the pages in github find their way onto the website?

**Comment by lurch** [comment]
@andrum99 https://www.raspberrypi.org/documentation/hardware/raspberrypi/bootmodes/host.md appears to have updated - does it look correct now?

**Comment by andrum99** [comment]
> @andrum99 https://www.raspberrypi.org/documentation/hardware/raspberrypi/bootmodes/host.md appears to have updated - does it look correct now?

Yes, it is now correctly rendered 😁

**Comment by lurch** [comment]
Great! Feel free to submit a PR which applies the same fix to any other indented-lists you find, and then I can close this issue.

**Comment by lurch** [comment]
@andrum99 Have all the relevant multi-level lists been fixed now? If so, can this issue be closed?
