### ISSUE TITLE
Raspberry pi is too slow over vnc

### ISSUE THREAD

**Issue by iskanderrr** [raspberrypi/documentation#1255]
I have a raspberry pi 3 b+ running lastest rasbian with a 32g SD card and its very laggy and slow when I'm using it over vnc ( no external devices connect to it) why is that ? I already checked the temperature it's not over heating (40°) and I powering it from a 2.2A phone charger

**Comment by lurch** [comment]
This sounds like a question for the https://www.raspberrypi.org/forums/ and not for the documentation repo.
