### ISSUE TITLE
Raspberry pi zero W, idle CPU usage when overclocking

### ISSUE THREAD

**Issue by ProDigit** [raspberrypi/documentation#1257]
When overclocking the pi zero W, to settings below, idle CPU usage increases for no apparent reason.

It first appeared on one device, so I bought another one, and it also happened on the second one.

I then reinstalled raspbian from scratch, to see if this issue wasn't a hardware issue, which it wasn't, as
Upon reinstallation, idke CPU usage was back to 0%.

Once overclocked to the below settings, and rebooted, idle CPU was still at 0%.

It's once I surpass these values, I get to see the idle CPU raise. There's no way back, except for reinstallation of Raspbian.

The idle CPU usage error seems to only affect the zero W, after doing a full upgrade. On the stock raspbian image install, this bug is not present.

arm_freq=1100
gpu_freq=525
core_freq=500
sdram_freq=550
over_voltage=2
sdram_over_voltage=2

**Comment by lurch** [comment]
**If** this is a problem, you probably want to report it on https://github.com/raspberrypi/linux as this isn't a documentation issue. And please be sure to include more specific details than you have above as "I get to see the idle CPU raise" doesn't provide much info.
