### ISSUE TITLE
Raspberry Pi 4B Mechanical Drawings DXF file does not have mounting holes

### ISSUE THREAD

**Issue by mvadu** [raspberrypi/documentation#1262]
The [PDF version of the Raspberry Pi 4B Mechanical Drawings](https://www.raspberrypi.org/documentation/hardware/raspberrypi/mechanical/rpi_MECH_4b_4p0.pdf) does show the mounting holes. But [DXF version](https://www.raspberrypi.org/documentation/hardware/raspberrypi/mechanical/rpi_MECH_4b_4p0.dxf) not show the mounting holes. Without the mounting holes in DXF usability or helpfulness of the drawings is severely degraded for the purposes of designing cases.

**Comment by lurch** [comment]
ping @jimbojr

**Comment by JamesH65** [comment]
This is fixed. See https://www.raspberrypi.org/documentation/hardware/raspberrypi/mechanical/README.md
