### ISSUE TITLE
problem with touch screen

### ISSUE THREAD

**Issue by topliftarm** [raspberrypi/documentation#1263]
i am using 7 inch lcd with cap. touch (waveshare) with raspberry pi zero w. my os is arch.
touch is working and in console i see character in cat /dev/input/event0. problem is after rebooting touch does not work and after that command no message display! when shutdown and again power on, touch is working!
plz help me!

**Comment by lurch** [comment]
This isn't the right place for that sort of question. Please ask on the [forums](https://www.raspberrypi.org/forums/).
