### ISSUE TITLE
what's the status of 64bit kernel for raspberrypi 4?

### ISSUE THREAD

**Issue by jongwu** [raspberrypi/documentation#1265]
I build a 64-bits kernel for raspberrypi 4 base on this tree, but failed to boot. as there is no guide for build this, I have no knowledge about 64 bits status of this kernel.

@asb @JamesHarrison @Nightblade @ifthenelse

**Comment by JamesH65** [comment]
The is no official 64bit kernel for the Raspberry Pi. It is being worked on by third parties. Check out the forum for more information.
