### ISSUE TITLE
Small typo on readme file

### ISSUE THREAD

**Issue by thierrypin** [raspberrypi/documentation#1279]
Hello, this documentation has been very helpful to me, and I'd like to report a small typo on a Readme file for correction.

The file is:
https://github.com/raspberrypi/documentation/blob/master/usage/python/README.md

The typo is:
Almost on the end of the file: "Raspbian is pre-configired to use piwheels for pip."
"configired" -> "configured".

I'm sorry if an issue is not the right way of doing this.

**Comment by lurch** [comment]
Thanks, I've created a PR.
