### ISSUE TITLE
Update webcam.md

### ISSUE THREAD

**Issue by pickfire** [raspberrypi/documentation#128]
Add capturing video in [webcam](https://github.com/raspberrypi/documentation/tree/master/usage/webcams).

**Comment by ebenupton** [comment]
PR please.

**Comment by pickfire** [comment]
I still doesn't know how to do it.

**Comment by bennuttall** [comment]
I like the idea. Why don't you ask on the [forums](http://www.raspberrypi.org/forums/) and see if anyone's done it? Then open a PR if you feel inclined or post links to the solution in this comment thread.

**Comment by phiney0711** [comment]
i think I may have a solution for USB webcam for Pi that has H.264 encode on the camera chip. As long as there's a USB host video class driver for Raspbian it should work well.  Let me check tomorrow and advise.

**Comment by JamesH65** [comment]
This has been dormant for nearly two years, so closing. If someone feels inclined to update the page and send in a PR, please go ahead.

**Comment by jgwinner** [comment]
Darn, with the Pi 4, was hoping someone had updated this!

Time for some investigations ...

**Comment by JamesH65** [comment]
Feel free to put in a PR.
