### ISSUE TITLE
ambiguity in Boot sequence page

### ISSUE THREAD

**Issue by RichMorin** [raspberrypi/documentation#1293]
The [Boot sequence](https://www.raspberrypi.org/documentation/hardware/raspberrypi/bootmodes/bootflow.md) page says:

> The following boot sequence applies to the BCM2837-based models of Raspberry Pi only.
On all other models, the Pi will try SD card boot, followed by USB device mode boot.

The "USB device boot mode" page applies to models prior to the RasPi 3. So, it appears that this restriction is meant to apply to these models. However, it isn't clear whether the content of page is accurate with regard to the 3B+, which uses the BCM2837B0. Given that the following text discusses the setting of OTP bits (which isn't needed on the 3B+), it appears that it may not be.

This page should be edited to clarify whether it applies to the BCM2837B0. If not, the BCM2837B0 boot sequence needs to be documented.

In addition, it would be useful to document which USB device will be booted from, if more than one is plugged in. Based on [this post](https://www.raspberrypi.org/forums/viewtopic.php?t=219462), I gather that this is timing dependent...

**Comment by lurch** [comment]
Does #1252 help?
ping @andrum99 (although he seems to have deleted his github account? :confused: )

**Comment by JamesH65** [comment]
This will be fixed as part of #1296 

Fixed by #1296

**Comment by JamesH65** [comment]
#1296 is merged so closing.
