### ISSUE TITLE
page listing bootable USB devices?

### ISSUE THREAD

**Issue by RichMorin** [raspberrypi/documentation#1295]
The blog page [Pi 3 booting part I: USB mass storage boot beta](https://www.raspberrypi.org/blog/pi-3-booting-part-i-usb-mass-storage-boot/) lists several USB devices that are thought to boot without problems on the RasPi. The comments section includes several more.

Unfortunately, this information is unorganized and somewhat incomplete. Also, because the comments section is now closed, additions and corrections aren't possible. So, I would like to propose a page listing bootable USB devices. I'd divide it into sections by device type (e.g., flash drive, SSD). Each entry should contain the name, size, and model number for a device.

**Comment by lurch** [comment]
Surely _any_ such list will always be incomplete? :man_shrugging: 
This suggestion reminds me a bit of https://elinux.org/RPi_SD_cards and I'm not sure the documentation repo is the place for such a list? @JamesH65 ?

**Comment by JamesH65** [comment]
I agree with @lurch - lists of 'compatible' ancillaries are always out of date, no matter how often they are updated, and things might suddenly stop working anyway, so the testing burden is quite horrendous to keep this sort of thing up to date.

**Comment by lurch** [comment]
> For example, is there a wiki where this could be located?

The link in my previous reply is a wiki... :wink:

**Comment by RichMorin** [comment]
> For example, is there a wiki where this could be located?
> 
> The link in my previous reply is a wiki... 😉

Ah; I didn't realize that.  I've asked for an account and plan to
make a start on a page.

-r

**Comment by JamesH65** [comment]
Going to close, as this sort of almost ephemeral  data isn't suitable for docs which cannot really afford to have inaccurate/very incomplete data in it.
