### ISSUE TITLE
Error in your AP documentation

### ISSUE THREAD

**Issue by Memoi** [raspberrypi/documentation#1297]
Hello,

your documentation https://github.com/raspberrypi/documentation/blob/master/configuration/wireless/access-point.md doesn't work !
Thanks to update it

**Comment by lurch** [comment]
"It doesn't work" is never a helpful complaint :frowning_face: 

Please provide more details about exactly what doesn't work, what error messages you get, etc. etc.

Or if you're looking for more general help, ask on the [forums](https://www.raspberrypi.org/forums/)

**Comment by Memoi** [comment]
Hi,

I found the problem, you forget to add :

sudo systemctl enable systemd-networkd

Without it the ip of br0 is 169.xxx so we loose ssh connection after the reboot because this service is not enable by default

**Comment by lurch** [comment]
ping @XECDesign as I believe he looked at this most recently?

**Comment by XECDesign** [comment]
I believe OP is right. It doesn't seem to be enabled by default.

It should be fixed when #1268 is merged.

**Comment by jarrah31** [comment]
"sudo systemctl enable systemd-networkd" isn't in the instructions yet within "Using the Raspberry Pi as an access point to share an internet connection (bridge)". I came hunting on here for an answer as to why the IP I had specified wasn't being picked up, even after a reboot.

**Comment by JamesH65** [comment]
https://github.com/raspberrypi/documentation/pull/1333 is still being copy edited. Sorry about the delay.

**Comment by aallan** [comment]
#1333 got merged. Can we close this one?

**Comment by JamesH65** [comment]
Guess so!
