### ISSUE TITLE
Missing revision info?

### ISSUE THREAD

**Issue by andreiw** [raspberrypi/documentation#1298]
Hi,

The  https://www.raspberrypi.org/documentation/hardware/raspberrypi/revision-codes/README.md is pretty thorough, but it doesn't document bit 31 being set.

What is bit 31 supposed to be?

I'm getting 80C03111 via the mailbox, which corresponds to a Pi4 4GB...but what's that 0x80000000 for?

A

**Comment by P33M** [comment]
What is the full output as seen in /proc/cpuinfo?

**Comment by JamesH65** [comment]
/proc/cpuinfo does not have the high bit set. 

Which mailbox call is returning with the high bit set?

**Comment by lurch** [comment]
I'd assume @andreiw is talking about https://github.com/raspberrypi/firmware/wiki/Mailbox-property-interface#get-board-revision ?  I've not tested it myself though.
:man_shrugging:

**Comment by JamesH65** [comment]
That bit appears to be the over voltage bit in the OTP - @andreiw Have you ever asked that bit to be set in config.txt?

You can double check what is on OTP using `vcgencmd otp_dump`

**Comment by andreiw** [comment]
I’ve only set the never overvoltage option.

A

**Comment by JamesH65** [comment]
Sorry, typo in my post, that is the never overvoltage bit, so that matches. 

I'll see whether I can add those bits to the docs.

**Comment by JamesH65** [comment]
I believe this is fixed.
