### ISSUE TITLE
Instructions about starting and reloading NGINX

### ISSUE THREAD

**Issue by ethanyoung** [raspberrypi/documentation#130]
It would be better to specify the starting and reloading steps for NGINX in [NGINX setup page](https://github.com/raspberrypi/documentation/blob/master/remote-access/web-server/nginx.md). Starting is after the installation and reloading is after php configuration. Otherwise there will be "page not available" and 403 errors in the browser (at least I encountered these problems).

**Comment by ebenupton** [comment]
PR please.

**Comment by ethanyoung** [comment]
The starting has been solved in  2f74577.

The reloading was in #204.
