### ISSUE TITLE
"HDMI configuration" page needs to mention cable needs plugged in before bootup

### ISSUE THREAD

**Issue by pete-heirendt-vacasa** [raspberrypi/documentation#1309]
By default if you boot up a Raspberry Pi, and then plug in an HDMI cable, the HDMI will not work. The cable must be plugged in *before* you bootup.
The opening line on "HDMI configuration" page is helpful (see below), but should mention the cable must be plugged in **before** you bootup:
> In the vast majority of cases, simply plugging your HDMI-equipped monitor into the Raspberry Pi using a standard HDMI cable will automatically lead to the Pi using the best resolution the monitor supports. 

https://github.com/raspberrypi/documentation/blob/master/configuration/hdmi-config.md

**Comment by JamesH65** [comment]
I've added a sentence to that effect.
