### ISSUE TITLE
Repository for Raspbian Buster

### ISSUE THREAD

**Issue by retro-desert** [raspberrypi/documentation#1314]
I damaged the sources.list file and I searched for official repositories for a long time (by default), but did not find it. Can you write them?
P.S. and can be pinned for beginners to see?

**Comment by lurch** [comment]
Sounds like a question for the https://www.raspberrypi.org/forums/

But if you're curious, have a look at the files in https://github.com/RPi-Distro/pi-gen/tree/master/stage0/00-configure-apt/files
