### ISSUE TITLE
Add Model A+ details and specs

### ISSUE THREAD

**Issue by bennuttall** [raspberrypi/documentation#132]
I added the A+ to [models](https://github.com/raspberrypi/documentation/blob/master/hardware/raspberrypi/models/README.md) but it needs more detail, and adding to [specs](https://github.com/raspberrypi/documentation/blob/master/hardware/raspberrypi/models/specs.md) and [schematics](https://github.com/raspberrypi/documentation/tree/master/hardware/raspberrypi/schematics) and probably more places.

**Comment by GeorgeSapkin** [comment]
This issue is closed, yet I cannot find A+ schematics neither in this repo nor on official website. Am I missing something?

**Comment by JamesH65** [comment]
I don't believe we will be releases schematics for the Model A+.
