### ISSUE TITLE
in users.md change word 'preceded' to 'followed' to make sentence logical

### ISSUE THREAD

**Issue by shticktical** [raspberrypi/documentation#1335]
In [documentation/linux/usage/users.md](https://www.raspberrypi.org/documentation/linux/usage/users.md)  the example is correct, but sentence is not:

> ...change another user's password with `passwd` __preceded__ by the user's username. For example, `sudo passwd bob` will allow you to set the user `bob`'s password...

[github link](https://github.com/raspberrypi/documentation/blob/master/linux/usage/users.md)

**Comment by lurch** [comment]
Fixed in `master`. Thanks :+1:
