### ISSUE TITLE
GenevaAdamsCareGiver

### ISSUE THREAD

**Issue by adamskahlil39** [raspberrypi/documentation#1337]

**Comment by lurch** [comment]
@adamskahlil39 Did you mean to post an issue about the Raspberry Pi documentation, or is this spam?

**Comment by JamesH65** [comment]
Spammer.

**Comment by JamesH65** [comment]
Is there any way to completely delete an issue?

**Comment by lurch** [comment]
@JamesH65 There's a "report abuse" button under the "..." on the original comment?
