### ISSUE TITLE
Please, use new overlay names

### ISSUE THREAD

**Issue by frank1119** [raspberrypi/documentation#1340]
pi3-miniuart-bt has been renamed to miniuart-bt
pi3-disable-bt has been renamed to disable-bt

May be the text in uart.md should reflect these changes.

**Comment by JamesH65** [comment]
@pelwell If you can confirm the name changes, I'll quickly fix up the page. Ta!

**Comment by frank1119** [comment]
Attached the output of `dtoverlay -h pi3-disable-bt` and `dtoverlay -h pi3-miniuart-bt`
I'm running "Linux raspberrypi 4.19.66+ #1253 Thu Aug 15 11:37:30 BST 2019 armv6l GNU/Linux"

![depricated-overlays](https://user-images.githubusercontent.com/12035455/69483852-c4b88b80-0e2c-11ea-860b-0c3093e4fc88.PNG)

**Comment by pelwell** [comment]
Yes - @frank1119 is correct.

**Comment by JamesH65** [comment]
Cheers, will make the changes.

**Comment by JamesH65** [comment]
Fixed by #1342
