### ISSUE TITLE
Add info on cmdline.txt

### ISSUE THREAD

**Issue by pickfire** [raspberrypi/documentation#135]
I hope for a chapter about cmdline.txt on [configuration](https://github.com/raspberrypi/documentation/tree/master/configuration).

**Comment by Ruffio** [comment]
@pickfire is this still an issue?

**Comment by pickfire** [comment]
Yeah, there is stil no cmdline.txt and I have no idea what I can add.

**Comment by bennuttall** [comment]
@Ruffio are you offering to fill in some gaps? Feel free to create PRs to complete some of these open issues

**Comment by Ruffio** [comment]
@bennuttall I'm not that a technical developer so don't know where to find and digest any information. I can read the link to have posted, but the only thing I can do is to copy the contents of the link, and I don't see much value in that...

**Comment by pickfire** [comment]
On Mon, Jun 29, 2015 at 02:12:33AM -0700, Rasmus Christiansen wrote:
>@bennuttall I'm not that a technical developer so don't know where to find and digest any information. I can read the link to have posted, but the only thing I can do is to copy the contents of the link, and I don't see much value in that...
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/raspberrypi/documentation/issues/135#issuecomment-116553487

You could put the link in the page for references and add some of your
own.

-- 
 _____________________________________
< Do what you like, like what you do. >
 -------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

**Comment by bennuttall** [comment]
If you need help please try the [forums](https://www.raspberrypi.org/forums)

**Comment by JamesH65** [comment]
PR now added #523

**Comment by JamesH65** [comment]
This is merged #523
