### ISSUE TITLE
Need "zlib1g:i386" and "bc" for cross-compiling kernel

### ISSUE THREAD

**Issue by hhaoyan** [raspberrypi/documentation#1351]
Problem: when I tried the cross-compiling instructions at (https://www.raspberrypi.org/documentation/linux/kernel/building.md), I found two more dependencies are required to build:
```
sudo apt-get install zlib1g:i386 bc
```

`zlib1g:i386` is for the cross-compiler (cross-compiler is i386 and I'm running x86_64) and `bc` is for the build process.

**Comment by lurch** [comment]
That page has a section about "If you are on a 64-bit host system" ... ?

**Comment by hhaoyan** [comment]
I see. Thank you for pointing out, but I guess we still need to add installation instructions for bc?

**Comment by JamesH65** [comment]
Presumably just the following?

`sudo apt install bc`

**Comment by lurch** [comment]
@JamesH65 I just remembered about #1100 :wink:

**Comment by hhaoyan** [comment]
> Presumably just the following?
> 
> `sudo apt install bc`
> 
> Is that needed on 32 and 64 bit systems? I don't remember having to install it on Lubuntu, but it was a while ago.

I agree. But I don’t have a 32 bit Linux to test with.

I assume adding more dependencies won’t hurt? At least some people (like me) don’t have them.

**Comment by JamesH65** [comment]
I'm just going to copy that line from #1100 in to the cross section as well.

**Comment by JamesH65** [comment]
OK, done, and merged direct to master as such a small change.

**Comment by lurch** [comment]
@JamesH65 Apologies for not explaining things very well - https://github.com/raspberrypi/documentation/blob/master/linux/kernel/building.md#build-sources already included the cross-compilation dependencies, so I've fixed things "properly" in https://github.com/raspberrypi/documentation/commit/9f4580ebee74fcfc13dbf891261995a278c6fae1

**Comment by JamesH65** [comment]
Ahhhhh, gotcha. Completely missed that line in the next section. Thanks.
