### ISSUE TITLE
Missing drawing for RPi 2B

### ISSUE THREAD

**Issue by jstjst** [raspberrypi/documentation#1367]
I would need the drawing for the Raspberry Pi 2B.
Will you be able to upload them?

Thanks Jonas

**Comment by JamesH65** [comment]
I'll see if we have one anywhere, but if not, I doubt we would produce one just to fill the gap. The 2B is quite an old device (in raspberry pi terms), so the cost effectiveness of doing it is questionable.

**Comment by JamesH65** [comment]
@jstjst Checked, we don't have a specific drawing for the 2B, and won't be doing one,  BUT, the B+ drawing is pretty much the same so for positioning of sockets etc, using that would be fine.
