### ISSUE TITLE
Documentation refers to Pi 4 HDMI port 0 without specifying which that is.

### ISSUE THREAD

**Issue by HughR** [raspberrypi/documentation#1372]
[HDMI Config](https://www.raspberrypi.org/documentation/configuration/hdmi-config.md) says that HDMI port 0 must be used for UltraHD at 60Hz.  But it isn't clear which of the two ports is 0.

I read the [schematic](https://www.raspberrypi.org/documentation/hardware/raspberrypi/schematics/rpi_SCH_4b_4p0_reduced.pdf) to find port 0 is labelled "j6".  This is silk-screened onto the circuit board.

I think that the clearest description is "the port closest to the USB C power connector".  This should be added to the HDMI Config page.

**Comment by andrum99** [comment]
> I read the [schematic](https://www.raspberrypi.org/documentation/hardware/raspberrypi/schematics/rpi_SCH_4b_4p0_reduced.pdf) to find port 0 is labelled "j6". This is silk-screened onto the circuit board.

It's actually labelled HDMI0 on the silk screen. I've opened #1374 to address this.

**Comment by JamesH65** [comment]
Fixed merged. Thanks all.
