### ISSUE TITLE
"Network boot your Raspberry Pi" Error on Last Step

### ISSUE THREAD

**Issue by peter-chineham** [raspberrypi/documentation#1380]
(https://www.raspberrypi.org/documentation/hardware/raspberrypi/bootmodes/net_tutorial.md) Final step says "echo "10.42.0.211:/tftpboot /boot nfs defaults,vers=3 0 0" | sudo tee -a /etc/fstab" but surely this should be "echo "10.42.0.211:/tftpboot /boot nfs defaults,vers=3 0 0" | sudo tee -a **/nfs/client1**/etc/fstab"?

**Comment by andrum99** [comment]
Good catch - see #1381

**Comment by lurch** [comment]
See also #1368 ?

**Comment by JamesH65** [comment]
Fixed
