### ISSUE TITLE
Wireless Access Point - Some explanation for IP address chosen required

### ISSUE THREAD

**Issue by edbird** [raspberrypi/documentation#1400]
Path `documentation/configuration/wireless/access-point.md`

Line 44: The IP address chosen was `192.168.4.1/24`.

It is not immediately clear to me why this was chosen. My guess is that this Pi is on a network where the default address space/main local network address space is `192.168.1.X`, and there are an additional 2 networks `192.168.2.X`, `192.168.3.X`. Then the next sequential address is `192.168.4.X`, and `192.168.4.1` is chosen for the IP of the Access Point. (IP of Raspberry Pi's wireless interface.)

It is unlikely that a new user already has a network `192.168.4.X` in use - so for the vast majority just blindly following the instructions without thinking this is unlikely to be an issues, but some further explanation may be necessary here?

**Comment by lurch** [comment]
I suggest we revisit this after #1333 has been merged?

**Comment by aallan** [comment]
So #1333 got merged. Does it resolve this issue?

**Comment by aallan** [comment]
Closed due to inactivity.
