### ISSUE TITLE
Add info for using GNU Privacy Gaurd.

### ISSUE THREAD

**Issue by pickfire** [raspberrypi/documentation#141]
I hope there is documentation about using GPG in [usage](https://github.com/raspberrypi/documentation/tree/master/usage#usage) explaining public keys and private keys and using [GPG](https://gnupg.org/) in Raspberry Pi.

**Comment by ebenupton** [comment]
Please submit a PR if you'd like to see this.

**Comment by pickfire** [comment]
Yeah, I will create a pull request. But where should I put into?
