### ISSUE TITLE
Add picture of microHDMI to the setup page

### ISSUE THREAD

**Issue by JamesH65** [raspberrypi/documentation#1412]
https://www.raspberrypi.org/documentation/setup/monitor-connection.md

Has a picture of the large HDMI, needs a smaller one. 

Maybe the Zero Mini as well?

**Comment by lurch** [comment]
While adding these, might also be worth showing a 4-ring 3.5mm plug as well under the composite section?

**Comment by JamesH65** [comment]
> While adding these, might also be worth showing a 4-ring 3.5mm plug as well under the composite section?

Was wondering about that. Will ask if there is an appropriate picture somewhere

**Comment by JamesH65** [comment]
fixed by #1416

**Comment by JamesH65** [comment]
Fixed merged

**Comment by lurch** [comment]
No plan to add the mini-HDMI then?

**Comment by JamesH65** [comment]
I'll see what images are available.
