### ISSUE TITLE
TCP/IP documentation lacks IPv6 information

### ISSUE THREAD

**Issue by imp1sh** [raspberrypi/documentation#1420]
The documentation found here `https://www.raspberrypi.org/documentation/configuration/tcpip/README.md`
lacks information about how IPv6 can be configured. 
I think it should cover:
- static IPv6
- SLAAC IPv6 and
- Statefull IPv6
dhcpcd should be able to hand all of those, right?

**Comment by lurch** [comment]
Does #1318 cover what you're looking for?

**Comment by imp1sh** [comment]
No.
The user needs information on how to give a raspbian host an IPv6 address. In default settings it's doing SLAAC but to do what if it wants a static IPv6 address or use dhcpv6 client?

**Comment by JamesH65** [comment]
I have no idea how to do any of that, and don't have any time to acquire to required knowledge, so I would welcome a PR.

**Comment by thomasschaeferm** [comment]
It is documented inside the `/etc/dhcpcd.conf` as comments.

**Comment by aallan** [comment]
> Parts of that are included in my pull request. For dyndns I need a predictable/stable address.

Which PR is this?

**Comment by thomasschaeferm** [comment]
#1318
