### ISSUE TITLE
A SSH / UART dongle client for Android suggestion.

### ISSUE THREAD

**Issue by green-green-avk** [raspberrypi/documentation#1427]
Um... Not so humble from my side. It's rather a suggestion.
I tried different SSH and UART dongle clients for Android... and found a lack of good input / rendering features.
But what do you think about this one:
https://play.google.com/store/apps/details?id=green_green_avk.anotherterm

Thank you for your patience in advance.

**Comment by lurch** [comment]
Are you suggesting that this should be added to the list of clients on [this page](https://github.com/raspberrypi/documentation/blob/master/remote-access/ssh/android.md) ?

**Comment by lurch** [comment]
Although @JamesH65 do you think it might be worth adding a "serial console" section to https://github.com/raspberrypi/documentation/blob/master/remote-access/README.md ? :man_shrugging:

**Comment by green-green-avk** [comment]
It sounds funny but my initial intent to create the proposed client was the access to Raspberry-Pi through serial to use `raspi-config` and possibly other ncurses software. A long search for a suitable client brings nothing. Another concern was the requirement of a specific screen keyboard, so I just made it built-in.

**Comment by duckida** [comment]
To me that looks like a terminal for the Droid and not an SSH Client

**Comment by green-green-avk** [comment]
Yes, it also has a local pty support.

**Comment by JamesH65** [comment]
> Although @JamesH65 do you think it might be worth adding a "serial console" section to https://github.com/raspberrypi/documentation/blob/master/remote-access/README.md ? 🤷‍♂️

Hmm, does appear to be a gap in the docs there. Might be worth spending some time on that. Not sure we want a list of third party serial terminals though, been trying to get rid of that sort of thing.

**Comment by aallan** [comment]
Policy is no third party products. Closing.
