### ISSUE TITLE
Windows ssh client

### ISSUE THREAD

**Issue by parlitu** [raspberrypi/documentation#1432]
You can now connect with ssh using Windows Powershell 7
https://devblogs.microsoft.com/powershell/announcing-powershell-7-0/

**Comment by lurch** [comment]
I don't use Windows myself - does this offer something that https://github.com/raspberrypi/documentation/blob/master/remote-access/ssh/windows.md or https://github.com/raspberrypi/documentation/blob/master/remote-access/ssh/windows10.md don't already cover?

**Comment by parlitu** [comment]
Covered but outdated. The Documentation should be updated by removing Putty and include the new PowerShell 7 ssh mode...

**Comment by lurch** [comment]
We always welcome Pull Requests... :slightly_smiling_face:

**Comment by JamesH65** [comment]
Unless Powershell7 works on all current Windows version that are still in support, we should not be removing Putty.

Is the SSH in Powershell a graphical/windows one? Or command line?

**Comment by parlitu** [comment]
What operating systems does PowerShell 7 support?
PowerShell 7 supports the following operating systems on x64, including:

Windows 7, 8.1, and 10
Windows Server 2008 R2, 2012, 2012 R2, 2016, and 2019
macOS 10.13+
Red Hat Enterprise Linux (RHEL) / CentOS 7+
Fedora 29+
Debian 9+
Ubuntu 16.04+
openSUSE 15+
Alpine Linux 3.8+
Additionally, we support ARM32 and ARM64 flavors of Debian and Ubuntu, as well as ARM64 Alpine Linux.

**Comment by parlitu** [comment]
![image](https://user-images.githubusercontent.com/52703502/76623580-b83c7800-656e-11ea-9704-70679954251b.png)
