### ISSUE TITLE
Booteeprom tweaks?

### ISSUE THREAD

**Issue by lurch** [raspberrypi/documentation#1436]
ping @timg236 

I was looking at https://github.com/raspberrypi/documentation/blob/master/hardware/raspberrypi/booteeprom.md and I wonder if it needs a couple of updates?
 * Should it mention the new `stable` directory?
 * Should it mention that network boot _is_ now available (via switching to the stable version), rather than it still being a "yet to be implemented" feature?
 * The page mentions how to check **if** an update is available, but doesn't really mention **how** to update (assuming that the systemd service isn't disabled). After reading the page a couple of times I spotted the bit that says "which installs a service that runs at boot-time to check for critical updates.". I think this means that if you want to switch from the `critical` version to the `stable` version then you need to edit `/etc/default/rpi-eeprom-update` and perform **two** manual reboots? The first reboot spots that there's a newer bootloader version, and the second reboot actually applies the update? (before then auto-rebooting a 3rd time back to Raspbian)

**Comment by timg236** [comment]
Maybe but I'm a bit busy on other stuff right now

**Comment by lurch** [comment]
I'll see if I can put together a PR later this afternoon (unless @JamesH65 beats me to it!).

**Comment by JamesH65** [comment]
Feel free!

**Comment by lurch** [comment]
Well, afraid I didn't get round to this, as you may have guessed :confounded:

**Comment by lurch** [comment]
#1460 updates `hardware/raspberrypi/bcm2711_bootloader_config.md` but I guess we need a similar PR to update `hardware/raspberrypi/booteeprom.md`
(mainly adding this comment just to link the two issues)

**Comment by JamesH65** [comment]
@lurch Lots of changes made around this area I think since this was posted - is this issue still relevant?

**Comment by lurch** [comment]
Everything here has been resolved - good work guys!
