### ISSUE TITLE
Installation documentation update for linux systems without automounter

### ISSUE THREAD

**Issue by zonk1** [raspberrypi/documentation#144]
Hi,

the installation howto in linux.md implicitly assumes that some kind of automounter will mount sd card once it's inserted into system which isn't always true.

I propose mentioning this explicitly as in https://github.com/zonk1/documentation/blob/patch-1/installation/installing-images/linux.md

**Comment by ebenupton** [comment]
PR please.

**Comment by JamesH65** [comment]
@Zonk1. This seems like a sensible idea - could you submit a PR with your changes please against the latest version of the documentation. (sorry about the delay!)

**Comment by JamesH65** [comment]
Will be fixed by #564

**Comment by JamesH65** [comment]
Now merged, closing

**Comment by zonk1** [comment]
@JamesH65 For some reason I've missed the PR request. Thanks for the update!
