### ISSUE TITLE
I dont have permissions to remove python libraries.

### ISSUE THREAD

**Issue by Jaccccc** [raspberrypi/documentation#1446]
Hello, i have tried to pip install neat python, realised that there were some files missing, and tried to delete it. I got a long string of error messages, the last of which stating that i didnt have permissions to delete it. Any advice would be great on how to remove this file!

**Comment by JamesH65** [comment]
Please use the forums for technical support questions. This repo is for reporting and fixing issues with the Pi documentation.

www.raspberrypi.org/forums
