### ISSUE TITLE
Unclosed <a> tag

### ISSUE THREAD

**Issue by burtyb** [raspberrypi/documentation#1448]
Both os_prefix and overlay_prefix sections in https://github.com/raspberrypi/documentation/blob/master/configuration/config-txt/boot.md have unclosed tags.

**Comment by JamesH65** [comment]
Fixed pushed to master. Takes an hour or so to get to the main website.  Will close when it has been confirmed.

Thanks!

**Comment by JamesH65** [comment]
Looks OK, closing.

**Comment by JamesH65** [comment]
Weird, thought I had closed this.
