### ISSUE TITLE
Pi 3B missing component

### ISSUE THREAD

**Issue by benklop** [raspberrypi/documentation#1454]
Hello, I have a Pi 3B+ that I have discovered has a missing SMT component. I'd like to replace it, but I don't have any idea what the value is, nor the component type. It is missing from the back of the board directly opposite the CPU. It's the unlabeled component to the right directly above FB2. I've attached a picture showing the component. Can I get info about what this missing part is?
![InkedIMG_20200331_195502572_LI](https://user-images.githubusercontent.com/2729824/78091433-05e81b80-738a-11ea-86fe-c7c21a6b48e7.jpg)
.

**Comment by JamesH65** [comment]
You are asking this question in the wrong place (this is for issues with the documentation). Please use the forums for this sort of thing.

www.raspberrypi.org/forums
