### ISSUE TITLE
GPIO output voltage levels

### ISSUE THREAD

**Issue by szilvasyz** [raspberrypi/documentation#1463]
Hello,
All places in the page /hardware/raspberrypi/gpio/gpio_pads_control.md there are mistakenly mentioned V(IH) and V(IL) parameters and their represented numeric values as the datasheet references for the output voltage of a pad. Instead, the datasheet parameters V(OL) and V(OH) reflect for output levels of pads. Please, correct these on the documentation page and the regarding voltage levels too. Thank you.
Zoltan

**Comment by JamesH65** [comment]
@jimbojr @mike-stimson I thought that page was correct, any comment?

https://www.raspberrypi.org/documentation/hardware/raspberrypi/gpio/README.md

**Comment by mike-stimson** [comment]
Looks ok to me. Can't see the problem.

Mike

**Comment by szilvasyz** [comment]
Please take a look at the "subpage" linked by "Output [drive strength](https://www.raspberrypi.org/documentation/hardware/raspberrypi/gpio/gpio_pads_control.md)". That page, discussing characteristics of **output mode pads** (usable output currents and voltage levels) always refers to V<sub>IL</sub> and V<sub>IH</sub> **input mode parameters** of datasheet. But, in real, these parameters reflect the behavior of an input mode pad. For output mode you should use V<sub>OL</sub> and V<sub>OH</sub> parameters.

Moreover, not only the parameter names, but the parameter numeric values themselves are mixed up in the "drive strength" page. For example a 3.3V output mode pad should never go up to 0.9V (suggested by V<sub>IL</sub>) in normal circumstances (below the configured output current), but it must remain not more than 0.14V as V<sub>OL</sub> shows.

Of course, V<sub>IL</sub> and V<sub>IH</sub> are describing voltage levels of an input pad, which are to be interpreted as "low" and "high" logic levels, respectively. The quoted table from the datasheet on the main "GPIO" page is correct with absolutely usual values for such kind of I/O pad.

**Comment by mike-stimson** [comment]
Ah, I see your point. @JamesH65 can you fix this? IIRC, I think this is because the very first BRCM datasheet had the output and inputs parameters reversed, and this explanation is probably based on that.

**Comment by JamesH65** [comment]
Is it just this bit that needs reversing?

> VIL, the maximum low-level voltage (0.9V at 3V3 VDD IO)
VIH, the minimum high-level voltage (1.6V at 3V3 VDD IO)

**Comment by JamesH65** [comment]
Ah, sorry, read this completely wrong.  It would be easier if someone who knows about this simply provides a PR!

**Comment by JamesH65** [comment]
Or is it on that page that all IH/IL simply need to be changed to OH/OL?

**Comment by mike-stimson** [comment]
Not quite, unfortunately. As Zoltan describes, the values of 0.9V and 1.6V
are not appropriate (they are the actual VIL/IH levels). Infact, the worked
example of a 16mA drive strength afterwards isn't quite right, as we only
define our VOH/OL levels with a 8mA drive setting, but whilst sink/sourcing
2mA (if the notes on the table are to be believed).

**Comment by JamesH65** [comment]
In which case I have no idea what to change because I am a HW idiot. Going to need someone who knows more about this than me to update that stuff.

**Comment by ernestguillem** [comment]
Sent a PR with the fix.
`https://github.com/raspberrypi/documentation/pull/2081`
