### ISSUE TITLE
Add explicit description of line length limit

### ISSUE THREAD

**Issue by insekt** [raspberrypi/documentation#1466]
I think it is better to add explicit description of line length limit to File format section.

Now there is a mention of such limit here
https://github.com/raspberrypi/documentation/blob/master/configuration/config-txt/boot.md
"taking care not to exceed the 80-character line length limit"

I ran into this problem and spent an hour looking for a cause.

**Comment by JamesH65** [comment]
Proposed fix here https://github.com/raspberrypi/documentation/pull/1467

**Comment by lurch** [comment]
Closing issue, as #1467 has been merged.
