### ISSUE TITLE
Remote-access/VNC/README.md - VNC comes builtin to newer Raspbian Distros

### ISSUE THREAD

**Issue by duckida** [raspberrypi/documentation#1470]
I was lookin through VNC and I saw you have to install it with a command. On my Pi, VNC is pre-installed.

**Comment by lurch** [comment]
[The page](https://www.raspberrypi.org/documentation/remote-access/vnc/README.md) _does_ already say "VNC Connect from RealVNC is included with Raspbian.".
And the "install instructions" you mention are actually prefaced with "On your Raspberry Pi, run the following commands to make sure you have the latest version of VNC Connect:".

@spl237 @XECDesign Do you think it's worth tweaking the documentation to make it clearer that this is an optional step?

**Comment by duckida** [comment]
Yes

**Comment by spl237** [comment]
It's included in the full image; it's not in the standard image, but is available in Recommended Software; no need to use apt to install it.

It's probably worth updating the page to reflect that rather than suggesting the use of apt.

**Comment by JamesH65** [comment]
See https://github.com/raspberrypi/documentation/pull/1476

**Comment by lurch** [comment]
Fixed by #1476
