### ISSUE TITLE
Sense HAT documentation does not provide instructions on how to use it

### ISSUE THREAD

**Issue by duckida** [raspberrypi/documentation#1471]
I was browsing through  and found that the SenseHat docs do not tell you how to control it but only debug it.

**Comment by lurch** [comment]
https://www.raspberrypi.org/documentation/hardware/sense-hat/README.md includes "After installation, example code can be found ..." ?

Maybe you're looking also for https://projects.raspberrypi.org/en/projects?hardware%5B%5D=sense-hat  :question:

**Comment by duckida** [comment]
I think that noobs will think to come here but then just find this debug stuff

**Comment by JamesH65** [comment]
Ouch, that page is pretty bad. Not sure what to do with it though. Will think about it.

**Comment by duckida** [comment]
We should make it a page on How To use sense hat

**Comment by aallan** [comment]
Page now lives at https://www.raspberrypi.org/documentation/accessories/sense-hat.html, source for that now lives at https://github.com/raspberrypi/documentation/blob/develop/documentation/asciidoc/accessories/sense-hat.adoc.

Does someone that's used a Sense HAT want to offer up a PR for this one?
