### ISSUE TITLE
How to save camera rotation ?

### ISSUE THREAD

**Issue by mattx38** [raspberrypi/documentation#1475]
Hello,

I managed to rotate the camera image by using "raspistill -rot 270", but I would like this parameter to be saved after rebooting the Pi or when using another application ? I use TouchSelfie, and the camera is always rotated the same (wrong) way.
 
Is there a way to put this parameter into the /boot/config.txt file ?

Thank you

**Comment by JamesH65** [comment]
No. Best bet is to create a simple bash script that simply calls raspistill with all the parameters you need. 

(This is not the place for tech support question - please use the forums)
