### ISSUE TITLE
How do I measure the voltage of my PI 4 B?

### ISSUE THREAD

**Issue by hackercyclops12** [raspberrypi/documentation#1510]
How do I measure the voltage using commands via the command line?

Thanks in advance :)

**Comment by lurch** [comment]
https://github.com/raspberrypi/documentation/blob/master/raspbian/applications/vcgencmd.md#measure_volts-block

However, if you mean the power-input voltage, then note that if it's too low, a [warning icon](https://github.com/raspberrypi/documentation/blob/master/configuration/warning-icons.md) will be displayed.

I suspect that this is really the sort of question you should be asking on the [forums](https://www.raspberrypi.org/forums/) though, so closing this issue for now. Feel free to follow up with further comments if you have specific questions about the [documentation](https://www.raspberrypi.org/documentation).

**Comment by hackercyclops12** [comment]
Thankyou that really helped me :)
