### ISSUE TITLE
BCM2711 EEPROM config question

### ISSUE THREAD

**Issue by lurch** [raspberrypi/documentation#1522]
I just noticed that when I run `vcgencmd bootloader_config` (as documented at https://github.com/raspberrypi/documentation/blob/master/hardware/raspberrypi/bcm2711_bootloader_config.md ) on my Pi4B the output includes `[all]` and `[none]` lines. (The same output is present in the result of `rpi-eeprom-config /lib/firmware/raspberrypi/bootloader/critical/pieeprom-2020-04-16.bin` so I guess these are actually values in the EEPROM config itself rather than being something added by `vcgencmd`)

What do these lines mean @timg236 ? Should they be added to the [documentation](https://github.com/raspberrypi/documentation/blob/master/hardware/raspberrypi/bcm2711_bootloader_config.md) ?

**Comment by timg236** [comment]
It already is documented https://www.raspberrypi.org/documentation/configuration/config-txt/conditional.md

**Comment by lurch** [comment]
Fixed by #1523 , thanks Tim.
