### ISSUE TITLE
BCM2836 listed as compatible with 64-bit kernel on configuration/boot_folder

### ISSUE THREAD

**Issue by trejan** [raspberrypi/documentation#1535]
BCM2836 from the original Pi 2 has Cortex-A7 cores which don't support ARMv8 instructions. However, it is listed as supporting the 64-bit kernel8.img on https://github.com/raspberrypi/documentation/blob/master/configuration/boot_folder.md

Only the Pi 2 v1.2 with BCM2837 should be listed as compatible with kernel8.img

**Comment by lurch** [comment]
Fixed by #1538
