### ISSUE TITLE
About Noob's page

### ISSUE THREAD

**Issue by Spangenhelm** [raspberrypi/documentation#154]
Hello,
While i was starting to use my raspberrypi i have noticed a few things about the [doc page](
https://github.com/raspberrypi/documentation/blob/master/installation/noobs.md)

In [this section](https://github.com/raspberrypi/documentation/blob/master/installation/noobs.md#noobs-and-noobs-lite):
> The full version has the images of each of the operating systems included, so they can be installed from the SD card while offline..

I don't understand because i have downloaded the full/offline version and when i was not connected to the internet the only option available to install was raspian, did i miss something ?

Also in the section under "Noobs development" the version mentionned is outdated.

Voila! Hope it helps
+++

**Comment by lurch** [comment]
Nope, you didn't miss anything, I'll update the docs shortly.
Thanks for highlighting the outdated info!
