### ISSUE TITLE
technical_faq.md needs updated for Pi 4

### ISSUE THREAD

**Issue by andrum99** [raspberrypi/documentation#1540]
Currently says GPU is the same on all models, latest model is Pi 3B+, and probably other things too. Opening this as an issue so it doesn't get forgotten about.

**Comment by JamesH65** [comment]
I'm not sure that technical faq is used any more. I think all the content was moved to the main faq? Will check.

**Comment by JamesH65** [comment]
Yes, I think most of the content of the technical-faq was moved in to the main faq. Should probably delete that file.

**Comment by andrum99** [comment]
No problem - just flagging it up as I came across it while doing #1539.

**Comment by JamesH65** [comment]
See #1541

**Comment by lurch** [comment]
Closing this in light of #1541
