### ISSUE TITLE
Document how to use multiple Raspberry Pi boards with a single keyboard and mouse

### ISSUE THREAD

**Issue by aallan** [raspberrypi/documentation#1544]
There is an open source version of [Synergy](https://symless.com/synergy) which allows you to share a single keyboard and mouse between multiple computers. See https://www.rauchland.com/articles/using-barrier-to-control-multiple-pcs-with-one-keyboard-and-mouse/ for an existing walkthrough (that isn't Raspberry Pi specific).

**Comment by lurch** [comment]
With the obvious caveat that you need a separate display attached to each Raspberry Pi :wink:

**Comment by andrum99** [comment]
See Gordon's rather excellent write up and video on the blog at https://www.raspberrypi.org/blog/share-your-keyboard-and-mouse-between-computers-with-barrier/

**Comment by lurch** [comment]
@aallan and @ghollingworth actually work together (although not in the same office ATM, for obvious reasons) :smiley:

**Comment by aallan** [comment]
I think I opened this before Gordon's article got published based on the internal email thread.

**Comment by andrum99** [comment]
I'm wondering if it is perhaps worth reproducing Gordon's blog post in the documentation. Blog posts sort of get lost after a while.

**Comment by aallan** [comment]
This might get done as part of #1911, but in any case, closing.
