### ISSUE TITLE
Possibility for extension

### ISSUE THREAD

**Issue by Chewbury** [raspberrypi/documentation#1548]
The usage of "client1" throughout this suggests the possibility of also running clients2,3,4...X this way. While doing this kind of thing (routinely) in Solaris, clients would be recognised (and authenticated) by MAC address. It would be useful to extend this documentation to add the configuration of a second (unique) client.

I intend implementing this over the next few weeks, so I'm happy to extend the page if anyone would think it worthwhile. Yes, I'm going to run the world's least powerful cluster :)

**Comment by lurch** [comment]
Sorry, which page in the documentation are you referring to??

**Comment by aallan** [comment]
Closed due to lack of response.
