### ISSUE TITLE
Pi HQ camera documentation incorrect

### ISSUE THREAD

**Issue by Adam-Langley** [raspberrypi/documentation#1552]
I've just received my HQ camera with the intention of following these instructions to remove the filter.

https://github.com/raspberrypi/documentation/blob/master/hardware/camera/hqcam_filter_removal.md

However, removing the hex screws has no effect on the fixing of the housing to the PCB. It appears the manufacturer has begun to glue the housing to the PCB. Please confirm?

Thanks

**Comment by JamesH65** [comment]
@simon-martin-rpi @davidplowman Any thoughts?

**Comment by davidplowman** [comment]
I'm afraid I don't know anything about that... sorry!

**Comment by simon-martin-rpi** [comment]
I don't have an account so can't reply there. The gasket is rubber and
causes the mechanical assembly to act like a suction cup on the PCB. It is
not glued. Just needs a bit of force.

Simon

**Comment by simon-martin-rpi** [comment]
Sorry I do have an account :-)

**Comment by JamesH65** [comment]
@Adam-Langley Has that sorted out the problem? Please close the issue if so.

**Comment by Adam-Langley** [comment]
Hi @simon-martin-rpi, @JamesH65 

Thanks guys - your affirmation gave me the confidence to apply more force. I was really concerned about damaging the PCB surface. (I work in software - do a lot of issue diagnostics - so I have a very well developed "make no assumptions, confirm all facts" mentality :)

I see the gasket is quite significant, and a little bit sticky - which caused it to bond quite firmly.

Additionally, I got the filter out without damaging it - a little bit of isopropyl, and warming it a little (30-40 degrees), then pushing at the very edge worked. I might fork and describe my process for anyone else concerned...

Thanks for the help guys, greatly appreciated!
