### ISSUE TITLE
Python FAQs

### ISSUE THREAD

**Issue by elParaguayo** [raspberrypi/documentation#156]
Hi,

I'd like to add an FAQ page for python as we see the same questions over and over again in the forum.

More here: http://www.raspberrypi.org/forums/viewtopic.php?f=32&t=97816

If the idea is ok then I'm happy to have a go at this.

**Comment by bennuttall** [comment]
I like the idea of technical FAQs - we've been discussing something similar recently. Breaking up into sections would make sense too.

Let me check with the team and see what everyone thinks.

If I haven't responded by mid- next week feel free to bump this issue to remind me.

Thanks

**Comment by elParaguayo** [comment]
Ben,

Bumping as requested!

**Comment by JamesH65** [comment]
@ben More bumping - has this been done?

**Comment by JamesH65** [comment]
@bennuttall More bumping - any progress on this?

**Comment by bennuttall** [comment]
No - I don't think this belongs in documentation.

**Comment by JamesH65** [comment]
OK, closing.
