### ISSUE TITLE
bootconf.txt missing documentation

### ISSUE THREAD

**Issue by cleverca22** [raspberrypi/documentation#1578]
`ENABLE_SELF_UPDATE` is incorrectly documented as `SELF_UPDATE`
and the following `bootconf.txt` options are not documented
* `USB_DEV_BOOT_MAX_RETRIES`
* `USB_DEV_FILE_TIMEOUT`
* `USB_MSD_BOOT_MAX_RETRIES`
* `TFTP_FILE_TIMEOUT`
* `MAC_ADDRESS`

**Comment by lurch** [comment]
ping @timg236

**Comment by timg236** [comment]
USB_DEV can wait until it's supported because those options might get removed anyway. 
Pushed PR for ENABLE_SELF_UPDATE the others will be updated at some point

**Comment by lurch** [comment]
Seems that these are all addressed by #1581

**Comment by lurch** [comment]
Now merged, resolving the original issue.
