### ISSUE TITLE
Missing pullup resistors on RPI 4B schematics 

### ISSUE THREAD

**Issue by planitar** [raspberrypi/documentation#1592]
RPI4 schematics has pullup resistors on GPIO2/3 missing, whereas they are physically present on the board and are shown on RPI3 schematics. It is important to know when interfacing with peripherals that may have their own pullups.

**Comment by lurch** [comment]
ping @jimbojr @Roger-Thornton

**Comment by JamesH65** [comment]
ping @jimbojr @Roger-Thornton
