### ISSUE TITLE
Scratch documentation needs update for new gui

### ISSUE THREAD

**Issue by DeeJay** [raspberrypi/documentation#162]
[usage/scratch/README.md](https://github.com/raspberrypi/documentation/tree/master/usage/scratch/README.md) needs update for 'new' gui.

"You'll find Scratch on the desktop of Raspbian and in the applications menu under Education."

There are no icons on the new desktop. There is no 'Education' section in the applications menu.

**Comment by bennuttall** [comment]
Thanks for reporting these issues. While it's helpful to alert us, I'd prefer if these were all reported in the same issue as they are exactly the same change required in multiple pages.

I'm closing all these individual issues and I've made Issue #169 which will track each of these.
