### ISSUE TITLE
raspberrypi.org/help: Raspbian -> Raspberry Pi OS

### ISSUE THREAD

**Issue by andrum99** [raspberrypi/documentation#1620]
The main documentation page at raspberrypi.org/documentation has had the square that previously said 'Raspbian' on it changed to say 'Raspberry Pi OS', and the logo changed as well. The same thing needs done on raspberrypi.org/help.

(Filing this here as I can't find a bug tracker for the website).

**Comment by JamesH65** [comment]
I've reported this upstream to the comms team.

**Comment by andrum99** [comment]
Seems to be fixed now - closing.
