### ISSUE TITLE
Python documentation needs updating for 'new' gui

### ISSUE THREAD

**Issue by DeeJay** [raspberrypi/documentation#163]
https://github.com/raspberrypi/documentation/blob/master/usage/python/README.md needs updating for 'new' gui

"Start by opening IDLE from the desktop."

and

"The easiest introduction to Python is through IDLE. Double click the IDLE icon on the Desktop (or IDLE3 for Python 3):"

There are no default icons for any applications on the desktop of the revised gui.

**Comment by bennuttall** [comment]
See #169
