### ISSUE TITLE
Add a tip about forcing IPV4 ping in remote-access/ip-address.md

### ISSUE THREAD

**Issue by shaunakg** [raspberrypi/documentation#1632]
When the guide is followed and you run `ping raspberrypi.local`, many machines will return an IPV6 address which isn't supported on some SSH clients. It would be helpful to include the `-4` flag in the documentation command, which will force IPV4 on Windows and Unix.

**Comment by lurch** [comment]
Did you intend this to be a PR rather than an issue? (I see you have a linked commit)
