### ISSUE TITLE
Documentation needed to revert back rpi3b to original booting state

### ISSUE THREAD

**Issue by OkenKhuman** [raspberrypi/documentation#1642]
I made a try to network boot RPi3b with RPi4b as server but fail. After that when I try to boot my RPi3b from sd card it is getting delayed by 45-75 seconds. 

How can I remoove the delay. Please describe how to revert back.

**Comment by lurch** [comment]
What's on the SD card? AFAIK if the SD card is bootable (e.g. if you write the latest version of [Raspberry Pi OS](https://www.raspberrypi.org/downloads/raspberry-pi-os/) to it), then it should boot directly from that without attempting to network boot?
https://github.com/raspberrypi/documentation/blob/master/hardware/raspberrypi/bootmodes/bootflow.md

**Comment by OkenKhuman** [comment]
It happens that the delay was on starting VNC after boot. Regarding SSH there is no delay after boot. 
Sorry for my ignorance.
