### ISSUE TITLE
Wireless Access Point creation document is missing the DAEMON_CONF edit step

### ISSUE THREAD

**Issue by rushilsoni** [raspberrypi/documentation#1646]
https://www.raspberrypi.org/documentation/configuration/wireless/access-point-routed.md

The official link to generate Acess Point on RPI is missing the step where the configuration file of HOSTAPD needs to be modified

Path to File: /etc/default/hostapd
Edit Required: 
Change #DAEMON_CONF= to DAEMON_CONF="/etc/hostapd/hostapd.conf"

Rpi will fail to generate a network, In case of RPI zero, any access to board over Wi-Fi will be lost in case this step is not performed.

**Comment by JamesH65** [comment]
No longer relevant.
