### ISSUE TITLE
SPI Documentation Out of Date

### ISSUE THREAD

**Issue by TerryJColes** [raspberrypi/documentation#1649]
Hi,

Over the past few days, I've been trying to understand the capabilities of the SPI Bus(es) on the Raspberry Pi.  Yesterday I raised a query on the Raspberry Pi Forums https://www.raspberrypi.org/forums/viewtopic.php?f=44&t=282970 because I'd found discrepancies between this document and the information at https://pinout.xyz/pinout/spi .  As a result of the responses I received, I raised an issue on the Pinouts GutHub page https://github.com/Gadgetoid/Pinout.xyz/issues/372 .

Since then, various contributors to both sites have agreed that there are discrepancies between the official documentation, what pinout.xyz says and what /boot/overlays/README implies you can do.  The most recent post at the Pinouts GitHub page points out that some of the information in the SPI spec was only valid in 2014.  In particular, the page says that one SPI Bus is available on the Raspberry Pi, whereas others can also be enabled using the overlays in /boot/overlays, depending on the Raspberry Pi Model.

Would it be possible to update the page to include the latest information, in particular:

- How many SPI Buses are available on each type of Pi.
- What the functionality of each bus is, eg, number of CE pins, etc
- How to use the overlays to enable these features (or a link to the necessary information).

I would do this myself, but I fear I still do not understand enough to get this right.

_Edited by lurch to make the URL's clickable_

**Comment by hoshank** [comment]
@TerryJColes   I agree. Even if someone could post links here for a better understanding or books that might have latest information. I started in this field a couple of weeks back.

**Comment by hoshank** [comment]
This looks interesting https://elinux.org/BCM2835_datasheet_errata

**Comment by JamesH65** [comment]
Which page ion our docs is out of date/incorrect?

**Comment by TerryJColes** [comment]
The SPI page; [https://www.raspberrypi.org/documentation/hardware/raspberrypi/spi/README.md](url).

**Comment by hoshank** [comment]
Can we confirm that the clock speed mentioned are from 2014/15 ?
It's  a little sad, the official documentation seemed outdated. Was thinking of reading a book now.

**Comment by lurch** [comment]
> Can we confirm that the clock speed mentioned are from 2014/15 ?

I'm not quite sure what you're asking, but it looks like the [current kernel driver](https://github.com/raspberrypi/linux/blob/rpi-5.4.y/drivers/spi/spi-bcm2835.c#L1086) has a multiple-of-two clock divisor rather than a power-of-two clock divisor.

**Comment by JamesH65** [comment]
I'll need to find someone who knows about SPI on the Pi's. I have no idea, never used it. Will update when I get some information.

**Comment by JamesH65** [comment]
OK, so its does look like we ar e bit behind on that page. However, we currently don;t have manpower to fix it up right now. The elinux page is probably a good reference point for the moment until I have time to update things.

**Comment by lurch** [comment]
Fixed by #1664

**Comment by TerryJColes** [comment]
Nice to see.

Thanks.
