### ISSUE TITLE
Images in this repo are out-of-date

### ISSUE THREAD

**Issue by hackercyclops12** [raspberrypi/documentation#1650]
**Many images referred to / inside the repo are out of date.
Could we consider updating them?**

**Comment by lurch** [comment]
I don't think anybody at Raspberry Pi has the time to look at every image to decide whether it's out-of-date or not, but if you could provide a list of images that you think need updating, that'd probably be useful :slightly_smiling_face:

**Comment by JamesH65** [comment]
This issue will be closed within 30 days unless further interactions are posted. If you wish this issue to remain open, please add a comment. A closed issue may be reopened if requested.
