### ISSUE TITLE
Missing configuration option: max_framebuffers

### ISSUE THREAD

**Issue by YuGiOhJCJ** [raspberrypi/documentation#1656]
Hello,

It seems that there is a missing configuration option in the documentation: `max_framebuffers`.

It is described here:
https://www.raspberrypi.org/forums/viewtopic.php?p=1500422

It has to be added here:
https://www.raspberrypi.org/documentation/configuration/config-txt/video.md

Thank you.
Best regards.

**Comment by JamesH65** [comment]
Fixed.
