### ISSUE TITLE
Mathematica documentation needs updating for 'new' gui

### ISSUE THREAD

**Issue by DeeJay** [raspberrypi/documentation#167]
http://www.raspberrypi.org/documentation/usage/mathematica/README.md needs updating for 'new' gui

"If your SD card was updated since late 2013 then you should have Mathematica and Wolfram pre-installed and should see their icons on the Raspbian desktop:

[[ Wolfram and Mathematica icons ]]

or find the programs in your applications menu under Education."

The revised gui has no application icons on the Desktop by default. There is no 'Education' section in the applications menu.

**Comment by bennuttall** [comment]
See #169
