### ISSUE TITLE
WiFi configuration documentation needs updating for 'new' gui

### ISSUE THREAD

**Issue by DeeJay** [raspberrypi/documentation#168]
http://www.raspberrypi.org/documentation/configuration/wireless/README.md needs updating for 'new' gui

The first option, Using GUI application is a link to http://learn.adafruit.com/adafruits-raspberry-pi-lesson-3-network-setup/setting-up-wifi-with-raspbian

The linked page begins "Raspbian releases after 2012-10-28 include a WiFi configuration utility. You will find the shortcut for this on the Desktop." The illustrative screenshot is outdated.

There are no application icons on the revised Desktop.

(I know RPF can't be held responsible for the content of third-party websites, but perhaps an alternative, current, tutorial could be substituted in the RPF documentation.)

**Comment by bennuttall** [comment]
See #169
