### ISSUE TITLE
csi-2-usage.md links to v4l2 like VIDIOC_G_DV_TIMINGS are broken

### ISSUE THREAD

**Issue by rgl** [raspberrypi/documentation#1681]
The links at https://www.raspberrypi.org/documentation/linux/software/libcamera/csi-2-usage.md for the v4l pages are broken.

For example it links to the latest version of the kernel documentation, but for example, this link about VIDIOC_G_DV_TIMINGS is broken:

https://www.kernel.org/doc/html/latest/media/uapi/v4l/vidioc-g-dv-timings.html

Should this be changed to use a specific kernel version? For example, v5.4:

https://www.kernel.org/doc/html/v5.4/media/uapi/v4l/vidioc-g-dv-timings.html

Or should they be changed to the new page at the following url?

https://www.kernel.org/doc/html/latest/userspace-api/media/v4l/vidioc-g-dv-timings.html

**Comment by lurch** [comment]
ping @naushir @davidplowman @6by9

**Comment by 6by9** [comment]
Yes, kernel.org changed their paths just to make life more interesting.

Replace
```https://www.kernel.org/doc/html/latest/media/uapi```
with
```https://www.kernel.org/doc/html/latest/userspace-api/media```
in all instances.
We don't want to reference any particular kernel release as then we have the maintainence headache every time we change kernel version.

**Comment by JamesH65** [comment]
Updated.
