### ISSUE TITLE
Securing Raspberry PI - sudo visudo command usage

### ISSUE THREAD

**Issue by Zaederx** [raspberrypi/documentation#1685]
While reading the [Securing Raspberry Pi Documentation](https://www.raspberrypi.org/documentation/configuration/security.md)  I found that the command:

 ```bash
sudo visudo /etc/sudoers.d/010_pi-nopasswd
```
 requires "-f" option before specifying file location. So maybe it should be change in the documentation to say:

```bash
sudo visudo -f /etc/sudoers.d/010_pi-nopasswd
```
![IMG_8946](https://user-images.githubusercontent.com/38586415/94154399-bdf80c00-fe75-11ea-80fd-ff7c07ff4e71.jpeg)
![IMG_8947](https://user-images.githubusercontent.com/38586415/94155020-66a66b80-fe76-11ea-8e9e-31582b21b77c.jpeg)

**Comment by JamesH65** [comment]
Odd, works fine for me. Looking at the visudo docs, it looks like the current installed version does not need the -f.


```
-f sudoers, --file=sudoers
                 Specify an alternate sudoers file location, see below.  As of version 1.8.27, the sudoers path can be specified without using the -f option.
```

**Comment by JamesH65** [comment]
Because this works on the latest OS, closing.
