### ISSUE TITLE
Provide more specific detail on updating EEPROM in Pi 4 section of msd.md

### ISSUE THREAD

**Issue by tgelite** [raspberrypi/documentation#1688]
https://www.raspberrypi.org/documentation/hardware/raspberrypi/bootmodes/msd.md

In the "USB mass storage boot" document section for "Raspberry Pi 4" it states:

`Use the Raspberry Pi Imager to install the latest bootloader EEPROM image.`

Which can be confusing.  The suggested change is to state this step clearly by modifying it to read: 

`Use the "Misc Utility Images" option in the Raspberry Pi Imager to create a SD card with the latest "Raspberry Pi 4 EEPROM boot recovery" image.`

**Comment by lurch** [comment]
ping @timg236

**Comment by timg236** [comment]
No objection, raise a PR

**Comment by JamesH65** [comment]
Done
