### ISSUE TITLE
Raspbian MacOS installation uses slow device

### ISSUE THREAD

**Issue by rhiller** [raspberrypi/documentation#170]
In http://www.raspberrypi.org/documentation/installation/installing-images/mac.md the instructions specify the use of /dev/diskn in the `sudo dd bs=1m if=path_of_your_image.img of=/dev/diskn`.

This runs much much faster if instead the raw disk device is used: `sudo dd bs=1m if=path_of_your_image.img of=/dev/rdiskn`.

An internet search of "os x dd very slow" turns up lots of relevant links, including: http://daoyuan.li/solution-dd-too-slow-on-mac-os-x/

**Comment by ebenupton** [comment]
Please propose a pull request.

**Comment by flashspys** [comment]
this issue can be closed. PR is merged
