### ISSUE TITLE
Provide IDF (.emn) file of PCBs for use in MCAD

### ISSUE THREAD

**Issue by phkahler** [raspberrypi/documentation#1700]
Mechanical designs can be done quicker from an IDF file of the board with a minimum feature set:  board outline, mounting holes, and keep-out regions. Parts placement with outline and heights would be even better. Hopefully this is an easy export from the original PCB design tool.

I would imagine these files would go along with the PDF and DXF files here:
https://github.com/raspberrypi/documentation/blob/master/hardware/raspberrypi/mechanical/README.md

**Comment by lurch** [comment]
Duplicate of #1059 ?

**Comment by aallan** [comment]
Yup. Duplicate of #1059
