### ISSUE TITLE
please the revision code of rpi 400

### ISSUE THREAD

**Issue by dogi** [raspberrypi/documentation#1726]
.. to https://github.com/raspberrypi/documentation/blob/master/hardware/raspberrypi/revision-codes/README.md

**Comment by JamesH65** [comment]
That list is not meant to be exhaustive - we update it as and when. The important part is the Pi400 type code which has been updated. If you want to identify a board, you should NOT be using the entire revision code (as it include build location which is irrelevant to board identification and can change as locations change), but extracting the correct bits - e,.g. the type.

**Comment by JamesH65** [comment]
Closing, as revision code will get added over time, but the important stuff (type) has already been updated.
