### ISSUE TITLE
clarify cm4 pin 76

### ISSUE THREAD

**Issue by aep** [raspberrypi/documentation#1727]
in the datasheet, pin 76 is marked as "76 Reserved Do not Connect anything to this pin."
but on the io board pin 76 is SD_DET

please clarify what the pin actually does in the datasheet

**Comment by JamesH65** [comment]
@dp111 FYI

**Comment by dp111** [comment]
It should be not connected. The IO board has a series resistor which is not fitted and so isn't connected

**Comment by JamesH65** [comment]
@dp111 Was this clarified in the recent datasheet changes? Or do we believe is all OK anyway?

**Comment by dp111** [comment]
The datasheet says it is reserved, and it connected to a part that isn't fitted on the CM4IO board so all is okay
