### ISSUE TITLE
Wireless Regulatory Domain [Country Code] in configuration/wireless/desktop.md

### ISSUE THREAD

**Issue by DeeJay** [raspberrypi/documentation#1728]
configuration/wireless/desktop.md says -
"Note that on the Pi 3B+, which supports the 5G protocol, wireless networking is disabled for regulatory reasons, until the country code has been set. "

Presumably this is also true of later hardware, including RPi4B and RPi400 at the time of writing?

**Comment by JamesH65** [comment]
I believe that is correct. I'll update the docs when I get the chance.

**Comment by JamesH65** [comment]
@XECDesign Can you confirm?

**Comment by aallan** [comment]
We should also change 5G to 5GHz, as I'm presuming we're talking about 5GHz wireless networking here, rather than 5G celluar?

**Comment by lurch** [comment]
Is the country code also set by the startup-wizard @spl237 ? If it is, that's probably worth mentioning here too?

**Comment by spl237** [comment]
Yes it is.

**Comment by XECDesign** [comment]
> @XECDesign Can you confirm?

Yup, this applies to al 5GHz models... or should. I may be wrong, but IIRC, CM4 uses a different chip, so I'll need to check that this works before the next image release.

**Comment by JamesH65** [comment]
Fixed on master.
