### ISSUE TITLE
No Audio Output Selection possible

### ISSUE THREAD

**Issue by IsabellLehmann** [raspberrypi/documentation#1736]
Hi, in the documentation (https://github.com/raspberrypi/documentation/blob/master/configuration/audio-config.md) it is explained how to set the Audio Output.

However, maybe there was an update, but I do not have this option on my raspberry Pi 4B. I installed the current version of Raspbian and also used sudo apt-get update and upgrade to really get the newest version.

This is how my menu looks:
![image](https://user-images.githubusercontent.com/47631771/99440767-54492b00-2917-11eb-8609-182ed4fe8cb7.png)
and in the advanced options:
![image](https://user-images.githubusercontent.com/47631771/99440844-6aef8200-2917-11eb-94b9-2a2bd68e6809.png)
So there is no possiblity to change the audio output.

**Comment by IsabellLehmann** [comment]
The documentation needs to be updated that the audio is now set in the System options:
![image](https://user-images.githubusercontent.com/47631771/99441394-17316880-2918-11eb-94da-16f903b2f846.png)

**Comment by lurch** [comment]
I agree that the documentation about `raspi-config` is probably outdated (see also e.g. #1041 ), but FYI you can also control most of these raspi-config options using the "Raspberry Pi Configuration" GUI program, which you can find in the "Preferences" menu on the desktop. Except the audio options, which you can configure by right-clicking on the Volume icon in the top-right corner of the screen :slightly_smiling_face:

**Comment by JamesH65** [comment]
OK, have updated the page to remove the images (they are such a PITA to keep updated) and corrected the usage to reflect the current version of raspi-config.
