### ISSUE TITLE
[WONTFIX] Raspberry Pi camera raw sample coverage wanted

### ISSUE THREAD

**Issue by LebedevRI** [raspberrypi/documentation#1741]
Hello.

@dustinkerstein is asking for native darktable / rawspeed support
for Raspberry Pi camera raws in https://github.com/darktable-org/darktable/issues/6998.
However, to do that, we need to have a reasonable test coverage,
i.e. to have one raw image from each possible camera.
There's a public repository for such images - https://raw.pixls.us/ - all new contributions are under CC0 license.

So we were wondering if people could help with samples.

X-Ref: https://github.com/darktable-org/darktable/issues/6998 https://github.com/schoolpost/PyDNG/issues/30 https://github.com/waveform80/picamera/issues/657 https://github.com/raspberrypi/documentation/issues/1741

**Comment by JamesH65** [comment]
Not really a docs issue, so locking, but the data is here for future reference. 

You could try posting on the Raspberry Pi forums. Lots of active camera users on there.
