### ISSUE TITLE
computers/configuration/headless.adoc contains an error

### ISSUE THREAD

**Issue by NielsGx** [raspberrypi/documentation#1748]
Hello,

in the headless.md file, you should say that we need to copy the wpa_supplicant.conf file into the boot partition, instead of saying boot folder.
I thought I needed to mount the ext4 partition, and then copy the wpa file into the boot folder, which is clearly not the same location than in the small boot partition.

You could inspire yourself from documentation/remote-access/ssh/README.md :

"For headless setup, SSH can be enabled by placing a file named ssh, without any extension, onto the boot partition of the SD card from another computer. When the Pi boots, it looks for the ssh file. If it is found, SSH is enabled and the file is deleted.[...]"

and also this in the end :

"If you have loaded Raspberry Pi OS onto a blank SD card, you will have two partitions. The first one, which is the smaller one, is the boot partition. Place the file into this one."

**Comment by lurch** [comment]
Does https://github.com/raspberrypi/documentation/commit/9c649c9602069c3973c7d741c15bf07152227132 help ? :slightly_smiling_face:

**Comment by NielsGx** [comment]
No.

As I said, boot partition and boot folder is not the same thing. Should be boot partition, the only partition that is readable/writable natively by windows mac OS. Should be a fat32 partition, if you used the imager tool, at least on windows.


As I said, there's a boot FOLDER in the other partition, the "real" partition, in ext3/ext4. And it's not here we should put the files..

Thanks for your help.

**Comment by NielsGx** [comment]
for a lite image, the fat32 boot partition is like 300mb, and the "real" ext4 partition is more than 1Gb.

So ssh and wpa_supplicant have to be out in the root of boot PARTITION. 

not in the real partition/boot folder.

**Comment by NielsGx** [comment]
replacing the word folder by partition and adding this at the end should be enough imho.

"If you have loaded Raspberry Pi OS onto a blank SD card, you will have two partitions. The first one, which is the smaller one, is the boot partition. Place the file into this one."

**Comment by aallan** [comment]
Source file now lives at computers/configuration/headless.adoc

**Comment by aallan** [comment]
...and has been reworded.
