### ISSUE TITLE
suggested pip usage on installing python packages is buggy 

### ISSUE THREAD

**Issue by djh42** [raspberrypi/documentation#1752]
documentation/linux/software/python.md suggests using `sudo pip` in several places. This is wrong and dangerous. Please see [(https://github.com/pypa/pip/issues/5599)] for further details

**Comment by lurch** [comment]
Feel free to create a PR with the "correct" usage :slightly_smiling_face:

**Comment by djh42** [comment]
Sorry I'm not a python expert, just a python user who got caught by this documentation error. I wouldn't know how to word it.

**Comment by JamesH65** [comment]
So why is it dangerous and wrong? Need to know before any changes are made.

**Comment by aallan** [comment]
Potentially closing ahead of #1911.
