### ISSUE TITLE
Raspberry Pi Revision c03114 not in the list

### ISSUE THREAD

**Issue by tom-2015** [raspberrypi/documentation#1760]
Seems like revision c03114 is missing in the documentation.
[https://www.raspberrypi.org/documentation/hardware/raspberrypi/revision-codes/README.md](url)

Does anyone know if there are other revision numbers missing?

**Comment by JamesH65** [comment]
Probably - that list is never exhaustive, I just update it every now and again. Using the table above to correctly decode the revision number.

**Comment by JamesH65** [comment]
I've updated the table to include the code you have.
