### ISSUE TITLE
Update the over_voltage ranges for Pi 4

### ISSUE THREAD

**Issue by worproject** [raspberrypi/documentation#1772]
over_voltage can be set above 8 on a Pi 4 (15 seems to be the maximum)
The same limit might apply to the over_voltage_sdram_ values too.

Can someone confirm this?

**Comment by lurch** [comment]
ping @popcornmix

**Comment by popcornmix** [comment]
It is chip specific and subject to change if dvfs settings are tweaked. 
over_voltage adds an offset to the default voltage, which varies with chip. 
On Pi4 the minimum voltage a chip could run at is 0.83V. The max is 1.1V.
So in theory the maximum effective over_voltage is 270mV, so ~11 25mV units.
But most chips would run at a higher voltage than the minimum, so their effective range would be smaller.

As voltages are clamped to 1.1V setting a higher over_voltage will have no addional effect.

**Comment by aallan** [comment]
OP should reopen if this hasn't answered your question.
