### ISSUE TITLE
tvservice docs missing -l and -v options

### ISSUE THREAD

**Issue by 6by9** [raspberrypi/documentation#1777]
https://www.raspberrypi.org/documentation/raspbian/applications/tvservice.md
-l to list all devices and -v N to get the status of a specific device are missing.

**Comment by lurch** [comment]
Fancy creating a PR? :wink:

**Comment by 6by9** [comment]
> Fancy creating a PR?

No time at the moment, sorry.
I had Gordon not being aware of them this morning hence creating the issue.

**Comment by andrum99** [comment]
Let me see what I can do 😉

There's also a PR open on the userland repo - https://github.com/raspberrypi/userland/pull/663 could integrate - which would add man pages for `tvservice` and most of the other userland binaries.

Note that there is basic usage available from `tvservice` itself by invoking it with no parameters: this includes just about enough information to let you figure out how to use the -l and -v N options.

**Comment by andrum99** [comment]
See #1778

**Comment by andrum99** [comment]
Fixed by #1778

**Comment by andrum99** [comment]
Fixed by https://github.com/raspberrypi/documentation/commit/94be38c47cecea2ea3551d1be24f05783c97397d
