### ISSUE TITLE
Blank monitor

### ISSUE THREAD

**Issue by cowboysdude** [raspberrypi/documentation#1780]
I still cannot find anywhere the instructions on how to blank the monitor or unblank the monitor via the command line.  Commands for the Pi3 do not work.

Did I miss something somewhere?

**Comment by JamesH65** [comment]
Do you mean turn the HDMI on/off, or simply blank? Does this page help? https://www.raspberrypi.org/documentation/configuration/screensaver.md

**Comment by cowboysdude** [comment]
Yes turn HDMI on/off.

**Comment by michaelstoops** [comment]
`vcgencmd display_power 0` does what you want.

Does the updated documentation here help? https://github.com/michaelstoops/documentation/commit/c1b7c4c55603d4da545cd5393fbced4c26330f76

**Comment by michaelstoops** [comment]
PR: https://github.com/raspberrypi/documentation/pull/1848
