### ISSUE TITLE
external storage

### ISSUE THREAD

**Issue by street-grease-coder** [raspberrypi/documentation#1786]
https://github.com/raspberrypi/documentation/blob/master/configuration/external-storage.md

would be nice if it included an option to automatically mount in case usb device gets disconnected / reconnected, i.e. mount at 'plug-in' time

**Comment by lurch** [comment]
> mount at 'plug-in' time

It already _does_ do that automatically? As that page notes: "By default, your Raspberry Pi automatically mounts some of the popular file systems such as FAT, NTFS, and HFS+ at the /media/pi/<HARD-DRIVE-LABEL> location."

Or are you asking for something else?

**Comment by street-grease-coder** [comment]
no, I overlooked this, thank you, mea culpa
