### ISSUE TITLE
Wrong filename for dd command in Linux install, should end in raspbian-wheezy.img not wheezy-raspbian.img

### ISSUE THREAD

**Issue by jaypl** [raspberrypi/documentation#179]
[/installation/installing-images/linux.md](https://github.com/raspberrypi/documentation/blob/master/installation/installing-images/linux.md) :raising_hand:

**Comment by lurch** [comment]
Hmmm, the same problem as https://github.com/raspberrypi/documentation/commit/1adf5e7384992b60a7b273e68c3e76b3a916ca63 which means it wasn't the 'simple error' just in `mac.md` that I first thought. So I looked into a bit more, and found that all [previous versions of Raspbian](http://downloads.raspberrypi.org/raspbian/archive/) were named like `YYYY-MM-DD-wheezy-raspbian.img`, except for the last two versions, which were named `2015-01-31-raspbian.img` and `2015-02-16-raspbian-wheezy.img`.
Temporary naming-convention blip, @asb ?
