### ISSUE TITLE
RP2040 Datasheet - Page 179 - Figure 20 - Capacitor Unit

### ISSUE THREAD

**Issue by Muny** [raspberrypi/documentation#1797]
Link to datasheet: https://datasheets.raspberrypi.org/rp2040/rp2040_datasheet.pdf

I noticed a slight typo in the voltage regulator application circuit figure. The capacitor connected to the bottom DVDD pin has a unit of "µnF". I believe this should be just "nF".

Edit: Just realized this probably isn't the right place for this. Not really sure where to direct this then.

**Comment by lurch** [comment]
If you could report this at https://github.com/raspberrypi/pico-feedback that'd be great thanks :+1:
