### ISSUE TITLE
NOOBS [https://www.raspberrypi.org/documentation/installation/]

### ISSUE THREAD

**Issue by DeeJay** [raspberrypi/documentation#1801]
The NOOBS Installer is no longer available for download from the Software page.

https://www.raspberrypi.org/documentation/installation/ says "Beginners should start with NOOBS, "

**Comment by lurch** [comment]
Fixed by https://github.com/raspberrypi/documentation/commit/b266375f59ae6f3ab13122113ea1d97e11ef704e
