### ISSUE TITLE
NOOBS [ https://www.raspberrypi.org/documentation/installation/noobs.md ]

### ISSUE THREAD

**Issue by DeeJay** [raspberrypi/documentation#1802]
The NOOBS Installer is no longer available for download from the Software page.

The now-orphaned NOOBS installation guide https://www.raspberrypi.org/documentation/installation/noobs.md says -

"Download
Alternatively, NOOBS is available for download on the Raspberry Pi website: raspberrypi.org/downloads"

There does not seem to be a relevant link on that page, since Raspberry Pi Imager is now the preferred/promoted installation tool.

**Comment by vj-codes** [comment]
@aallan @lurch @JamesH65 @DeeJay hey I would like to work on this please, suggest removing the alternative part completely as we can't download it from the website anymore, what say?

**Comment by JamesH65** [comment]
I've made a couple of changes that should help push people towards Imager, but if anyone see's anywhere else that NOOBS is still highlighted, please report here.

**Comment by aallan** [comment]
Going forward I don't see the NOOBS documentation making the cut when we're revising the repo to the new documentation-ng structure. We're going to be sliming down the documentation considerably, so it'll be a good opportunity to remove deprecated stuff like this.

**Comment by lurch** [comment]
I think this might have been "fixed" by https://github.com/raspberrypi/documentation/commit/43e973420515e9895a228314f5918585393a4d14  :shrug:

**Comment by vj-codes** [comment]
@lurch oh yeah, this issue and #1815 can be closed then
