### ISSUE TITLE
Add fix for wireless AP not visible after reboot

### ISSUE THREAD

**Issue by crosland** [raspberrypi/documentation#1806]
documentation/configuration/wireless/access-point-routed.md should explain the fix for wireless AP not working after reboot. See forum topic https://www.raspberrypi.org/forums/viewtopic.php?&t=209818

**Comment by aallan** [comment]
If someone can provide a pull request, that'd be great!

**Comment by lurch** [comment]
a) I've just read through the linked forum thread, and it's not clear what "the fix" is?

b) The last post to that thread was over 2 years ago, so _maybe_ this is no longer a problem on the latest versions of Raspberry Pi OS? :man_shrugging:

**Comment by aallan** [comment]
@ghollingworth is this still an issue that needs fixing in the docs, or did it get fixed in software?
