### ISSUE TITLE
NGINX web server setup document contains inconsistent references to both php5 and php7.0, should be php7.3

### ISSUE THREAD

**Issue by adrianyorke** [raspberrypi/documentation#1811]
This issue relates to NGINX web server setup document which can be found here:
https://github.com/raspberrypi/documentation/blob/master/remote-access/web-server/nginx.md

In the section labelled "Edit by removing the `#` characters on the following lines:" there is a reference to php5 in the following line:
```
fastcgi_pass unix:/var/run/php5-fpm.sock;
```

This should read:
```
fastcgi_pass unix:/run/php/php7.3-fpm.sock;
```

Also update this line later in the same document which references php7.0 to be consistent:
```
fastcgi_pass unix:/var/run/php/php7.0-fpm.sock;
```

**Comment by aallan** [comment]
This is resolved by #1812 I think?
