### ISSUE TITLE
Add Pi2 details and specs

### ISSUE THREAD

**Issue by lurch** [raspberrypi/documentation#182]
Just like #132, but for the Raspberry Pi 2 Model B ;)

Also, where things used to say "Model A", "Model B+", etc. should these now be updated to "Pi1 Model A", "Pi1 Model B+", or is there some other official nomenclature that should be used?  Something to add to https://github.com/raspberrypilearning/creating-resources/blob/master/style.md ?

**Comment by lurch** [comment]
Also needs adding to http://www.raspberrypi.org/documentation/hardware/raspberrypi/models/

**Comment by ebenupton** [comment]
Ben to clean up

**Comment by lurch** [comment]
After seeing #199 I went looking for the "model specs" page on http://www.raspberrypi.org/documentation/ and was confused when I couldn't find it. I eventually discovered that I couldn't find it because of https://github.com/raspberrypi/documentation/commit/f68bfc961423aa200bb7fea610f0a255bf32f73a ;-)

I can see how `hardware/raspberrypi/models/README.md` (originally added by @JamesH65 ) is a bit of a duplication of http://www.raspberrypi.org/products/ , but IMHO the `hardware/raspberrypi/models/specs.md` page **is** still useful, which now has no links to it. When Ben gets round to tackling this issue (I know he's still busy with resources stuff) maybe he could add a link to `hardware/raspberrypi/models/specs.md` from somewhere else?

**Comment by ebenupton** [comment]
I think the conclusion was to retire the specs page completely, and to move any useful information onto the main website product pages.

________________________________

**Comment by flashspys** [comment]
Is the Peripheral specification for the BCM2836 (Pi2's cpu) already somewhere in the internet? We need it because some adresses were changed.

**Comment by P33M** [comment]
See https://github.com/raspberrypi/documentation/commit/b0639f5a3ff6ba9b5006c62d643403d97408b1f7 for details on how the Cortex-A7 cluster on BCM2836 has been implemented.

Other than that, Pi2 is basically identical to a B+ in terms of mechanical layout.

**Comment by bennuttall** [comment]
Are we dropping specs or updating them? They ought to be on the product pages really...

**Comment by ebenupton** [comment]
We should retire this page.
