### ISSUE TITLE
Constant Low Voltage Message Despite Adequate Voltage/Current Supplied

### ISSUE THREAD

**Issue by MachineSaver** [raspberrypi/documentation#1822]
My touchscreen is constantly displaying a message that tells me to check my voltage.
Used a digital multi-meter to verify that the voltage was adequate (5.015V with a supply that will give up to 2 Amps).
I am not sure how to handle this message as it seems that the device is supplying adequate voltage.
The screen and the Raspberry Pi both work well, other than this seemingly unnecessary message.

**Comment by aallan** [comment]
This is the sort of question you should be asking on the [forums](https://www.raspberrypi.org/forums/), so I’m closing this issue. But please follow up with further comments if you have specific questions about the [documentation](https://www.raspberrypi.org/documentation/).
