### ISSUE TITLE
My Touches on Official Touchscreen are Way Off

### ISSUE THREAD

**Issue by wjm103052** [raspberrypi/documentation#1824]
I have a new raspi 4 and an official 7" touchscreen. The touches are ok in the upper left corner and the error increases as you go to the lower right where it is 1/2 inch off. This makes the screen unusable as you can't even close a window.

I have followed all of the troubleshooting tips and the problem persists. Any help to solve this would be appreciated.

Bill

**Comment by wjm103052** [comment]
The problem is with my openplotter app and not with regular pi os.

**Comment by lurch** [comment]
Thanks for closing the issue so promptly, but in future questions like this are better suited for the https://www.raspberrypi.org/forums/ rather than the documentation repo :slightly_smiling_face:
