### ISSUE TITLE
Not an issue - just a suggestion

### ISSUE THREAD

**Issue by fdl333** [raspberrypi/documentation#1829]
Thank you very much for your clear guide!

I was interested in booting libreelec (the KODI OS) from HD.

I followed you instructions, but :
- copied Raspbian on the MicroSD (as you instruct)
- copied the latest libreelec image on the SD instead of raspbian.. it works

Worked like a charm!

**Comment by lurch** [comment]
This sounds like a discussion for the forums https://www.raspberrypi.org/forums/ rather than an issue for the documentation repo?
