### ISSUE TITLE
document ipv6 routed access point

### ISSUE THREAD

**Issue by jimmont** [raspberrypi/documentation#1834]
please expand the material in the following documentation to include details for routing ipv6, thank you
https://www.raspberrypi.org/documentation/configuration/wireless/access-point-routed.md
https://github.com/raspberrypi/documentation/blob/master/configuration/wireless/access-point-routed.md

**Comment by JamesH65** [comment]
This will be a useful addition, however, I don't believe we have anyone in house with the relevant experience and/or time to do this at the moment.

I would be more than happy to accept a PR from anyone who does have that experience.

**Comment by jimmont** [comment]
Thanks @JamesH65 I started working through the details and if successful plan to open a PR (provided no one beats me to it).

**Comment by aallan** [comment]
Is this issue resolved by #1318?

**Comment by lurch** [comment]
> Is this issue resolved by #1318?

Nope - #1318 seems to be about forwarding an external IPv6 connection into your internal network (e.g. if you want to make a webserver running on your Pi reachable by the whole internet), whereas this seems to be asking for details of setting up an internal IPv6 wireless network?
