### ISSUE TITLE
pip-3.2

### ISSUE THREAD

**Issue by paddywwoof** [raspberrypi/documentation#184]
any chance of changing pip-3.3 to pip-3.2 in 
documentation/linux/software/python.md
to make whole thing a little less confusing for people new to python (ideally raspbian would have called it pip3 to avoid the inevitable confusion which will happen once the switch to jessie happens (bugs.debian.org/release-critical/))

**Comment by lurch** [comment]
Fixed, thanks. This doesn't have anything to do with Jessie, but it looks like addf098 was wrong in introducing mentions of pip-3.3
\#BlameNuttall ;-)

**Comment by bennuttall** [comment]
Yeah the use of `pip-3.3` just a mistake.

But yeah what you said about `pip`, `pip2` and `pip3` is correct. Hopefully we'll move to those soon or when we upgrade to Jessie.
