### ISSUE TITLE
Win32DiskImager now downloads as a .exe file instead of a .zip

### ISSUE THREAD

**Issue by lurch** [raspberrypi/documentation#185]
[installation/installing-images/windows.md](https://github.com/raspberrypi/documentation/blob/master/installation/installing-images/windows.md) says "Download the Win32DiskImager utility from the Sourceforge Project page (it is also a zip file); you can run this from a USB drive." but the link to SourceForge now downloads `Win32DiskImager-0.9.5-install.exe` by default, which means the documentation now needs updating.
(It means it can't be run from a USB drive, but there's now no need to **Run as administrator** as it requests elevated privileges itself)

**Comment by JamesH65** [comment]
Fixed by #544

**Comment by JamesH65** [comment]
Fix merged.
