### ISSUE TITLE
UART 2-5 on Debian buster

### ISSUE THREAD

**Issue by lokeb** [raspberrypi/documentation#1852]
I am trying to enable UARTs 2-5 on Debian buster. I have added the following lines to config.txt, but it seems to have no effect. 
```
dtoverlay=uart2
dtoverlay=uart3
dtoverlay=uart4
dtoverlay=uart5
```
I see `/dev/ttyS0`, `/dev/ttyS1`, `/dev/ttyS2`, `/dev/ttyS3` with or without them.

kernel version:
Linux 5.9.0-0.bpo.5-arm64 #1 SMP Debian 5.9.15-1~bpo10+1 (2020-12-31) aarch64 GNU/Linux

vcgencmd version:
Jun  1 2020 13:23:40 
Copyright (c) 2012 Broadcom
version 6379679d1ec6a8c746d7e77e015f5b56b939976f (clean) (release) (start)

**Comment by lurch** [comment]
I believe you want to look at `/dev/ttyAMA*` rather than `/dev/ttyS*` ?

**Comment by lokeb** [comment]
They are not present on Debian. 

Regards
Loknath Bharti

**Comment by lurch** [comment]
Problem for Debian, not a problem with the Raspberry Pi documentation.
