### ISSUE TITLE
Link to aspects depending on the pi user

### ISSUE THREAD

**Issue by Gatada** [raspberrypi/documentation#1863]
Currently it is suggested to leave the `pi` user intact as "there are some aspects that require the pi user to be present".

It would be quite helpful to add a reference to those "aspects"; I assume that somewhere these are listed (I'm just not able to find it).

**Comment by lurch** [comment]
This is probably a question for @XECDesign and @spl237 ?

**Comment by XECDesign** [comment]
A lot of the hard-coded references to 'pi' have been removed, but I can't promise that all of them have been. The suggestion is just there to save headaches if somebody happens to stumble upon more.

**Comment by aallan** [comment]
Will probably get resolved by #1911.
