### ISSUE TITLE
Mechanical drawings etc for A+, Pi 2 and other new toys

### ISSUE THREAD

**Issue by ebenupton** [raspberrypi/documentation#188]
Sticking this in here so we don't forget.

**Comment by ebenupton** [comment]
Dummy comment.

**Comment by hultqvist** [comment]
I assume [MECHANICAL DRAWINGS](https://www.raspberrypi.org/documentation/hardware/raspberrypi/mechanical/README.md) is the page that needs updating.

I've read in a random forum thread that that RPi 2 uses almost the same machanical schematics as the Rpi 1 B+, if that is the case it would really help if a note about that was added to the page.

**Comment by JamesH65** [comment]
@Roger-Thornton Roger, si there anything we need/can add to the mechanical drawings page? Or is it as complete as we can do?

**Comment by JamesH65** [comment]
See also #517

**Comment by lurch** [comment]
#642 claims to have closed this, but #642 didn't add a mechanical drawing for the A+ ?

**Comment by stefanwendelmann** [comment]
Yes a mechanical drawing fpr A+ is still missing :(

**Comment by lurch** [comment]
Just like #382 , perhaps this should be re-opened?

**Comment by JamesH65** [comment]
Yes, it is missing, had a quick chat the other day with the person who
deals with this - its will get done, but we are extremely busy at the
moment with more important stuff. I'll reopen the issue.

On 9 February 2018 at 08:42, Andrew Scheller <notifications@github.com>
wrote:

> Just like #382
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_raspberrypi_documentation_issues_382&d=DwMCaQ&c=DpyQ_ftY536pf7wCBQXXU58xADDRY77THQzJu1OmzOo&r=w09_2ePv8G3zRjoV19Wm1Q6rI7CDlOns4PuRv2hHkek&m=GnChKIQL08hb_R3Rlrxn7Pr87mTnNp8VatqNyDUPko4&s=XkffC5ee7jpumA1XVQ47r1TmZI93oV6PPmTeC0gfpsQ&e=>
> , perhaps this should be re-opened?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_raspberrypi_documentation_issues_188-23issuecomment-2D364370658&d=DwMCaQ&c=DpyQ_ftY536pf7wCBQXXU58xADDRY77THQzJu1OmzOo&r=w09_2ePv8G3zRjoV19Wm1Q6rI7CDlOns4PuRv2hHkek&m=GnChKIQL08hb_R3Rlrxn7Pr87mTnNp8VatqNyDUPko4&s=LQ3yJ_791LSARU-CUYpiNvWEg3VVjEvTEeJV4Ck9ZVs&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ADqrHQ-5F0IFjZGNsc9HKF9rGOTQG-5FnmOsks5tTATigaJpZM4DpePx&d=DwMCaQ&c=DpyQ_ftY536pf7wCBQXXU58xADDRY77THQzJu1OmzOo&r=w09_2ePv8G3zRjoV19Wm1Q6rI7CDlOns4PuRv2hHkek&m=GnChKIQL08hb_R3Rlrxn7Pr87mTnNp8VatqNyDUPko4&s=zlBY4MJcxu1E5NFco91w9p4Jr-0DDZiEv8I6rVSybyA&e=>
> .
>



-- 
James Hughes
Principal Software Engineer,
Raspberry Pi (Trading) Ltd

**Comment by JamesH65** [comment]
@Roger-Thornton Did we ever get the missing A+ drawing done?

**Comment by matthieu-lapeyre** [comment]
I raise my hand as well to get a Raspberry Pi 3 A+ mechanical drawing with the precise position of each I/O port. 
It should not require more than a half an hour to get it done. I can help if you miss time to do it.

**Comment by JamesH65** [comment]
OK, just uploaded the 3A+ (also applicable to A+) drawing to the github repo, should be online on the main website within an hour.

**Comment by JamesH65** [comment]
I'm going to close this as its been around a bit; if there are missing diagrams, please start a new issue for each missing item.
