### ISSUE TITLE
Proposal: grouping by categories (hardware/raspberrypi)

### ISSUE THREAD

**Issue by wancom** [raspberrypi/documentation#1880]
https://github.com/raspberrypi/documentation/blob/master/hardware/raspberrypi/README.md
In this page, we can see the a lot of items.
I believe they are necessary, however, it may be a little difficult to find the items we need.

I suggest that making groups by categories.
This is my suggested version.
https://github.com/wancom/documentation/blob/group_by_cat/hardware/raspberrypi/README.md

(I referred the page for layout: https://github.com/raspberrypi/documentation/blob/master/linux/README.md)

I believe there is much room for discussion. Sorry for the poor suggestion.

I hope this issue makes better the documentation.

**Comment by lurch** [comment]
See #1911
