### ISSUE TITLE
Documentation for Raspberry Pi OS is still filed under raspbian

### ISSUE THREAD

**Issue by mrlowndes** [raspberrypi/documentation#1884]
Could we change the path to Documentation > Raspberry Pi OS instead?

<img width="897" alt="Screen Shot 2021-04-21 at 3 10 49 PM" src="https://user-images.githubusercontent.com/45582888/115627413-cdc4bb00-a2b3-11eb-8385-f46f1fc6f926.png">

**Comment by JamesH65** [comment]
@mudge This is one for you I think.

**Comment by lurch** [comment]
@aallan is going to be having a big docs refactoring at some point, so this might be better tackled as part of that?

**Comment by JamesH65** [comment]
Now that I think about it, this rings a bell. I think to prevent external links to the docs breaking, we left that folder named Raspbian.

**Comment by aallan** [comment]
Yup. This is already on my list to fix during the `documentation-ng` refactor.

**Comment by aallan** [comment]
> Now that I think about it, this rings a bell. I think to prevent external links to the docs breaking, we left that folder named Raspbian.

Yes. We can get @mudge to fix up the redirects when the time comes to deploy.
