### ISSUE TITLE
Touch Screen Orientation X-axis is not working

### ISSUE THREAD

**Issue by engrr-usama** [raspberrypi/documentation#1891]
I have used the Official Guide given here:
[https://www.raspberrypi.org/documentation/hardware/display/](url)
and I have tried all of the possible variations by changing touchscreen-inverted-x, touchscreen-inverted-y from 0 to 1 four binary pairs
`dtoverlay=rpi-ft5406,touchscreen-swapped-x-y=1,touchscreen-inverted-x=0, touchscreen-inverted-y=1`
But the X-Axis pointer is going in the opposite direction while Up-Down is working correctly.
I'm using **90 degrees** Rotation.

**Comment by lurch** [comment]
This sounds like a question for the https://www.raspberrypi.org/forums/ rather than for the documentation repo?
But if you manage to find a working solution, feel free to add a PR (Pull Request) updating / clarifying the documentation repo with your discoveries :slightly_smiling_face:
