### ISSUE TITLE
[help]UFW, iptables, firewalld can not enable port, do not know how to enable

### ISSUE THREAD

**Issue by Conmi-WhiteJoker** [raspberrypi/documentation#1898]
I tried using them to open port 3306, but never succeeded.However, if SSH is checked in the "raspi-config", port 22 will open normally.
I don't know if the Raspberry Pi has updated any firewall Settings, it used to be able to open port 3306 directly using UFW.
I might need a little help.
Thank you.

**Comment by Conmi-WhiteJoker** [comment]
Can someone give me a hand?

**Comment by aallan** [comment]
This is the sort of question you should be asking on the [forums](https://www.raspberrypi.org/forums/) as this repo is for documentation, so I’m closing this issue. But please follow up with further comments if you have specific questions about the [documentation](https://www.raspberrypi.org/documentation/).

**Comment by Conmi-WhiteJoker** [comment]
> 这是你应该在[论坛上](https://www.raspberrypi.org/forums/)问的问题， 因为这个回购是文档， 所以我要结束这个问题。但是，如果您对[文档](https://www.raspberrypi.org/documentation/)有具体问题，请跟进进一步的评论。

Okay, thank you.

**Comment by Conmi-WhiteJoker** [comment]
> This is the sort of question you should be asking on the [forums](https://www.raspberrypi.org/forums/) as this repo is for documentation, so I’m closing this issue. But please follow up with further comments if you have specific questions about the [documentation](https://www.raspberrypi.org/documentation/).

Okay, thank you.
