### ISSUE TITLE
Wrong specs on Raspberry Pi official website 

### ISSUE THREAD

**Issue by rusigenev** [raspberrypi/documentation#1908]
Hello,
On the [official website](https://www.raspberrypi.org/products/raspberry-pi-4-model-b/specifications/)   the product tech specification for the Pi 4 are not up to date - the graphic specs are saying “OpenGL ES 3.0 graphics” which is not correct any more. Can someone please update this to “OpenGL ES 3.1” and maybe add Vulkan 1.0?
Ps.  There are probably other places that need to be updated (as pdf-s and so)
Thanks

**Comment by aallan** [comment]
Thanks, we'll direct that to the correct person internally.
