### ISSUE TITLE
Documenting GPIO 3's "wake from HALT" function

### ISSUE THREAD

**Issue by Gadgetoid** [raspberrypi/documentation#1935]
As raised in https://github.com/Gadgetoid/Pinout.xyz/pull/413 there doesn't appear to be any primary source of documentation for the "wake" functionality exposed by GPIO 3 (Physical pin 5).

Some scant, out of date documentation is available here - https://elinux.org/RPI_safe_mode#cite_note-1

And there are a scattering of other references, forum posts and mentions- many lamenting the lack of documentation, but nothing canonical.

1. Would this be an appropriate addition this documentation?
2. Where would it fit?

Points we should probably cover:

1. Works only in HALT state when the Pi still has power
2. GPIO 3 was chosen due to the external, strong pull-up that keeps the pin in a known state and avoids accidental wakes
3. Pin cannot be changed
4. Should be shorted to ground via a button to trigger a wake (physical pin 6 is *right there*)
5. Which versions of the Pi is this supported on? (All? or post a given firmware version?)

**Comment by aallan** [comment]
> 1. Would this be an appropriate addition this documentation?

Yes

> 2. Where would it fit?

Bearing in mind the looming nature of #1911…

Potentially as a section in the [GPIO](https://github.com/raspberrypi/documentation/tree/master/hardware/raspberrypi/gpio) documentation?

**Comment by lurch** [comment]
Or possibly somewhere in https://github.com/raspberrypi/documentation/tree/master/hardware/raspberrypi/bootmodes ? :shrug:

**Comment by aallan** [comment]
> Or possibly somewhere in https://github.com/raspberrypi/documentation/tree/master/hardware/raspberrypi/bootmodes ? 🤷

Jinx! I just edited my comment to add that one. 😁

**Comment by aallan** [comment]
I'm probably going to be freezing the current markdown-based documentation tree, and deleting any pending PRs, at the end of the week (see #1911 for more information as to why). It probably makes sense to pause this until after the new documentation site is released and then PR ontop of the new Asciidoc documentation (end of the month maybe?)

**Comment by Gadgetoid** [comment]
I’d figured as much. I’d need to get a feel for the new style/format and figure out where to put this. Plus get some authoritative answers about the what’s, why’s and where’s of it all 🤣

**Comment by aallan** [comment]
New site is live! 😄

**Comment by Gadgetoid** [comment]
It's... uh... nice n'all... but a little bit completely broken without Javascript... and somewhat difficult to browse when it runs on continuously with no pagebreaks and very little differentiation between first and second level headers :grimacing:
