### ISSUE TITLE
Kernel building guide does not work with newer kernels (5.8? onwards)

### ISSUE THREAD

**Issue by neilzone** [raspberrypi/documentation#1936]
The [current guide](https://www.raspberrypi.org/documentation/linux/kernel/building.md) says:

`make -j4 zImage modules dtbs`

This produces the error:

`No rule to make target 'zImage'. Stop`

Instead, one needs to use:

`make -j4 Image modules dtbs`

**Comment by ghollingworth** [comment]
@pelwell I recently rebuilt the kernel and had trouble with the 64bit but not with the 32bit...

Not sure what the right thing is here, but we could do with a quick check through for both local and cross compiling...

**Comment by aallan** [comment]
Source file now lives at computers/linux_kernel/building.adoc

**Comment by aallan** [comment]
@ghollingworth Did you have time to check this?
