### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by dasrecord** [raspberrypi/documentation#1937]
dead link appears on this page: [Setting up an Apache Web Server on a Raspberry Pi](https://github.com/raspberrypi/documentation/blob/master/remote-access/web-server/apache.md)

-->> "https://github.com/raspberrypi/documentation/blob/master/usage/wordpress/README.md" leads to 404

**Comment by aallan** [comment]
Thanks. I've removed the link to the 404'ed page.
