### ISSUE TITLE
Raspberry Pi GPIO controller

### ISSUE THREAD

**Issue by JanF-04** [raspberrypi/documentation#1945]
I want to program a smart home system in python which controls a 433 mHz transmitter and several relais. Is there any software currently available for the Raspberry Pi OS which supports controlling the GPIOs from different scripts at the same time. Please notive I do not just want to turn the relais on or off, but also switch the current state. 
I would ask this question on the official forum, but the registration has some problems and all of my email adresses do not work...
Thanks for helping...
JanF_04

**Comment by lurch** [comment]
This is definitely a question more suitable for the forums, but in the meantime you might find that http://abyz.me.uk/rpi/pigpio/pigpiod.html does what you're looking for?
