### ISSUE TITLE
External storage configuration: automount

### ISSUE THREAD

**Issue by dkoehler69** [raspberrypi/documentation#1949]
The page at  documentation/configuration/external-storage.md  says:

By default, your Raspberry Pi automatically mounts some of the popular file systems such as FAT, NTFS, and HFS+ at the /media/pi/<HARD-DRIVE-LABEL> location.

This does not work for me. The /media folder was and remained empty. I was able to manually add a mount point and make it automount by editing /etc/fstab.

OS: Raspbian GNU/Linux 10 (buster), Lite version, 64bit kernel activated.
External drive: Seagate Backup Plus, 2 TByte, NTFS.

Perhaps the Lite version does not include automount? If this is the case, then it should by mentioned in the documentation.

**Comment by lurch** [comment]
ping @spl237  Does automount only work when you're running the graphical version of Raspberry Pi OS?

**Comment by aallan** [comment]
We have fuse installed by default so yes it should work..?

**Comment by spl237** [comment]
> ping @spl237 Does automount only work when you're running the graphical version of Raspberry Pi OS?

Check with @XECDesign - the lite version is his baby.

**Comment by XECDesign** [comment]
No, lite does not have automount.

**Comment by aallan** [comment]
> No, lite does not have automount.

Thanks. I'll add that as a note on the docs page.

@dkoehler69 looks like it's working as expected.
