### ISSUE TITLE
bluetooth stopped working after latest update

### ISSUE THREAD

**Issue by 0d0a** [raspberrypi/documentation#1959]
when setting up a new pi400 i noticed that bluetooth works and connects to my bluetooth device(s) before i do the standard update
after the update bluetooth does not connect anymore. 
bluetoothctl says no default controller available 
uname -a 
5.10.52-v7l+ #1441 SMP Tue Aug 3 18:11:56 BST 2021 armv7l GNU/Linux

**Comment by aallan** [comment]
This repo is for the Raspberry Pi documentaiton. This is the sort of problem you should ask about on the [forums](https://www.raspberrypi.org/forums/), so I’m closing this issue. But please follow up with further comments if you have specific questions about the [documentation](https://www.raspberrypi.org/documentation/).

**Comment by 0d0a** [comment]
Sorry. Posted in the forums.
Thx

the white rider
(Het leuke van ... is weten op reis te zijn
