### ISSUE TITLE
VNCs other than Tight are available

### ISSUE THREAD

**Issue by jamleed** [raspberrypi/documentation#197]
Here at RealVNC we've just ported our flagship VNC product to the Pi: http://www.realvnc.com/products/vnc/raspberrypi/

Reading the current doc you'd be forgiven for thinking Tight was the only VNC available: http://www.raspberrypi.org/documentation/remote-access/vnc/README.md.

We appreciate Tight are in the Debian repository system and RealVNC are a commercial organization now, but we actively promote free licenses, and there's the additional benefit that VNC can remote both console and virtual (Xvnc) sessions at the same time. Plus being easier to set up, in our opinion.

We'd like to edit the README to suggest that there are multiple flavours of VNC available, and namecheck ourselves as one of them.

**Comment by Ruffio** [comment]
@jamleed this issue can be closed, right?

**Comment by jamleed** [comment]
Yes, I think we're all done here, thanks a lot!
