### ISSUE TITLE
Page location changes have broken raspberrypi.org website and external links

### ISSUE THREAD

**Issue by andrum99** [raspberrypi/documentation#1973]
All links from pages which don't live within the documentation repo are broken, including from elsewhere on raspberrypi.org. For example:

https://www.raspberrypi.org/software/

All links on that page which point into the documentation return a 404 error.

**Comment by aallan** [comment]
Thanks, we thought we'd caught them all! We're fixing the links on the software page,

<img width="1355" alt="Screenshot 2021-08-09 at 12 22 58" src="https://user-images.githubusercontent.com/53625/128699086-2805e111-3d05-4d6a-a098-6ee47fb4504e.png">

Is there anywhere else you can point to that 404's rather than being redirected?

NOTE: Some deep links will *by design* 404, but there shouldn't be any directly off the Raspberry Pi homepage(s).

**Comment by andrum99** [comment]
Is there a redirect in place? If not, you probably should have one, since all links on 3rd party sites into the documentation pages will now be broken without one. It should be relatively straightforward to come up with a rewrite rule to do the redirect.

**Comment by aallan** [comment]
> Is there a redirect in place? If not, you probably should have one, since all links on 3rd party sites into the documentation pages will now be broken without one. It should be relatively straightforward to come up with a rewrite rule to do the redirect.

There are redirects in place for all (hopefully) of the PDFs and other not-markdown files that were hosted as part of the documentation repo. However, we are not going to redirect all the deep links into the documentation to the new locations. 

That said, I totally agree the generic 404 page isn't helpful. We should generate a documentation-specific 404 page that is more helpful in directing users into the new documentation stack.

**Comment by andrum99** [comment]
> Is there anywhere else you can point to that 404's rather than being redirected?

I've not checked - the 'software' page was the first one I hit when I was looking for something else. The web team may wish to avail themselves of an automated dead link checker, since upon running a free one online there seems to be quite a few internal links which have gone walkabout.

**Comment by aallan** [comment]
> The web team may wish to avail themselves of an automated dead link checker, since upon running a free one online there seems to be quite a few internal links which have gone walkabout.

That's with the Foundation team. Not Trading.

**Comment by andrum99** [comment]
> > The web team may wish to avail themselves of an automated dead link checker, since upon running a free one online there seems to be quite a few internal links which have gone walkabout.
> 
> That's with the Foundation team. Not Trading.

Indeed. I was kind of assuming you would have some way of communicating with the Foundation though.

**Comment by andrum99** [comment]
What I meant was you could just use a single rewrite rule to point `raspberrypi.org/documentation/something` to `raspberrypi.org/documentation/computers/something, i.e. exclude raspberrypi.org/documentation/ itself from the redirect.

**Comment by aallan** [comment]
We'll fix any internally hosted links we find — and pass any Foundation hosted links to our counterparts there — but for external links I think #1976 will be the solution.

**Comment by wolfd** [comment]
Is there a good place to report those dead links?

For now, here's two more:
- https://www.raspberrypi.org/blog/an-open-source-camera-stack-for-raspberry-pi-using-libcamera/
- https://libcamera.org/open-projects.html#learning-how-an-isp-is-used - not Raspberry Pi hosted, but a collaboration

**Comment by aallan** [comment]
Links to individual `*.md` pages will not be redirected. We can't be expected to maintain, forever, a complex tree of links, and then redirect every page when the documentation is restructured, and then again when we restructure it the next time. Additionally, I'm about to embark on a large scale cull. My current estimate is about 1/3 of the existing documentation will probably be deleted. 

Link rot is a thing everybody has to deal with. 

However the link from the libcamera.org post you pointed at is to a PDF, those we are going to throw redirects in place for, in fact they should be there already — that one obviously got missed — we'll fix that one up.

**Comment by aallan** [comment]
…we've also now added some category level redirects (see #2010) which should catch most 404'ed pages.
