### ISSUE TITLE
A documentation-specific 404 page is needed

### ISSUE THREAD

**Issue by aallan** [raspberrypi/documentation#1976]
I think the best solution to #1973 is that the documentation site has its own 404 page which is more helpful; perhaps having the top-level categories? This will help redirect lost users back into the main documentation rather than just stranding them with a generic "404" message. 

<img width="1399" alt="Screenshot 2021-08-09 at 12 39 10" src="https://user-images.githubusercontent.com/53625/128700579-f871cbdc-12db-42ef-8dea-a4fbdedfe79d.png">

Any ideas what should be on this page @jackbenwillis, @mudge ?

**Comment by andrum99** [comment]
I wonder if it would be possible to have the documentation-specific 404 page just be the documentation index page itself? You could trigger some specific error message within the page by passing a parameter as part of the URL.

**Comment by aallan** [comment]
We've now added some category level redirects (see #2010) which should catch most 404'ed pages. But a custom 404 page for the documentation is still needed I think.

**Comment by aallan** [comment]
@jackbenwillis Can you have a think about what this should look like?

**Comment by lurch** [comment]
https://web.archive.org/web/20140714193525/www.raspberrypi.org/404

**Comment by aallan** [comment]
> https://web.archive.org/web/20140714193525/www.raspberrypi.org/404

The new 404 page should presumably direct people to the new documentation site, maybe let people search for things, and encourage them to update their dead links. Not entirely sure that helps! 😆

**Comment by jackbenwillis** [comment]
![image](https://user-images.githubusercontent.com/25119475/128864416-1cf572de-fdc1-4dd5-b45e-6aadc7803a0d.png)
What about this? Replacing the header with a 404 message and asking people to browse the updated documentation. This way you'll already be on the documentation landing page and be able to get going right away

**Comment by aallan** [comment]
That'd work for me. Hopefully it'd be possible to configure it so that the landing page in the 404 isn't static or separately generated (and have to be updated independently from the main top page)...? @nelliemckesson @mudge ?

**Comment by mudge** [comment]
> That'd work for me. Hopefully it'd be possible to configure it so that the landing page in the 404 isn't static or separately generated (and have to be updated independently from the main top page)...? @nelliemckesson @mudge ?

@nelliemckesson can confirm but I expect we can generate a separate 404 page much like we do the current index page, dynamically populating it with the same categories and even including the search functionality. I can then configure our web server to use that page whenever it encounters a 404 error rather than taking users to https://www.raspberrypi.org/404.html

**Comment by aallan** [comment]
Let's do it this way then.

**Comment by lurch** [comment]
@mudge I think we'd want to keep the existing generic https://www.raspberrypi.org/404.html page, and only use this new design fro 404s coming from the https://www.raspberrypi.org/documentation/ "subdirectory"? Is it possible to do that?

**Comment by aallan** [comment]
>  Is it possible to do that?

I was presuming that's what he meant?

**Comment by mudge** [comment]
Yes, that's what I meant. We won't touch https://www.raspberrypi.org/404.html as that is used by other parts of the site but instead configure the documentation server specifically to use our new documentation-only 404 page.

**Comment by lurch** [comment]
Ah, sorry for getting my wires crossed :laughing:

**Comment by lurch** [comment]
I just knocked up a quick prototype and came up with this:
![Screenshot from 2021-08-10 13-40-19](https://user-images.githubusercontent.com/476186/128868454-9cc00fb5-ae2a-4849-9d8f-9aa619bcf527.png)

Is everyone happy enough with that for me to create a PR?

**Comment by jackbenwillis** [comment]
Could we increase the size of the '404'?

Otherwise looks good!

**Comment by lurch** [comment]
I dunno how to change font-sizes, that's a CSS thing :laughing:  So I'll put together a PR with what I've got and @nelliemckesson can bump the font-sizes later :+1:

**Comment by lurch** [comment]
@nelliemckesson I tried making "Raspberry Pi Documentation" into a link, but it didn't look right, so I won't do that for now :wink: 
![Screenshot from 2021-08-10 14-05-34](https://user-images.githubusercontent.com/476186/128872083-64db338d-ed44-4dad-a49f-ea3c669262e5.png)

**Comment by aallan** [comment]
>  I tried making "Raspberry Pi Documentation" into a link, but it didn't look right, so I won't do that for now 

Eek. No, that's not right. 😬

**Comment by lurch** [comment]
See #2026

**Comment by jackbenwillis** [comment]
Yup! leave it out for now ;)

small thing, full stop after for and uppercase P in please (all my fault)!

"We couldn't find what you were looking for. Please browse our updated **Raspberry Pi** Documentation"

**Comment by jackbenwillis** [comment]
and a full stop!

**Comment by aallan** [comment]
@nelliemckesson If you could look at #2026 and sprinkle some CSS magic that'd be great! Thanks!
