### ISSUE TITLE
Rendering: code sections always have a scroll bar at the bottom

### ISSUE THREAD

**Issue by andrum99** [raspberrypi/documentation#1984]
Best illustrated by an example:

![Screenshot 2021-08-09 142933](https://user-images.githubusercontent.com/58046090/128714625-e7343e07-b6c0-44b7-a3f7-ce64934cd97f.png)

While it is certainly useful to have a scroll bar to cope with long lines, particularly on narrow displays, e.g. on mobile phones, I would personally prefer it if they did not appear all of the time.

**Comment by aallan** [comment]
That's interesting. What Browser+OS are you seeing that in?

**Comment by andrum99** [comment]
> That's interesting. What Browser+OS are you seeing that in?

Chrome version 92.0.4515.131 (Official Build) (64-bit) on Windows 10. I've got scaling set to 125% as it's a 15" laptop screen that's 1080p, which is the default for that device. I've not tried with scaling set to 100% but I would not expect that to make any difference.

**Comment by aallan** [comment]
Thanks. We'll take a look. Not seeing that on either Chrome or Safari on Mac. 

<img width="1399" alt="Screenshot 2021-08-09 at 14 41 25" src="https://user-images.githubusercontent.com/53625/128715807-e138c4b6-b616-45c2-89d2-c41228f36286.png">

**Comment by lurch** [comment]
I get the scrollbar in Chrome 92.0.4515.107 on Ubuntu Linux
![Screenshot from 2021-08-09 14-54-47](https://user-images.githubusercontent.com/476186/128717929-f6c486c8-7ddf-479b-a32f-dade264ea962.png)

**Comment by aallan** [comment]
This is where @nelliemckesson and I both being on Mac becomes a problem. 😆

**Comment by andrum99** [comment]
> This is where @nelliemckesson and I both being on Mac becomes a problem. 😆

![5j1tlv](https://user-images.githubusercontent.com/58046090/128723552-da20a502-5c4c-447e-8f5b-589a3ebe240e.jpg)

I used browsershots.org back in the day, but unfortunately this seems to be no more 😢

**Comment by DeeJay** [comment]
Just as another data point, I also see the redundant horizontal scroll with MS Edge Version 92.0.902.67 (Official build) (64-bit) on MS Windows 10 Home - 
Version	20H2
Installed on	‎05/‎11/‎2020
OS build	19042.1110
Experience	Windows Feature Experience Pack 120.2212.3530.0

**Comment by nelliemckesson** [comment]
@aallan what's the preferred behavior here? Scrollbar only visible for elements that actually overflow? Scrollbar only visible when hovering over an element that overflows? Scrollbar never visible?

**Comment by aallan** [comment]
> @aallan what's the preferred behavior here? Scrollbar only visible for elements that actually overflow? Scrollbar only visible when hovering over an element that overflows? Scrollbar never visible?

Too many choices 🧠 

Umm. I **think** I'm going to opt for scrollbar only visible for elements that actually overflow, to give the visual cue that you can scroll, although personally I'd lean towards scrollbar only visible when hovering over an element that overflows, I think that might not be obvious to some users.

**Comment by lurch** [comment]
"scrollbar only visible for elements that actually overflow, to give the visual cue that you can scroll"

If we could do the same for the ToC scrollbar, that'd fix #1979  :wink:
