### ISSUE TITLE
Add Issue and Pull Request templates

### ISSUE THREAD

**Issue by aallan** [raspberrypi/documentation#1986]
We need Issue and Pull Request templates, see https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates for details. Should also update the [`CONTRIBUTING.md`](https://github.com/raspberrypi/documentation/blob/develop/CONTRIBUTING.md) file to make it more useful and less generic.

**Comment by andrum99** [comment]
I notice that the link to the style guide has been removed from contributing.md. Presumably this means the technical docs have their own distinct style?

**Comment by aallan** [comment]
> I notice that the link to the style guide has been removed from contributing.md. Presumably this means the technical docs have their own distinct style?

The style guide is getting updated as I type by @LizUpton and there will be some documentation specific stuff going in there, err eventually, from me. The `CONTRIBUTING.md` file needs a refresh as well.

**Comment by andrum99** [comment]
>The `CONTRIBUTING.md` file needs a refresh as well.

Most of contributing.md is brand new as of the conversion to asciidoc. (And the stuff that was added is unnecessary in my view, since all you really need to do to contribute a change is create a PR - Github walks you through the process of forking the repo and creating a branch anyway when you press the edit button).

**Comment by aallan** [comment]
After [reading up](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository) and playing around with them, I'm actually somewhat unconvinced that either issue or PR templates will get us anything. I'm going to close this for now and think about it for a bit.
