### ISSUE TITLE
Add anchor links for sections in the documentation

### ISSUE THREAD

**Issue by geerlingguy** [raspberrypi/documentation#1991]
If possible, it would be a huge improvement to have permalink icons appear on hover over any section heading (since they're already set up as a named anchor in code), and when the user clicks on it they can get the permalink to that section of the page:

<img width="538" alt="Screen Shot 2021-08-09 at 9 33 43 AM" src="https://user-images.githubusercontent.com/481677/128723908-977a29df-2e91-40ce-b5a7-be11b7d22c2c.png">

It doesn't matter to me whether on the right or left, but here's what I'm talking about (example from GitHub's default README layout, in this case on this repo's readme (https://github.com/raspberrypi/documentation):

<img width="547" alt="Screen Shot 2021-08-09 at 9 35 12 AM" src="https://user-images.githubusercontent.com/481677/128724283-38992a52-302d-4704-9186-309980985547.png">

**Comment by andrum99** [comment]
On a related note, with such long pages it would be useful to have a "go to top of page" button somewhere.

**Comment by lurch** [comment]
a) There's not (yet) a way to get the anchor from the titles themselves, but you _can_ get the anchor links from the Table-of-Contents on the left.

b) There's not (yet) a "go to top", but if you're looking at e.g. https://www.raspberrypi.org/documentation/computers/raspberry-pi.html then you can click on "Computers" at the top of the Table-of-Contents to go directly to https://www.raspberrypi.org/documentation/computers/

**Comment by DeeJay** [comment]
I came to make the request already raised by @geerlingguy .

So a 'me too.'

But referring to Andrew @lurch - "you can get the anchor links from the Table-of-Contents on the left."  Under what circumstances? With Edge under Win10 a standard RightClick doesn't work. [Workaround is to 'screenscrape' from the address bar at the head of the browser window: that does contain the 'anchor-fied' url.]

**Comment by lurch** [comment]
@DeeJay Oh yeah, I never noticed that :confused:   It must be a side-effect of http://gregfranko.com/jquery.tocify.js/ (which is what we use to underline the section-titles in the ToC as you scroll through the main body-contents).

**Comment by aallan** [comment]
We like this suggestion to the extent that we're going to implment it. It's in the queue.
