### ISSUE TITLE
Rendering: docs home page mostly blank above the fold

### ISSUE THREAD

**Issue by andrum99** [raspberrypi/documentation#1992]
Best illustrated by a screenshot:

![Screenshot 2021-08-09 154422](https://user-images.githubusercontent.com/58046090/128725841-996491f3-feaa-47cd-8a84-ea5da4d15678.png)

The actual page content, with the exception of the search box, i.e. the icon links to the individual sections of documentation, is below the fold on a 1080p screen, scaling (set in the OS, not the browser) set to 125%. This means the user most scroll down to find it. By contrast, all of the top-level pages linked from the page header all have at least a paragraph of content above the fold.

**Comment by aallan** [comment]
The above and below the fold thing is a mostly dead concept in web design. Users seem to mostly not care about this anymore, A/B testing shows that it doesn't do anything to engagement.
