### ISSUE TITLE
Asciidoc support on Github

### ISSUE THREAD

**Issue by aallan** [raspberrypi/documentation#2005]
Issue to keep track of  github/markup#1095 and support for Asciidoc include directives on Github.

**Comment by aallan** [comment]
Issue is still there. 🤷‍♂️

**Comment by lurch** [comment]
Issue is still there.

**Comment by aallan** [comment]
Issue still there.

**Comment by aallan** [comment]
...but I'm going to close it anyway, because I have finally given up on the Github dev team ever fixing this problem.
