### ISSUE TITLE
Creative Commons Attribution is hard to read

### ISSUE THREAD

**Issue by capjamesg** [raspberrypi/documentation#2025]
The Creative Commons attribution statements that appear at the bottom of the page content before the footer are hard to read.

I would recommend adding a `<hr>` separator to make it clear the attribution statements are not part of a page article and making the text darker so that it passes a [colour accessibility and contrast test](https://webaim.org/resources/contrastchecker/). I did not want to make this a pull request as I was unsure on the colours and shades that are part of your style guide (although I'll make it a PR if necessary).

To replicate the issue, install the WAVE accessibility too land test any article page where the CC attribution statements are present.

Example page affected:

https://www.raspberrypi.org/documentation/accessories/display.html

Picture of text affected:

![Screenshot from 2021-08-10 14-02-36](https://user-images.githubusercontent.com/37276661/128871514-815c973a-dbd0-4086-9b2a-6fc9bed12181.png)

**Comment by aallan** [comment]
We've slightly tweaked this, but it's supposed to be fairly unobtrusive.
