### ISSUE TITLE
README.md and CONTRIBUTING.md - duplicate content

### ISSUE THREAD

**Issue by andrum99** [raspberrypi/documentation#2076]
Build instructions for this repo are included in both files, and each has different wording (and perhaps method). Only one file should contain the build instructions, otherwise it makes things confusing and creates an unnecessary maintenance overhead.

**Comment by aallan** [comment]
I actually can't see any build instructions in the `CONTRIBUTING.md` file, but I've been meaning to rewrite it anyway, see d1150d2.

**Comment by andrum99** [comment]
> I actually can't see any build instructions in the `CONTRIBUTING.md` file, but I've been meaning to rewrite it anyway, see [d1150d2](https://github.com/raspberrypi/documentation/commit/d1150d25078625576483364756f0d2d53a18b07a).

Apologies - I got that slightly wrong. In actual fact, CONTRIBUTING.md contained instructions for how to contribute to the repo, which is related to the build instructions but is not the same as them. I think today's rewrite is a big improvement.
