### ISSUE TITLE
Inconsistent spelling of licence?

### ISSUE THREAD

**Issue by pelwell** [raspberrypi/documentation#2086]
The licensing footer on the documentation pages includes both spellings of "licence":
> The Raspberry Pi Documentation is Copyright (c) 2012-2021 Raspberry Pi (Trading) Ltd and is licensed under a Creative Commons Attribution-ShareAlike 4.0 International (CC BY-SA) Licence.
> Some content originates from the eLinux wiki, and is licensed under the Creative Commons Attribution-ShareAlike 3.0 Unported license.

The first is capitalised ("Licence") and the second isn't ("license"), which could account for a variation from a house style or could just be another example of inconsistency.

**Comment by aallan** [comment]
We had both an American and a Brit writing it, I think Nellie wrote one line and I wrote the other, and I've spent enough time in the States that I sometimes use the American spelling. Which might explain things. Fixed to "licence" everywhere in 40b23fb.
