### ISSUE TITLE
WiFi cli page needs some more options for hidden SSID

### ISSUE THREAD

**Issue by mohamnag** [raspberrypi/documentation#209]
I have a WPA2-Personal hidden network which I tried to setup for connection on my Pi.
So I read the page on https://github.com/raspberrypi/documentation/blob/master/configuration/wireless/wireless-cli.md and followed it exactly but I could not connect. After one or two hours hacking and trying different options, I found out that the problem is that network is hidden and could solve it using the following `/etc/wpa_supplicant/wpa_supplicant.conf` file:

```
ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
updateconfig=1

ap_scan=1

network={
    ssid="myhiddenssid"
    scan_ssid=1
    psk="mywlanpass"
}
```

Which is basically only minor change.
I'm not sure if this config works for all hidden networks, but maybe this is worth being noted in that page so not many people like me have to reinvent the wheel.

**Comment by LornaLynch** [comment]
Resolved by PR #525.
