### ISSUE TITLE
Default branch problem?

### ISSUE THREAD

**Issue by aallan** [raspberrypi/documentation#2095]
This is **not** the same UI problem we saw before (pre-launch) involving PR notifications (which got fixed!). However, when you switch Github to display the `master` rather than the `develop` (default) branch you see this notification at the top of the screen.

<img width="1394" alt="Screenshot 2021-08-18 at 14 34 54" src="https://user-images.githubusercontent.com/53625/129907546-6bb781e1-51ad-4be8-889f-27d4fdef30d5.png">

These 38 commits (at time of writing) are the 38 "Push to Production" merge commits,

<img width="1308" alt="Screenshot 2021-08-18 at 14 36 18" src="https://user-images.githubusercontent.com/53625/129907910-86b8349f-778c-457b-9ec2-d2c7b192505d.png">

while I can totally see why it's doing this, it seems like a UI bug rather than a thing Github should be tell us?

What do you think @martinwoodward?

**Comment by lurch** [comment]
We've now fixed up a slight snafu that resulted in the "Files changed: 1" in that screenshot, but https://github.com/raspberrypi/documentation/tree/master still displays "This branch is 40 commits ahead of develop.".

**Comment by aallan** [comment]
> We've now fixed up a slight snafu that resulted in the "Files changed: 1" in that screenshot, but https://github.com/raspberrypi/documentation/tree/master still displays "This branch is 40 commits ahead of develop.".

Yes, was wondering if the cherry-pick would fix it. It did not.

**Comment by aallan** [comment]
Still wracking up diverging "push to production" commits. 

<img width="1327" alt="Screenshot 2021-09-07 at 16 43 51" src="https://user-images.githubusercontent.com/53625/132373964-a8a55d2c-0fc4-4d86-87ab-fa8bfa95b5a7.png">
