### ISSUE TITLE
[NOTE] versus NOTE: style differences

### ISSUE THREAD

**Issue by aallan** [raspberrypi/documentation#2101]
If we do,

```
[NOTE]
=======
foobar
=======
```

we get this,

<img width="957" alt="Screenshot 2021-08-18 at 16 46 29" src="https://user-images.githubusercontent.com/53625/129929740-42a520b1-f404-423b-bcdf-5044e003a9f2.png">

but if we do

```
NOTE: foobar
```

we get this,

<img width="935" alt="Screenshot 2021-08-18 at 16 46 33" src="https://user-images.githubusercontent.com/53625/129933476-b3384fd7-0b84-4c3b-beef-0ad9974175ba.png">

which looks better and doesn't have the excess whitespace at the bottom of the box.

**Comment by lurch** [comment]
Hmmm, https://docs.asciidoctor.org/asciidoc/latest/blocks/admonitions/ implies that they ought to be equivalent? I wonder at which stage of the processing-pipeline the discrepancy is creeping in?

**Comment by lurch** [comment]
Haha, and I guess you actually meant "[IMPORTANT] versus IMPORTANT: style differences" ? :wink:

**Comment by aallan** [comment]
> Haha, and I guess you actually meant "[IMPORTANT] versus IMPORTANT: style differences" ? :wink: 

Sure. But I figure the problem is generic to all the call out blocks.

**Comment by lurch** [comment]
> I wonder at which stage of the processing-pipeline the discrepancy is creeping in?

Out of curiosity I just added one of each and then looked at the HTML that comes out of the other end, and the only difference seems to be that
```
NOTE: foobar
```
results in
```
...
<td class="content">
foobar
</td>
...
```
whereas
```
[NOTE]
=======
foobar
=======
```
results in
```
...
<td class="content">
<div class="paragraph">
<p>foobar</p>
</div>
</td>
...
```

So it must be the extra `<div>` and `<p>` that are adding the excess whitespace.
