### ISSUE TITLE
Hardware/software information for UARTs

### ISSUE THREAD

**Issue by e107steved** [raspberrypi/documentation#2105]
A section similar to https://www.raspberrypi.org/documentation/computers/raspberry-pi.html#spi-hardware is needed to cover UART hardware.
And a section similar to https://www.raspberrypi.org/documentation/computers/raspberry-pi.html#spi-software to cover UART software.

**Comment by e107steved** [comment]
I've subsequently found some of the information I was looking for here: https://www.raspberrypi.org/documentation/computers/configuration.html#configuring-uarts - but not all. In particular, it doesn't mention modem control signals.
So possibly new sections as originally suggested, with more detail than already exists, and cross-references.

**Comment by lurch** [comment]
IMVHO, those tables of pinouts might be better served by something like https://pinout.xyz and https://datasheets.raspberrypi.org/bcm2835/bcm2835-peripherals.pdf & https://datasheets.raspberrypi.org/bcm2711/bcm2711-peripherals.pdf ?
Although it's obviously a decision for @aallan to make...

**Comment by e107steved** [comment]
Each to their own, I think - personally I often end up compiling tables like that from disparate (and sometimes conflicting!) sources of information. So I'd be pleased to see a single source.
Incidentally, assuming information is added, I'm particularly interested in confirming the capabilities of the RTS signal for controlling an RS-485 transceiver.

**Comment by e107steved** [comment]
....and to provide the information for SPI and not for UARTs would surely be inconsistent?

**Comment by lurch** [comment]
> from disparate (and sometimes conflicting!) sources of information.

AFAIK, in the event of conflicting information the two datasheet PDFs I linked to above ought to be taken as definitive (although be aware of the [errata](https://elinux.org/BCM2835_datasheet_errata) for the BCM2835 datasheet).
