### ISSUE TITLE
CM4 data sheet - document additional pin functions

### ISSUE THREAD

**Issue by e107steved** [raspberrypi/documentation#2125]
According to https://www.raspberrypi.org/documentation/computers/raspberry-pi.html#spi-hardware, the CM4 (along with other CMs) supports SPI0 and SPI2 on GPIOs 35-45.
However there is no mention of where these pins appear on the connectors in the CM4 data sheet (12th July build)

**Comment by aallan** [comment]
Ping @dp111

**Comment by lurch** [comment]
That section also says "SPI2, also with three hardware chip selects, is only available on Compute Module 1, 3 and 3+." ?
@andrum99 did some work on this recently in #2001

**Comment by e107steved** [comment]
Must be in an unpublished version - I checked immediately before posting this issue. Still leaves SPI0, though

**Comment by aallan** [comment]
> Must be in an unpublished version

That should be live?

**Comment by dp111** [comment]
Andrew is correct  "SPI2, also with three hardware chip selects, is only
available on Compute Module 1, 3 and 3+." maybe your cache needs refreshing?

There is a table heading which could be misleading :
"SPI2 (compute modules only)"

Maybe it should be "SPI2 (compute modules only, except CM4)"

**Comment by aallan** [comment]
Updated the table header on `develop` will go to the live site next time I push to `master`.
