### ISSUE TITLE
Information on release schedule

### ISSUE THREAD

**Issue by Dreamsorcerer** [raspberrypi/documentation#2128]
https://www.raspberrypi.org/documentation/computers/os.html#upgrading-from-operating-system-versions

This documentation describes how to upgrade from stretch to buster. This is the only documentation I could find regarding upgrading releases.

What I'd like to know is how to upgrade to bullseye, and when it will be available to upgrade. Is there a release schedule or anything else that can be added to this documentation?

**Comment by lurch** [comment]
@aallan It might be worth removing the "how to upgrade from stretch to buster" section at some point after Bullseye is released? :shrug:

**Comment by aallan** [comment]
> @aallan It might be worth removing the "how to upgrade from stretch to buster" section at some point after Bullseye is released? 🤷

Yup. Needs rewording to a generic "if you are not on the most up to date release you can upgrade by…" sort of thing.
