### ISSUE TITLE
Floating images left or right of text doesn't work?

### ISSUE THREAD

**Issue by aallan** [raspberrypi/documentation#2150]
@nelliemckesson Attempting to float an image to the left of text (so the image is on the left, and the text flows around it to the right) doesn't seem to work. 

None of [these](https://docs.asciidoctor.org/asciidoc/latest/macros/image-position/) suggested commands to float the image seem to affect things, and the text is put below the images I want to wrap it around.

<img width="972" alt="Screenshot 2021-09-09 at 10 45 00" src="https://user-images.githubusercontent.com/53625/132665561-8dddb6d4-daaf-4d67-83e1-3be0dfc14a0d.png">

I've created a branch called [`aallan-add-mp-book`](https://github.com/raspberrypi/documentation/tree/aallan-add-mp-book), can you take a look at [`asciidoc/microcontrollers/micropython/what-is-micropython.adoc`](https://github.com/raspberrypi/documentation/blob/aallan-add-mp-book/documentation/asciidoc/microcontrollers/micropython/what-is-micropython.adoc) on that branch and see what's going on. Presuming we need a tweak to the style file?

**Comment by nelliemckesson** [comment]
@aallan see #2153 !
