### ISSUE TITLE
  Add resize partition in installing-images/README.md ?

### ISSUE THREAD

**Issue by jreso** [raspberrypi/documentation#216]
After create sd card, it seems a good idea to add problems about size of the partition.
And how-to resize it : http://raspberrypi.stackexchange.com/questions/499/how-can-i-resize-my-root-partition

It freezes me one day long before finding the problem ...

**Comment by lurch** [comment]
Raspbian is the only OS covered by the official Raspberry Pi documentation, and resizing the root partition is covered by https://www.raspberrypi.org/documentation/configuration/raspi-config.md

**Comment by bennuttall** [comment]
Don't you just use `raspi-config`?

**Comment by XECDesign** [comment]
Is there a reason for that given that the raspbian image has a tool to resize the partition? What other distros do is up to them, but the steps aren't quite that universal. It comes down to removing and recreating the partition, then running resize2fs, but different operating systems have different partition layouts. Documenting that in a way that is easy to follow, universally applicable and clear about the risks involved isn't trivial.

**Comment by jreso** [comment]
> Don't you just use raspi-config?

You are right. I didn't notice it, because I didn't really understand what it means. 

When I write other linux images on SD card I never had this issue. It could be nice to mention it directly at the end of all 3 pages of https://www.raspberrypi.org/documentation/installation/installing-images/ for every platform for raspbian distribution and link to raspi-config to solve it.

**Comment by bennuttall** [comment]
But the first time you boot into Raspbian, it opens `raspi-config` for you to change things like that (unless that's just NOOBS?)

**Comment by XECDesign** [comment]
NOOBS creates the partitions of the right size to begin with. Expanding the filesystem only needs to be done when using the raw image. However, the first thing that pops up is raspi-config and the first option is to expand the filesystem. I'm leaning towards closing this one.

**Comment by bennuttall** [comment]
Yup
