### ISSUE TITLE
BCM2835-ARM-Peripherals.pdf and other datasheets missing

### ISSUE THREAD

**Issue by cleverca22** [raspberrypi/documentation#2178]
https://github.com/raspberrypi/documentation/blob/develop/documentation/redirects/datasheets.csv has setup redirects to them
but the files themselves are no longer in this repo

https://datasheets.raspberrypi.org/bcm2835/ directory indexing is also disabled on the new location
so there is no way to discover what other datasheets exist, and no way to view any history of how they have changed

i would prefer if they are available in some git repo, so history is maintained, and its easy to list every datasheet

**Comment by lurch** [comment]
https://datasheets.raspberrypi.org/ seems to be what you're looking for? :wink:  Some of the datasheets include a release history, but not all.
Note also that the conformity-section of the documentation now lives in https://pip.raspberrypi.org/

**Comment by aallan** [comment]
The files currently (temporarily) live on http://datasheets.raspberrypi.org. However they will eventually be moving to the new Product Information Portal (PIP), http://pip.raspberrypi.org. Going forward they won’t be kept here in Git.
