### ISSUE TITLE
Downloads page on raspberry Pi website grammar error!

### ISSUE THREAD

**Issue by LOVE2CODE123** [raspberrypi/documentation#221]
On the raspberry Pi website it says 

NOOBS is an easy operating system installer WITH contains Raspbian. It also provides a selection of alternative operating systems which are then downloaded from the internet and installed.

Although I think it should say...

NOOBS is an easy operating system installer WHICH contains Raspbian. It also provides a selection of alternative operating systems which are then downloaded from the internet and installed.

**Comment by XECDesign** [comment]
Thanks, fixed.

**Comment by LOVE2CODE123** [comment]
Yeah, I contributed to raspberry Pi website, say hi to even upton!
