### ISSUE TITLE
Power rails in pi4B 8GB.

### ISSUE THREAD

**Issue by GoWest279** [raspberrypi/documentation#2217]
Hi, 
I'm trying to measure the power consumption with DVFS in pi4B 8GB. 
I’m not sure:
* whether the pi4 board/processor comes with the A/D converter to measure the current?
* If not, what’s the output power rails of U2 (in reduced-schematic) used for? 
   Is VDD_CORE the only power rail that drives the Arm processor? 
   If Yes, does this power rail pass through any inductor, resistor?
* I also noticed U3 is also driving 1V05_VLI and 1V0_SOC. What do those two power rails stand for?
Is there any way to get the schematic of power rails? 
Any idea will be appreciated!

**Comment by lurch** [comment]
> Is there any way to access the information?

Raspberry Pi hardware (generally) isn't open source, so I _suspect_ there probably won't be any further official information provided? :shrug:  But maybe if you ask on the [forums](https://forums.raspberrypi.com/) some of the people there might be able to provide you with unofficial information?
