### ISSUE TITLE
Is there a Chinese document?

### ISSUE THREAD

**Issue by AppleOfGray** [raspberrypi/documentation#2228]
Localization translation is very important, which can make the technology spread more widely

**Comment by lurch** [comment]
We don't have the resources to provide or maintain translations of the documentation in other languages. :earth_asia: 
However as long as you adhere to the [licence](https://www.raspberrypi.com/licensing/) and [trademark rules](https://www.raspberrypi.com/trademark-rules/) you're welcome to host your own translated versions of the documentation.
