### ISSUE TITLE
Build HAT docs - Data Dashboard project broken PDF download/embed

### ISSUE THREAD

**Issue by SimUKdev** [raspberrypi/documentation#2231]
On the "LEGO® data dashboard" project, "Make a LEGO® sliding indicator" page, at https://projects.raspberrypi.org/en/projects/lego-data-dash/2 there is a link to a PDF and also an embedded version. The link is broken, going to a "not found" page.

URL of linked file that is being used (but not found) is: https://projects.raspberrypi.org/en/resources/lego-data-dash-slider.pdf

Screenshot of issue:
![__pi_buildhat_2](https://user-images.githubusercontent.com/52102399/138443319-7bf85ecc-738d-4258-be3b-01aa2daffdbd.png)

**Comment by topshed** [comment]
This is now fixed, thanks
