### ISSUE TITLE
Policy statement desirable regarding absent schematics for RPi 2B

### ISSUE THREAD

**Issue by DeeJay** [raspberrypi/documentation#224]
re: https://github.com/raspberrypi/documentation/blob/master/hardware/raspberrypi/schematics/README.md

and 

https://www.raspberrypi.org/forums/viewtopic.php?f=29&t=110975&p=766074#p766074

If it is a policy decision by RPF to not publish schematics for the RPi 2B it would save confusion and frustration to have this fact documented on the summary page for other schematics.

**Comment by mtrudel** [comment]
I agree with this. I count at least a handful of issues on this project that could be resolved (and/or never be opened in the first place) by a clear statement one way or the other. 

Speaking personally, it's not a deal breaker for me one way or the other if they're released (it basically just changes how much of a black box I treat the Pi as being), but trying to divine hardware interface specifics from hearsay and vague forum posts (see #282 for my particular itch) helps nobody.
