### ISSUE TITLE
Documentation for setting up WiFi is out of date?

### ISSUE THREAD

**Issue by juj** [raspberrypi/documentation#225]
STR:

1. Install Raspbian via NOOBS, and proceed with an out of the box installation of Raspbian, which was the recommended setup.
2. Plug in a USB Wifi dongle and power up Raspbian.
3. Navigate via the following trail to learn how to set up WiFi:
     - https://www.raspberrypi.org/help/
       -> Choose "Documentation" -> "Configuration" -> "Wireless" to get to
          - https://www.raspberrypi.org/documentation/configuration/wireless/README.md
       -> Choose "Using GUI Application" to get to https://learn.adafruit.com/adafruits-raspberry-pi-lesson-3-network-setup/setting-up-wifi-with-raspbian

4. The documentation refers to a "WiFi Config" icon on the desktop, but such a configuration utility does not exist in the out of the box menus.

Expected: The official documentation should instruct how to install the WiFi Config utility if user is expected to somehow install it manually, or perhaps the utility should be included, and the out of the box installation is just missing it?

I recognize that the documentation links to an external blog-style page at adafruit.com, and if that documentation is plain old, it would be best to update https://www.raspberrypi.org/documentation/configuration/wireless/ to stop referring to that  blog page, and instead update the official documentation to refer to an updated version of the docs. If the blog post is not meant for Raspbian (the menus look quite different), the official docs would be good to be rewritten to contain GUI instructions for Raspbian since that was the default recommended distribution choice.

**Comment by XECDesign** [comment]
Thank you. Seems like this has been fixed a little over a week ago.
