### ISSUE TITLE
Pi Zero 2 W: Conditional model filters in config.txt

### ISSUE THREAD

**Issue by dwhinham** [raspberrypi/documentation#2254]
Hi there!

Is there a conditional `config.txt` filter that will specifically capture the new Pi Zero 2 W (i.e., apart from `[board-type=0x12]`)

Using `[pi0]` or `[pi02w]` seems to be working for me but I'm not sure if the latter is correct - ideally I'd like to apply some settings to the Zero 2 W only and not the original Zero.
Either way it'd be great if this could be documented in the table shown at: https://www.raspberrypi.com/documentation/computers/config_txt.html#model-filters

Many thanks!

**Comment by aallan** [comment]
Ping @ghollingworth

**Comment by ghollingworth** [comment]
@pelwell

**Comment by pelwell** [comment]
`[pi02]` is the model-specific section. The Zero 2 is also included by `[pi0]` sections.

**Comment by aallan** [comment]
Added in 12c3c2a, pushed to production in #2257.

**Comment by dwhinham** [comment]
Thanks for the fast responses everyone, much appreciated! :tada:

Really enjoying the new model. :slightly_smiling_face:
