### ISSUE TITLE
Needs update the Power Supply documentation with Pi Zero 2 W requirements.

### ISSUE THREAD

**Issue by Pearl-852** [raspberrypi/documentation#2265]
Needs update for Pi Zero 2 W Power Supply requirements on the [Power Supply documentation](https://github.com/raspberrypi/documentation/blob/develop/documentation/asciidoc/computers/raspberry-pi/power-supplies.adoc).

**Comment by aallan** [comment]
Updated in 49236f5. Will go live next time I push to production.
