### ISSUE TITLE
Add instruction to unzip image file after downloading

### ISSUE THREAD

**Issue by andrewerrington** [raspberrypi/documentation#227]
On this page:
https://github.com/raspberrypi/documentation/blob/master/installation/installing-images/README.md

It does not say to unzip the zip file that was obtained from this page:
https://www.raspberrypi.org/downloads/

So when you go to this page:
https://www.raspberrypi.org/documentation/installation/installing-images/windows.md

Some users may try to write the zip file to the sd card.

I suggest the text for the middle section should be edited from:
Download the image

Official images for recommended Operating Systems are available to download from the Raspberry Pi website: raspberrypi.org/downloads

Alternative distributions are available from third party vendors.

to:
Download the image

Official images for recommended Operating Systems are available to download from the Raspberry Pi website: raspberrypi.org/downloads

Alternative distributions are available from third party vendors.

After downloading a .zip file, unzip it to get the image file (.img) for writing to your SD card.

**Comment by LornaLynch** [comment]
I've added this sentence: I suspect I'm one of the novice users who'd need it!
