### ISSUE TITLE
Audio - omxplayer unsupported

### ISSUE THREAD

**Issue by DeeJay** [raspberrypi/documentation#2282]
Ref: https://www.raspberrypi.com/documentation/computers/os.html#playing-audio-and-video

> The simplest way of playing audio and video on Raspberry Pi is to use the installed OMXPlayer application.

Apparent conflict with recent advice from RPT in RP forums - https://forums.raspberrypi.com/viewtopic.php?t=323281&start=75#p1935385

> {omxplayer on bullseye} No longer supported

Also -
https://forums.raspberrypi.com/viewtopic.php?t=323322#p1935186

_(edited by lurch to fix link-formatting)_

**Comment by aallan** [comment]
The forum answer is correct. OMXPlayer is no longer supported. The documentation needs updating, I've added a quick `[WARNING]` note to the [relevant section](https://www.raspberrypi.com/documentation/computers/os.html#playing-audio-and-video) until that is done.
