### ISSUE TITLE
Docs website inconsistent scrolling area for index

### ISSUE THREAD

**Issue by JamesH65** [raspberrypi/documentation#2285]
![image](https://user-images.githubusercontent.com/3844893/141461410-caa4dbd2-c6be-4fc0-b47a-42d90f8672fe.png)

When mouse is over the index panel, the mouse wheel scrolls the index if you are over text (the red area in picture) but the main window in other places, so a very inconsistent user experience, a slight change in mouse position and suddenly a completely different windows starts scrolling.

**Comment by aallan** [comment]
> When mouse is over the index panel, the mouse wheel scrolls the index if you are over text (the red area in picture) but the main window in other places

When the mouse is over the index it scrolls the index.

When the mouse is over the main panel it scrolls the main panel. 

Not sure what the problem is?

**Comment by lurch** [comment]
I think James is expecting the index to still scroll if the mouse-cursor is to the *left* of the index-area.

**Comment by JamesH65** [comment]
That is indeed what I expect.

**Comment by aallan** [comment]
That's counterintuitive to me, if you're not over the index the main panel should be the one that scrolls.

**Comment by JamesH65** [comment]
You are over the index, just not over the textual part of the index. Mouse scroll over the text, then move the mouse *left* off the text but still in the index. Stop scrolling, start again, suddenly the other window starts scrolling.

Perhaps I should add this is on Chrome on Windows. Might behave differently on other devices.

**Comment by JamesH65** [comment]
Ping. this should not be forgotten.

**Comment by JamesH65** [comment]
Reopening as this is still very odd behaviour which should be fixed.

**Comment by aallan** [comment]
This isn't going to get fixed.

**Comment by JamesH65** [comment]
Shame, it's really odd behaviour that should be fixed.
