### ISSUE TITLE
Documentation PDF Files Use Placeholder Colophon

### ISSUE THREAD

**Issue by Marsfan** [raspberrypi/documentation#2297]
A lot of the Documentation PDF files do not have a colophon set in them, instead they just use the placeholder colophon. 

For an example, see the start of page 2 of the CM4 datasheet.
https://datasheets.raspberrypi.com/cm4/cm4-datasheet.pdf

**Comment by aallan** [comment]
I'm not really sure what you mean by "placeholder colophon" ..?

**Comment by Marsfan** [comment]
Here is the an example from the CM4 datasheet. The bit word **Colophon** should probably not be there.

<details> 
<summary> Missing Colophon </summary>

![image](https://user-images.githubusercontent.com/9311953/142912880-c289021f-7bdc-43e7-b09a-0c719f2376b9.png)

</details>

As a side note, I had sent an email in through the contact form on the Raspberry Pi website and was told to put the issue here instead.

**Comment by aallan** [comment]
You're arguing that the Colophon shouldn't have a section header "Colophon" in the books?

**Comment by Marsfan** [comment]
I may be mistaken, but I believe that instead of saying "Colophon", it should have some sort of publisher's wwordmark. 
Feel free to close if I am mistaken.
