### ISSUE TITLE
Add helpful SIGALERT (CNTL+T) to Mostly Graphical Install section of Mac doc

### ISSUE THREAD

**Issue by willingc** [raspberrypi/documentation#230]
The Command line section of the Mac installation document has this helpful message:

"This will take a few minutes, depending on the image file size. You can check the progress by sending a SIGINFO signal pressing Ctrl+T."

It would be helpful to include this useful tip in the Graphical Install section too. Since writing the image to the SD card takes a while, this tip helps the user know whether writing is progressing.

**Comment by pranav16255** [comment]
https://github.com/raspberrypi/documentation

**Comment by JamesH65** [comment]
Fixed by #445
