### ISSUE TITLE
Update documentation for ahead of Bookworm

### ISSUE THREAD

**Issue by lurch** [raspberrypi/documentation#2314]
~We now [offer both](https://www.raspberrypi.com/news/new-old-functionality-with-raspberry-pi-os-legacy/) Bullseye and Buster (Legacy) releases of Raspberry Pi OS. However some features work in one but not the other, and vice-versa.~

~@JamesH65 has an internal document which is probably a useful starting point for this.~

(edit by @aallan) We need to update the documentation for Bookworm. Online documentation will focus on supporting Bookworm only. There will be NOTE blocks referencing that "things worked differently" in the previous (legacy) version if that's appropriate/needed. We'll try and keep those blocks short.

**Comment by lurch** [comment]
And perhaps https://www.raspberrypi.com/documentation/computers/getting-started.html#installing-the-operating-system and/or https://www.raspberrypi.com/documentation/computers/os.html#introduction ought to mention the different versions too?

**Comment by URRG** [comment]
I want to work on this issue so from where should i start

**Comment by JamesH65** [comment]
This is already underway internally, but it's a private repo.

**Comment by JamesH65** [comment]
Sorry, closed by accident.

**Comment by lurch** [comment]
This should stay open.

**Comment by aallan** [comment]
Should stay open. Still some updating needed. See also #2398.

**Comment by RuffaloLavoisier** [comment]
@aallan 
Are you simply updating the vlc and omx examples according to the version?

**Comment by aallan** [comment]
> @aallan Are you simply updating the vlc and omx examples according to the version?

OMX Player no longer works under Bullseye. All the examples using it in the documentation need to be replaced with an equivalent invocation for VLC (or other relevant software), see #2398 which is the linked issue.

However this issue is the more general "other things that Bullseye broke" issue. There are some other things beyond the OMX Player issue that haven't yet been fixed.

**Comment by RuffaloLavoisier** [comment]
If there is something to be done externally, I would be happy to contribute.

**Comment by lurch** [comment]
This still needs doing, at some point.

**Comment by JamesH65** [comment]
ping

**Comment by aallan** [comment]
Headline things:

 
* X goes away and is replaced by Wayland
   - nominally a big thing, but there has been a lot of work to keep the user experience the same
   - but some change is inevitable
* dhcpcd goes away and is replaced by Network Manager
* random bookworm stuff

**Comment by aallan** [comment]
**Note:**  Documentation should be updated to reflect the *latest* version of the OS. So we're going to go through and make sure it all works with Bookworm. We may need some NOTE blocks that mention "for previous versions of Raspberry Pi OS" from time to time, but these need to be kept short (a couple of medium-length paragraphs at most). We do not have the availability to support multiple versions of the OS in the documentation going forward with breaking changes like Wayland and Network Manager happening.

**Comment by aallan** [comment]
Current tasks associated with this issue:

```[tasklist]
### Bookworm Issues
- [ ] https://github.com/raspberrypi/documentation/issues/2687
- [ ] https://github.com/raspberrypi/documentation/issues/2398
- [ ] https://github.com/raspberrypi/documentation/issues/2310
```

this task list will expand rapidly when @lurch does the documentation audio.

**Comment by lurch** [comment]
Child-issues:
* #2999 
* #2947 
* #2948 
* #2949 
* #2950 
* #2951 
* #2952 
* #2953

**Comment by aallan** [comment]
Done.
