### ISSUE TITLE
Bluetooth "hciattach /dev/serial1 bcm433xx 921600 noflow - $BDADDR" just never works!

### ISSUE THREAD

**Issue by trickkiste** [raspberrypi/documentation#2327]
Bluetooth "hciattach /dev/serial1 bcm433xx 921600 noflow - $BDADDR" just never works!

times out every time
The documentation in this repo is also insufficient!
We need a list of all necessary modules, which need to be loaded in order for this to work, the recommended config.txt setting, ...

**Comment by aallan** [comment]
This is the sort of question you should be asking on the [forums](https://www.raspberrypi.org/forums/), so I’m closing this issue. But please follow up with further comments if you have specific questions about the [documentation](https://www.raspberrypi.org/documentation/).
