### ISSUE TITLE
 apt-get purge raspberrypi-ui-mods breaks networking components.

### ISSUE THREAD

**Issue by robertely** [raspberrypi/documentation#233]
The 'raspberrypi-ui-mods' is unexpectedly tied to some networking components. I'm not entirely sure why, a quick dpkg -c didn't show any thing that should break it.

**Comment by XECDesign** [comment]
Although this isn't a documentation issue, I guess it's because that would remove /etc/network/interfaces. You should have the old version backed up in /etc/network/

**Comment by robertely** [comment]
My mistake, I posed this in the wrong place. I've refiled it, and yes you were right, It did remove /etc/network/interfaces.

https://github.com/RPi-Distro/raspberrypi-ui-mods/issues/2
