### ISSUE TITLE
access-point-routed: iptables

### ISSUE THREAD

**Issue by DeeJay** [raspberrypi/documentation#2337]
Ref: [https://www.raspberrypi.com/documentation/computers/configuration.html#enable-routing-and-ip-masquerading](https://www.raspberrypi.com/documentation/computers/configuration.html#enable-routing-and-ip-masquerading)

Requires **iptables**, but iptables is not pre-installed in any of the 3 variants of the current (31Oct2021) RasPiOS Bullseye [32] image.

**Comment by lurch** [comment]
ping @XECDesign  Did iptables used to be included by default in Buster but no longer included by default in Bullseye?

**Comment by XECDesign** [comment]
iptables was previously included, but not explicitly. It was dragged in by something else.

Documentation should probably be updated to use nftables instead.

**Comment by lurch** [comment]
> Documentation should probably be updated to use nftables instead.

Is nftables also supported in Buster, or would the instructions need to use iptables on Buster and nftables on Bullseye?

**Comment by DeeJay** [comment]
> > Documentation should probably be updated to use nftables instead.
> 
> Is nftables also supported in Buster, or would the instructions need to use iptables on Buster and nftables on Bullseye?

There is no overlap. Buster comes with iptables but not nftables. Conversely, Bullseye comes with nftables but not iptables. (Determined by inspection of the .info files for each image/distro.)

**Comment by XECDesign** [comment]
> Is nftables also supported in Buster,

I assume either is supported in both cases (I haven't had cause to use nftables myself yet), you'd just need to add an appropriate `apt install` step.

> or would the instructions need to use iptables on Buster and nftables on Bullseye?

Is the documentation policy that instructions need to work on oldstable as well? Seems like that could be quite painful in some situations.

**Comment by aallan** [comment]
> Is the documentation policy that instructions need to work on oldstable as well? Seems like that could be quite painful in some situations.

Since the "Legacy" release is officially supported, and is currently Buster (not Bullseye) both have to be supported by the documentation.
