### ISSUE TITLE
Links to documentation on BCM2835 are gone

### ISSUE THREAD

**Issue by peterhgombos** [raspberrypi/documentation#234]
In the [page about the SOC](https://github.com/raspberrypi/documentation/blob/master/hardware/raspberrypi/bcm2835/README.md), there is a link to a Broadcom page with data on the processor, but this page has been removed from the Broadcom web page, and I can't find any alternative source on this.

Is there any current official source on the data of the SoC, i.e. not Wikipedia?

**Comment by XECDesign** [comment]
Was there anything useful on that page? IIRC, it was mostly a 'contact broadcom for more information' page.

**Comment by peterhgombos** [comment]
I have no idea. But I need an official site so I can cite the specifications of the processor for my master thesis, and I guess this page should contain it? I see Wikipedia also cites this missing page a lot.

**Comment by XECDesign** [comment]
Checking through archive.org, it doesn't look like the page contained any real information https://web.archive.org/web/20150411220113/http://www.broadcom.com/products/BCM2835
Perhaps the peripherals manual and the relevant ARM documentation is the thing to cite?

**Comment by XECDesign** [comment]
@bennuttall I guess the link should be removed?

**Comment by bennuttall** [comment]
Yeah it looks like they don't have any info on the chips any more.

**Comment by JamesH65** [comment]
I was unable to find any references to 2835 at all on the Brcm site. Not sure why. Perhaps ask Eben?

**Comment by Doug-Wyman** [comment]
Is this of any help?

 

Never stop learning

Never stop Evolving

 

Doug Wyman

**Comment by Doug-Wyman** [comment]
Mea Culpa, I don't see my attachment which was the 
BCM2835 ARM Peripherals PDF. I am new here so please forgive newby errors.

**Comment by peterhgombos** [comment]
Thanks, @Doug-Wyman, but it seems that the document you sent is at a lower level than what I'm looking for. Not having read it all (I'm sorry, but hardware specs _is_ hard to read), I can't find any overview of the hardware available in it. And this was linked to on the same page, I think.

**Comment by Doug-Wyman** [comment]
@peterhgombos  Ah well, it was worth a try.  I hope your master's thesis is accepted with honors.
And remember to keep on learning.

**Comment by XECDesign** [comment]
Since the link is broken and there isn't anything to replace it with, I've just remove it.
