### ISSUE TITLE
Some spelling Style Guide

### ISSUE THREAD

**Issue by RuffaloLavoisier** [raspberrypi/documentation#2372]
Should I understand most of the English spelling in the technical document based on the [style guide](https://github.com/raspberrypi/style-guide/blob/master/style-guide.md#spelling)? 
Or does this need to be corrected?
`Colour`, `Behaviour`...

**Comment by aallan** [comment]
> Should I understand most of the English spelling in the technical document based on the [style guide](https://github.com/raspberrypi/style-guide/blob/master/style-guide.md#spelling)?
> Or does this need to be corrected?
> `Colour`, `Behaviour`...

English spelling, not American, is correct. So "colour" rather than "color", and "Behaviour" rather than "Behavior". We're a British company after all!

**Comment by RuffaloLavoisier** [comment]
@aallan Thank you for your answer.
