### ISSUE TITLE
CM4 Spi3 Dma

### ISSUE THREAD

**Issue by lovaselek** [raspberrypi/documentation#2373]
Hi,
I read the cm4 documentation and searched all the available sources, but I couldn't find any information about using SPI3 with dma.

The https://datasheets.raspberrypi.com/bcm2711/bcm2711-peripherals.pdf on page 62 does not list the SPI3 in list of DERQ, but Chapter 9 does not write that spi3 could not be used with dma.

Does spi3 also have a bit in the PACTL_CS register? Or it is really not assigned the Spi3 to Dma. 
Any explanation would be great.

Thanks

**Comment by aallan** [comment]
Ping @dp111

**Comment by lurch** [comment]
ping also @pelwell 
Although I suspect the answer is that if SPI3 isn't listed in "4.2.1.3. Peripheral DREQ Signals", then the simple answer is that it isn't supported?

**Comment by pelwell** [comment]
The relevant bits of PACTL_CS have been documented, and no, there is no DREQ signal for SPI3 (nor SPI2) - so no DMA.

**Comment by lovaselek** [comment]
Thanks for the quick response!
Then I will only be able to use it in interrupt mode.
