### ISSUE TITLE
Replacing omxplayer examples in documentation

### ISSUE THREAD

**Issue by aallan** [raspberrypi/documentation#2398]
`omxplayer` was removed in Bullseye. Examples [using it](https://www.raspberrypi.com/documentation/computers/os.html#playing-audio-and-video) need to be replaced. See discussions in #2395.

**Comment by lurch** [comment]
See also #2314

**Comment by omarecd** [comment]
Dear team.
I'm a big Fan of raspberry Pi and following the documentation and I was confused...

If
_The simplest way of playing audio and video on Raspberry Pi is to use the installed OMXPlayer application._
Then
Why was it removed ? :(

I just tried the "vlc example.mp3" and it doesn't work straightforward... Could you remove legacy information and put updated one?

Thanks for the great work.

**Comment by omarecd** [comment]
Ps.
I'm trying "mpg123 example.mp3" and it works like a charm :)
That could be also an option

**Comment by lurch** [comment]
omxplayer uses the 'legacy' graphics stack, which isn't supported on 64-bit. See the section about KMS in https://www.raspberrypi.com/news/raspberry-pi-os-debian-bullseye/

**Comment by omarecd** [comment]
Dear Raspberry Pi Team.
You're doing a great job, it's just that as the situation is still the same (examples need to be updated) I am not sure if closing the issue would be correct. I say this because I received a mail telling me that this would be closed.
Thanks for the great support.

**Comment by aallan** [comment]
Yes, still needs to be done. Unfortunately, we're a small team, and it hasn't reached the top of the pile. We welcome pull requests!

**Comment by lurch** [comment]
Still needs to be done.

**Comment by JamesH65** [comment]
ping

**Comment by aallan** [comment]
Part of the hanging chad from the buster to bullseye move that needs to be done for bookworm.

**Comment by aallan** [comment]
Still a thing!

**Comment by lurch** [comment]
In progress; I'm in the middle of documenting some of VLC's command-line option equivalents to omxplayer.

**Comment by lurch** [comment]
Fixed on the `bookworm` branch. OMXPlayer is still mentioned in `documentation/asciidoc/accessories/tv-hat.adoc`, but that'll get fixed as part of #2936
