### ISSUE TITLE
Add documentation for non-interactive use of raspi-config

### ISSUE THREAD

**Issue by aallan** [raspberrypi/documentation#2454]
Need to document non-interactive use of `raspi-config` through using the `nonint` argument. See RPi-Distro/raspi-config#123 for background details.

**Comment by andrum99** [comment]
I don't think there should actually be any documentation for `raspi-config` in the documentation repo: the reason it exists is that previously there was no GUI-based config tool on the Pi, and it was deemed useful to document the text-based `raspi-config`. Non-technical users will generally use the GUI-based tool, and for the rest the tool should be obvious enough. Each menu option is effectively self-documented, so I don't see any need for there to be documentation for `raspi-config` in this repo.

**Comment by andrum99** [comment]
> > I don't think there should actually be any documentation for `raspi-config` in the documentation repo
> 
> Okay. But as the head of documentation, I _do_ think there should be documentation for `raspi-config` in the documentation repo? 🤔

I'm obviously completely fine with that, and respect that it is entirely up to you. I was just adding my tuppence worth: apologies if that was inappropriate.

**Comment by aallan** [comment]
Still on the list.

**Comment by aallan** [comment]
The #2766 pull request addresses this issue. I think it needs reworked before merge however.

**Comment by aallan** [comment]
Alternative PR #2827 which should close this issue.
