### ISSUE TITLE
Remote Desktop Viewer Conection Configuration

### ISSUE THREAD

**Issue by sbstn-jmnz** [raspberrypi/documentation#246]
On ubuntu 14.04 is needed to supply the full port for a successful connection, not just  ip:X

![issue](https://cloud.githubusercontent.com/assets/4334071/9375078/ce65c52e-46d2-11e5-83d1-0d8cba7e74c7.png)

**Comment by JamesH65** [comment]
We no longer have any Ubuntu specific VNC instruction (the page has changed a lot since this Issue was brought up), so closing.
