### ISSUE TITLE
dtoverlay uart pins

### ISSUE THREAD

**Issue by pbevilac** [raspberrypi/documentation#2490]
[Docs here](https://www.raspberrypi.com/documentation/computers/configuration.html#cm1-cm3-cm3-and-cm4) says: 
_You must also specify which GPIO pins to use, for example_

That is not correct. Specifying GPIO pins is optional, To find what are the default pins used, enter dtoverlay -help uart0, replacing 0 with the UART number of your interest. In addition, UARTs above 0 and 1 do not allow changing GPIO pins.

**Comment by aallan** [comment]
Ping @dp111, this is wrt UART on CM1, CM3, CM3+ and CM4 I think?

**Comment by pbevilac** [comment]
Just to clarify. The section I quoted above is under the header **CM1, CM3, CM3+ and CM4**

But in fact, specifying pins is not a must for UART 0 and 1, and, one can't change them for UARTs numbered above 1.

**Comment by aallan** [comment]
Fixed in 021fe13
