### ISSUE TITLE
please provide burnt capacitor values

### ISSUE THREAD

**Issue by CastixGitHub** [raspberrypi/documentation#2499]
Hello I'm unable to find the value of `C20` and `C101` in this [sheet](https://datasheets.raspberrypi.com/rpi/raspberry-pi-b-plus-reduced-schematics.pdf)
 for raspberry pi B+ v1.2

also what's `U3`?
Thank you

**Comment by lurch** [comment]
The Raspberry Pi isn't open hardware - we won't be publishing details beyond those already provided.

> also what's U3?

![Screenshot from 2022-04-06 23-59-57](https://user-images.githubusercontent.com/476186/162086828-83c992ca-d690-4947-be75-735b12ef310e.png)

Looks like an IC that takes a 5V input on pins 7 and 1, and generates a 3.3V output on pin 8 and a 1.8V output on pin 2 ?
