### ISSUE TITLE
QRCODE purpose on rpi's back (rpi model 2 B v1.1)

### ISSUE THREAD

**Issue by d0t0** [raspberrypi/documentation#250]
Sorry for creating an issue, but I didn't find anything related on this matter in the documentation or rpi message boards.

There is a QRCODE label on the back of the rpi 2. The code is 16 digits long. It starts with 5 zeros and then random decimal values.

My question is, what data is the QRCODE holding and how do I parse it. I've attached a image of the code.

![img_20150907_134635](https://cloud.githubusercontent.com/assets/14161802/9716355/22ffdfe4-5569-11e5-9448-40157d6544e7.jpg)

**Comment by ghollingworth** [comment]
It is a serial number used by the manufacturer to track the Pi, if you decode it, it'll just give you some random number that gets put into the big random number storage system at Sony!

Gordon
