### ISSUE TITLE
raspios 2022-04-07 image format changed from zip to xz

### ISSUE THREAD

**Issue by CNMan** [raspberrypi/documentation#2510]
related chapters
https://www.raspberrypi.com/documentation/computers/getting-started.html

**Comment by aallan** [comment]
This is the sort of question you should be asking on the [forums](https://www.raspberrypi.org/forums/), so I’m closing this issue. But please follow up with further comments if you have specific questions about the [documentation](https://www.raspberrypi.org/documentation/).
