### ISSUE TITLE
Change headless documentation

### ISSUE THREAD

**Issue by nmcc1212** [raspberrypi/documentation#2513]
change https://www.raspberrypi.com/documentation/computers/configuration.html#setting-up-a-headless-raspberry-pi

to reflect the changes outlined here

https://www.raspberrypi.com/news/raspberry-pi-bullseye-update-april-2022/

mainly that `If you are installing Raspberry Pi OS Lite and intend to run it headless, you will need to create a new user account.` now also applies to the full pi os now as well as lite

**Comment by aallan** [comment]
That has been done? e.g.
<img width="962" alt="Screenshot 2022-04-20 at 20 51 20" src="https://user-images.githubusercontent.com/53625/164311590-65388937-1549-4e04-b86d-4d566797b9e1.png">
and
<img width="946" alt="Screenshot 2022-04-20 at 20 51 25" src="https://user-images.githubusercontent.com/53625/164311599-b7646384-4470-4012-9be4-34a0b764003e.png">
in the headless section, and if you're talking about the full installation, see this entire section? 

https://www.raspberrypi.com/documentation/computers/getting-started.html#configuration-on-first-boot

**Comment by nmcc1212** [comment]
the message says Raspberry Pi OS Lite but this happens on Raspberry Pi OS aswell

**Comment by aallan** [comment]
The message says "since you will not be able to create a new user account on first boot". In the full desktop OS, as is documented, a wizard runs on first boot that allows you to create a new user.
