### ISSUE TITLE
Default pi user has been removed

### ISSUE THREAD

**Issue by Steccah** [raspberrypi/documentation#2515]

**Comment by lurch** [comment]
Yes, see https://www.raspberrypi.com/news/raspberry-pi-bullseye-update-april-2022/ and https://www.raspberrypi.com/documentation/computers/getting-started.html#configuration-on-first-boot

**Comment by Steccah** [comment]
Sorry my fault, i wanted to reference this: https://www.raspberrypi.com/documentation/computers/using_linux.html#linux-users

**Comment by RuffaloLavoisier** [comment]
@lurch 
Should these changes be reflected throughout the document?

> Yes, see https://www.raspberrypi.com/news/raspberry-pi-bullseye-update-april-2022/ and https://www.raspberrypi.com/documentation/computers/getting-started.html#configuration-on-first-boot

**Comment by lurch** [comment]
Ah, right...

**Comment by RuffaloLavoisier** [comment]
@lurch 
I want to help you with this part. What should I do?

**Comment by lurch** [comment]
Myself and @aallan will be discussing this on Monday (we're both going to be in Cambridge!).

**Comment by aallan** [comment]
We may just entirely remove the "Using Linux" section. We're not really in the business of teaching folks to use UNIX, and honestly, the section doesn't do a great job in any case. Perhaps it's had its day and should just be deleted. 🤔

**Comment by RuffaloLavoisier** [comment]
@aallan 
I agree with you.  website is full of more extensive material.

**Comment by aallan** [comment]
Submitted PR to remove the 'Using Linux' section entirely. See #2519.
