### ISSUE TITLE
config.txt: The conditional-filters label is duplicated

### ISSUE THREAD

**Issue by pelwell** [raspberrypi/documentation#2560]
The label `conditional-filters` is used twice in the config.txt documentation - once in the Advanced Features section on a small heading for a paragraph that is just a taster link to the dedicated Conditional Filters section, and once in the Conditional Filters section itself. The duplication breaks the taster link, causing the user to have to search for the content some other way.

**Comment by lurch** [comment]
"Duplicate" of #2351

**Comment by aallan** [comment]
Oh! Yes, forgot that one. Closing as duplicate.
