### ISSUE TITLE
missing datasheet(s) for chipset on display interface board

### ISSUE THREAD

**Issue by chriscamacho** [raspberrypi/documentation#257]
as per title really!

with even just the datasheet for the LCD/backlight controller there would be at least 1/2 a chance the community could make simple tools like backlight manipulation etc

oh and a circuit diagram would be useful, especially to see what's on the 5v and grd rails

**Comment by JamesH65** [comment]
Unfortunately the display chip used datasheet is under NDA and cannot be released, and there is no current intention to release the schematic of the board. So will close for the moment.
