### ISSUE TITLE
Question: How do you guys make your datasheets?

### ISSUE THREAD

**Issue by John15321** [raspberrypi/documentation#2609]
I'm sorry if this question could be placed in some sort of discussion section but I couldn't find it.

I think your datasheets look amazing and I wanted to know what tools/templates are you using to create them.
I would love to be using the same ones in my projects

https://datasheets.raspberrypi.com/rp2040/rp2040-datasheet.pdf

**Comment by aallan** [comment]
Thanks! We're pretty happy with them. Our datasheets and other PDFs are generated from Asciidoc source, using asciidoctor and asciidoctor-pdf with a custom template system and a Python and Make-based toolchain. While I'm happy to talk about architecture and toolchain in general, and will be doing that at [PageBreak](https://www.pagebreakconf.com/) later in the year, the templates and code aren't public and we don't currently intend to release them. Sorry!
