### ISSUE TITLE
Problem with PiFace Inputs

### ISSUE THREAD

**Issue by tompreston** [raspberrypi/documentation#262]
In the file: `documentation/usage/scratch/gpio/README.md` regarding PiFace, it says:

> There is an observed problem with the inputs being flighty to say the least, and merely holding a finger near the input terminal blocks appears to cause flickering of the read values.

This sounds like the input pull-ups have not been initialised causing the inputs to float rather that *default* to 1. 

See:
- https://github.com/piface/pifacedigitalio/blob/master/pifacedigitalio/core.py#L113
- https://github.com/piface/libpifacedigital/blob/master/src/pifacedigital.c#L59-L60

That is, register `GPPUB` needs to be set to `0xFF`.

Can someone fix this or point me in the right direction to correct it please? :)

**Comment by bennuttall** [comment]
Thanks @tompreston I've passed this on
