### ISSUE TITLE
exec format error on vncboot direct copy/paste

### ISSUE THREAD

**Issue by chahld** [raspberrypi/documentation#263]
I tried to follow the directions in the readme for setting up vncboot. When I copy and pasted the text as is into the vncboot file, it didn't work because the exec fails to run the script since the first line is a comment. 

I moved the #! /bin/sh to the first line from the 10th line or so, and it worked properly. 

I was using the following image: 2015-09-24-raspbian-jessie.img running on a Raspberry Pi 2 B V1.1

**Comment by lurch** [comment]
Looking at the current content of that page (it had some recent updates), I guess this issue can be closed now?
