### ISSUE TITLE
cross compiling linux kernel

### ISSUE THREAD

**Issue by MisterAero** [raspberrypi/documentation#2631]
[the unclear section](https://github.com/raspberrypi/documentation/blob/develop/documentation/asciidoc/computers/linux_kernel/building.adoc#install-directly-onto-the-sd-card)

It doesn't say whether the sd card should be taken off from the rpi into the other Linux host and then inserted back,
or directly need to work on the rpi.

**Comment by lurch** [comment]
Doesn't the title "Install Directly onto the SD Card" and the part that says "this is best done directly using an SD card reader" make it clear that you need to insert your Raspberry Pi's SD card into a card-reader on your PC (the one where you're doing the actual cross-compiling) ? :man_shrugging:
