### ISSUE TITLE
UART doc misses Zero 2W

### ISSUE THREAD

**Issue by cmangla** [raspberrypi/documentation#2713]
The [UART documentation](https://github.com/raspberrypi/documentation/blob/198fa799af0bdf1c7d8a4f5d17a03ffffc3402aa/documentation/asciidoc/computers/configuration/uart.adoc) contains a table in the section "Primary and Secondary UART" listing all Pi models, except for Pi Zero 2W.

Please add Pi Zero 2W to the table.

**Comment by lurch** [comment]
@pelwell Are the UART mappings on the Pi Zero 2 W the same as on the Pi Zero W?

**Comment by pelwell** [comment]
Yes.
