### ISSUE TITLE
[TUTORIAL] Connecting via SSH/ retrieving one's IP address

### ISSUE THREAD

**Issue by epoch1970** [raspberrypi/documentation#2716]
Some tutorials advocate (rightly, IMHO) using mDNS to connect without prior knowledge of the IP address.

However this one at least https://www.raspberrypi.com/tutorials/nas-box-raspberry-pi-tutorial/ directs users to lookup the IP address in their router.

**Comment by aallan** [comment]
Thanks. That's one of the older ones. That needs fixing. Ping @tobybroberts.

**Comment by lurch** [comment]
@tobybroberts You'll also need to advise the user to set a unique hostname in the Raspberry Pi Imager settings.

**Comment by tobybroberts** [comment]
Still to do.

**Comment by aallan** [comment]
Still a thing!

**Comment by aallan** [comment]
Still needs doing.

**Comment by aallan** [comment]
@tobybroberts If you have time could you duck into the tutorial and resolve this one? Shouldn't take that long I think?

**Comment by tobybroberts** [comment]
Tutorial updated. Although it's worth noting that whilst the setup can use hostname.local the openmediavault webserver can only be opened using the LAN IP address.
