### ISSUE TITLE
USB Ports documentation

### ISSUE THREAD

**Issue by cmangla** [raspberrypi/documentation#2719]
See documentation/asciidoc/computers/raspberry-pi/usb-bus-on-raspberry-pi.adoc

For pi4, the document clearly states how many USB ports of which version are available. For pi{zero,1,2,3}, under the paragraph "Raspberry Pi Zero, 1, 2 and 3", the same information is not explicitly noted. It would be useful to note here, for each Pi, the USB ports and versions, and possibly the connected controllers.

**Comment by lurch** [comment]
Sounds similar to #2657 ?
For the benefit of anybody else reading this: [here](https://www.raspberrypi.com/documentation/computers/raspberry-pi.html#raspberry-pi-4) is where the above-mentioned page appears in our online documentation.

**Comment by aallan** [comment]
Stil valid.

**Comment by aallan** [comment]
Still valid.
