### ISSUE TITLE
Does micropython for Pico W support PEAP/MSCHAPV2 ?

### ISSUE THREAD

**Issue by jjzheng01** [raspberrypi/documentation#2722]
Hi,

I want to connect the Pico W to WiFi network which requires the username and password. But there is no document about it. 

Does the micropython for the Pico W support PEAP/MSCHAPV2 ? Or when is this feature available? 

Thanks,

**Comment by aallan** [comment]
MicroPython specific questions are probably better directed to the MicroPython forum, https://forum.micropython.org/viewforum.php?f=21.
