### ISSUE TITLE
Supports liunx header command in custom compile kernel.

### ISSUE THREAD

**Issue by BrokenWingsIcarus** [raspberrypi/documentation#2746]
In the kernel header section, the header files provided in the source code library are described. If the kernel is compiled manually, you should provide specific commands to copy the header files to the pi at the same time, so as to obtain the complete binary kernel and its header files.

https://www.raspberrypi.com/documentation/computers/linux_kernel.html#kernel-headers

**Comment by aallan** [comment]
Not a documentation issue. This is the sort of question you should be asking on the [forums](https://www.raspberrypi.org/forums/), so I’m closing this issue. But please follow up with further comments if you have specific questions about the [documentation](https://www.raspberrypi.org/documentation/).

**Comment by BrokenWingsIcarus** [comment]
In the kernel header section, it is described that the header file has been provided in the source code library. If the kernel is compiled manually, the corresponding header file should also be copied to pi 4 at the same time, so as to obtain the complete binary kernel and its header file.

https://www.raspberrypi.com/documentation/computers/linux_kernel.html#kernel-headers

**Comment by BrokenWingsIcarus** [comment]
Forgive me, I'm not a native speaker..
