### ISSUE TITLE
Debug Probe docs - OpenOCD info

### ISSUE THREAD

**Issue by ndabas** [raspberrypi/documentation#2789]
In https://github.com/raspberrypi/documentation/blob/develop/documentation/asciidoc/microcontrollers/debug-probe/installing-tools.adoc:

- I believe the currently tested and recommended branch to use from https://github.com/raspberrypi/openocd/ is `rp2040-v0.12.0` -- so we should update the `git ... --branch ...` commands appropriately.
- The link in the MS Windows section saying "An OpenOCD Windows package is available for download" points to a very old build from 2021 which will likely not work (unless a new release is planned to be uploaded.) The Windows installer does have a new, tested build available though: https://github.com/raspberrypi/pico-setup-windows/releases/download/v0.4.0/openocd-0.12.0-g4257276-202301271019-x64-standalone.zip.

**Comment by aallan** [comment]
> * The link in the MS Windows section saying "An OpenOCD Windows package is available for download" points to a very old build from 2021 which will likely not work (unless a new release is planned to be uploaded.) 

That should be updated later today.

> The Windows installer does have a new, tested build available though: https://github.com/raspberrypi/pico-setup-windows/releases/download/v0.4.0/openocd-0.12.0-g4257276-202301271019-x64-standalone.zip.

I'll link to that. Thanks.
