### ISSUE TITLE
Documentation for LED 2/3/4/5 for Debug Probe

### ISSUE THREAD

**Issue by resterampeberlin** [raspberrypi/documentation#2799]
Picoprobe contains several status LED (LED 2/3/4/5) attached to GPIOs (7/8/15/16) of the internal RP2040. However, their meaning is not documented yet.

**Comment by aallan** [comment]
Do you mean the LEDs on the [Debug Probe](https://www.raspberrypi.com/documentation/microcontrollers/debug-probe.html) hardware, or for the [Pico Probe](https://github.com/raspberrypi/picoprobe) software you run on a Raspberry Pi Pico?

**Comment by resterampeberlin** [comment]
I mean D2/3/4/5 in the actual probe hardware and as depicted in the schematic. I received the probe hardware yesterday, and after the first tests, I have some ideas about what those LEDs mean, but formal documentation would be great.

**Comment by P33M** [comment]
D2 (green) - GPIO7 - UART_RX activity
D3 (yellow) - GPIO8 - UART_TX activity
D4 (green)  - GPIO15 - DAP_CONNECTED
D5 (yellow) - GPIO16 - DAP_TARGET_RUNNING

Note that OpenOCD just switches both DAP LEDs on when the target is connected, and turns them off when it calls DAP_DISCONNECT. Other debug hosts do more fanciful things.

**Comment by aallan** [comment]
I'll add that to the documentation page.
