### ISSUE TITLE
Doxygen: Fix Copy-to-Clipboard functionality for code

### ISSUE THREAD

**Issue by nelliemckesson** [raspberrypi/documentation#2806]
Adjust code HTML so that copy to clipboard works.

**Comment by lurch** [comment]
...or disable it for the doxygen-code-examples, as we expect people to be getting example code directly from the https://github.com/raspberrypi/pico-examples repo? :shrug:  It's @aallan 's call to make.

**Comment by aallan** [comment]
May as well allow copy to clipboard. I mean it'd be a nice-to-have to link it to the example that's getting pulled in maybe. But that sounds like more work when we all have lots to do.
