### ISSUE TITLE
Doxygen: Add sdk version number in a different location

### ISSUE THREAD

**Issue by nelliemckesson** [raspberrypi/documentation#2807]
> It's kinda a shame that the SDK-version-number gets written to _config.yml, which is a file that's under version-control, as it means that git shows _config.yml as changed whenever the SDK-version changes. Would there be any way to do this without modifying a git-controlled file?

**Comment by aallan** [comment]
Related #2811 (may influence how the SDK version number is pulled out or written to?)

**Comment by nelliemckesson** [comment]
Fixed by #2846
