### ISSUE TITLE
Doxygen: Fix formatting of email address

### ISSUE THREAD

**Issue by nelliemckesson** [raspberrypi/documentation#2808]
This section of the HTML-doxygen (see https://raspberrypi.github.io/pico-sdk-doxygen/group__pico__printf.html )

![dox-orig](https://user-images.githubusercontent.com/812739/221643115-948296ed-0418-4c21-b9db-e27bbba8ca52.png)

renders like this on the new version:

![Screenshot from 2023-02-26 21-32-27](https://user-images.githubusercontent.com/812739/221643171-cc52cc01-89c6-4fd0-b3d5-e952a896bf79.png)

**Comment by nelliemckesson** [comment]
@lurch is the problem that there's no space above the first line of normal text?

**Comment by lurch** [comment]
Nope, the problem is the way the email address is getting mangled.

**Comment by nelliemckesson** [comment]
Ohhhhhh @lurch my eyes were not prepared to see that, haha
