### ISSUE TITLE
Wordpress instructions need an update.

### ISSUE THREAD

**Issue by DougieLawson** [raspberrypi/documentation#281]
The instructions at: https://www.raspberrypi.org/learning/lamp-web-server-with-wordpress/worksheet/ need to be updated to take account of the changes from Apache2 2.2 (Wheezy) to Apache2 2.4 (Jessie)

Basically the stuff about editing /etc/apache2/sites-available/default needs some reworking. The stuff that says 
```
You'll also need to tell the virtual host serving the site to allow requests to be 
overwritten. Do this by editing the virtual host file (with root permissions): 
sudo nano /etc/apache2/sites-available/default; also, change the AllowOverride 
setting on line 11 (inside the <Directory /var/www/> block) from None to All. 
Save the file and then restart Apache with sudo service apache2 restart. 
Once it's restarted, refresh the page and it should load successfully.
```
does not work, because /etc/apache2/sites-enabled/default doesn't exist and the replacement /etc/apache2/sites-enabled/000-default.conf doesn't have AllowOverride on line 11.

**Comment by bennuttall** [comment]
This is a learning resources issue, not a documentation issue. The resource has been updated now.
