### ISSUE TITLE
Doxygen: Use correct top-level title

### ISSUE THREAD

**Issue by nelliemckesson** [raspberrypi/documentation#2810]
I've just noticed that every single page under /pico-sdk/ has "Pico C SDK" as its top-level header.

![Screenshot from 2023-02-27 12-19-19](https://user-images.githubusercontent.com/812739/221643873-12de4590-5cfd-4b73-85aa-521ff4b2303c.png)

Perhaps it'd be more appropriate to put the "page title" there (if we have one), so "High Level APIs" in the screenshot above?

**Comment by aallan** [comment]
Yup the page title should be there, so "High Level APIs" in that particular case

**Comment by nelliemckesson** [comment]
@lurch turns out this is being caused by the [asciidoc variables that are added in create_build_adoc.py](https://github.com/raspberrypi/documentation/blob/develop/scripts/create_build_adoc.py#L89-L98). The page titles are pulled from those variables, and since those variables are added before the index.json gets generated (which is how the pico-sdk subpages are included in index.json), they're just using the default page title for everything. I attempted to fix but ran into some walls related to the sequence that things are being run -- figured it might be best just to toss it over to you and let you take a stab.
