### ISSUE TITLE
Doxygen: Display pico-sdk version number on all (doxygen) pages

### ISSUE THREAD

**Issue by lurch** [raspberrypi/documentation#2811]
At the moment the SDK version-number is visible on the "boxes page"
![Screenshot from 2023-02-27 17-59-54](https://user-images.githubusercontent.com/476186/221645615-e96507b6-88b0-42ee-a7f5-c54d7b9c7120.png)

It might be nice if this was visible on _every_ Doxygen page?
![Screenshot from 2023-02-27 18-00-46](https://user-images.githubusercontent.com/476186/221645830-8b8bdb9d-10e5-4860-93d9-51c785eac1fb.png)

(but obviously only if @aallan agrees)

**Comment by aallan** [comment]
Yes, I think I agree with this one. The version number should be on all of the `pico-sdk/*` pages.
