### ISSUE TITLE
Doxygen: inter-page navigation isn't quite working properly

### ISSUE THREAD

**Issue by lurch** [raspberrypi/documentation#2829]
If I'm looking at https://www.raspberrypi.com/documentation/pico-sdk/networking.html and then in the LHS-menu I expand the "High Level APIs" section, if I then click on the "pico_multicore -> Functions" menu-item, it goes to https://www.raspberrypi.com/documentation/pico-sdk/high_level.html#functions-5 but it doesn't auto-scroll to the right part of the page. On this new page (now that I'm looking at `high_level.html`) the LHS-menu says that the "pico_multicore -> Functions" menu-item is https://www.raspberrypi.com/documentation/pico-sdk/high_level.html#functions30 and clicking on that _does_ auto-scroll to the right part of the (same) page.

**Comment by lurch** [comment]
Hmmm, I've also just spotted that if I do "open in new tab" on that https://www.raspberrypi.com/documentation/pico-sdk/high_level.html#functions30 link above, it also doesn't scroll to the right part of the page! So then I noticed that on the **right**-hand-side of the page, the funny-symbol (see screenshot below) on the "pico_multicore -> Functions" header has the URL https://www.raspberrypi.com/documentation/pico-sdk/high_level.html#rpipf840d967c7b8d6fef316 and this is a URL which _does_ scroll to the right part of the page when I "open in new tab".
![Screenshot from 2023-03-03 17-51-32](https://user-images.githubusercontent.com/476186/222792584-176cf4d5-54c6-491c-b19e-4eac83e0ce6b.png)

**Comment by aallan** [comment]
Fixed by #2865

**Comment by nelliemckesson** [comment]
See #3117
