### ISSUE TITLE
CSS problem with copyright block in Safari

### ISSUE THREAD

**Issue by aallan** [raspberrypi/documentation#2874]
In Safari the copyright block is fully left justified against the side of the browser. 

<img width="1131" alt="Screenshot 2023-03-23 at 13 04 48" src="https://user-images.githubusercontent.com/53625/227213298-bd2ad675-1d26-4c51-8a48-62586205386e.png">

In Chrome everything seems to render as it should

<img width="1067" alt="Screenshot 2023-03-23 at 13 05 00" src="https://user-images.githubusercontent.com/53625/227213373-9ad596ab-4b96-4a63-b1ac-640dd1d8b6d6.png">

**Comment by nelliemckesson** [comment]
Seems to be a screen-size issue (happens for me in Chrome as well at smaller window sizes). Should be fixed by #2890 !
