### ISSUE TITLE
docs: openssl passwd -6 command not work on macOS

### ISSUE THREAD

**Issue by xgqfrms** [raspberrypi/documentation#2895]
# `openssl passwd -6` command does not work on macOS 

> Documentation needs to be updated to clearly describe it.

```sh
# Linux
$ openssl passwd -6

```

https://www.raspberrypi.com/documentation/computers/configuration.html#configuring-a-user

https://github.com/raspberrypi/documentation/blob/develop/documentation/asciidoc/computers/configuration/headless.adoc#configuring-a-user

## env

macOS `13.1`

![image](https://user-images.githubusercontent.com/7291672/232274796-1b68a75c-be67-4ad1-918e-8417d0d35b12.png)

```sh
$ openssl version
LibreSSL 3.3.6
````

![image](https://user-images.githubusercontent.com/7291672/232275275-6453ecbd-c002-4790-8727-bed140ca45eb.png)

## macOS

```sh
#  ❌
$ openssl passwd -6
unknown option '-6'
usage: passwd [-1 | -apr1 | -crypt] [-in file] [-noverify] [-quiet]
    [-reverse] [-salt string] [-stdin] [-table] [password]

 -1                 Use MD5 based BSD password algorithm 1
 -apr1              Use apr1 algorithm (Apache variant of BSD algorithm)
 -crypt             Use crypt algorithm (default)
 -in file           Read passwords from specified file
 -noverify          Do not verify password
 -quiet             Do not output warnings
 -reverse           Reverse table columns (requires -table)
 -salt string       Use specified salt
 -stdin             Read passwords from stdin
 -table             Output cleartext and hashed passwords (tab separated)


```

![image](https://user-images.githubusercontent.com/7291672/232274675-f4986838-1b3e-4179-b159-46a2ac3c758a.png)

```sh
# ✅
$ openssl passwd
$ openssl passed  -noverify

```

![image](https://user-images.githubusercontent.com/7291672/232274680-4414f16a-d732-40c6-871c-f473e86bbef5.png)

## situation

I just want to `Set up a Headless Raspberry Pi` with my Mac, by adding a `userconf.txt` file to the boot folder to create a user on the first boot, then just copy it to the SD card's `boot partition`.

By the way, I do have not a monitor for PC / Linux.

That's why I come to the issue.

## refs

https://www.raspberrypi.com/documentation/computers/configuration.html#setting-up-a-headless-raspberry-pi

https://www.raspberrypi.com/documentation/computers/configuration.html#configuring-a-user

https://www.raspberrypi.com/documentation/computers/getting-started.html#installing-the-operating-system

**Comment by aallan** [comment]
I'm not sure why you're asking a macOS question on the Raspberry Pi documentation site?

**Comment by xgqfrms** [comment]
In my opinion it's just that the documentation doesn't describe it clearly.

**Comment by cmitu** [comment]
@xgqfrms but you're not actually using `openssl`, but a fork - LibreSSL.

The latest version of `openssl` is 3.1.0, which doesn't have the issue you're describing:
```
$ openssl version
OpenSSL 3.1.0 14 Mar 2023 (Library: OpenSSL 3.1.0 14 Mar 2023
$ echo test | openssl passwd -6 -in -
$6$8L2unG1nB1wI46pM$vk2WctBAKSZNYunjjn.P4PjHEj62CN.SOZW8gAkYHpwRsP.wvWuy1Lytrpo1PPi39Ryha51fm62JyFmv5wi0Q0
```

**Comment by DG12** [comment]
Please reopen this issue. 
Documentation should not instruct user to issue a command that does not work on Mac OS.  
What is the alternative for Mac OS users?

**Comment by katshann-raspberry** [comment]
> Please reopen this issue. Documentation should not instruct user to issue a command that does not work on Mac OS. What is the alternative for Mac OS users?

Hello, the openssl command does work on Mac OS if you have openssl installed. (But doesn't work with the default Mac alternative of LibreSSL). I believe you can install openssl on your Mac OS with `brew install openssl`. 
Let me know if that works for you.

**Comment by DG12** [comment]
Thank you for the recommendation, 
however,
the documentation causes **dismay** when instructions given fail :-(

And I know this is not raspberry territory but,down another rabbit hole...
brew install 
**Reinstalled pkgconf due to macOS version mismatch
Failed during: /opt/homebrew/bin/brew update --force --quiet**

**Comment by katshann-raspberry** [comment]
@DG12 Ah - sorry to hear that you're in a macOS rabbit hole with this. Sadly, we don't have the resource or knowledge to document deeply for other folks' operating systems and their idiosyncrasies. We'll shortly be adding a note to the docs to warn macOS users that their behaviour ay differ and require extra steps.

**Comment by DG12** [comment]
Thank you again for your response. 
Is it possible to correct the documentation to omit the algorithm ?
The openssl documentation at [https://docs.openssl.org/1.0.2/man1/passwd/](https://docs.openssl.org/1.0.2/man1/passwd/) defines it as optional and this would work an all systems.

**Comment by lurch** [comment]
@DG12 You've linked to a very old version of the OpenSSL docs (1.0.2) - the latest version is 4.0 https://docs.openssl.org/4.0/man1/openssl-passwd/#description

As you can see on that page:
> * -1
Use the MD5 based BSD password algorithm 1 (default).

So if you omit the algorithm, you'll get [MD5](https://en.wikipedia.org/wiki/MD5) by default, which is a known-insecure hashing algorithm, so we won't be recommending that.

**Comment by DG12** [comment]
As it appears that the only secure algorithm supported is -6.

Please add note to the documentation that Mac OS does not support this and homebrew should be used to install the more recent version of openssl.

Thank you gain for you attention to the distressing issue.

**Comment by lurch** [comment]
> As it appears that the only secure algorithm supported is -6.

Yep. I did a bit of investigation yesterday, and found [this](https://www.baeldung.com/linux/shadow-passwords#3-crypt-and-encryption-algorithms) nice explanation of Linux password-hashing methods, and [how](https://www.baeldung.com/linux/shadow-passwords#generate-etcshadow-passwords-with-openssl) to create them with OpenSSL.

I also found the LibreSSL implementation of the `openssl passwd` command [here](https://github.com/libressl/openbsd/blob/master/src/usr.bin/openssl/passwd.c#L56) and I can't see _any_ reason why it would omit the `-5` and `-6` options 🤷  Although obviously even if those options _were_ added to LibreSSL, it'd take a while before they appeared in macOS.
 
> Please add note to the documentation that Mac OS does not support this and homebrew should be used to install the more recent version of openssl.

Yes, as explained earlier, this is exactly what @katshann-raspberry is in the process of doing 🙂

**Comment by DG12** [comment]
Thank you both. What about the idea of directing users to use an on-line website to generate the password hash?
This would this would make it easy for users on any platform.

For example [https://tools.keycdn.com/sha256-online-generator](https://tools.keycdn.com/sha256-online-generator) generates sha256 passwords, 
[https://bcrypt.online/](https://bcrypt.online/) will generate bcrypt passwords or [https://argon2.online/](https://argon2.online/) to generate argon2 hashes.

**Comment by lurch** [comment]
> What about the idea of directing users to use an on-line website to generate the password hash?

There's no way of guaranteeing that any online password-hashing website isn't also storing a copy of your original password! 😉 
Also, we generally have a policy of only documenting our own software, and don't link to or recommend 3rd-party websites / services.

**Comment by DG12** [comment]
My final comment:
To allay fears of password storing and without recommending any 3rd party website I am sure that raspberry pi team has sufficient talent an time to create simple web page to accept a password string, sanitize it, call openssl passwd and display the password hash.

Out.

**Comment by lurch** [comment]
...or you could just use Raspberry Pi Imager https://www.raspberrypi.com/documentation/computers/getting-started.html#imager-install
