### ISSUE TITLE
Sense Hat calibration instructions

### ISSUE THREAD

**Issue by keithellis74** [raspberrypi/documentation#290]
The calibration information is missing from hardware/sense hat/README.md.  This information exists spread over a few posts in the Raspberry Pi forum but is hard to find.  I have forked the repo and have consolidated the calibration instructions into the Sense Hat README.md ready to be pushed.  If you give me the okay, I shall push.  I think it really needs to be added here, it is the easiest place to find.

**Comment by XECDesign** [comment]
Yes please, that would certainly be helpful. There are a few things I'd change, but that can be done later.

**Comment by keithellis74** [comment]
Pull request completed.
