### ISSUE TITLE
Duplicated 'Getting Started' documentation

### ISSUE THREAD

**Issue by aallan** [raspberrypi/documentation#2907]
Should integrate any unique content from https://www.raspberrypi.com/tutorials/how-to-set-up-raspberry-pi/ into the main getting started documentation, https://www.raspberrypi.com/documentation/computers/getting-started.html.

**Comment by aallan** [comment]
Still valid, and I'm tagging as a Bookworm issue now.

**Comment by jehlers42** [comment]
Merged into bookworm branch.
