### ISSUE TITLE
Tutorial: Magic Mirror updates 

### ISSUE THREAD

**Issue by tobybroberts** [raspberrypi/documentation#2923]
Tested the tutorial with Bookworm. NPM not currently bundled with NodeJS in Bookworm and needs to be installed manually. PM2 autostart now doesn't start the Magic Mirror. NPM stop command also does not work.

**Comment by tobybroberts** [comment]
`sudo apt install npm` and then running `git pull && npm run install-mm` from within the MagicMirror folder seems to fix all issues when using Bookworm.

**Comment by tobybroberts** [comment]
To rotate your screen by 90 degrees using Bookworm edit the `.config/wayfire.ini `file and add the following -
```
[output]
transform=90
```

**Comment by tobybroberts** [comment]
Amended tutorial ready to be published.

**Comment by aallan** [comment]
Deployed (needed feature image as did a lot of these things)
