### ISSUE TITLE
Tutorial: How to set up a Raspberry Pi 

### ISSUE THREAD

**Issue by tobybroberts** [raspberrypi/documentation#2924]
How to set up a Raspberry Pi tutorial will need new screen grabs when Bookworm is added to Raspberry Pi Imager

**Comment by aallan** [comment]
See #2907. That tutorial needs integrating into the main documentation site, it doesn't sit where it currently lives.

**Comment by aallan** [comment]
Still needs doing.

**Comment by aallan** [comment]
This has been merged into our mainline documentation in #3041. Post bookworm that tutorial in Wordpress just needs turning "off".
