### ISSUE TITLE
Tutorial: How to build a Raspberry Pi NAS

### ISSUE THREAD

**Issue by tobybroberts** [raspberrypi/documentation#2927]
Tutorial does not work with Raspberry Pi Bookworm OS. Installation error - Unsupported version.  Only Debian 10 (Buster) and 11 (Bullseye) are supported.  Exiting...

**Comment by aallan** [comment]
> Installation error - Unsupported version. Only Debian 10 (Buster) and 11 (Bullseye) are supported. Exiting...

Where does this error come from?

**Comment by tobybroberts** [comment]
Error when running - sudo wget -O - https://github.com/OpenMediaVault-Plugin-Developers/installScript/raw/master/install | sudo bash

**Comment by lurch** [comment]
Presumably Open Media Vault will update to support Bookworm at some point in future, after it has been released as stable? So perhaps we could add a warning at the top of the tutorial that it'll currently only work on Bullseye, and then revisit this when OMV updates? :shrug:

**Comment by aallan** [comment]
I'd presume so, but honestly if we're doing a tutorial I'd prefer something a lot closer to the metal — something to show folks how to set up network shares and other such things from the command line and using the config files — rather than using something monolithic like OMV.

**Comment by aallan** [comment]
Still a thing.

**Comment by aallan** [comment]
@nathan-contino So this is a Wordpress press thing rather than a doc site thing (although there is now a macro to insert a pointer to a wordpress tutorial, see #3082 for that) so we should point to the tutorial in the appropriate place in the documentation now.

**Comment by lurch** [comment]
> (although there is now a macro to insert a pointer to a wordpress tutorial, see https://github.com/raspberrypi/documentation/pull/3082 for that)

Once Bookworm is out of the way, maybe we need some meta-docs in this repo that future-us can refer to, for how to use all these new features that @nelliemckesson has been adding? :thinking:

**Comment by aallan** [comment]
Probably a fair, so #3096.

**Comment by aallan** [comment]
Closing in favour of #3126.
