### ISSUE TITLE
Update the Raspberry Pi cluster tutorial for Bookworm

### ISSUE THREAD

**Issue by aallan** [raspberrypi/documentation#2928]
The [cluster tutorial](https://www.raspberrypi.com/tutorials/cluster-raspberry-pi-tutorial/) makes extensive use of networking, all of which is going to change hugely due to the switch to Network Manger.

**Comment by aallan** [comment]
Still needs doing.

**Comment by aallan** [comment]
WIll probably be a post-Bookworm release task. But it still needs doing.

**Comment by BrookeDot** [comment]
Hi @aallan is there a TL;DR: version on what the switch to Network Manager means for this tutorial and clustering in general on the Pi 4/5?

**Comment by vlzambr2** [comment]
Commenting on this just to make sure it doesn't go stale again 🙈 . Definitely in need of this tutorial, my cluster is going to be stuck on Bullseye until a beginners' guide to clustering with Network Manager is published.

**Comment by aallan** [comment]
Sorry. Forgot to update the issue. The tutorial has been already been updated for Bookworm.
