### ISSUE TITLE
After setting up VNC, mouse pointer shows as "x"

### ISSUE THREAD

**Issue by DSA101** [raspberrypi/documentation#293]
After following the instructions how to setup VNC, and connecting to my PI with a VNC client (RealVNC), mouse cursor showed as an "x" instead of the more common arrow. This looks strange and not particularly good if you are coming coming from a Mac, Windows or Ubuntu Linux flavors where arrow mouse cursors are used.

I've proposed the doc change to address this (pull request #292). The solution is to use the following parameter for xsetroot in ./vnc/xstartup
-cursor_name left_ptr

**Comment by bennuttall** [comment]
Fixed in #292
