### ISSUE TITLE
Hardware: check that our Camera instructions work on Bookworm

### ISSUE THREAD

**Issue by lurch** [raspberrypi/documentation#2933]
https://www.raspberrypi.com/documentation/accessories/camera.html
https://www.raspberrypi.com/documentation/computers/camera_software.html

**Comment by lurch** [comment]
Nothing can be done here until `libcamera-apps` gets packaged for Bookworm.

**Comment by lurch** [comment]
Issue in bookworm-feedback https://github.com/raspberrypi/bookworm-feedback/issues/27

**Comment by aallan** [comment]
Now a raspberrypi/bookworm-feedback issue.
