### ISSUE TITLE
Hardware: check that our Display instructions work on Bookworm

### ISSUE THREAD

**Issue by lurch** [raspberrypi/documentation#2934]
https://www.raspberrypi.com/documentation/accessories/display.html

**Comment by aallan** [comment]
Still needs doing.

**Comment by aallan** [comment]
There is problem under Wayland. It looks as if Wayland only has touch begin, end, update and cancel events - there doesn't seem to be anything at all in there which does any specific handling of double-taps. Simon L is looking into it.

**Comment by lurch** [comment]
Assigning this to myself, as I already started making some of the changes for this a while ago.

**Comment by lurch** [comment]
Fixed on `bookworm` branch.
