### ISSUE TITLE
Hardware: check that our TV HAT instructions work on Bookworm

### ISSUE THREAD

**Issue by lurch** [raspberrypi/documentation#2936]
https://www.raspberrypi.com/documentation/accessories/tv-hat.html

**Comment by aallan** [comment]
Still needs doing.

**Comment by lurch** [comment]
Issue in bookworm-feedback https://github.com/raspberrypi/bookworm-feedback/issues/25

**Comment by aallan** [comment]
Now a raspberrypi/bookworm-feedback issue.

**Comment by aallan** [comment]
Removed OMXPlayer reference in 4fb9841.
