### ISSUE TITLE
Remove raspicam documentation

### ISSUE THREAD

**Issue by lurch** [raspberrypi/documentation#2938]
MMAL is no longer supported in Bookworm, which means the old raspistill / raspivid / etc. commands will no longer work.
https://www.raspberrypi.com/documentation/computers/camera_software.html#raspicam-applications

Should just leave a NOTE that if users really want to use the legacy camera applications, they'll need to use Legacy OS (which will become Bullseye, once Bookworm has been released).

**Comment by JamesH65** [comment]
End of an era! Those apps are 10 years old this year!

**Comment by lurch** [comment]
:birthday:

**Comment by lurch** [comment]
Also need to remove any parts that talk about using `raspi-config` to enable the camera, as I believe that's no longer necessary.

**Comment by lurch** [comment]
Merged to `bookworm` branch.
