### ISSUE TITLE
Tutorial: Block ads on every device in your house with a Raspberry Pi and Pi-hole

### ISSUE THREAD

**Issue by tobybroberts** [raspberrypi/documentation#2939]
Pi-hole using Raspberry Pi Bookworm OS fails to install. Currently Pi-Hole only support  Buster and Bullseye

**Comment by aallan** [comment]
Still a thing.

**Comment by aallan** [comment]
@nathan-contino Another Wordpress one for you!

**Comment by aallan** [comment]
So Pi Hole now supports Debian 12 (aka Bookworm) according to https://docs.pi-hole.net/main/prerequisites/#supported-operating-systems. While it doesn't officially support our downstream Bookworm on Raspberry Pi, there is presumably no show-stoppers here. Upstream is *probably now ready* for us to proceed on this one.

If you do run into problems with installation @nathan-contino, can you please raise a compatibility issue on the project's Github repo, https://github.com/pi-hole/pi-hole. If they're not preparing for Bookworm on Pi, they need to be.

**Comment by nathan-contino** [comment]
Updated tutorial is live now!
