### ISSUE TITLE
VNC Instructions require some modifications

### ISSUE THREAD

**Issue by seancull** [raspberrypi/documentation#294]
When following the instruction ( https://www.raspberrypi.org/documentation/remote-access/vnc/ ) on a vanilla install of RASPBIAN JESSIE I had the following issue

If the default setting of auto login is enabled then the session : 0 cannot be used and the error message below is created.
Warning: raspberrypi:0 is taken because of /tmp/.X0-lock
Remove this file if there is no X server raspberrypi:0
A VNC server is already running as :0

see http://stackoverflow.com/a/34577704/1167715

**Comment by seancull** [comment]
sorry - ignore item 2 - it is covered in the instructions

**Comment by lurch** [comment]
Looking at the current content of that page (it had some recent updates), I guess this issue can be closed now?
