### ISSUE TITLE
Remove or heavily edit the Python documentation

### ISSUE THREAD

**Issue by lurch** [raspberrypi/documentation#2943]
The Raspberry Pi documentation doesn't feel like the right place to be teaching people about variables and lists in Python. https://www.raspberrypi.com/documentation/computers/os.html#python

So at the very _least_ we should get rid of the "Basic Python usage" section https://www.raspberrypi.com/documentation/computers/os.html#basic-python-usage

**Comment by aallan** [comment]
I think just cut this entire section, https://github.com/raspberrypi/documentation/blob/develop/documentation/asciidoc/computers/os/using-python.adoc.

**Comment by lurch** [comment]
The only reason I didn't _immediately_ say cut the entire section, was because it also mentions piwheels, which **is** Raspberry Pi-specific.  :man_shrugging:
