### ISSUE TITLE
Copy-edit needed

### ISSUE THREAD

**Issue by lurch** [raspberrypi/documentation#2944]
![Screenshot from 2023-05-16 16-58-40](https://github.com/raspberrypi/documentation/assets/476186/498b7a8f-5d0d-4c60-ae20-88dad41629c4)
https://www.raspberrypi.com/documentation/computers/os.html#useful-utilities

Shockingly, it's been like this since August 2021 :rofl: 
![Screenshot from 2023-05-16 17-00-51](https://github.com/raspberrypi/documentation/assets/476186/453a77c7-00d7-430f-ba9d-77b391d156c8)

**Comment by aallan** [comment]
Still needs doing.

**Comment by lurch** [comment]
I already fixed this on the `bookworm` branch, so this will get fixed when that gets merged in. https://github.com/raspberrypi/documentation/blob/bookworm/documentation/asciidoc/computers/os/graphics-utilities.adoc
