### ISSUE TITLE
Mother-issue: Removal of support for "Legacy graphics"

### ISSUE THREAD

**Issue by lurch** [raspberrypi/documentation#2952]
KMS is now the supported graphics-stack.

Child issues:
* #2941 
* #2942 
* #2725 
* #2310 
* #2940 
* #2957
* #2959
* #2989

**Comment by macmpi** [comment]
Hi,
It would be helpful to mention in `config.txt` (**current** and **legacy**) from which kernel version/rpi-firmware commit kms driver has become default for all Pis.
This information is very important for Pi users/maintainers on other distros than PiOS.
Thanks for consideration.
