### ISSUE TITLE
Mother-issue: Base Debian-version changing from bullseye (11) to bookworm (12)

### ISSUE THREAD

**Issue by lurch** [raspberrypi/documentation#2953]
Child issues:
* #2927 
* #2939 
* #2954 
* #2923 
* #2924 
* #2932 
* #2933
* #2934 
* #2935 
* #2936 
* #2937

**Comment by aallan** [comment]
Still needs doing.

**Comment by aallan** [comment]
Okay. All done. Tutorials are either waiting for upstream changes or ready to merge. So I'm closing this one.
