### ISSUE TITLE
Screen-blanking section needs to be checked / updated

### ISSUE THREAD

**Issue by lurch** [raspberrypi/documentation#2959]
https://www.raspberrypi.com/documentation/computers/configuration.html#configuring-screen-blanking

**Comment by aallan** [comment]
Still needs doing.

**Comment by lurch** [comment]
https://forums.raspberrypi.com/viewtopic.php?p=2139724#p2139847 has new information on adjusting the screen-blanking timeout. Do we want to add that to the documentation @aallan ?
