### ISSUE TITLE
Various parts of camera-software page need to be updated

### ISSUE THREAD

**Issue by lurch** [raspberrypi/documentation#2960]
see e.g.
https://www.raspberrypi.com/documentation/computers/camera_software.html#driver-differences-when-using-libcamera-or-the-legacy-stack
https://www.raspberrypi.com/documentation/computers/camera_software.html#software-interfaces
https://www.raspberrypi.com/documentation/computers/camera_software.html#raspicam-applications

**Comment by aallan** [comment]
> https://www.raspberrypi.com/documentation/computers/camera_software.html#raspicam-applications

I think it's likely we'll cut the chord and remove documentation around the legacy raspicam apps.

**Comment by lurch** [comment]
> I think it's likely we'll cut the chord and remove documentation around the legacy raspicam apps.

Yes, there's already #2938 for that; this issue is more about updating any "other wording" that refers to the legacy raspicam apps.
