### ISSUE TITLE
Firmware Warning Icons are no longer a thing

### ISSUE THREAD

**Issue by lurch** [raspberrypi/documentation#2962]
According to @spl237 these were removed (from the firmware?) back in 2020! So we should remove them from the documentation https://www.raspberrypi.com/documentation/computers/configuration.html#firmware-warning-icons

**Comment by JamesH65** [comment]
Were they removed, or is it that KMS doesn't have them, but FKMS and legacy graphics stack still do?

(Another end of an era - I remember adding those to the docs many years ago!)

**Comment by aallan** [comment]
Still needs doing.
