### ISSUE TITLE
Adjust image caption styling

### ISSUE THREAD

**Issue by nelliemckesson** [raspberrypi/documentation#2968]
Figure captions are currently larger than body text.

![Screen Shot 2023-05-24 at 9 09 16 AM](https://github.com/raspberrypi/documentation/assets/812739/791f9166-17b6-4be8-91ca-f1cca8430f8c)

https://www.raspberrypi.com/documentation/computers/getting-started.html#configuration-on-first-boot

**Comment by aallan** [comment]
Can we drop the autogenerated "Figure X" as well, and just leave the captions?

**Comment by lurch** [comment]
https://docs.asciidoctor.org/asciidoc/latest/macros/images/#figure-caption-label

**Comment by aallan** [comment]
That works!
