### ISSUE TITLE
Clarification in DPI documentation - pixel clocks or line?

### ISSUE THREAD

**Issue by toptensoftware** [raspberrypi/documentation#2988]
Is this really "in pixel clocks"?  

Normally vsync pulse width is expressed in lines.  If this really is pixel clocks, perhaps explicitly state "yes pixel clocks, not lines".

https://github.com/raspberrypi/documentation/blob/dcbaf3813d7ff04e2bd2d4192a615597633070dc/documentation/asciidoc/computers/raspberry-pi/display-parallel-interface.adoc?plain=1#L430

**Comment by 6by9** [comment]
It's lines.

**Comment by lurch** [comment]
#2989 says "Use of dpi_timings= is only applicable to the legacy display stack" so closing this issue as invalid too.
