### ISSUE TITLE
linux - filesystem - backup.md : backing up Home directory does not work

### ISSUE THREAD

**Issue by DeeJay** [raspberrypi/documentation#299]
As documented:
cd /home/
tar czf pi_home.tar.gz pi

Result:
pi@raspberrypi ~ $ cd /home/
pi@raspberrypi /home $ tar czf pi_home.tar.gz pi
tar (child): pi_home.tar.gz: Cannot open: Permission denied
tar (child): Error is not recoverable: exiting now
pi@raspberrypi /home $

Clearly user pi does not have write permission into /home. Can be fixed by invoking tar with sudo.

**Comment by DeeJay** [comment]
A note about how to restore from this backup would also be beneficial.

**Comment by bennuttall** [comment]
Good point! PR welcome...

**Comment by lurch** [comment]
I guess "how to restore from this backup" would depend on whether you only want to overwrite particular files with older versions (in which case a graphical archive utility would be your best bet) - or whether you actually want to restore *everything* from the archive, potentially overwriting (or losing) any recent work you've done... ?

**Comment by JamesH65** [comment]
Currently waiting for confirmation to merge the linked PR.

**Comment by LornaLynch** [comment]
I've edited and merged the PR. Closing this.
