### ISSUE TITLE
/opt/vc/ directory no longer exists

### ISSUE THREAD

**Issue by lurch** [raspberrypi/documentation#2996]
...so any mentions of it should be deleted, or edited as appropriate.

**Comment by jehlers42** [comment]
Is there a replacement or alternate directory the docs should reference?

Looks like most of the references are related to the command line. For example:
* omxplayer --display n /opt/vc/src/hello_pi/hello_video/test.h264
* cc myfile.c -I/opt/vc/include -L/opt/vc/lib -lbcm_host -o myfile
* Enter the following command to give a list of DMT-supported modes: `/opt/vc/bin/tvservice -m DMT`

**Comment by lurch** [comment]
I've already done parts of this (on the [bookworm](https://github.com/raspberrypi/documentation/tree/bookworm) branch), and other parts will get done in due course, so I'm going to assign this back to me :slightly_smiling_face:

**Comment by lurch** [comment]
On the bookworm branch, `/opt/vc/` now only appears in `documentation/asciidoc/computers/legacy_config_txt/video.adoc` so I think this can be closed now.
