### ISSUE TITLE
Touch Display installation needs better instructions

### ISSUE THREAD

**Issue by lurch** [raspberrypi/documentation#3007]
The photo at https://www.raspberrypi.com/documentation/accessories/display.html#physical-installation doesn't seem very clear as to exactly which pins are being connected to which. Especially given that the pin-labels on the Touch Display's PCB aren't readable once a Raspberry Pi has been screwed onto the standoffs!

We should also add some wording about "if the touchscreen printed circuit board is powered directly", similar to that shown in https://datasheets.raspberrypi.com/display/7-inch-display-product-brief.pdf

**Comment by aallan** [comment]
See also #3007

**Comment by aallan** [comment]
So #3121 and subsequent changes by me to fix the narrative have fixed some of the problems here, but it needs an actual installation walkthrough, with step-by-step pictures. 

Possibly we should use GIFs like the [Build HAT instructions](https://www.raspberrypi.com/documentation/accessories/build-hat.html#preparing-your-build-hat) for this. That'll need Brian or possibly Jack involved.

**Comment by aallan** [comment]
One for you @nathan-contino, but networking things first!

**Comment by nathan-contino** [comment]
The installation instructions have since been overhauled significantly. I think this has been addressed!
