### ISSUE TITLE
Need to update screen shot instructions

### ISSUE THREAD

**Issue by aallan** [raspberrypi/documentation#3009]
With X being replaced by Wayland, scrot has gone away and has been replaced by grim, see https://forums.raspberrypi.com/viewtopic.php?t=353631. 

From that forum thread…

> The Wayland equivalent of scrot is grim - it is preinstalled and works the same; images are put in the Pictures directory; it is already linked to the PrtScn key.

**Comment by lurch** [comment]
I'd have to check more carefully, but it's _possible_ that there isn't any current documentation for taking screenshots?
```console
$ git grep -i "scrot" "*.adoc
$ git grep -i "screenshot" "*.adoc"
$ git grep -i "screen shot" "*.adoc"
$ git grep -i "screencapture" "*.adoc"
$ git grep -i "screen capture" "*.adoc"
documentation/asciidoc/computers/remote-access/vnc.adoc:Please note that direct screen capture is an experimental feature. If you're connecting from a desktop computer and mouse movements seem erratic, try pressing *F8* to open the VNC Viewer shortcut menu and selecting *Relative Pointer Motion*.
```
