### ISSUE TITLE
X Windows vs Wayland sudo permissions

### ISSUE THREAD

**Issue by aallan** [raspberrypi/documentation#3012]
See https://forums.raspberrypi.com/viewtopic.php?t=353648 for a very long discussion thread about what's going on. The most likely outcome for Bookworm on Pi is that, going forward, you are no longer able to `sudo` a Wayland application.

**Comment by ghollingworth** [comment]
This has now all been fixed

**Comment by lurch** [comment]
Confirmed fixed. I can now launch GParted from the menu, or `gparted` or `sudo gparted` from the CLI, and in all situations it works properly.
