### ISSUE TITLE
NetworkManager randomised MAC addresses

### ISSUE THREAD

**Issue by aallan** [raspberrypi/documentation#3013]
Document NetworkManager randomising MAC addresses, see for instance https://forums.raspberrypi.com/viewtopic.php?t=353678.

**Comment by lurch** [comment]
Latest comment in that forum thread suggests that MAC address randomisation might get disabled by default, in which case no change would be needed to the docs.

**Comment by aallan** [comment]
Need to check with @ghollingworth if there's been a final decision there then.

**Comment by ghollingworth** [comment]
Not sure this needs documenting?

It's normal behaviour for WiFi devices to randomise their MAC address while scanning for APs.

**Comment by aallan** [comment]
> It's normal behaviour for WiFi devices to randomise their MAC address while scanning for APs.

My impression was that the randomization was in a phone-like way every time it connected to the network, rather than just during the scanning stage?

**Comment by lurch** [comment]
According to that same forum thread, this has now been disabled. Closing this issue.
