### ISSUE TITLE
First installation wizard instructions

### ISSUE THREAD

**Issue by aallan** [raspberrypi/documentation#3028]
Make sure the first installation wizard looks and feels the same way as decribed in the Getting Started section. See also and affects #2907.

e.g. the overscan section *should* go away as it doesn't affect Wayland. Check with @spl237.

**Comment by spl237** [comment]
The overscan section is still required for Wayland, as some monitors still require it. 

We just haven't worked out how to support it in Wayland yet, as it is stupidly complicated to do so. The intention is still that it will be supported somehow by the time we release.

**Comment by spl237** [comment]
No significant changes that the user should notice, no - just stuff under the hood. The wizard stuff on that page looks fine to me.

**Comment by aallan** [comment]
Thanks! Closing this one!

**Comment by lurch** [comment]
@aallan I'm _fairly_ sure I've asked this before, but should the images on https://www.raspberrypi.com/documentation/computers/getting-started.html#configuration-on-first-boot be cropped better, so that the text is more discernible?

**Comment by lurch** [comment]
Fair enough.
