### ISSUE TITLE
Create top level "legacy" config.txt box

### ISSUE THREAD

**Issue by aallan** [raspberrypi/documentation#3029]
Move all the legacy `config.txt` options from the current `config.txt` page into a new top-level box to go on the Computers tab.

Need a box illustration from @jackbenwillis.

**Comment by aallan** [comment]
> Hey @aallan what's the name of this new section?

So the current section is this

<img width="493" alt="Screenshot 2023-07-27 at 16 30 17" src="https://github.com/raspberrypi/documentation/assets/53625/819d4b85-ea5a-4683-894b-ec6223f01bad">

So, err, I'm going to go with "Legacy config.txt" ? So something that looks like this icon, but suggests... older?

@lurch was going to make an Asana task for you, but I guess if you saw this, it is not needful. :)

**Comment by jackbenwillis** [comment]
<img width="1139" alt="Screenshot 2023-07-27 at 16 46 10" src="https://github.com/raspberrypi/documentation/assets/25119475/c2c571f5-2d27-420e-8402-c97a3370fe41">
This?

**Comment by jackbenwillis** [comment]
Please don't use this...

**Comment by jackbenwillis** [comment]
How about faded config.txt file?

**Comment by aallan** [comment]
Works! @lurch when you spin up the new top box can you please use the icon above! :)

**Comment by lurch** [comment]
Thanks @jackbenwillis !

**Comment by lurch** [comment]
![Screenshot from 2023-08-01 11-54-29](https://github.com/raspberrypi/documentation/assets/476186/8ec41094-98a5-4679-a9bc-f7235fcf72cc)
