### ISSUE TITLE
Expand RP2040 design file section

### ISSUE THREAD

**Issue by aallan** [raspberrypi/documentation#3034]
The [current section](https://www.raspberrypi.com/documentation/microcontrollers/rp2040.html#design-files) leaves a lot to be desired. Needs to be expanded. Should include pointers to the upcoming bookazine around the Hackspace [JLCPCB-friendly version](https://raspberrypi.social/@concretedog@mastodon.social/110814190940537756) of the Minimal Viable Board. Need to host the KiCAD of this design alongside Jame's original!

![image](https://github.com/raspberrypi/documentation/assets/53625/2484f035-d48a-4085-842d-f7edec640e06)

Reference to the bookazine should look like [this section](https://www.raspberrypi.com/documentation/computers/os.html#going-further) which reminds me, that needs templating and adding as a toolchain option (see #3035 for that) like we did for the White Papers (see #2973 for that).

**Comment by aallan** [comment]
Still waiting for upstream and the Hackspace lot.

**Comment by nllho** [comment]
Closing this as Won't Do: moving forward, we're going to avoid book callouts in this format.

**Comment by lurch** [comment]
Just for the benefit of anybody stumbling across this issue in future... the mentioned "bookazine" actually turned into a full book:
https://www.raspberrypi.com/news/new-book-release-design-an-rp2040-board-with-kicad/
