### ISSUE TITLE
Integration of Raspberry Pi Press book titles

### ISSUE THREAD

**Issue by aallan** [raspberrypi/documentation#3035]
A thought brought on by #3034.

There are a couple of these now, 

<img width="853" alt="Screenshot 2023-08-01 at 13 09 08" src="https://github.com/raspberrypi/documentation/assets/53625/553934c5-a226-476a-a879-041bc09d214d">

which link out to the [released PDFs repo](https://github.com/raspberrypipress/released-pdfs/). There is also this, 

<img width="893" alt="Screenshot 2023-08-01 at 13 10 25" src="https://github.com/raspberrypi/documentation/assets/53625/5782b48c-a9d8-4e8a-bc10-4fcb8031f7b6">

which doesn't and links to a "Buy Me" page (or at least should do).

We should template this link we did for the White Papers (see #2973 for more on that).

Book titles where it's free in the [released PDFs repo](https://github.com/raspberrypipress/released-pdfs/) we link directly to the PDF, when it's "current" and free we should go through an interstitial and allow people to donate (this is current practice for these titles @bjepson?), and where they are current for sale, it should link to the page where they can buy them!

**Comment by bjepson** [comment]
> Book titles where it's free in the released PDFs repo we link directly to the PDF, when it's "current" and free we should go through an interstitial and allow people to donate (this is current practice for these titles @bjepson?), and where they are current for sale, it should link to the page where they can buy them!

At the moment, the links to buy books are all on the store page: https://store.rpipress.cc/collections/latest-bookazines

But the downloads are on [The MagPi](https://magpi.raspberrypi.com/books) or [HackSpace](https://hackspace.raspberrypi.com/books) sites. Eventually we'll have a new version of the store, and will be only releasing free downloads for out of print books, so the GitHub repo will be a good choice for direct PDF downloads.

**Comment by nelliemckesson** [comment]
@aallan it looks like currently these are just level-3 sections. Should we turn them into boxes, like the whitepaper links, or keep them as sections but add the requisite metadata (image, link, etc.)?

**Comment by nelliemckesson** [comment]
@aallan [draft here](https://github.com/raspberrypi/documentation/pull/3040)! Is this what you had in mind? Should we automate the inclusion of the cover image as well?

**Comment by aallan** [comment]
Yes, we should totally automate the inclusion of the cover image.

**Comment by nelliemckesson** [comment]
@aallan ok, updated to automate the image as well -- see the updated comment in #3040

**Comment by aallan** [comment]
Merged #3040
