### ISSUE TITLE
Add documentation around Orca for visually impaired users

### ISSUE THREAD

**Issue by aallan** [raspberrypi/documentation#3036]
Our general advice to visually impaired users is to check out Raspberry VI (http://www.raspberryvi.org/pages/), a community project dedicated to providing blind and visually impaired Raspberry Pi users with answers, advice, and ideas. 

However, there is also Orca:

> There is a voice prompt when you run the [first installation?] wizard telling you how to install Orca. At any point, in the wizard or in the desktop, hit ctrl-alt-space and Orca will install and the Pi will reboot; when it comes back up, Orca will be running.

We need to find somewhere in the docs to add information about Orca.

**Comment by lurch** [comment]
Fixed by #3058
