### ISSUE TITLE
"Updating the firmware on the Debug Probe" needs editing

### ISSUE THREAD

**Issue by lurch** [raspberrypi/documentation#3051]
There's a [new release](https://github.com/raspberrypi/picoprobe/releases/tag/picoprobe-cmsis-v1.0.3) of PicoProbe / DebugProbe firmware, so the NOTE at https://www.raspberrypi.com/documentation/microcontrollers/debug-probe.html#updating-the-firmware-on-the-debug-probe will need some light editing.

**Comment by aallan** [comment]
Closed in #3074
