### ISSUE TITLE
Need to document touchscreen configuration

### ISSUE THREAD

**Issue by lurch** [raspberrypi/documentation#3086]
Under Wayland, the touch-screen part (input) of the Raspberry Pi Touch Display doesn't get automatically associated with the display-screen part (output) of the Raspberry Pi Touch Display. You need to configure it manually in the "Screen Configuration" program.

**Comment by aallan** [comment]
Guess that needs to get integrated into https://www.raspberrypi.com/documentation/accessories/display.html

**Comment by lurch** [comment]
Fixed on `bookworm` branch.
