### ISSUE TITLE
Mistake in webcam tutorial

### ISSUE THREAD

**Issue by aallan** [raspberrypi/documentation#3098]
The [webcam tutorial](https://www.raspberrypi.com/tutorials/plug-and-play-raspberry-pi-usb-webcam/) says that USB gadget mode can be used on any Pi, but it's only Pi Zero, Zero 2, and Pi 4 (USB-C connector). It can't work on the others as the USB ports are on the wrong side of a USB hub.

Needs fixing up. Forum thread at https://forums.raspberrypi.com/viewtopic.php?t=355020.

**Comment by tobybroberts** [comment]
Tutorial updated - removed unsuitable models, typo and updated rc.local commands.

**Comment by tobybroberts** [comment]
Done
