### ISSUE TITLE
How to tell which LED is ACT or Power

### ISSUE THREAD

**Issue by xgqfrms** [raspberrypi/documentation#3108]
# How to tell which LED is ACT or Power

> Raspberry Pi 4B 8GB

Red LED, long flash, no blink
Green LED, long flash, no blink

https://github.com/raspberrypi/documentation/blob/develop/documentation/asciidoc/computers/configuration/led_blink_warnings.adoc

**Comment by lurch** [comment]
The red LED is power, the green LED is activity.

I can't tell what you're asking here, are you having a problem with your Raspberry Pi? If you are, the right place to ask for questions about that is at https://forums.raspberrypi.com/

**Comment by xgqfrms** [comment]
## It seems the Raspberry Pi has a bug

The green LED blink 6 times, and the red LED not blink (long flashes).

https://github.com/raspberrypi/rpi-eeprom/issues/484

https://www.youtube.com/watch?v=LlQJZUC2jCw
