### ISSUE TITLE
libcamera-apps fails to detect tensorflow-lite

### ISSUE THREAD

**Issue by sihellem** [raspberrypi/documentation#3122]
Hi all,

I upgraded my Pi today (```Raspbian GNU/Linux 11 (bullseye)```), and it resulted in breaking libcamera, with any command resulting in:
```
libcamera-vid: error while loading shared libraries: libcamera.so.0.0.4: cannot open shared object file: No such file or directory
```

Hence, I decided to do a fresh install of all the suite (libcamera, libepoxy, libcamera-apps) using the last install type ```meson``` (instead of previously ```CMake```)

Everything went well but for TensorFlow Lite (which was previously running without any issue on the same machine).

Although I used the flags enabling TensorFlow Lite during the build, it fails to detect it:
```
meson setup build -Denable_libav=true -Denable_drm=true -Denable_egl=true -Denable_qt=true -Denable_opencv=true -Denable_tflite=true
The Meson build system
Version: 1.2.1
...
Run-time dependency opencv4 found: YES 4.5.1
Found CMake: /usr/bin/cmake (3.18.4)
Run-time dependency tensorflow-lite found: NO (tried pkgconfig and cmake)
Build targets in project: 7

libcamera-apps 1.2.1

  libcamera
    location             : /usr/local/lib/arm-linux-gnueabihf
    version              : 0.0.5

  Build configuration
    libav encoder        : YES
    drm preview          : YES
    egl preview          : YES
    qt preview           : YES
    OpenCV postprocessing: YES
    TFLite postprocessing: NO

  User defined options
    enable_drm           : true
    enable_egl           : true
    enable_libav         : true
    enable_opencv        : true
    enable_qt            : true
    enable_tflite        : true

Found ninja-1.11.1.git.kitware.jobserver-1 at /usr/local/bin/ninja
```

I read in the installation notes that the ```libcamera-apps/post_processing_stages/meson.build``` may need to be tweaked.

But how? What's to be modified?

**Comment by aallan** [comment]
This question is probably better suited to [the forums](https://forums.raspberrypi.com/viewforum.php?f=43&sid=98935758cf55b88bc1d0d91cb4b5ea76).
