### ISSUE TITLE
De-emphasise `userconf.txt`

### ISSUE THREAD

**Issue by lurch** [raspberrypi/documentation#3128]
Currently at https://www.raspberrypi.com/documentation/computers/configuration.html#setting-up-a-headless-raspberry-pi we have this boxout:
![Screenshot from 2023-09-21 00-06-10](https://github.com/raspberrypi/documentation/assets/476186/c86729a2-b485-4d80-a40b-1b7f2aef721b)

I _suspect_ that this was added before Raspberry Pi Imager gained the ability to add a new user account, as the above boxout makes it sound like creating `userconf.txt` is the preferred way of creating a new user. IMHO that boxout (and any other relevant sections on that page) should be re-ordered to **first** recommend configuring things using Raspberry Pi Imager, and then describe the manual methods afterwards.

**Comment by jehlers42** [comment]
Suppose I could look at this as part of #2537?

**Comment by lurch** [comment]
Fixed by #3166 :tada:
