### ISSUE TITLE
Replace instruction on how to install the OS in all tutorials

### ISSUE THREAD

**Issue by aallan** [raspberrypi/documentation#3150]
Replace the instructions on how to install the OS in [all of the tutorials](https://www.raspberrypi.com/tutorials) on the main site with a link back to the documentation, https://www.raspberrypi.com/documentation/computers/getting-started.html#installing-the-operating-system.

**Comment by lurch** [comment]
> Should also remove this tutorial entirely, https://www.raspberrypi.com/tutorials/how-to-set-up-raspberry-pi/.

See also #2907 ?

**Comment by aallan** [comment]
Oh, tagging @tdewey-rpi in this one for in-the-loop reasons.

**Comment by aallan** [comment]
So #2907 is closed, and I'm not sure why because it was not completed. So I've opened #3183.

**Comment by nathan-contino** [comment]
The tutorials have all been updated.
