### ISSUE TITLE
Add wifi to eth network bridge to documentation

### ISSUE THREAD

**Issue by BarnOwlDown** [raspberrypi/documentation#3163]
Hi there!
I will be nice and appreciated to have an how to about a network bridge from wifi to Ethernet.
I searched online and I found numerous way to do it, but some of them don't work.

**Comment by lurch** [comment]
You mean like this? https://www.raspberrypi.com/documentation/computers/configuration.html#use-your-raspberry-pi-as-a-network-bridge
:slightly_smiling_face:

**Comment by BarnOwlDown** [comment]
No, sorry for this misunderstanding. I mean a reverse bridge. My Raspberry is connected to internet through wlan0 and I want to share internet connection to ethernet.

The documentation show how to share Ethernet connection to wireless, isn't it?

**Comment by lurch** [comment]
ping @nathan-contino

**Comment by aallan** [comment]
What the OP is asking for is a mirrored but identical implementation to the example shown in the documentation. In this case you use wlan0 as the parent network in the bridge, and eth0 as the other network.
