### ISSUE TITLE
Remove references to using wpa_supplicant.conf

### ISSUE THREAD

**Issue by aallan** [raspberrypi/documentation#3164]
Since Bookworm shipped you can no longer use `wpa_supplicant.conf` to configure wireless networking before first boot, you have to use Imager to do this for while setting up the SD Card. This will become more obvious when "new Imager" ships (soon).

For now we need to remove instructions to configure wireless using `wpa_supplicant.conf` in the documentation.

**Comment by aallan** [comment]
@nathan-contino This got missed amongst the many changes. Can you do this as an interrupt task, shouldn't take long its not referenced widely.

```
configuration/boot_folder.adoc:==== wpa_supplicant.conf
configuration/headless.adoc:You will need to define a `wpa_supplicant.conf` file for your particular wireless network. Put this file onto the boot folder of the SD card. When the Raspberry Pi boots for the first time, it will copy that file into the correct location in the Linux root file system and use those settings to start up wireless networking.
configuration/headless.adoc:A xref:configuration.adoc#wireless-networking-command-line[`wpa_supplicant.conf`] file example:
```

**Comment by vinceskahan** [comment]
If possible, I'd suggest that you indicate it 'did' work (for many years) and that it is still supported in previous versions.  There are many places/uses where people will need to stay on older deb-based versions for quite a while until the various apps catch up, which might take a while.

I'd word it with a note box saying "for os based on debian-11 or earlier...." or the like with the old wording, which was fine.

**Comment by aallan** [comment]
> If possible, I'd suggest that you indicate it 'did' work (for many years) and that it is still supported in previous versions. 

Reasonable. See #3169.
