### ISSUE TITLE
Need to note that the TV HAT doesn't do ATSC

### ISSUE THREAD

**Issue by aallan** [raspberrypi/documentation#3175]
The TV HAT uses DVB-T and DVB-T2, and doesn't work with the US ATSC standard. Need to add a `NOTE` to the TV HAT documentation. See https://raspberrypi.social/@rodmur@socialclub.nyc/111236463499475040.

**Comment by lurch** [comment]
The [product brief](https://datasheets.raspberrypi.com/tv-hat/tv-hat-product-brief.pdf) has a useful link to http://www.dvb.org/resources/public/images/site/dvb-t2_map.pdf (although it seems that link now auto-redirects to https://dvb.org/solutions/dtt-deployment-data/ ).

**Comment by aallan** [comment]
Fixed up in ffe0fcda19e11c3d6058507f66ce65388bef2cb5. Will get pushed to production next time I do that.
