### ISSUE TITLE
3.5 320x480 touchscreen does not work under wayland-bookworm

### ISSUE THREAD

**Issue by mukral** [raspberrypi/documentation#3189]
Hi, to get the small touchscreen working again:
sudo raspi-config
goto 6 Advanced Options
goto A6 Wayland
choose W1 X11
ok
reboot

**Comment by lurch** [comment]
You might want to create an issue at https://github.com/raspberrypi/bookworm-feedback/issues for this.

**Comment by aallan** [comment]
> sudo raspi-config
> goto 6 Advanced Options
> goto A6 Wayland
> choose W1 X11

We're not going to be documenting switching back out to X11 from Wayland as a solution in the documentation.
