### ISSUE TITLE
Splitting up the Raspberry Pi Hardware category

### ISSUE THREAD

**Issue by aallan** [raspberrypi/documentation#3208]
We really need to look into splitting up the information in the [Raspberry Pi Hardware](https://www.raspberrypi.com/documentation/computers/raspberry-pi.html) category into slightly more granular top-level categories. The page currently spans several topics. 

* GPIO and the 40-pin Header (`computers/os/using-gpio.adoc`)
  * Voltages
  * Outputs
  * Inputs
  * Other functions
  * GPIO pinout
  * Permissions
  * GPIO in Python
* Schematics and Mechanical Drawings (`computers/raspberry-pi/raspberry-pi-schematics.adoc`)
  * Raspberry Pi 5
  * Raspberry Pi 4 Model B
  * Raspberry Pi 3 Model B+
  * Raspberry Pi 3 Model B
  * Raspberry Pi 2 Model B
  * Raspberry Pi 1 Model B+
  * Raspberry Pi 3 Model A+
  * Raspberry Pi 1 Model A+
  * Raspberry Pi Zero
  * Raspberry Pi Zero W
  * Raspberry Pi Zero 2 W
* Product compliance and safety (`computers/raspberry-pi/raspberry-pi-compliance.adoc`)
  * Flammability rating
  * Raspberry Pi Compliance Support
  * Powered by Raspberry Pi
  * Approved Design Partners
* Frequency management and thermal control (`computers/raspberry-pi/frequency-management.adoc`)
  * Using DVFS
  * Measuring temperatures
  * Adding heatsinks
  * Fan cases
* Raspberry Pi boot EEPROM (`computers/raspberry-pi/boot-eeprom-rpi4.adoc`)
  * Boot diagnostics
  * Update the bootloader
  * Updating the EEPROM Configuration
  * Automatic updates
  * Bootloader release status
* Boot Diagnostics on the Raspberry Pi 4 (`computers/raspberry-pi/boot-diagnostics-rpi4.adoc`)
* Raspberry Pi boot modes (`computers/raspberry-pi/bootmodes.adoc`)
  * Special bootcode.bin-only boot mode
  * bootcode.bin UART Enable
* Boot sequence (`computers/raspberry-pi/bootflow-legacy.adoc`)
* Raspberry Pi 4 and Raspberry Pi 5 boot flow (`computers/raspberry-pi/bootflow-2711.adoc`)
  * First stage bootloader
  * Second stage bootloader
  * Bootloader updates
  * Fail-safe OS updates (tryboot)
  * tryboot_a_b mode
* Raspberry Pi bootloader configuration (`computers/raspberry-pi/eeprom-bootloader.adoc`)
  * Editing the configuration
  * Configuration properties
  * Configuration Properties in config.txt
  * Secure Boot configuration properties in config.txt
* USB Boot Modes (`computers/raspberry-pi/boot-usb.adoc`)
  * USB device boot mode
  * USB host boot mode
* USB mass storage boot (`computers/raspberry-pi/boot-msd.adoc`)
  * Raspberry Pi 4B and Raspberry Pi 400
  * Compute Module 4
  * Raspberry Pi 3B+
  * Raspberry Pi 2B, 3A+, 3B, CM3, CM3+, Zero 2 W
  * Booting from USB mass storage
  * Known issues
  * Special bootcode.bin-only boot mode
  * Hardware compatibility
  * Multiple bootable drives
* Network booting (`computers/raspberry-pi/boot-net.adoc`)
  * Debugging network boot mode
  * Known problems
* GPIO boot mode (`computers/raspberry-pi/boot-gpio.adoc`)
  * Pin assignments
  * Boot flow
* NVMe SSD Boot (`computers/raspberry-pi/boot-nvme.adoc`)
  * Required hardware
  * Required software
  * Troubleshooting
* HTTP Boot (`computers/raspberry-pi/boot-http.adoc`)
  * Requirements
  * Keys
  * Secure boot
* Parallel Display Interface (`computers/raspberry-pi/display-parallel-interface.adoc`)
  * GPIO pins
  * Disable other GPIO peripherals
  * Configure a display
* General Purpose I/O (GPIO) (`computers/raspberry-pi/gpio-on-raspberry-pi.adoc`)
  * GPIO pads
  * Interrupts
  * Alternative functions
  * Voltage specifications
* GPIO pads control (`computers/raspberry-pi/gpio-pad-controls.adoc`))))
* Industrial use of the Raspberry Pi (`computers/raspberry-pi/raspberry-pi-industrial.adoc`)
  * One-time programmable settings
  * Write and read customer OTP values
  * Locking OTP on non-BCM2712 devices
  * Locking OTP on BCM2712 devices
  * Making customer OTP bits unreadable on non-BCM2712 devices
  * Customer MAC addresses on BCM2712 devices
  * Device-specific private key
* OTP register and bit definitions (`computers/raspberry-pi/otp-bits.adoc`)
  * OTP registers on non-BCM2712 devices
  * OTP Registers on BCM2712 devices
* Raspberry Pi connector for PCIe (`computers/raspberry-pi/pcie.adoc`)
  * Enable PCIe
  * Boot from PCIe
  * PCIe Gen 3.0
* Power button (`computers/raspberry-pi/power-button.adoc`)
  * Restart
  * Hard shutdown
  * Add your own power button
* Power Supply (`computers/raspberry-pi/power-supplies.adoc`)
  * Recommended power supplies
  * Power over Ethernet (PoE) connector
  * Typical power requirements
  * Power supply warnings
  * Power supplies and Raspberry Pi OS
  * Back-powering
* Real Time Clock (RTC) (`computers/raspberry-pi/rtc.adoc`)
  * Add a backup battery
  * Enable battery charging
  * Disable battery charging
* Serial peripheral interface (SPI) (`computers/raspberry-pi/spi-bus-on-raspberry-pi.adoc`)
  * SPI hardware
  * SPI software
  * Troubleshooting
* Universal Serial Bus (USB) (`computers/raspberry-pi/usb-bus-on-raspberry-pi.adoc`)
  * Maximum power output
  * Raspberry Pi 5
  * Raspberry Pi 4
  * Raspberry Pi Zero, 1, 2 and 3
  * Known USB issues
* Raspberry Pi revision codes (`computers/raspberry-pi/revision-codes.adoc`)
  * Old-style revision codes
  * New-style revision codes
  * New-style revision codes in use
  * Using revision codes for board identification
  * Best practices for revision code usage

**Comment by rohan-kapse** [comment]
hey @aallan could u guide me how can i help, its first time contributing ;)

**Comment by aallan** [comment]
> hey @aallan could u guide me how can i help, its first time contributing ;)

Unfortunately, I'm afraid this is not really a first-time contributor sort of issue. I'm going to have to try and figure out how to split the category into sub-topics that are narrative adjacent, which is why I self-assigned.

**Comment by aallan** [comment]
Too fast `github-actions` bot, too fast!

**Comment by aallan** [comment]
Not yet Gitbot. Not yet.
