### ISSUE TITLE
Raspberry Pi 3 B Schematics

### ISSUE THREAD

**Issue by jorgegarciadev** [raspberrypi/documentation#321]
Greetings,
Any plan on releasing the schematics for the Raspberry Pi 3 B?

**Comment by bennuttall** [comment]
Yes - they'll be added soon.

**Comment by wilfm** [comment]
Could you also please make sure there are the mechanical drawings as well?

**Comment by marc937** [comment]
Any ideas when the schematics will be available? Thanks!

**Comment by scramble45** [comment]
bump

**Comment by marc937** [comment]
Thanks!

**Comment by jorgegarciadev** [comment]
Thank you.

**Comment by awneil** [comment]
Why are there only "reduced" schematics?

Will full schematics be released?

**Comment by leeyu00** [comment]
good day, the Pi 3 schematic in the link below seems corrupted:
https://github.com/raspberrypi/documentation/tree/master/hardware/raspberrypi/schematics

**Comment by pelwell** [comment]
Can you elaborate? It looks OK to me in Adobe Reader, OSX Preview and Chrome.

**Comment by JamesH65** [comment]
Also fine in Chrome on Ubuntu 64bit.

**Comment by leeyu00** [comment]
hi there, i tried downloading the file,"RPI-3B-V1_2-SCHEMATIC-REDUCED.pdf" and open in a pdf reader (Foxit 6.1.1) and it says it is corrupted. Upon inspection, the downloaded file and the file viewed online from here "https://github.com/raspberrypi/documentation/blob/master/hardware/raspberrypi/schematics/RPI-3B-V1_2-SCHEMATIC-REDUCED.pdf" has different file size. pardon for the trouble, must have done the checking beforehand. i have now downloaded the file by clicking the "raw" button on the link. thanks.

**Comment by jeonghoonkang** [comment]
ㅍㅇ 투ㅡㅊ

2016년 4월 18일 월요일, leeyu00<notifications@github.com>님이 작성한 메시지:

> hi there, i tried downloading the file,"RPI-3B-V1_2-SCHEMATIC-REDUCED.pdf"
> and open in a pdf reader (Foxit 6.1.1) and it says it is corrupted. Upon
> inspection, the downloaded file and the file viewed online from here "
> https://github.com/raspberrypi/documentation/blob/master/hardware/raspberrypi/schematics/RPI-3B-V1_2-SCHEMATIC-REDUCED.pdf"
> has different file size. pardon for the trouble, must have done the
> checking beforehand. i have now downloaded the file by clicking the "raw"
> button on the link. thanks.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/raspberrypi/documentation/issues/321#issuecomment-211130494>
>


-- 
Jeonghoon Kang
Managerial Researcher
at Korea Electronics Technology Institute(www.keti.re.kr)
TinyOS Korea Forum Administrator
www.tinyos.or.kr
work = budge@keti.re.kr
private = gadin.kang@gmail.com
https://github.com/jeonghoonkang
www.pinkfloyd.re.kr/rnd/
*Kmote Connector
http://www.tinyos.re.kr/bbs/upload/kmote_connector.pdf

**Comment by lurch** [comment]
> i have now downloaded the file by clicking the "raw" button on the link.

If you want a "more direct" link (without github 'getting in the way'), you're probably better off accessing the documentation via https://www.raspberrypi.org/documentation/hardware/raspberrypi/schematics/README.md

**Comment by nilnullzip** [comment]
The posted schematic is incomplete. Only a single page that does not have all the components. Is a more complete schematic available?

**Comment by lurch** [comment]
> Is a more complete schematic available?

That's already answered by #347

**Comment by awneil** [comment]
And the question was already asked on 12 April: https://github.com/raspberrypi/documentation/issues/321#issuecomment-208803605
