### ISSUE TITLE
Pi Store link is wrong or the website is redirecting to somewhere weird.

### ISSUE THREAD

**Issue by Kezxo** [raspberrypi/documentation#322]
https://www.raspberrypi.org/documentation/linux/software/pi-store.md

The link to the store leads to some other site, maybe it was supposed to point to `http://store.raspberrypi.org` org instead or `http://store.raspberrypi.com/` but the .org link leads to nothing.

**Comment by bennuttall** [comment]
Thanks for pointing this out. Unfortunately the Pi Store has shut down. See https://www.raspberrypi.org/pi-store-shutdown/

I'll remove this page from the documentation and see about fixing the redirect.
