### ISSUE TITLE
Update power supply requirements for Pi 5

### ISSUE THREAD

**Issue by aallan** [raspberrypi/documentation#3227]
Update the tables in https://github.com/raspberrypi/documentation/blob/develop/documentation/asciidoc/computers/raspberry-pi/power-supplies.adoc for Raspberry Pi 5.

**Comment by aallan** [comment]
Too fast `github-actions` bot, too fast!

**Comment by aallan** [comment]
From #3490 it also appears that the last time the rest of the numbers were updated was back in 2016. So it all needs refreshed.

**Comment by aallan** [comment]
No so fast github bot.

**Comment by nathan-contino** [comment]
Turns out I did this a little while back. Done.
