### ISSUE TITLE
Path to libcamera tuning files has changed

### ISSUE THREAD

**Issue by FrenzyNatra** [raspberrypi/documentation#3235]
The path `/usr/share/libcamera/ipa/raspberrypi/` to libcamera tuning files stated [here ](https://www.raspberrypi.com/documentation/computers/camera_software.html#the-tuning-file) doesn't exist on my Pi (Pi4 / RaspiOS Bullseye), but the files in `/usr/share/libcamera/ipa/rpi/vc4/` seem to work properly.

**Comment by aallan** [comment]
Ping @davidplowman

**Comment by davidplowman** [comment]
This is true. And for a Pi 5 they'll be in `/usr/share/libcamera/ipa/rpi/pisp`. I've just started looking at getting documentation updated, so this will be on the list.
