### ISSUE TITLE
usb gadget on rpi A

### ISSUE THREAD

**Issue by prudy** [raspberrypi/documentation#324]
The rpi A could be used in device mode as the rpi Zero model. However as its otgid pin is permanently grounded it must force the HW/SW fixed device mode, not dual/otg.
Currently dwc2 driver gadget does not allow it as the gadget initialization overrides necessary settings.
Moreover, if dwc2 is compiled not in gadget-only but in dual-mode, the device mode must be forced with 'dtoverlay=dwc2,dr_mode=peripheral' in config.txt. Currently setting dr_mode parameter is ignored.
I'll issue the pull request fixing these, so gadgets with dwc2 work on raspberry A.

**Comment by francesco-vannini** [comment]
Prudy is there any workaround to make the A+ work as a peripheral till this is fixed?

**Comment by JamesH65** [comment]
@prudy Did you ever supply a PR for this? Cannot find one. Which part of the documentation are you suggesting needs updating?

**Comment by prudy** [comment]
Hi, actually I did not, I solved the problem and sent a patch.
For the documentation - I think the mystery of otg pin routing should be described/explained. All settings go the DeviceTree thus this could be good place. If I'm not wrong some description was already there, the functionality was just broken.

**Comment by JamesH65** [comment]
@prudy Do you have a PR number? Will make it easier to dig up.

**Comment by prudy** [comment]
Only the patch mailing list story:
https://lists.gt.net/linux/kernel/2404917

**Comment by JamesH65** [comment]
@ghollingworth @pelwell Is there any documentation covering this, if not should we have some. It's out of my knowledge base...

**Comment by bennuttall** [comment]
http://blog.gbaman.info/?p=791

**Comment by JamesH65** [comment]
So, what is actually required here? Do we need some documentation that parallels Ben's linked article?

**Comment by bennuttall** [comment]
More info here: http://www.lucadentella.it/en/2017/04/10/raspberry-pi-zero-utilizzo-via-usb/

**Comment by JamesH65** [comment]
I'd really like some confirmation on what needs/remains to be done here.  Is there actually something that needs doing, if so what, or can this issue be closed?

**Comment by prudy** [comment]
James, I raised this ticket to start the process of pulling changes to the code. Sine this is already done in upstream there is no real need of having this opened.

**Comment by JamesH65** [comment]
Ok, this is the documentation repo, so that has confused me. I'll close.
