### ISSUE TITLE
More Pi 5 Fan connector specifications

### ISSUE THREAD

**Issue by alessaba** [raspberrypi/documentation#3253]
Just got a Pi 5 and was aiming to hook up a fan i had laying around, which used a regular JST PH fan connector. In the documentation i saw the JST socket mentioned, so i thought that it was perfect for my application.
Yesterday my Pi 5 arrived and i discovered that it's a JST SH type of connector (The one used in QWIIC devices).
It's not a big deal, i will just change the connector on my fan, but it would have been nice to discover this in the official documentation instead of finding out in the forums or with the board in hand.

Also, it would be interesting to know the maximum current that Pi 5 can supply to the fan
Thanks in advance

**Comment by aallan** [comment]
The USB ports and fan connector both pull from the same 1.6A current limit for a 5A PSU, or 600mA for a 3A PSU.
