### ISSUE TITLE
Recommended Lenses: FOV vs Field Angle terminology

### ISSUE THREAD

**Issue by brianlow** [raspberrypi/documentation#3255]
The [Recommended Lenses](https://www.raspberrypi.com/documentation/accessories/camera.html#recommended-lenses) section:
* uses two different terms for the same concept: `Field Angle` (CS lenses) and `Field of View` (M12 lenses). I believe they can both use the same term
* uses two different formats for this value: `WxH` (CS lenses) and `DxHxW` (M12 lenses). Use the same format for both. If the diagonal isn't available for CS lenses, perhaps use `WxH` / `WxH (D diagonal)`

**Comment by sandyol55** [comment]
Some further comments on C/CS Lenses Table

Should the entry for Aperture in the 16mm Telephoto lens column  be F1.4 to F16 rather then F1.4 to 1.6?

Field Angle entries for various (unrelated to HQ or GS) sensor formats aren't particularly useful and may be misleading. More useful might be entries for the achieved field angles for each lens type on the specific HQ and GS sensor formats?
e.g.

```
			16mm telephoto		6mm wide angle
Field Angle 	HQ	  22.2 x 16.7		    55 x 45	
		GS	  17.8 x 13.4		    45 x 34
```
These values are only estimates, not known true values, for the two lens types!
