### ISSUE TITLE
pico-sdk/hardware.html freezes the tab because of a JS busy loop

### ISSUE THREAD

**Issue by mordae** [raspberrypi/documentation#3258]
Hi,

it seems that [scrollToElement()](https://github.com/raspberrypi/documentation/blob/803c08d739656dd6bad3be2a4afcee910c4467c8/jekyll-assets/_includes/scripts.html#L45) is somewhat broken.

As you can see in the following screenshot, it makes **thousands** of attempts to locate the element in this very long page before giving up. Obviously the whole time, 38 seconds for me, the tab is frozen and Firefox even advises interrupting the script. It happens to me both in Firefox and Chromium on Fedora 39 (beta).

![Screenshot from 2023-11-05 17-35-00](https://github.com/raspberrypi/documentation/assets/666693/f3c11e71-06c2-4cb9-8044-28526b497560)

**Comment by aallan** [comment]
@nelliemckesson Can you take a look? Thanks!

**Comment by nelliemckesson** [comment]
Confirming issue also occurs in Chrome: 

<img width="1417" alt="Screenshot 2023-12-08 at 4 25 11 PM" src="https://github.com/raspberrypi/documentation/assets/812739/d428bf2e-af2d-4072-a7bd-7ccd8a66cfca">
