### ISSUE TITLE
CM4 datasheet has been overwritten with an updated product brief

### ISSUE THREAD

**Issue by 6by9** [raspberrypi/documentation#3263]
https://forums.raspberrypi.com/viewtopic.php?t=359141

https://datasheets.raspberrypi.com/cm4/cm4-datasheet.pdf is now a Nov 2023 CM4 product brief

(https://datasheets.raspberrypi.com/cm4/cm4-product-brief.pdf is the Apr 2022 version).

**Comment by aallan** [comment]
Yes. I know. I accidentally uploaded the Product Brief over the top of the Datasheet. I’ll fix it this evening as soon as I’m back at my desk.

**Comment by aallan** [comment]
Fixed. Should be back to normal in about 15 minutes when the cache clears.
