### ISSUE TITLE
Tweaks to the "undo rpi-update" instructions

### ISSUE THREAD

**Issue by lurch** [raspberrypi/documentation#3268]
I've just been doing some testing (using bleeding-edge not-yet-public packages), and got my Pi into a "slightly odd" situation. I had a chat about it with @XECDesign and he says that the instructions at https://www.raspberrypi.com/documentation/computers/os.html#how-to-get-back-to-safety should probably be trimmed down to just
```
sudo apt-get update
sudo apt install --reinstall raspi-firmware
```
(apparently the `libraspberrypi*` packages are being deprecated), but he also said that it's worth double-checking with @popcornmix

**Comment by aallan** [comment]
@nathan-contino This sounds like a quick one you could knock out while waiting for me to pull my finger out reviewing your other PR.

**Comment by popcornmix** [comment]
@XECDesign don't we also need to reinstall the kernel? (which now have a range of names depending on Pi model and 32/64 bitness).

**Comment by XECDesign** [comment]
The kernel package only install it into /boot. raspi-firmware then handles copying it into /boot/firmware/. So, reinstalling raspi-firmware should also restore the kernel.

**Comment by popcornmix** [comment]
Okay - simpler instructions sounds right then.
