### ISSUE TITLE
Need to link to the USB PID repo

### ISSUE THREAD

**Issue by aallan** [raspberrypi/documentation#3270]
Need to link to the USB PID repo from relevant places in the documentation.

See https://github.com/raspberrypi/usb-pid for details of that!

**Comment by aallan** [comment]
Section in the [RP2040](https://www.raspberrypi.com/documentation/microcontrollers/rp2040.html) page probably.

**Comment by lurch** [comment]
I guess this can be closed now?

**Comment by nathan-contino** [comment]
Yes indeed!
