### ISSUE TITLE
Add note about Pi5 "power down" state

### ISSUE THREAD

**Issue by lurch** [raspberrypi/documentation#3276]
The [documentation](https://www.raspberrypi.com/documentation/computers/raspberry-pi-5.html#turning-it-off-and-back-on-again) _sort_ of implies that pressing the powerbutton (to do a shutdown) turns the Pi5 into a "fully off" state. However I found that when connecting a HAT to a Pi5 in this "shutdown" state, this then caused the Pi5 to wake up again, which surprised me. I checked with @timg236 and he said that connecting the HAT probably caused the PMIC to reset, so the official advice should be to always ensure that the USB-C power-supply is physically removed from the Pi5, before connecting or disconnecting any HATs or other hardware.

**Comment by timg236** [comment]
In the shutdown state the hat will still have 5v and possibly 3v3 connected so attempting to hotplug a hat in this state would be bad.
Always remove power cable before adding or removing HATs. This applies to all rpi models
