### ISSUE TITLE
[Question] Translation

### ISSUE THREAD

**Issue by ppigmans** [raspberrypi/documentation#328]
Hi!, lately i have translated RC_gui, i want to do NOOBS next, but i am also thinking maybe the documentation needs a dutch translation aswell?

If so i am happy to do it :)

**Comment by JamesH65** [comment]
@helenlynn What is RPF policy on translations of the documentation areas?

**Comment by JamesH65** [comment]
@ppigmans At the moment we have no plans for translation of the documentation due to the very high workload required (by the RPF and any volunteers helping)  to get it done in the first place, and secondly keep it up to date.  Thanks for the offer though!
