### ISSUE TITLE
config.txt: For HDMI_BOOST  add the acceptable values with description.

### ISSUE THREAD

**Issue by lwrbakro** [raspberrypi/documentation#331]
https://github.com/raspberrypi/documentation/blob/master/configuration/config-txt.md

Please add the acceptable values for the HDMI_BOOST.
Mentioning each value's effect on the HDMI TMDS signal.

**Comment by popcornmix** [comment]
The current documentation is not up to date.
config_hdmi_boost can go up to 11.
The default for a Pi1 model A or B is 2.
The default for Pi1 model B+ and all later boards (e.g. Pi0, Pi2, Pi3) is 5.

I think the default recommendation should be to try 7 if there are HDMI signal issues.
That can be increased further up to 11, but that should normally only be useful with very long HDMI cables.

**Comment by JamesH65** [comment]
#526 Incorporates the changes suggested by @popcornmix
