### ISSUE TITLE
config.txt

### ISSUE THREAD

**Issue by ezraholm50** [raspberrypi/documentation#332]
Hello, after searching a lot, i have not come up with a pleasing anwser.
Would the config.txt for a RPI2 be valid for RPI3? As in default clock/overclock settings?
And how about cmdline.txt?

Thank you very much for this project.

Kind regards,

Ezra

**Comment by Ruffio** [comment]
@ezraholm50 can this issue be closed?

**Comment by ezraholm50** [comment]
Yes I'm sorry, found my way. Not sure if it's clear to other new PI users though. Thanks!
