### ISSUE TITLE
Compute Module documentation incluedes only legacy display configuration

### ISSUE THREAD

**Issue by nbuchwitz** [raspberrypi/documentation#3324]
The firmware section  [1] of the compute module documentation explains how to use a dsi display with the compute module. Unfortunately it only mentions the legacy method with a `dt-blob.bin` (and don't mention that this has been replaced by the kms driver autodetection / display overlay).

It should at least mention that this is only needed for the legacy fkms driver and not with the kms driver (which is default). Ideally it should link to the official display documentation [2]

I'm not really sure, what would be the best approach, without duplicating too much content. Happy to provide a PR if we can find a suitable way.

[1] https://www.raspberrypi.com/documentation/computers/compute-module.html#firmware-configuration
[2] https://www.raspberrypi.com/documentation/accessories/display.html

**Comment by aallan** [comment]
@nathan-contino Another one for you to try and squeeze in before the Christmas break! :)
