### ISSUE TITLE
rpicam documentation still refers to cmake commands

### ISSUE THREAD

**Issue by naushir** [raspberrypi/documentation#3325]
We have moved on from cmake to meson for this package.  Remove all references to cmake.

**Comment by aallan** [comment]
Presuming this is the [online documentation](https://www.raspberrypi.com/documentation/computers/camera_software.html)? Not the PDF books?

**Comment by naushir** [comment]
Yes, all references in https://www.raspberrypi.com/documentation/computers/camera_software.htm.  I was going to do the leg-work at some point, so probably best to assign this to me.

**Comment by lurch** [comment]
See also #3252 ?

**Comment by aallan** [comment]
Not so fast github-bot!
