### ISSUE TITLE
Harvesting the forums

### ISSUE THREAD

**Issue by aallan** [raspberrypi/documentation#3327]
We're probably at the point where we should try and move some of the stuff that is only on the forums into the main documentation, e.g. This troubleshooting thread around booting, https://forums.raspberrypi.com/viewtopic.php?t=58151. This duplicates a lot of the documentation, but does have some things the documentation doesn't cover.

**Comment by aallan** [comment]
Unsure at this point whether we should just grab content and get it inserted in the right places. Or make a list of possible content topics, and grab the relevant content after we have a structure for the new site. Will think about it over Christmas.🎄🎁

**Comment by LizUpton** [comment]
Not so fast, bot. Stale label removed. Nate, we should talk about this next week.

**Comment by nathan-contino** [comment]
Still on the radar.
