### ISSUE TITLE
Link to spidev_test.c in SPI documentation broken

### ISSUE THREAD

**Issue by fivdi** [raspberrypi/documentation#333]
In the [SPI Loopback test documentation](https://github.com/raspberrypi/documentation/tree/master/hardware/raspberrypi/spi#loopback-test) there is a link to https://raw.github.com/torvalds/linux/master/Documentation/spi/spidev_test.c which no longer exists. `spidev_test.c` appear to have been removed form the master branch of Linux. It looks like v4.4 is the last version of Linux with `spidev_test.c` https://raw.githubusercontent.com/torvalds/linux/v4.4/Documentation/spi/spidev_test.c

**Comment by JamesH65** [comment]
See PR #528
