### ISSUE TITLE
raspberry pi cant boot

### ISSUE THREAD

**Issue by aliisfandyar** [raspberrypi/documentation#334]
hello!
i powered raspberry pi with 7 volts,now active and power lights are always high and it cant boot
please help

**Comment by lauraclay** [comment]
The Raspberry Pi should be powered by a 5V supply, as mentioned in the [FAQ](https://www.raspberrypi.org/help/faqs/#powerReqs) and the [documentation](https://www.raspberrypi.org/documentation/hardware/raspberrypi/power/README.md). Using a PSU with a higher voltage is not recommended, as it is very likely to damage the Pi beyond repair.

**Comment by lurch** [comment]
@lauraclay Looks like that documentation link you provided needs to be updated to cover the Pi 2B and Pi 3B as well?

**Comment by lurch** [comment]
@aliisfandyar If you want to power your Raspberry Pi from a 7V source, you'll need to use a 5V step-down converter e.g. https://www.adafruit.com/products/1385

**Comment by aliisfandyar** [comment]
will my rapberry pi will not work again :(

**Comment by lauraclay** [comment]
@aliisfandyar Unlikely, if you ran 7V through it!
