### ISSUE TITLE
3B+ revision a020d4 is missing.

### ISSUE THREAD

**Issue by stephan57160** [raspberrypi/documentation#3351]
Just received a few 3B+ with some unknown revision:
```
$> grep -e Model -e Revision /proc/cpuinfo
Revision	: a020d4
Model		: Raspberry Pi 3 Model B Plus Rev 1.4
$> 
```

Still digging in documentation, but I can't find this one under: 
https://github.com/raspberrypi/documentation/blob/develop/documentation/asciidoc/computers/raspberry-pi/revision-codes.adoc

**Comment by aallan** [comment]
Ping @JamesH65 who probably is the best person for this one?

**Comment by JamesH65** [comment]
That's just the v1.4 board (New PMIC), see PCN here https://pip.raspberrypi.com/categories/797-pcn/documents/RP-003337-PC/Pi3B-Revision-9-PCN.pdf. I'll update the page when I get the chance. Note that the table in the docs is not guaranteed to cover everything, and should not be relied upon for board identification - use the scheme noted later on the page.

**Comment by JamesH65** [comment]
See https://github.com/raspberrypi/documentation/pull/3354
