### ISSUE TITLE
2837

### ISSUE THREAD

**Issue by bennuttall** [raspberrypi/documentation#337]
In [hardware/raspberrypi](https://github.com/raspberrypi/documentation/tree/master/hardware/raspberrypi) we have [bcm2835](https://github.com/raspberrypi/documentation/tree/master/hardware/raspberrypi/bcm2835) and [bcm2836](https://github.com/raspberrypi/documentation/tree/master/hardware/raspberrypi/bcm2836). I guess we should add a 2837 folder with similar content.

**Comment by ED6E0F17** [comment]
Looks like a five minute job. Aarch64 Crypto Instructions are an optional feature, so I am assuming it doesn`t have those, but you need to Document that choice.

**Comment by machinaut** [comment]
Have the relevant documents been released by broadcom?  Happy to send a pull request if that's the case.

I was under the impression that they weren't released yet.

**Comment by pelwell** [comment]
It would be much quicker just to try building with the crypto instructions
and see if it works.

**Comment by Ruffio** [comment]
@bennuttall can this issue be closed?

**Comment by JamesH65** [comment]
New page has been  added for some time. Closing.
