### ISSUE TITLE
Power supply page is ambiguous and not updated to latest product lines

### ISSUE THREAD

**Issue by P33M** [raspberrypi/documentation#343]
https://github.com/raspberrypi/documentation/tree/master/hardware/raspberrypi/power

Two points are being addressed in this page that should probably be separated
- How to power your Raspberry Pi
- How to power components attached to your Raspberry Pi

Each require updating to align with Pi2/Pi3 in any case.

**Comment by lurch** [comment]
And on a related note, the stuff about TP1 and TP2 should probably be removed from https://github.com/raspberrypi/documentation/blob/master/installation/sd-cards.md and https://github.com/raspberrypi/documentation/blob/master/configuration/config-txt.md

**Comment by LornaLynch** [comment]
We've edited these documents and made some changes. Please reopen this if there are still problems.
