### ISSUE TITLE
Nobble eLinux Wiki references

### ISSUE THREAD

**Issue by P33M** [raspberrypi/documentation#344]
e.g. https://www.raspberrypi.org/documentation/hardware/raspberrypi/gpio/README.md

Information exclusive to the eLinux wiki should be brought under the documentation site umbrella and external links removed.

**Comment by LornaLynch** [comment]
I've removed the link as requested. Can anyone point me to where we should link to, rather than http://elinux.org/RPi_Low-level_peripherals ?

**Comment by JamesH65** [comment]
@LornaLynch Any further comments on this, or shall I close it?

**Comment by LornaLynch** [comment]
I think it's probably ok to close it :)
