### ISSUE TITLE
raspivid page missing mp4/playback/encoding information

### ISSUE THREAD

**Issue by dtbaker** [raspberrypi/documentation#345]
The raspivid page was my first point of contact when I was trying to use this new command. I successfully followed the instructions and saved a video output, but that video output wouldn't play (or would play incorrectly) in mplayer/VLC. 

There is no information about encoding or playback options for this raw saved raspivid output. 

I suggest adding some basic information about the output file and some options on how to play that file back on a computer. Here is some basic information with a basic mp4 example:

https://github.com/raspberrypi/documentation/compare/master...dtbaker:patch-1?diff=split&name=patch-1

(have not issued a pull request on that patch as per the contrib guidelines which say open an issue first)

Cheers,
Dave

**Comment by JamesH65** [comment]
That patch looks fine - please submit it, then Ben or similar can review
and merge.

**Comment by JamesH65** [comment]
@dtbaker Any chance you can submit this as a PR?

**Comment by dtbaker** [comment]
@JamesH65 no worries, updated here: https://github.com/raspberrypi/documentation/pull/346
