### ISSUE TITLE
Kill the Pi 5 page with 🔥 

### ISSUE THREAD

**Issue by aallan** [raspberrypi/documentation#3479]
Introduced because we wanted somewhere pre-launch to put information about Raspberry Pi 5, it's time [this section of the documentation](https://www.raspberrypi.com/documentation/computers/raspberry-pi-5.html) was broken up and distributed into the correct places in the docs — or new places created if no such places exist.

Then the Pi 5 section needs to be deleted.

**Comment by LizUpton** [comment]
https://github.com/raspberrypi/documentation/edit/develop/documentation/asciidoc/computers/raspberry-pi/power-supplies.adoc is one SCHPLENDID example of a place where the relevant content has ended up on the Pi 5 page.

**Comment by aallan** [comment]
> https://github.com/raspberrypi/documentation/edit/develop/documentation/asciidoc/computers/raspberry-pi/power-supplies.adoc is one SCHPLENDID example of a place where the relevant content has ended up on the Pi 5 page.

Related to #3490 but not the entirety of that issue — everything else in that section also needs updated.

**Comment by aallan** [comment]
See also #3485
