### ISSUE TITLE
Note that the quality and configurability of the camera module is highly superior to a standard USB webcam.

### ISSUE THREAD

**Issue by woosanghun** [raspberrypi/documentation#348]
I don't understand this sentence, do you mean USB cameras are superior or the standard Pi camera?  Just trying to understand.  

Thanks,

Simon

**Comment by jshoyer** [comment]
Pi camera module superior.

I'm curious if anyone can recommend a document comparing the new pi camera module to high end USB cameras.

**Comment by JamesH65** [comment]
Nothing to do here, closing.
