### ISSUE TITLE
[Improvement] Info about defining multiple networks

### ISSUE THREAD

**Issue by aartek** [raspberrypi/documentation#349]
I think there could be info if it is possibile to define multiple networks in `/etc/wpa_supplicant/wpa_supplicant.conf` (page: `documentation/configuration/wireless/wireless-cli.md`)

I read that in raspbian jessie you can add multiple configurations and you should add `id_str`. But I cannot confirm it works.

**Comment by JamesH65** [comment]
PR #529

**Comment by JamesH65** [comment]
Fixes merged
