### ISSUE TITLE
Diagram doc error - says SRAM instead of SDRAM

### ISSUE THREAD

**Issue by drudru** [raspberrypi/documentation#3504]
The diagram at the top of the doc here:

https://github.com/raspberrypi/documentation/blob/develop/documentation/asciidoc/computers/raspberry-pi-5/introduction.adoc

I cannot edit the diagram.

The diagrams says 'SRAM' instead of 'SDRAM'. This is confusing to people who will generally interpret SRAM as 'Static RAM'. 
SRAM is very different than 'Synchronous DRAM'

**Comment by lurch** [comment]
This seems to be a duplicate of #3250 ?

**Comment by drudru** [comment]
Yes - correct.
I will close mine
