### ISSUE TITLE
Best practice for revision code usage

### ISSUE THREAD

**Issue by DeeJay** [raspberrypi/documentation#3509]
Ref: https://www.raspberrypi.com/documentation/computers/raspberry-pi.html#best-practice-for-revision-code-usage

Please also see forum discussion [[Re: cpuinfo model name missing](https://forums.raspberrypi.com/viewtopic.php?t=364313#p2185233)]([Re: cpuinfo model name missing](https://forums.raspberrypi.com/viewtopic.php?t=364313#p2185233))

This is the latest recommendation > [Detect RPi 5 Best Practices?](https://forums.raspberrypi.com/viewtopic.php?p=2176416#p2176416)

Does the recommendation have official standing and should the related documentation be revised?

**Comment by JamesH65** [comment]
I think the current documentation recommendation is still the best practice as it is consistent across all models. Although the comment about working on upstream kernels is valid, so the question is really about support for non Pi OSs.
