### ISSUE TITLE
Can there be a download documentation on the rapberry pi documentation site?

### ISSUE THREAD

**Issue by CraftedPixel** [raspberrypi/documentation#351]
Sure I can just read the documentation online, but it is always convenient for me to download the docs. For example, I have a router that I connect with Ethernet and does not have wifi.

**Comment by bennuttall** [comment]
You can git clone this repo and read the markdown files:

```bash
git clone https://github.com/raspberrypi/documentation
cat documentation/usage/README.md
```

Not perfect but it works.
