### ISSUE TITLE
raspberry pi usb port

### ISSUE THREAD

**Issue by sundas6** [raspberrypi/documentation#3518]
Hi!, can anyone guide me to how access the usb ports in raspberry pi 4 model B, on raspberrry pi os (debain bookworm).   i want to make some changes in usb ports settings at software level. so when ever i connect any usb my changes reflect on the connected hardware device.

**Comment by LizUpton** [comment]
This is not a venue for technical support: please visit the [forums](https://forums.raspberrypi.com/).
