### ISSUE TITLE
Partially fixed by #3284

### ISSUE THREAD

**Issue by wasi4440** [raspberrypi/documentation#3519]
Partially fixed by #3284

_Originally posted by @lurch in https://github.com/raspberrypi/documentation/issues/3249#issuecomment-1818059999_

**Comment by aallan** [comment]
I'm sorry, but what is the issue here?

**Comment by wasi4440** [comment]
[Uploading daemon.json…]()

**Comment by aallan** [comment]
Sorry but this issue doesn't make any sense. If you have a documentation issue, please create a new issue with a title, and an explanatory paragraph.
