### ISSUE TITLE
Boot Coding then Blank Screen Just Mouse

### ISSUE THREAD

**Issue by CodingChris10** [raspberrypi/documentation#352]
WHAT'S HAPPENED? 
I booted up my raspberry pi today I am a regular user but today is just dose nothing.

Help would be appreciated

**Comment by pelwell** [comment]
What have you changed since it last worked:
* Software update?
* Editing config.txt?

Please post the content of config.txt and .firmware_revision.

**Comment by bennuttall** [comment]
Hi - this isn't the place for troubleshooting.

Please post this in our [forums](https://www.raspberrypi.org/forums/).
