### ISSUE TITLE
removing lightdm service command is incorrect

### ISSUE THREAD

**Issue by marvado69** [raspberrypi/documentation#353]
the command `update-rc.d lightdm remove` is incorrect, should be `update-rc.d -f lightdm remove`

**Comment by XECDesign** [comment]
What page is this on?

**Comment by marvado69** [comment]
Page: https://www.raspberrypi.org/documentation/remote-access/vnc/
To remove the service lightdm the -f option should be added in the command.

**Comment by XECDesign** [comment]
I wonder if the correct thing to do is actually `sudo systemctl set-default multi-user.target`. Is the idea to prevent a 'real' X session from running and eating up resources? If so, that would be the correct systemd way to do it, I think.

**Comment by marvado69** [comment]
Well, could be. Can't say because lack of knowledge.
Without the -f option it won't work.

**Comment by XECDesign** [comment]
Does it prevent VNC from running or just doesn't prevent lightdm from starting on `:0`? Could you give `sudo systemctl set-default multi-user.target` a go and see if that works as expected?

**Comment by marvado69** [comment]
It prevents lightdm from starting on `:0`.
I've restored the situation by command 'sudo update-rc.d lightdm defaults' and rebooted. Lightdm was on  ':0' and VNC on ':1'.
Then command 'sudo systemctl set-default multi-user.target' was given. After reboot the result was the same; Lightdm was on  ':0' and VNC on ':1'.

**Comment by XECDesign** [comment]
Thanks. To keep things consistent and backwards compatible, I'll update the page using your original suggestion. It's probably worth revisiting that page at some point and properly re-writing it for jessie.
