### ISSUE TITLE
Device specific private key is now supported for 2712

### ISSUE THREAD

**Issue by peterharperuk** [raspberrypi/documentation#3548]
There's a comment in here https://www.raspberrypi.com/documentation/computers/raspberry-pi.html#device-specific-private-key
that says "Device specific private key" is not implemented for 2712. This is now fixed. The only difference is that there are 16 rows for 2712.

**Comment by peterharperuk** [comment]
Please assign to me, raised this so I don't forget

**Comment by JamesH65** [comment]
ping

**Comment by nathan-contino** [comment]
not so fast!
