### ISSUE TITLE
document disabled "GPU" features when setting gpu_mem <64 MiB

### ISSUE THREAD

**Issue by txt-file** [raspberrypi/documentation#3553]
In https://github.com/raspberrypi/documentation/blob/8146e76eaaafaa588a7fdec315609a7c71e53301/documentation/asciidoc/computers/legacy_config_txt/memory.adoc#L35 you write "The minimum value is `16`, however this disables certain GPU features.". I want to know which features are disabled by which limit. Something like
* is video encoding still possible with 16/20/32/40/50/64 MiB gpu_mem?
* is video decoding still possible with 16/20/32/40/50/64 MiB gpu_mem?
* is "L2 cache" still available with 16/20/32/40/50/64 MiB gpu_mem?
* what other features are enabled/disabled?

**Comment by lurch** [comment]
See https://www.raspberrypi.com/documentation/computers/configuration.html#start-elf and https://www.raspberrypi.com/documentation/computers/config_txt.html#start_file-fixup_file
