### ISSUE TITLE
Need to mention the Raspberry Pi 4 Case Fan in the thermals section

### ISSUE THREAD

**Issue by aallan** [raspberrypi/documentation#3566]
The section on thermals and official products, see https://www.raspberrypi.com/documentation/computers/raspberry-pi.html#fan-cases, doesn't mention the Raspberry Pi 4 Case Fan, https://www.raspberrypi.com/products/raspberry-pi-4-case-fan/.

**Comment by lurch** [comment]
Cool! :rofl:

**Comment by JamesH65** [comment]
Please fetch coat.
