### ISSUE TITLE
Anchor links zoOoooOoooom you way back up to the top of the page when the page finishes loading

### ISSUE THREAD

**Issue by nathan-contino** [raspberrypi/documentation#3569]
Title say it like it be. Happens in Firefox, Chrome, and Safari. So pretty much all browser engines in existence!

**Comment by lurch** [comment]
Fixed by #3714 ?

**Comment by nathan-contino** [comment]
Seems to be fixed -- I can no longer reproduce the scroll position issue in Firefox or Safari, even with developer tools restricting bandwidth to 3G speeds. Happy to re-open this if it surfaces again, but for now I think we can call this closed! 🥳
