### ISSUE TITLE
Link from voltage problem lightning indicator is broken?

### ISSUE THREAD

**Issue by sandyol55** [raspberrypi/documentation#3573]
I guess this may not be a documentation issue but not sure where else to flag it?

On a 2G Pi4 running latest Bookworm.
Yellow Lightning power indicator came up with a link to :-
raspberrypi.com/documentation/computers/raspberry-pi-5.html#powering-raspberry-pi-5
which gave a 404 message.

**Comment by aallan** [comment]
@nathan-contino Where did you move that content to when we tore down the Pi 5 specific page? I'll set up a redirect for now, and mail Simon to fix it for the next OS update.
