### ISSUE TITLE
Add a summary table with SBC models into the documentation

### ISSUE THREAD

**Issue by aallan** [raspberrypi/documentation#3584]
At the top of the Raspberry Pi hardware section, https://www.raspberrypi.com/documentation/computers/raspberry-pi.html, there should be a summary of the models of hardware we make (e.g. something like https://en.wikipedia.org/wiki/Raspberry_Pi#Model_comparison, although we could lose a couple of columns from that).

**Comment by nathan-contino** [comment]
Alternatively, we could create sections to briefly summarise each model, similar to what we already do in the Compute Module section: https://www.raspberrypi.com/documentation/computers/compute-module.html#compute-modules

... though I think I'll also add a table similar to the wikipedia one linked. Probably one in the Raspberry Pi section, one in the Compute Module section, each with the header "Model comparison".
