### ISSUE TITLE
DebugProbe version needs updating

### ISSUE THREAD

**Issue by lurch** [raspberrypi/documentation#3591]
https://www.raspberrypi.com/documentation/microcontrollers/debug-probe.html#updating-the-firmware-on-the-debug-probe says "The current version of the Debug Probe firmware is version 1.0.3.", but [debug probe v2.0.1](https://github.com/raspberrypi/debugprobe/releases/tag/debugprobe-v2.0.1) was recently released.
So either the version needs updating, or maybe that NOTE should be tweaked to not actually mention any specific version number? :thinking:

**Comment by nathan-contino** [comment]
Already fixed! https://github.com/raspberrypi/documentation/blob/develop/documentation/asciidoc/microcontrollers/debug-probe/updating-firmware.adoc
... I just need to roll out the changes.

**Comment by lurch** [comment]
Hah, whoops!

**Comment by lurch** [comment]
Website-docs have now been updated :+1:
