### ISSUE TITLE
raspi-config documentation needs updating for Pi 5

### ISSUE THREAD

**Issue by lurch** [raspberrypi/documentation#3595]
There's lots of text at https://www.raspberrypi.com/documentation/computers/configuration.html#the-raspi-config-tool which talks about Raspberry Pi 4 (Wayland, EEPROM, etc.), but I believe most of these apply to Raspberry Pi 5 too.

**Comment by LizUpton** [comment]
Thanks Andy. If you're at all able to make the textual changes and make a PR when you spot stuff like this it'd be a MASSIVE help at the minute; we're spread very thin. 🤗
