### ISSUE TITLE
there is nothing written about the power requirements for RPi3

### ISSUE THREAD

**Issue by beta-tester** [raspberrypi/documentation#360]
at https://github.com/raspberrypi/documentation/tree/master/hardware/raspberrypi/power
and https://www.raspberrypi.org/documentation/hardware/raspberrypi/power/README.md
there is nothing written about the power requirements for RPi3
 only at https://www.raspberrypi.org/help/faqs/#power
there is written something about that.
but i bet my bottom dollar, that some newbies buy a too weak power supply because they were searching for the power requirements at the hardware section above instead of searching in the FAQ...

please keep the official raspberry pi documentation in sync.

**Comment by LornaLynch** [comment]
Thanks for noting this.
