### ISSUE TITLE
Kernel header build documentation page is empty

### ISSUE THREAD

**Issue by MartyMacGyver** [raspberrypi/documentation#362]
The main kernel docs are here:
https://www.raspberrypi.org/documentation/linux/kernel/

The header build page is here, but it's empty:
https://www.raspberrypi.org/documentation/linux/kernel/headers.md

It's not exactly complicated, but it's predicated on the kernel build so perhaps it'd be better integrated with the kernel building page:
https://www.raspberrypi.org/documentation/linux/kernel/building.md

`sudo make headers_install`

**Comment by JamesH65** [comment]
See PR #531

**Comment by LornaLynch** [comment]
PR has been merged by @AisforAstronaut: is it now OK to close this issue, @JamesH65?

**Comment by JamesH65** [comment]
Thanks.
