### ISSUE TITLE
missing led flash code

### ISSUE THREAD

**Issue by Riley869** [raspberrypi/documentation#3699]
I get a short blink long blink and then short blink when booting my rpi zero. What does this mean?

**Comment by Riley869** [comment]
it doesnt recieve video signal either

**Comment by nathan-contino** [comment]
Have you tried booting from a fresh Raspberry Pi OS install on a different SD card? It is likely an issue with your current SD card. Could be a hardware issue (they do wear out eventually) or a software issue.

**Comment by nathan-contino** [comment]
We already document error codes here: https://www.raspberrypi.com/documentation/computers/configuration.html#led-warning-flash-codes

Check out the [forums](https://forums.raspberrypi.com/) for support with specific issues.

**Comment by Riley869** [comment]
Thanks! I just checked and .-. means r in morse code which stands for reading
