### ISSUE TITLE
nginx setup page contains wrong directory paths

### ISSUE THREAD

**Issue by GarethOates** [raspberrypi/documentation#370]
Having recently installed nginx on a raspberry pi, I noticed the default location for the web page is now /usr/share/nginx/html  not /usr/share/nginx/www like previously described.  Also currently there's no mention that the default config options are visible in the file named "default" in the /etc/nginx/sites-available directory.

**Comment by JamesH65** [comment]
See PR #484, will close this issue once that PR is merged.

**Comment by LornaLynch** [comment]
I've just merged the PR. Closing this.
