### ISSUE TITLE
..

### ISSUE THREAD

**Issue by ntewinkel** [raspberrypi/documentation#372]

**Comment by pelwell** [comment]
Now you know what that button does.

**Comment by ntewinkel** [comment]
LOL. I thought I was in a terminal window when I typed "cd .." and hit return. oops!

**Comment by bennuttall** [comment]
I know your game...

![screenshot from 2016-06-03 19-23-05](https://cloud.githubusercontent.com/assets/1609725/15788688/9fc5468c-29c0-11e6-9f81-5c9ad2393519.png)

**Comment by ntewinkel** [comment]
I don't know what "game" you're referring to, bennuttall?  Those 829 contributions are not raspberry pi related (they are client work for private repositories).
Is there a way I can delete this issue?

**Comment by pelwell** [comment]
We can't, but don't worry about it - there was an invisible smiley at the end of Ben's message. He was probably suggesting that you were trying to up your reputation by being seen to contribute to our repo, but knowing the kind of people who write our documentation it's not a club you'd want to join. (BTW 829 is the number of people who have starred our documentation repo.)

**Comment by lurch** [comment]
> but knowing the kind of people who write our documentation it's not a club you'd want to join

lolz

**Comment by bennuttall** [comment]
> don't worry about it - there was an invisible smiley at the end of Ben's message. He was probably suggesting that you were trying to up your reputation by being seen to contribute to our repo

Indeed. Just kidding.

> but knowing the kind of people who write our documentation it's not a club you'd want to join.

Good point. Maybe we need a logo...

![](http://www.rch.org.au/uploadedImages/Main/Content/rchhis/doc_documentation_200w.gif)

**Comment by lurch** [comment]
The first rule of Documentation Club...

**Comment by bennuttall** [comment]
...is to document the club's rules.

The second rule of Documentation club is ** to document the club's rules**.
