### ISSUE TITLE
rpicam-apps : unsupported option --rawfull

### ISSUE THREAD

**Issue by DeeJay** [raspberrypi/documentation#3751]
Ref: [https://www.raspberrypi.com/documentation/computers/camera_software.html#rawfull](https://www.raspberrypi.com/documentation/computers/camera_software.html#rawfull)

Option has been removed.
Ref: [https://github.com/raspberrypi/rpicam-apps/pull/560](https://github.com/raspberrypi/rpicam-apps/pull/560)

Forum discussion:
[https://forums.raspberrypi.com/viewtopic.php?p=2233047#p2233041](https://forums.raspberrypi.com/viewtopic.php?p=2233047#p2233041)

**Comment by nathan-contino** [comment]
Thank you! I'll get to this early next week during some spare cycles.
