### ISSUE TITLE
Microcontrollers / MicroPython : broken link to Getting Started book

### ISSUE THREAD

**Issue by DeeJay** [raspberrypi/documentation#3756]
Microcontrollers / MicroPython : broken link to Getting Started book

Ref: **MicroPython** - [https://www.raspberrypi.com/documentation/microcontrollers/micropython.html#what-is-micropython](https://www.raspberrypi.com/documentation/microcontrollers/micropython.html#what-is-micropython)

Under the sub-heading [Further Reading](https://www.raspberrypi.com/documentation/microcontrollers/micropython.html#further-reading)

Link to [https://store.rpipress.cc/collections/getting-started/products/get-started-with-micropython-on-raspberry-pi-pico](https://store.rpipress.cc/collections/getting-started/products/get-started-with-micropython-on-raspberry-pi-pico) is broken. Returns 404

**Comment by lurch** [comment]
Maybe this link now needs to be https://store.rpipress.cc/collections/getting-started/products/get-started-with-micropython-on-raspberry-pi-pico-2nd-edition ?
ping @bjepson
