### ISSUE TITLE
Raspberry Pi Connect | WINDOWS

### ISSUE THREAD

**Issue by Bra1nsen** [raspberrypi/documentation#3764]
Dear Developer Team,

I have created a Raspberry Pi account and am logging in via the website from a Windows PC. How can I add a Raspberry Pi device?

Is it currently only possible to access a Pi from another Pi?

![image](https://github.com/raspberrypi/documentation/assets/58213050/36951420-a84a-4809-b764-a34da3bd3143)

Best regards,
Paul

**Comment by lurch** [comment]
1. Please see https://www.raspberrypi.com/documentation/services/connect.html#link-a-raspberry-pi-with-a-raspberry-pi-id
2. Please ask questions like this at https://forums.raspberrypi.com/viewforum.php?f=167 rather than on GitHub.

**Comment by Bra1nsen** [comment]
So could you just confirm thats not yet working for Windows? Only Pi-to-Pi?

**Comment by lurch** [comment]
The Connect website works fine on Windows, but you need to use the Pi itself to register the Pi with your Connect account. But once you've done that you can access the Pi from Windows.
See https://www.raspberrypi.com/news/raspberry-pi-connect/

**Comment by Bra1nsen** [comment]
Thanks alot Lurch. Last question.🙏 Is it allowed for companies to use Raspberry Connect or does it require a license?

Best, 
Paul
