### ISSUE TITLE
Add info on codecs

### ISSUE THREAD

**Issue by bennuttall** [raspberrypi/documentation#38]
[installing-codecs.md](https://github.com/raspberrypi/documentation/blob/master/raspbian/installing-codecs.md)

**Comment by ebenupton** [comment]
@EmmaAdminRPTL there was a vague recollection you might have volunteered to write something about this?

**Comment by Ruffio** [comment]
@bennuttall is this still an issue?

**Comment by lurch** [comment]
The (placeholder) `installing-codecs.md` was deleted in c08ca80b5226c9ec10d6cff78dd4ba9b2b7db178 - does that mean this issue should now be closed?

**Comment by JamesH65** [comment]
I'm inclined to close this as nothing has been forthcoming. Might be worth adding a bit more detail to the confix.txt instructions at a later date if there is actually an issue.
