### ISSUE TITLE
Missing KiCad files for RP2350

### ISSUE THREAD

**Issue by arturo182** [raspberrypi/documentation#3808]
In the [Hardware Design with RP2350](https://datasheets.raspberrypi.com/rp2350/hardware-design-with-rp2350.pdf) document, a minimal KiCad example is linked at https://datasheets.raspberrypi.com/rp2350/Minimal-KiCAD.zip but this file doesn't exist.

![image](https://github.com/user-attachments/assets/49a3a5d8-583b-449e-9493-6d58aadcb34e)

Not sure if it's an omission or you just need more time, but just letting you know 🙂

**Comment by JamesH65** [comment]
Looking in to it.

**Comment by nathan-contino** [comment]
Fixed!
