### ISSUE TITLE
No GPIO Pins Listed in Codec Zero Documentation

### ISSUE THREAD

**Issue by mwshafer** [raspberrypi/documentation#3812]
The RPI pins that are used by the Codec Zero for are not listed in its documentation and makes it hard to know if it will work with other RPI hats. https://www.raspberrypi.com/documentation/accessories/audio.html#raspberry-pi-codec-zero

This should be added. Competitors have entire pages devoted to these details: https://www.hifiberry.com/docs/hardware/gpio-usage-of-hifiberry-boards/

**Comment by lurch** [comment]
Does https://www.raspberrypi.com/documentation/accessories/audio.html#gpio-usage provide the information you're looking for?

**Comment by mwshafer** [comment]
Why yes it does. Sorry I missed that!
