### ISSUE TITLE
Invalid link to firmware/overlays README file.

### ISSUE THREAD

**Issue by scotty3785** [raspberrypi/documentation#3822]
[****](https://github.com/raspberrypi/documentation/blame/d96c5376b304b89ef5620e42969a61c727c3c871/documentation/asciidoc/computers/configuration/device-tree.adoc#L827)

This documentation currently says "Please refer to the [README](https://github.com/raspberrypi/firmware/blob/master/boot/firmware/overlays/README) file found alongside the overlay .dtbo files in /boot/firmware/overlays. It is kept up-to-date with additions and changes." 

The link to the overlays README returns a 404 error.

**Comment by lurch** [comment]
Ahhh, looks like the link ought to be https://github.com/raspberrypi/firmware/blob/master/boot/overlays/README - perhaps things got rearranged? ping @popcornmix

**Comment by nathan-contino** [comment]
Thanks! Fixing this now...

**Comment by nathan-contino** [comment]
https://github.com/raspberrypi/documentation/pull/3823
