### ISSUE TITLE
Configuring the Kernel - Update for cross-compilation

### ISSUE THREAD

**Issue by melvinisken** [raspberrypi/documentation#383]
I don't know if it is the right place to mention:
In the documentation of configuring the kernel (documentation/linux/kernel/configuring.md) it should be mentioned, that for cross compilation, the command 
`make bcmrpi_defconfig` has to be changed to
`make ARCH=arm bcmrpi_defconfig`
Otherwise it results in errors. It would be a nice hint for non-professional users.

**Comment by lurch** [comment]
This is already covered on the 'building' page https://github.com/raspberrypi/documentation/blob/master/linux/kernel/building.md#cross-compiling - I dunno if it needs repeating on the 'configuring' page? \*shrug\*

**Comment by MrAda** [comment]
I have tried both bcmrpi_defconfig and bcm2709_defconfig and neither seem to produce a zImage that works.  I have an RPI3.

**Comment by pelwell** [comment]
Follow the instructions on the [building](https://www.raspberrypi.org/documentation/linux/kernel/building.md) page, using bcm2709_defconfig for Pi, and it should work. If not, report back with the actual error messages.

**Comment by MrAda** [comment]
I am doing it again right now.  When I originally did the bcm2709_defconfig, the Pi would constantly reboot itself.

**Comment by pelwell** [comment]
I would recommend updating your firmware as well - use rpi-update to get the latest kernel and firmware. You could also post your config.txt and cmdline.txt in case there are harmful or outdated settings.

**Comment by MrAda** [comment]
I am doing this compilation from a VM running Ubuntu.  Will your "rpi-update" command even work?

**Comment by pelwell** [comment]
It is the firmware on the Pi3 that might need updating - you haven't said what your current kernel is - so I was suggesting that you run rpi-update on the Pi to get the latest.

**Comment by MrAda** [comment]
Well I downloaded a zip file.  Says linux-rpi-4.4.y.zip

**Comment by MrAda** [comment]
Ok.  I removed the extra partitions and I am still getting a panic.  I'll reinstall Jessie's boot folder and overwrite with the new stuff to see if that works.

**Comment by MrAda** [comment]
I am stuck.  Can't get past panic.  I took a picture with my phone to show what I am seeing.  Also I am getting some strange green lines too.
![pi-boot](https://cloud.githubusercontent.com/assets/9904416/22407281/b19ae2fa-e620-11e6-997f-fae22308bc07.jpg)
config.txt and cmdline.txt are standard jessie ones.

**Comment by MrAda** [comment]
I completed reburned the jessie image and overlayed the new kernel on top.  That seems to have made it happy.  Still think it takes too long to boot up and I hope I can dig more into stream-lining the kernel.

**Comment by JamesH65** [comment]
Is this covered by PR #465?

**Comment by MrAda** [comment]
I don't know.  I have given up pretty much.

**Comment by JamesH65** [comment]
#465 has been merged, and I think it fixes this issue so closing.
