### ISSUE TITLE
PicoW SWD pins swapped

### ISSUE THREAD

**Issue by ENAC-Robotique** [raspberrypi/documentation#3888]
Hello,
I don't know if this is the right place to report this, but the SWDCLK and SWDIO pins are swapped in the documentation.
I had trouble debugging the PicoW(H), and it worked after swapping SWDCLK and SWDIO.
I have a "Raspberry Pi Pico WH 2022".
https://www.raspberrypi.com/documentation/microcontrollers/pico-series.html#raspberry-pi-pico-w-and-pico-wh

**Comment by nathan-contino** [comment]
Hmmm. I just looked at my Pico 2 and my Pico, and SWCLK is on the left side of the board, looking at the front, just like the documentation says.

Whenever we put a bunch of letters on a silkscreen and make a bunch of docs, it's possible that we mess something up. But I _think_ the diagram on the linked page (and the linked PDF diagram on that page, and the diagrams in Getting Started with Pico and the Pico Datasheet) is correct. Is it possible that your board is just upside-down?

A picture of your setup could be helpful here. Any chance you can include one?

**Comment by nathan-contino** [comment]
And I just checked the Pico W datasheet, and SWCLK appears to be in the correct place, on the left, especially notable because it's square instead of a circle. I don't think there's a hardware difference between the Pico W board and the Pico WH board aside from the soldered-on bits, so I'd like some evidence from your side before I make any changes.

Thanks for bringing this up, though. The documentation doesn't get any better unless we get feedback from people like you.

**Comment by ENAC-Robotique** [comment]
This is working just fine:
The yellow wire is `SWDCLK` and the blue one is `SWDIO`.
So from the left to the right I have `SWDIO, GND, SWDCLK`.
I am absolutely certain of the labels on my debug probe because I used it with other microcontrollers.
![image](https://github.com/user-attachments/assets/1f591181-d38b-481a-abb0-415bd8432edb)
![image](https://github.com/user-attachments/assets/63c66af7-c13e-41a5-83b1-d1790aeccd83)

In the doc, this is the opposite.
![image](https://github.com/user-attachments/assets/656d5ca9-7380-4dbd-85f3-6ebb2b171ec1)

**Comment by lurch** [comment]
@ENAC-Robotique I think you're mixing up Pico W and Pico WH :slightly_smiling_face:  The diagram you've posted above is correct for the Pico W, but the Pico WH (and also the Pico H) use the smaller 3-pin debug connector, which is documented in https://datasheets.raspberrypi.com/debug/debug-connector-specification.pdf

@nathan-contino I guess a variation of this NOTE from the Pico / Pico H section probably also needs adding to the Pico W / Pico WH section?
![Screenshot from 2024-10-22 13-20-27](https://github.com/user-attachments/assets/22d5f9f6-3125-45fd-812e-9dd8c38be188)

**Comment by nathan-contino** [comment]
Aha, thank you @lurch . That explains everything. Thanks for the suggestion, @ENAC-Robotique !
