### ISSUE TITLE
Touch 2 documentation update

### ISSUE THREAD

**Issue by jackjameshoward** [raspberrypi/documentation#3905]
The hyperlink is incorrect for the product page

https://github.com/raspberrypi/documentation/blob/227c4785b504434a58f6fd4556358c99b7690bbc/documentation/asciidoc/accessories/touch-display-2/about.adoc?plain=1#L3

```suggestion
The https://www.raspberrypi.com/products/touch-display-2/[Raspberry Pi Touch Display 2] is a portrait orientation touchscreen LCD display designed for interactive projects like tablets, entertainment systems, and information dashboards. 
```

**Comment by nathan-contino** [comment]
Thanks. I had to guess at the URL before launch, should have double-checked at release time!

FYI, feel free to open a PR for this sort of thing in the future. I'm happy to take the credit for [the fix](https://github.com/raspberrypi/documentation/commit/81ad4daf85b84369050b36ff014fd757e6109684), but you do deserve it.
