### ISSUE TITLE
Unmount commnd nonexistent

### ISSUE THREAD

**Issue by BenIanGifford** [raspberrypi/documentation#392]
While following the installation guide for linux [here](https://www.raspberrypi.org/documentation/installation/installing-images/linux.md) i noticed that the `unmount` command is missing from Raspbian so you cant prepare an sd card for a pi on a pi. Is there a similar command or cn you just not use pi's to dd cards for other pi's?

**Comment by bennuttall** [comment]
You mean `umount`?

**Comment by BenIanGifford** [comment]
I'm very sorry for wasting your time it would seem as though i have been reading it wrong for months.

**Comment by bennuttall** [comment]
No worries
