### ISSUE TITLE
Ai hat+ schematic incorrect?

### ISSUE THREAD

**Issue by Gordon999** [raspberrypi/documentation#3932]
The schematic here https://www.raspberrypi.com/documentation/accessories/m2-hat-plus.html

Shows a m2 socket which the hat+ doesn't have.

**Comment by nathan-contino** [comment]
You linked to the M.2 HAT+ documentation. That HAT+ does indeed have an M.2 socket, since that's the entire point of the M.2 HAT+ 😄 

The AI HAT+ is here: https://www.raspberrypi.com/documentation/accessories/ai-hat-plus.html#ai-hat-plus

However, it currently lacks a schematic.

**Comment by lurch** [comment]
> Is there a schematic anywhere ?

No.
