### ISSUE TITLE
Error in documentation: Raspberry Pi Pico 2 W powerpath schematic

### ISSUE THREAD

**Issue by jalzat-e** [raspberrypi/documentation#3951]
In the Raspberry Pi Pico 2 W documentation, in the schematic of the power path for batteries (page 18), drain and source are swapped. If the schematic is followed as it, the MOSFET reverse diode could drive current to VSYS from the battery even if VBUS is still present, defeating the purpose of the power path.
![powerpath pico2w](https://github.com/user-attachments/assets/94b09df3-013c-4cc2-83b7-d48afce83d6e)

**Comment by dp111** [comment]
If I understand you correctly this will only happen when Vsys is below
VBatt i.e. exactly when you want Vbat to take over powering the Pico. If
you swap the drain and the source then VSys could end up
permanently charging the battery causing damage.
