### ISSUE TITLE
Pinout/hardware/interfacing information 

### ISSUE THREAD

**Issue by arunkumar413** [raspberrypi/documentation#401]
Hi Team,

Over the years Raspberry Pi has evolved and various revisions have been made. However the documentation on them isn't properly maintained on the raspberry official website. I had discussed it on the forum (https://www.raspberrypi.org/forums/viewtopic.php?f=63&t=154936&p=1013261#p1013261
) regarding this. 

Could you please document the pinouts and hardware of different models on the official website. 

For example, I have a model B but I couldn't find a page which contains detailed information about the hardware/GPIO pinouts and how to interface external hardware with RPi.

Thanks,
Arun

**Comment by waveform80** [comment]
The information as to the hardware available in each model is admittedly rather scattered over the official docs at the moment. However, the GPIO pin-outs are pretty well documented on the following two pages:

* [GPIO: Raspberry Pi Models A and B](https://www.raspberrypi.org/documentation/usage/gpio/README.md)
* [GPIO: Models A+, B+, Raspberry Pi 2 B and Raspberry Pi 3 B](https://www.raspberrypi.org/documentation/usage/gpio-plus-and-raspi2/README.md)

**Comment by lurch** [comment]
#106 added a page just like you're asking for... and #132 & #182 enhanced it; but it later got removed again... https://github.com/raspberrypi/documentation/issues/182#issuecomment-83832608 and the following comments.

**Comment by waveform80** [comment]
Hmmm ... that products page is nice (albeit difficult to find: as an experiment I tried locating it from the homepage; after exhausting several paths from the links at the top, I finally scrolled down :). Unfortunately it doesn't cover the historic models. Anyway ... might be nice to have a link to the products page from, perhaps, the hardware section of the docs?

**Comment by lurch** [comment]
Ping @bennuttall as AFAIK he's responsible for the homepage navigation ;-)

**Comment by bennuttall** [comment]
Yeah, not the most obvious but it's linked from the "shop" tag. And you'll find it in the homepage section on products, and in the footer.

**Comment by lurch** [comment]
Doesn't seem to be in the footer any more?

**Comment by bennuttall** [comment]
I stand corrected

**Comment by Ruffio** [comment]
@arunkumar413 can this issue be closed?

**Comment by JamesH65** [comment]
@bennuttall Anything further to comment on this? Can we close or is there more work to do?

**Comment by JamesH65** [comment]
bump @bennuttall

**Comment by bennuttall** [comment]
@JamesH65 Can we have a chat about this and other GPIO issues?

**Comment by JamesH65** [comment]
@bennuttall Anytime.

**Comment by JamesH65** [comment]
@bennuttall Still need to sort this out, got any time to discuss?

**Comment by azrdev** [comment]
at least https://www.raspberrypi.org/documentation/hardware/raspberrypi/spi/ only documents Pi 1, without even mentioning later models (Pi 3 at least adds a second SPI interface, so there is a difference)

**Comment by gnbl** [comment]
Also, "schematics" is not the appropriate term for what is available in the PDFs (e.g. https://github.com/raspberrypi/documentation/blob/master/hardware/raspberrypi/schematics/Raspberry-Pi-Zero-W-V1.1-Schematics.pdf) as these basically only show the connectors. And there is no explanation why these are so limited.

**Comment by JamesH65** [comment]
@bennuttall Not sure where we are with this one. We could do with a decent pinout diagram in the docs - is there already one elsewhere on the site that's better than this one? https://www.raspberrypi.org/documentation/usage/gpio/images/gpio-numbers-pi2.png

**Comment by azrdev** [comment]
@JamesH65 maybe just copy those from <pinout.xyz> (<https://github.com/gadgetoid/Pinout.xyz>). They are CC-BY-NC-SA, but maybe the authors are fine with official integration.

**Comment by JamesH65** [comment]
@samalderhyde Ping re: incoming waffle ticket! This is the issues that has prompted the GPIO diagram request.

**Comment by bennuttall** [comment]
The `pinout` command line tool shows the GPIO pinout of the Pi you're on, and can be run with a specified revision code to get others.

It might be worth just creating a markdown table of the pinout for each pinout, specifying which models the pinout covers. The source of `pinout` data is here: https://github.com/RPi-Distro/python-gpiozero/blob/master/gpiozero/pins/data.py

**Comment by michaelstoops** [comment]
It looks like this has been addressed with `pinout` since https://github.com/raspberrypi/documentation/commit/3a76b6fd23fb77d4aee39b51185d023ed3991a8e.

Can we close this issue?

Cheers,
Michael

**Comment by bennuttall** [comment]
I'd say so 👍

**Comment by JamesH65** [comment]
Closing this issue as questions answered/issue resolved.
