### ISSUE TITLE
Network Boot - Pi 3 not sending out packets at boot

### ISSUE THREAD

**Issue by nh1402** [raspberrypi/documentation#405]
I have configured the Pi 3 to boot to USB alone successfully, and have followed the documentation to setup a second Pi (Pi 2 with Jessie if that makes any difference) to act as the server for the Pi 3 but it's (Pi 3) not sending any packets out to the server so it doesn't boot over the network.

EDIT: Even after yesterday's update.

**Comment by P33M** [comment]
This is unrelated to the documentation referenced on the site. Please post about your problem on the communit forum: https://raspberrypi.org/forums
