### ISSUE TITLE
raspiyuv: padding 16 -> padding 32; see issue raspberrypi/userland#329

### ISSUE THREAD

**Issue by reiner-dolp** [raspberrypi/documentation#412]
According to the current docs `raspistillyuv` is padding images to be divisible by 16. However, it actually pads images to be a multiple of 32. See issue raspberrypi/userland#329 for details.

I already opened pull request #411 with the trivial fix.

**Comment by lurch** [comment]
No need for both a PR and an issue, the PR alone is enough :)

**Comment by Ruffio** [comment]
@lurch if an issue is not required, then perhaps the frontpage (https://github.com/raspberrypi/documentation) should be changed, as it says:

>  If you have anything to fix or details to add, first file an issue on GitHub to see if it is likely to be accepted, then file a pull request with your change (one PR per issue).

**Comment by reiner-dolp** [comment]
@ruffio @lurch also: https://github.com/raspberrypi/documentation/blob/master/CONTRIBUTING.md

**Comment by lurch** [comment]
`CONTRIBUTING.md` also says:

> With the exception of typos and spelling mistakes...

While it's not a typo, I believe a small technical fix like #411 implemented kinda falls under the same category (especially as it was already confirmed by @6by9 in the userland repo).
