### ISSUE TITLE
Add details for access-over-internet service

### ISSUE THREAD

**Issue by timfernando** [raspberrypi/documentation#414]
My first contribution here, I'm proposing an addition/deletion to [access-over-internet](https://github.com/raspberrypi/documentation/blob/master/remote-access/access-over-Internet/internetaccess.md) to better explain the already-listed remote access service Dataplicity and how it works. 

I'm adding an issue here as per contribution instructions, but as the change is minor I've also the PR for it. Hope that's OK 👍

**Comment by lurch** [comment]
There's ongoing discussion on the relevant PR, so closing this issue.

**Comment by timfernando** [comment]
I believe the discussion is complete as the requested change has been made. Should the merge request go in the PR or in the issue?

**Comment by lurch** [comment]
The PR (Pull Request) *is* the merge request ;)
