### ISSUE TITLE
Memory Split on gpu-mem under 32MB influences MPG2 license activation output of vcgencmd

### ISSUE THREAD

**Issue by FlyinFistOfJuda** [raspberrypi/documentation#424]
Hello,

just lost some grey hair today & a few bucks on the raspi-foundation, but gained some wisdom:

I had my GPU Memory Sharing (`gpu-mem`) set to 16MB when i bought a MPG2 License.
Registration went fine, but the output of `vcgencmd codec_enabled MPG2` kept returning DISABLED.

The gpu-mem value has to be a minimum of 32MB for successful activation (or just for returning ENABLED). Would be nice if this gets a place in documentation and/or additionaly in the communication from sales in the installation guide.

BTW, this is Linux ras211 4.4.20-v7+ #908 SMP Wed Sep 7 14:44:27 BST 2016 armv7l GNU/Linux
Raspian 8.0

Hope this is not too off-topic for documentation, but seemed to make some sense to place it here.

Cheers!

**Comment by lurch** [comment]
This was already partially addressed in #117 ?

**Comment by FlyinFistOfJuda** [comment]
That would explain my out of memory errors. Shouldnt open bugs that late. :)
I've read #117 , it fits, but perhaps you may consider making this "problem" more obvious to the users who try to enable mpg2. Anyhow, guess they will find this bug report. For now, i'd leave the decision to you guys and close this one.

Thanks & Reg.
