### ISSUE TITLE
Typo in the ComputeModule datasheet

### ISSUE THREAD

**Issue by lurch** [raspberrypi/documentation#443]
In Table 7 on Page 15 of https://www.raspberrypi.org/documentation/hardware/computemodule/RPI-CM-DATASHEET-V1_0.pdf it says "GPIO28-27 I/O Supply Voltage". I believe this should be "GPIO28-45 I/O Supply Voltage".

Ping @jimbojr

**Comment by jimbojr** [comment]
Thanks, I've captured that for a future release.
