### ISSUE TITLE
Include instructions for Etcher 

### ISSUE THREAD

**Issue by johannrichard** [raspberrypi/documentation#455]
[Etcher](https://etcher.io) is a graphical, cross-platform tool that is by far the easiest way to flash disk images to SD cards (also for Mac OS X which has been short of suitable, graphical installers so far).

It would probably be helpful to have a short instruction on using Etcher in the documentation.

![product](https://cloud.githubusercontent.com/assets/189003/20457964/f7909b30-ae97-11e6-9e6f-c44b3cb2f1e9.gif)

**Comment by Ruffio** [comment]
@lurch what is the opinion of introducing Etcher here?

**Comment by brianjking** [comment]
@Ruffio -- I highly suggest it! It makes it very easy to add the `ssh` folder to the `boot` partition to enable headless connection via `ssh` to the Pi with the recent changes to the Raspbian distribution releases.

I opened a PR #511 for this on the MacOS page and as I mentioned in the pull request if this is merged in I'm happy to write instructions for Windows as well as this is also proposed in #450.

Thanks!

**Comment by Ruffio** [comment]
@brianjking I'm not within the foundation and have no ruling :-( You must convince them in order to get your RP accepted.

**Comment by brianjking** [comment]
@Ruffio Sorry - updated post & tagged @lurch

**Comment by JamesH65** [comment]
The MAC docs for Etcher have been merged - would it be possible for a Windows version to be written as suggested above? @johannrichard

**Comment by JamesH65** [comment]
Actually, Etcher on Linux should also be documented if you have the time.

**Comment by lurch** [comment]
Only needing one set of instructions for all three platforms, was part of the original reason behind Etcher ;-)
https://resin.io/blog/introducing-etcher/

**Comment by JamesH65** [comment]
I wonder if we should have one page for Etcher, and link to it from the other OS specific pages?

**Comment by JamesH65** [comment]
After thinking about it for another 2 minutes, Yes, I think that is the way to go - one Etcher page, then link to it from the individual OS installation pages. So if @brianjking fancies knocking up a PR to do that, that would be splendid.

**Comment by pimterry** [comment]
Looks like this has gone quiet - anybody object if I pick this up?

**Comment by JamesH65** [comment]
Feel free!

**Comment by pimterry** [comment]
@lurch @JamesH65 This is now done, see #614.

**Comment by JamesH65** [comment]
Fixed by #614
