### ISSUE TITLE
Display page is messed up at the bottom

### ISSUE THREAD

**Issue by mrichardson23** [raspberrypi/documentation#464]
https://github.com/raspberrypi/documentation/blob/master/hardware/display/README.md

At the bottom of the page, beneath the headline "MODULE MECHANICAL SPECIFICATION" seems a bit weird. The list stops and there's a non-sentence and what possibly should be another list item?

**Comment by lurch** [comment]
https://github.com/raspberrypi/documentation/commit/f007cadf3536cda8b87ce4649feb6d51a86bf189

ping @ghollingworth

**Comment by LornaLynch** [comment]
I looked at it a while ago but assumed it wasn't finished yet.

**Comment by ghollingworth** [comment]
Edited again...

**Comment by LizUpton** [comment]
Opening again: @ghollingworth, please don't make edits without putting them past the copyeditors! @LornaLynch, could you please do the honours?

**Comment by Ruffio** [comment]
@mrichardson23 this can be closed, right?

**Comment by JamesH65** [comment]
looks OK to me. Closing.

**Comment by mrichardson23** [comment]
Sorry! Missed this mention. Thanks all.
