### ISSUE TITLE
Trouble enabling VNC Server at the command line

### ISSUE THREAD

**Issue by JordanLyons** [raspberrypi/documentation#466]
I am following the [documentation](https://github.com/raspberrypi/documentation/blob/master/remote-access/vnc/README.md) and "Advanced Options" in my raspi-config does not include a VNC option. I am using Jessie/Pixel/NOOBS.

I'm very new to Raspberry Pi, so I'm not sure if this is just my issue or something worth addressing in the documentation.

**Comment by waveform80** [comment]
Have a look under "Interfacing Options" instead of "Advanced Options". I think there's another ticket somewhere correcting that page but it evidently hasn't been merged yet...

**Comment by waveform80** [comment]
Ah, my mistake - #472 corrected the documentation for SSH, but not VNC. I'll bung a quick PR together to fix that too.

**Comment by waveform80** [comment]
Opened #476 to fix the VNC docs

**Comment by LornaLynch** [comment]
Thanks: I've merged the PR.
