### ISSUE TITLE
Hardware documentation for the BCM2837 in rPi 3

### ISSUE THREAD

**Issue by machinaut** [raspberrypi/documentation#473]
The hardware documentation seems to only cover the 1 and 2 chips (BCM 2835 and 2836 respectively).

**Comment by machinaut** [comment]
Found this: https://github.com/raspberrypi/documentation/blob/master/hardware/raspberrypi/bootmodes/sdcard.md

Is it a matter of reading a datasheet and translating it into a human-friendly doc?

**Comment by bennuttall** [comment]
Duplicate of #337
