### ISSUE TITLE
Adding driver M25P80 to bcmrpi_config

### ISSUE THREAD

**Issue by Naegolus** [raspberrypi/documentation#481]
Hello,

we (a little open source hardware startup) would like to add an existing driver in the bcmrpi_config.
Motivation: Our first product is an extension board for the Raspberry Pi Zero and Raspberry Pi A+. The users of this extension board should be able to install it by just adding a device tree overlay. Unfortunately the needed M25P80 driver isn't included in the official Raspbian image.

May we activate this?

Joe

**Comment by pelwell** [comment]
Please create this issue on the linux repo, and be sure to say what the device does and which config option is needed to enable the driver module.
