### ISSUE TITLE
simplify imaging with linux

### ISSUE THREAD

**Issue by smallal** [raspberrypi/documentation#487]
Image directly from zip file to SD card without 4 gig limitation.

The -p option for unzip pipes the unzipped binary to standard output and it gets piped to sudo dd:

pi@raspberrypi ~ $ unzip -p 2016-11-25-raspbian-jessie.zip | sudo dd of=/dev/mmcblk0 bs=4096
1067264+0 records in
1067264+0 records out
4371513344 bytes (4.4 GB) copied, 544.201 s, 8.0 MB/s

I did this from my laptop booted up on Simon Long's Pixel for 386 live boot dvd.
It can be seen that more than 4294967295 (4GB) were written to the SD card.
it took about 9 minutes to write the image.
It booted up well on my Raspberry Pi 2B.

**Comment by JamesH65** [comment]
Not sure what to do with this. It works. but not sure where it would fit in the docs. @bennuttall ?

**Comment by JamesH65** [comment]
Will be fixed by #598

**Comment by bennuttall** [comment]
Sorry I missed this - good idea, and makes sense to add another header.

**Comment by JamesH65** [comment]
Merged, can be found on this page.

https://www.raspberrypi.org/documentation/installation/installing-images/linux.md
