### ISSUE TITLE
WiFi cli page 256-bit preshared key addition

### ISSUE THREAD

**Issue by swerveshot** [raspberrypi/documentation#489]
The WIRELESS-CLI page describes how to enter a preshared key to the /etc/wpa_supplicant/wpa_supplicant.conf file. But wouldn't it be much nicer if the key is in a 256-bit psk form as described in the WPA supplicant page on [the archlinux wiki](https://wiki.archlinux.org/index.php/WPA_supplicant#Connecting_with_wpa_passphrase). Please note that the wpa_supplicant command can't be run with sudo.

**Comment by lurch** [comment]
Duplicate of #490 ?

**Comment by swerveshot** [comment]
What do you mean duplicate of #490? I raised the issue first. :stuck_out_tongue_closed_eyes:
But jokes aside I'll close this issue and give any comments on issue #490.
