### ISSUE TITLE
Using `wpa_passphrase` for generating secret token instead of entering password as plain text

### ISSUE THREAD

**Issue by aleksandaratanasov** [raspberrypi/documentation#490]
Many tutorials (including the official documentation here) store the password for a profile inside `wpa_supplicant.conf` as plain text. This is wrong since it not only doesn't mention the security concerns related to this but also doesn't nurture a more security-oriented approach from the user when handling such information. In addition `wpa_passphrase` ensures a minimal length for a password (8..63 characters) which adds to the security enhancement it already offers.

I have added some information about this in my edit (check my fork of the documentation and the **Wireless CLI** article in particular).

**Comment by lurch** [comment]
Saying "check my fork" isn't very useful - if you have changes to suggest, please submit a pull request.

**Comment by aleksandaratanasov** [comment]
The guidelines state that an issue has to be created first and then a pull request. Believe me, I wouldn't have bothered posting this otherwise. :) I'll create a pull request now.
