### ISSUE TITLE
Wi-Fi guide should mention key_mgmt=NONE

### ISSUE THREAD

**Issue by Lokathor** [raspberrypi/documentation#493]
If the desired wifi network had no password, you can't simply leave out the password line. You need to put key_mgmt=NONE instead. This should be in the guide.

**Comment by JamesH65** [comment]
@Lokathor Please submit a pull request with the change and we will check and merge it.

**Comment by JamesH65** [comment]
Will be fixed by #583 when merged.

**Comment by JamesH65** [comment]
Merged
