### ISSUE TITLE
SSH docs outdated

### ISSUE THREAD

**Issue by jlian** [raspberrypi/documentation#499]
1. The interface described in the docs for `raspi-config` was different than what appears in the latest version of Raspian. 

2. Need more context for the extension-less 'ssh' file you could place on the boot partition to enable ssh. I was having some network issues with my router and was confused why the 'ssh' file would disappear all the time. 

I fixed above problems with the PR #492

**Comment by jlian** [comment]
Pinging @LornaLynch @bennuttall I think it would really help some folks with why the 'ssh' files disappear

**Comment by JamesH65** [comment]
This was fixed in PR #492
