### ISSUE TITLE
Update to Mass Storage Device boot instructions

### ISSUE THREAD

**Issue by leepenney** [raspberrypi/documentation#501]
Minor quibble, but running through the instructions on booting from a mass storage device in /hardware/raspberrypi/bootmodes/msd.md I found it could use the line:

Type `quit` to exit parted.

after the parted print instructions and before creating the boot and root file systems.

**Comment by mkretzschmar** [comment]
Another quibble:

Before "First, prepare the /boot directory with experimental boot files:" there should be a hint that system clock (date/time) should be verified, e.g. "Make sure that the system time is set correctly".
Reason: If the date is wrong (e.g. 2016-11-xx) an curl certificate validation error occures ("curl: (60) SSL certificate problem...") while rpi-update.

**Comment by JamesH65** [comment]
We are happy to accept a PR for this change if you have time @leepenney @mkretzschmar

**Comment by leepenney** [comment]
Created PR 560 https://github.com/raspberrypi/documentation/pull/560

**Comment by JamesH65** [comment]
PR merged, closing
