### ISSUE TITLE
Feature request: How to mount hard drives 

### ISSUE THREAD

**Issue by SWLF** [raspberrypi/documentation#506]
I've written some documentation on mounting a hard drive in Raspbian. If you think that this information will be a useful addition to the documentation, I can submit a pull request so you can review it.

**Comment by JamesH65** [comment]
We are always happy to look at PR's. Send it in and we can take a look.

**Comment by JamesH65** [comment]
Please update this issue with a link to the PR when you submit it.

**Comment by SWLF** [comment]
PR: https://github.com/raspberrypi/documentation/pull/516

**Comment by JamesH65** [comment]
Fixed by #516
