### ISSUE TITLE
Feature Request:  Mechanical Drawing, Pi Zero, label smd capacitors and resistors

### ISSUE THREAD

**Issue by binaryDilation** [raspberrypi/documentation#517]
Labelling the SMD components on the mechanical drawing would be very helpful.

I have a short to ground on PP9 (and PP1), going to desolder C8 to see if the short is through C8 or LX2 on PAM2306AYPKE.  So identifying C8 would be awesome.

**Comment by JamesH65** [comment]
@Roger-Thornton Another drawings issue.

**Comment by JamesH65** [comment]
See also #188

**Comment by JamesH65** [comment]
Closing as duplicate, see #188
