### ISSUE TITLE
Camera Timelapse page missing raspistill -tl

### ISSUE THREAD

**Issue by robgithub** [raspberrypi/documentation#54]
the raspistill command now contains the -tl (timelapse) parameter.

/master/usage/camera/raspicam/timelapse.md only mentions cron which presents file overwriting issues the the -tl parameter was designed to avoid.

Would be happy to leave the cron section on the page but add and promote to the top details and examples for raspistill -tl

**Comment by ebenupton** [comment]
PR please.

**Comment by Ruffio** [comment]
@robgithub is this still an issue?

**Comment by lurch** [comment]
See also https://github.com/raspberrypi/documentation/pull/269#issuecomment-149205981

**Comment by JamesH65** [comment]
I've updated the docs to add the raspistill timelapse mode #519, please review and comment, if OK I'll ask comms to check  and then merge.

**Comment by lurch** [comment]
Closing this, as #519 has now been merged.
