### ISSUE TITLE
Enable SSH on headless Raspberry Pi's

### ISSUE THREAD

**Issue by MatsK** [raspberrypi/documentation#559]
On https://www.raspberrypi.org/documentation/remote-access/ssh/

I would propose that the last part gets a heading like:
4. Enable SSH on headless Raspberry Pi's

to highlight this feature.

**Comment by JamesH65** [comment]
Not sure about this. The headless stuff is covered, albeit without a title. It really needs to go in that section 2 to keep the order correct. Perhaps just a better highlighted title? Dunno. @AisforAstronaut @LornaLynch  any comments?

**Comment by AisforAstronaut** [comment]
Another sub heading could work!

**Comment by JamesH65** [comment]
@AisforAstronaut  Do you want to give it a go?

**Comment by AisforAstronaut** [comment]
*Rolls up sleeves*

**Comment by AisforAstronaut** [comment]
Edited in GitHub, but I have no idea how to publish that to the website.

**Comment by bennuttall** [comment]
It deploys automatically every hour

**Comment by AisforAstronaut** [comment]
A proper magic trick, then! Thank you! I shall wait for the fairies to do
their jobs...

:-)

**Comment by JamesH65** [comment]
Fixed, closing.

**Comment by adsche** [comment]
What are the credentials when setting up ssh like that? Should that be added to the documentation?

**Comment by JamesH65** [comment]
Default credentials are just the standard logins.
