### ISSUE TITLE
dt-blob.bin description needs updating for Pi3, Pi0(w) and cm3 pins_* values

### ISSUE THREAD

**Issue by 6by9** [raspberrypi/documentation#563]
https://github.com/raspberrypi/documentation/blob/master/configuration/pin-configuration.md lists 8 pins_* sections:
pins_rev1
pins_rev2
pins_bplus1
pins_bplus2
pins_aplus
pins_2b1
pins_2b2
pins_cm

It's missing (at least) 
pins_pi0
pins_pi0w
pins_cm3
pins_3b1
pins_3b2

**Comment by JamesH65** [comment]
@pelwell Is this simply a matter of adding those pin sections and writing a short description?

**Comment by JamesH65** [comment]
OK, I'll go through and add them.

**Comment by JamesH65** [comment]
There doesn't appear to be a Pi0w entry in the dts file - is that planned to be added? Should I put it in docs now?

**Comment by pelwell** [comment]
I've added it now.

**Comment by JamesH65** [comment]
Now THAT's magic!

**Comment by JamesH65** [comment]
See #565

**Comment by JamesH65** [comment]
Merged
