### ISSUE TITLE
Documentation lacks OMXPlayer section

### ISSUE THREAD

**Issue by JamesH65** [raspberrypi/documentation#566]
There are no comprehensive instructions on omxplayer in the docs. Should be a subfile of 

/documentation/raspbian/applications

**Comment by bennuttall** [comment]
omxplayer usage examples are given in usage/audio and usage/video but yeah we could definitely do with comprehensive docs for the cli :+1: 

See https://github.com/raspberrypi/documentation/search?utf8=%E2%9C%93&q=omxplayer

**Comment by JamesH65** [comment]
See #568 for a first blast at this.

**Comment by JamesH65** [comment]
Have merged the first draft  #568
