### ISSUE TITLE
config-txt.md minor changes, suggestion.

### ISSUE THREAD

**Issue by MatsK** [raspberrypi/documentation#567]
[https://www.raspberrypi.org/documentation/configuration/config-txt.md](https://www.raspberrypi.org/documentation/configuration/config-txt.md)

The section: Monitoring temperature and voltage
is mixing a how to meassure voltage manually and how to get the temperature from CLI/Bash.

Suggestion is to split them into two sections, "Monitoring temperature" and "Meassuring PSU voltage manually".

**Comment by JamesH65** [comment]
This section has very recently (today) been reformatted - can you point me at the new file the issue is in? The link  provided is now broken.

**Comment by MatsK** [comment]
OK,
[https://github.com/raspberrypi/documentation/blob/master/configuration/config-, stxt/overclocking.md](https://github.com/raspberrypi/documentation/blob/master/configuration/config-txt/overclocking.md)

**Comment by JamesH65** [comment]
I have made a change to the appropriate file and also added a bit more new information #569. Please check out and comment.

**Comment by JamesH65** [comment]
Fixed by #569
