### ISSUE TITLE
documentation URI in /boot/config.txt leads to 404

### ISSUE THREAD

**Issue by jjsanderson** [raspberrypi/documentation#572]
I'm not entirely clear where `/boot/config.txt` is generated; this may not be a documentation bug as such. However, on a fresh flash of 2017-03-02-raspbian-jessie.zip, the header comment of that file points to: `http://www.raspberrypi.org/documentation/configuration/config-txt.md`.

...which leads to a rewritten address and a 404 error.

The correct link should presumably be `https://www.raspberrypi.org/documentation/configuration/config-txt/README.md`.

Trivial nit-picking error, I know, but this is the sort of thing that derails newcomers. Or, indeed, people with misplaced confidence that they may know what they're doing. Like... er... me.

**Comment by JamesH65** [comment]
The config.txt documentation has moved slightly, two days ago! I had no idea this was referenced from the config file itself. Will get that updated asap.

**Comment by XECDesign** [comment]
Well, spotted. I can make sure the next image points to the updated location. Perhaps a goo.gl link should be used to prevent this happening in the future.

**Comment by JamesH65** [comment]
It's not likely to change again in the foreseeable future, but having links like that are always going to be prone to becoming out of date. There's no way when updating the documentation to know they even exist outside the documentation tree.

**Comment by XECDesign** [comment]
Would you prefer a goo.gl link or just a direct link?

**Comment by jjsanderson** [comment]
Doesn't a goo.gl link just provide another point of failure? – in that somebody would have to remember to update the link address if the document ever moved, and that person would need access to the account, and so on... or have I misunderstood?

**Comment by XECDesign** [comment]
I believe the address the link redirects to can be changed without having to change the link itself. Although I can easily fix the link on future installs, config.txt is a little trickier to update on existing installs. Right now the solution is: update a Raspbian package and make it update the file when it's upgraded, which is a little more prone to go wrong than just updating the redirection.

That's still not much use if we forget who owns which goo.gl link, but that should be easy to sort out with git blame.

**Comment by XECDesign** [comment]
Should be fixed by https://github.com/RPi-Distro/raspberrypi-sys-mods/commit/7c9e35de87fa5392fd01ac4961d877aa20ee4fcc and https://github.com/RPi-Distro/pi-gen/commit/9cffa42a3514cd2a4d0aa648a6e52860ae86e1b5

**Comment by JamesH65** [comment]
@XECDesign has fixed this so closing. Reopen if further issues arise.
