### ISSUE TITLE
Use /dev/rdiskn when installing images on OS X

### ISSUE THREAD

**Issue by lukasbestle** [raspberrypi/documentation#58]
Hi,

I just read your documentation on how to install the disk image for Raspbian to a SD card on OS X.
It says that the user should use `dd` with `/dev/diskn`. On OS X, `/dev/rdiskn` is a lot faster with SD cards, so I guess that would make the process simpler and faster for users.

You write about it in the alternative method description, but it should be used in the first place.

Cheers,
Lukas

**Comment by ebenupton** [comment]
Closed, having merged PR #170.
