### ISSUE TITLE
Link to GPU driver and source code needs updating

### ISSUE THREAD

**Issue by toothbrush7777777** [raspberrypi/documentation#584]
The link titled "GPU documentation and open source driver" in `hardware/raspberrypi/bcm2835/README.md` points to http://www.broadcom.com/support/.
There are no links to the GPU documentation and source code on the Broadcom support page that I can find.
I haven't found the correct URL. Perhaps someone can find out?

**Comment by toothbrush7777777** [comment]
I found the link to download the documentation for the GPU: https://docs.broadcom.com/docs/12358545 (PDF) and the source code: https://docs.broadcom.com/docs/12358546 (TAR GZ).

**Comment by JamesH65** [comment]
@toothbrush7777777  If you have time, a PR would be great. Thanks.

**Comment by JamesH65** [comment]
Thanks, I'll get the docs updated.

On 16 March 2017 at 13:50, Toothbrush <notifications@github.com> wrote:

> I found the link to download the documentation for the GPU:
> https://docs.broadcom.com/docs/12358545
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__docs.broadcom.com_docs_12358545&d=DwMFaQ&c=DpyQ_ftY536pf7wCBQXXU58xADDRY77THQzJu1OmzOo&r=w09_2ePv8G3zRjoV19Wm1Q6rI7CDlOns4PuRv2hHkek&m=G_xBNj4kXUWFjsMQB3BaLsT9e6nEjs2KK6c-Ax_EF2g&s=I03gate6yRuCQrBR4ao9QBSw4YO3lr9k3QbvJGapXTc&e=>
> (PDF) and the source code: https://docs.broadcom.com/docs/12358546
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__docs.broadcom.com_docs_12358546&d=DwMFaQ&c=DpyQ_ftY536pf7wCBQXXU58xADDRY77THQzJu1OmzOo&r=w09_2ePv8G3zRjoV19Wm1Q6rI7CDlOns4PuRv2hHkek&m=G_xBNj4kXUWFjsMQB3BaLsT9e6nEjs2KK6c-Ax_EF2g&s=QjPD7LVLLWR85ipYmAB7TxYD4bJZaFWi7XZKZV_pAiY&e=>
> (TAR GZ).
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_raspberrypi_documentation_issues_584-23issuecomment-2D287062299&d=DwMFaQ&c=DpyQ_ftY536pf7wCBQXXU58xADDRY77THQzJu1OmzOo&r=w09_2ePv8G3zRjoV19Wm1Q6rI7CDlOns4PuRv2hHkek&m=G_xBNj4kXUWFjsMQB3BaLsT9e6nEjs2KK6c-Ax_EF2g&s=ktxL0G8IcJILKLMhNIerZAO7a5pZ5JYKXakTO5e-bU0&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ADqrHT6TMwXU4XkvnJf3KHNS6HxIlbUlks5rmT4agaJpZM4MeJex&d=DwMFaQ&c=DpyQ_ftY536pf7wCBQXXU58xADDRY77THQzJu1OmzOo&r=w09_2ePv8G3zRjoV19Wm1Q6rI7CDlOns4PuRv2hHkek&m=G_xBNj4kXUWFjsMQB3BaLsT9e6nEjs2KK6c-Ax_EF2g&s=cNuVc1GtHz1ohi7jpSl6bRU3_LlorBK0hRzu765foYw&e=>
> .
>



-- 
James Hughes
Principal Software Engineer,
Raspberry Pi (Trading) Ltd

**Comment by JamesH65** [comment]
Merged
