### ISSUE TITLE
missing webpage

### ISSUE THREAD

**Issue by wfucsc** [raspberrypi/documentation#594]
Greetings,  The web page https://www.raspberrypi.org/learning/physical-computing-with-python/pull_up_down/ seems to have gone missing.  Would you please return it?

thanks

**Comment by bennuttall** [comment]
That resource has been superseded by the 'Physical Computing with Python' resource: https://www.raspberrypi.org/learning/physical-computing-with-python/

If you need access to the old resource, you'll find it on GitHub: https://github.com/raspberrypilearning/physical-computing-guide/blob/master/pull_up_down.md
