### ISSUE TITLE
The documentation/Troubleshooting section is inadequately scoped

### ISSUE THREAD

**Issue by P33M** [raspberrypi/documentation#61]
There are several stub pages in documentation/troubleshooting that require filling out.

At first when @bennuttall created the troubleshooting/usb page I was tempted just to cross-link to the "article" I already wrote on the USB hardware and its differences to EHCI, but then the obverse argument became apparent: users will hit (or be directed to) the troubleshooting guide without any understanding of the underlying issues, nor do they wish to know about why OTG is different from EHCI.

The way I see it, the Pi lacks tier 1 technical support. Well, it doesn't actually: it has a very well staffed and managed user forum but this is an energy barrier to people that just want their Pi to work.

I propose scoping the troubleshooting section of the documentation tree to an apparent symptom/recommended solution based approach. The top page should be "what is wrong with your Pi?" with the top four or five links directly linking to the most common causes of problems. Inexperienced users are typically terrible at diagnosing the root issue with unfamiliar hardware: a simple "my Pi doesn't do X" -> "page full of solutions for X" should nab 80% of nonfunctional cases.

**Comment by ebenupton** [comment]
Close for inactivity.
