### ISSUE TITLE
Website Font for 'code' text

### ISSUE THREAD

**Issue by bsimmo** [raspberrypi/documentation#611]
l and 1 in text are very similar in the 'code' part.
Consider using something easier to distinguish.
Maybe look at dyslexic and teaching fonts, they should know what is best for the situation.

I know I've had it before and it just came up from two people on the new AP article.
https://www.raspberrypi.org/forums/viewtopic.php?f=28&t=179618

**Comment by JamesH65** [comment]
@bennuttall Ben, is there anything we can do about this?

**Comment by bennuttall** [comment]
I don't think so. There's always issues telling `1` from `l` in fonts, especially monospace. Code needs to be a monospace font. Unless someone suggests a monospace font that is considerably better, then we can't really do anything.

**Comment by bsimmo** [comment]
There are some that use a curly l, a quick search shows quite a few here. 
No idea on the implications of getting them in use on a website or if PIXEL may need them as well.

https://fedoramagazine.org/5-great-monospaced-fonts-for-coding-and-the-terminal-in-fedora/

**Comment by XECDesign** [comment]
Hack tends to be pretty good.
https://github.com/chrissimpkins/Hack#web-font-usage

**Comment by JamesH65** [comment]
So, should we use hack? If so, how do we use hack? Does the font need to be on the end users device?

**Comment by bennuttall** [comment]
@grega do you have any comments on this?

**Comment by XECDesign** [comment]
Looks simple enough to use without having it installed:
https://www.w3schools.com/code/tryit.asp?filename=FEZ96O3WIJQV

**Comment by JamesH65** [comment]
@grega Is there any chance we could do this? Not my field...

**Comment by grega** [comment]
@JamesH65 yep this is definitely possible to sort out, I've added this to the current support backlog & will confirm the font choice with the design team.

**Comment by JamesH65** [comment]
@grega Hi Greg, ISTR this being fixed? If so can this be closed?

**Comment by grega** [comment]
@JamesH65 It's fixed:

![screen shot 2017-11-30 at 09 24 09](https://user-images.githubusercontent.com/91799/33423398-914df4f8-d5b0-11e7-8e3e-a734ede41549.png)
