### ISSUE TITLE
Wifi CLI Config with False Security Promise Using wpa_passphrase

### ISSUE THREAD

**Issue by kressnerd** [raspberrypi/documentation#633]
In [wireless-cli.md](https://github.com/raspberrypi/documentation/blob/master/configuration/wireless/wireless-cli.md) point 3 states:

> 3. If security is a concern, entering a password as plain text is not recommended. You can use wpa_passphrase to create a unique token and enter it instead.

As far as I understand `wpa_passphrase`, the only security advantage is that your passphrase has a minimum of 8 characters. The “token” created is actually the PSK calculated from the SSID and the passphrase. This PSK can be used on any device. From a security point there is no difference between storing the passphrase or the PSK. There is also no point in deleting the out commented line with the passphrase. (cf. [man page](https://linux.die.net/man/8/wpa_passphrase))

To achieve more security you should make sure that only root has access to `wpa_supplicant.config` (default). If you used the suggested `wpa_passphrase "testing" "testingPassword"` you should also make sure to cleanup your .(bash|zsh)_history or delete the file with the passphrase. To avoid that cleanup you call it without the passphrase and enter it via stdin. SSID and passphrase are optional.

The advantage using `wpa_passphrase` for the PSK is that WPA does not have to call `wpa_passphrase` to calculate the PSK from the ASCII string each time it connects to the wifi. Doesn’t sound like a real advantage for my setup (fixed RPi installation with power supply).

**Comment by JamesH65** [comment]
Fixed merged
