### ISSUE TITLE
scp instructions incorrect

### ISSUE THREAD

**Issue by JamesH65** [raspberrypi/documentation#665]
Reported by email.

> I was trying to follow the information about file moving with scp at:
> 
> https://www.raspberrypi.org/documentation/remote-access/ssh/scp.md
> 
> The examples would not work for me. I find that I must enclose the file
> name in quotes. With that change, the example works.

**Comment by XECDesign** [comment]
Any idea what the filename was? Unless it had spaces or something, it should work.

**Comment by bennuttall** [comment]
The instructions are not incorrect. However, it's probably worth noting that files with spaces in them require quotes.

Filename with no spaces:

```bash
scp myfile.txt pi@192.168.1.3:
```

:+1:

File with spaces:

```bash
scp my file.txt pi@192.168.1.3:
```

:-1: 

Correct usage for filename with spaces:

```bash
scp "my file.txt" pi@192.168.1.3:
```

:+1: 

Spaces can also be used to separate files:

```bash
scp file1.txt file2.txt pi@192.168.1.3:
```

:+1:

**Comment by JamesH65** [comment]
From the linked document

> To copy multiple files within a directory, you can use wildcards (e.g., * or ?). However, to use wildcards for copying multiple source files from a remote system, you need to place quotes (" ") around the path to the source files. This is necessary because the Unix shell, not the scp command, expands unquoted wildcards.
> Therefore, to copy all the .txt files from the revenge directory on your deathstar.com account to your revenge directory on empire.gov, enter:
> 
>  scp dvader@deathstar.com:"revenge/*.txt" ~/revenge/
> You'll be prompted for your password on the source system (deathstar.com). The command won't work unless you enter the correct password.

**Comment by JamesH65** [comment]
I'm not sure what to do with this, perhaps just add the extra bits as Ben has suggested. I'll put it on the list.

**Comment by bsimmo** [comment]
Why not just have it with quotes around, while it's two more characters to type, it should work for everyone with or without spaces or wildcards.

It's then not wrong, but perhaps over engineered in some settings.
