### ISSUE TITLE
Need command-line methods for Zero

### ISSUE THREAD

**Issue by hariedo** [raspberrypi/documentation#674]
On the page at https://www.raspberrypi.org/documentation/remote-access/vnc/ we see this paragraph:

> If you're connecting from a non-RealVNC Viewer app, you'll first need to downgrade VNC Server's authentication scheme, specify a password unique to VNC Server, and then enter that instead. To do this, open the VNC Server dialog on your Raspberry Pi, select Menu > Options > Security, and choose VNC password from the Authentication dropdown.

This cannot be done on a headless Zero. What file contains the VNC Server's authentication settings?  Can this be done with a little 'sudo nano' editing?  There seems to be nothing in the default /etc/vnc/config or /etc/vnc/config.d/common of use here.

Also worth a mention, the MacOS built-in VNC viewer is a non-RealVNC Viewer, so this is a pretty typical scenario. Mentioning MacOS in that sentence may help when googling.

**Comment by waveform80** [comment]
There's some command line tools which you may find useful: `vncinitconfig` and `vncpasswd`. They've both got man-pages and the former (which is responsible for setting up various RealVNC configuration files) is a simple bash script (I haven't read through it to see where specific things are but it's probably worth a browse).

**Comment by JamesH65** [comment]
@minkustree Can RealVNC comment on this one please?

**Comment by jamleed** [comment]
Hopefully the command you need is:

sudo vncpasswd -service

This will prompt you to set a password and insert it for you in the right config file for VNC Server running in Service Mode, which is the default configuration on the Pi.

To downgrade the authentication scheme to VNC password (from the default Linux system auth), open the /root/.vnc/config.d/vncserver-x11 config file and replace 'Authentication=SystemAuth' with 'Authentication=VncAuth'. Then, restart VNC Server.

There are several other useful commands on the following page of our website: https://www.realvnc.com/docs/deployment-script.html

Please be aware some only apply to our Professional and Enterprise subscriptions. Hopefully these are clearly marked.

**Comment by JamesH65** [comment]
I'd be happy to accept a PR on the documentation if you think this should be in there. I think the RealVNC page was actually written by the RealVNC people in the first place.

**Comment by jamleed** [comment]
Thanks. Yes, it was written by me. I'll see if I can find some time to create one!
