### ISSUE TITLE
raspberrypi3 BCM2835LIB system timer compare register does not work!!!

### ISSUE THREAD

**Issue by KosingZhu** [raspberrypi/documentation#683]
hello everyone：
         I install the bcm2835lib [http://www.airspayce.com/mikem/bcm2835/] in my raspberrypi3. according to the  "BCM2835 ARM Peripherals"  address map table. i  has config the system timer relevant register to enable tne compare, but it does not work!
         my operation step is: 1. I write a number into the campare register.  2. then I poll read the CS register relevant bit, but do not found the match signal accuse.
         anybody knows what is wrong?

`   /*four systimer compare offset*/
  9 #define BCM2835_ST_C0   0x000C
 10 #define BCM2835_ST_C1   0x0010
 11 #define BCM2835_ST_C2   0x0014
 12 #define BCM2835_ST_C3   0x0018
void setBcm2835Timer(uint32_t us, int which)
 16 {
 17     uint32_t offset = BCM2835_ST_C0 / 4;
 18     volatile uint32_t *paddr = NULL;
 19 
 20     switch(which)
 21     {
 22         case 0:
 23             offset = BCM2835_ST_C0 / 4;
 24             break;
 25 
 26         case 1:
 27             offset = BCM2835_ST_C1 / 4;
 28             break;
 29 
 30         case 2:
 31             offset = BCM2835_ST_C2 / 4;
 32             break;
 33         case 3:
 34             offset = BCM2835_ST_C3 / 4;
 35             break;
        default:
 37             break;
 38     }
 39     paddr = bcm2835_st + offset;
 40 
 41     bcm2835_peri_write(paddr, us);
 42 
 43     uint32_t retus = bcm2835_peri_read(paddr);
 44     printf("bcm2835_st:%p, paddr:%p, us:%lu, retus:%lu\n", bcm2835_st, paddr    , us, retus);
 45 
 46     return;
 47 }

 51 int readTimerCompareStatus(int which)
 52 {
 53     int flag = 0;
 54 
 55     volatile uint32_t *paddr = bcm2835_st + BCM2835_ST_CS/4;
 56     uint32_t status = bcm2835_peri_read(paddr);
 57     printf("status:%lu, paddr:%p\n", status, paddr);
 58 
 59     switch(which)
 60     {
 61         case 0:
 62             flag = (status & (0x01));
 63            // bcm2835_peri_write(paddr, ((status & ~0x01)|0x01));
 64             break;
 65 
 66         case 1:
 67             flag = (status & (0x02));
 68             bcm2835_peri_write(paddr, ((status & ~0x02)|0x02));
 71         case 2:
 72             flag = (status & (0x04));
 73            // bcm2835_peri_write(paddr, ((status & ~0x04)|0x04));
 74             break;
 75         case 3:
 76             flag = (status & (0x08));
 77            // bcm2835_peri_write(paddr, ((status & ~0x08)|0x08));
 78             break;
 79         default:
 80             break;
 81     }
 82     //printf("flag:%d\n", flag);
 83 
 84     return flag;
 85 
 86 }
`

**Comment by JamesH65** [comment]
This is not a documentation issue. I'd suggest  posting on the Raspberry Pi forums where you will be able to get some help.
