### ISSUE TITLE
@ and " keys are mixed up

### ISSUE THREAD

**Issue by ahoang68** [raspberrypi/documentation#688]
Hi there,
I have a new Raspberry PI3 and try it with 2 different wireless keyboards. I have the same issue. The @ (at sign) and " (double quote) are mixed up.  I wonder if anyone has the same issues or just me.

**Comment by JamesH65** [comment]
I suspect you have the wrong keyboard layout selected. You are better off posting this question on the Pi forums, this github is for issues with documentation.
