### ISSUE TITLE
x86 image documentation

### ISSUE THREAD

**Issue by bennuttall** [raspberrypi/documentation#710]
Now that we have the RPD ISO on the [downloads page](https://www.raspberrypi.org/downloads/raspberry-pi-desktop/), it would be good to be able to link to some documentation on how to use it. I propose:

- How to write the image to a CD/DVD/USB stick
- How to boot from a live disc
- How to install it on a PC
- How to boot it in a VM

I'd be happy to write the VM tutorial, and I know we've had magpi articles on writing to a USB stick, but we should place them in here and keep them up-to-date. I haven't seen any tutorials on how to install it for good - I know there are some new options on boot in the more recent image, and these good do with explaining too.

Any volunteers?

**Comment by lurch** [comment]
`these good do with explaining too` -> `these could do with explaining too` ? ;-)
(feel free to delete this comment after fixing)

**Comment by lurch** [comment]
Is https://www.raspberrypi.org/downloads/raspberry-pi-desktop/ supposed to say "June 2017"? It currently says
```
Version: June 2016
Release date: 2017-06-22
```
which doesn't seem right?!

**Comment by bennuttall** [comment]
Thanks for the comments - have corrected the date on the web page.

**Comment by JamesH65** [comment]
Can this be closed? @bennuttall @lurch

**Comment by JamesH65** [comment]
@bennuttall Did this get done?

**Comment by JamesH65** [comment]
@bennuttall Ping

**Comment by aallan** [comment]
This has been open since 2018. Is it still relevant, can we close?

**Comment by JamesH65** [comment]
We still need some minimal docs on the x86 Desktop stuff, but it could be as simple as how to install, since in most respects it's the same as Debian. 

Perhaps we should close this one and be a bit more specific on the requirements in a new issue.

**Comment by bennuttall** [comment]
There's a PR for it at #711 but see my last comment: https://github.com/raspberrypi/documentation/pull/711#issuecomment-454876720

**Comment by lurch** [comment]
Now that "Raspbian" has been renamed to "Raspberry Pi OS", will the new version of "Raspberry Pi Desktop" also be given a different name, or will that be staying the same? Might be worth delaying this issue a bit longer until after the next release of the x86 Desktop, if that's going to be soon?

ping @XECDesign

**Comment by XECDesign** [comment]
I believe it will have a different name, but I'm not sure how soon it will be updated, given that a lot of focus in on the arm64 release right now.

**Comment by aallan** [comment]
Linked pull request closed, so closing.
