### ISSUE TITLE
USB TV Stick does not appear in /dev

### ISSUE THREAD

**Issue by lr101fc** [raspberrypi/documentation#716]
I have a Pi 3 running stretch. Clean install this week
I have a usb keyboard, usb mouse, rj45 ethernet and external power

When I connect my USB TV stick, it is recognised, however it doesn't seem to appear as item under /dev

if I list usb - i can see it attached in the tree, however the software I am using gqrx expects something like /dev/usb0

the infra-red receiver gets added as a device
How do I identify the USB stick explicitly ?

Older posts mention ttyusb but they do not exist on my Pi 3

thanks a lot

dmseg
 usb 1-1.3: new high-speed USB device number 9 using dwc_otg
 usb 1-1.3: New USB device found, idVendor=0572, idProduct=c688
 usb 1-1.3: New USB device strings: Mfr=1, Product=2, SerialNumber=3
 usb 1-1.3: Product: USB Stick
 usb 1-1.3: Manufacturer: Max
 usb 1-1.3: SerialNumber: 080116
 dvb-usb: found a 'Mygica T230 DVB-T/T2/C' in warm state.
 dvb-usb: will pass the complete MPEG2 transport stream to the software demuxer.
 DVB: registering new adapter (Mygica T230 DVB-T/T2/C)
 i2c i2c-3: Added multiplexed i2c bus 4
 si2168 3-0064: Silicon Labs Si2168-B40 successfully identified
 si2168 3-0064: firmware version: B 4.0.2
 si2157 4-0060: Silicon Labs Si2147/2148/2157/2158 successfully attached
 usb 1-1.3: DVB: registering adapter 0 frontend 0 (Silicon Labs Si2168)...
input: IR-receiver inside an USB DVB receiver as /devices/platform/soc/3f980000.usb/usb1/1-1/1-1.3/input/input4
 dvb-usb: schedule remote query interval to 100 msecs.
 dvb-usb: Mygica T230 DVB-T/T2/C successfully initialized and connected.

pi@raspberrypi:/sys/bus/usb/drivers/usb/1-1.3 $ lsusb

Bus 001 Device 006: ID 046d:c05a Logitech, Inc. M90/M100 Optical Mouse
Bus 001 Device 005: ID 413c:2106 Dell Computer Corp. Dell QuietKey Keyboard
Bus 001 Device 009: ID 0572:c688 Conexant Systems (Rockwell), Inc. Geniatech T230 DVB-T2 TV Stick
Bus 001 Device 003: ID 0424:ec00 Standard Microsystems Corp. SMSC9512/9514 Fast Ethernet Adapter
Bus 001 Device 002: ID 0424:9514 Standard Microsystems Corp. SMC9514 Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

pi@raspberrypi:/sys/bus/usb/drivers/usb/1-1.3 $ lsusb -t
/:  Bus 01.Port 1: Dev 1, Class=root_hub, Driver=dwc_otg/1p, 480M
    |__ Port 1: Dev 2, If 0, Class=Hub, Driver=hub/5p, 480M
        |__ Port 1: Dev 3, If 0, Class=Vendor Specific Class, Driver=smsc95xx, 480M
        |__ Port 3: Dev 9, If 0, Class=Vendor Specific Class, Driver=dvb_usb_cxusb, 480M
        |__ Port 4: Dev 5, If 0, Class=Human Interface Device, Driver=usbhid, 1.5M
        |__ Port 5: Dev 6, If 0, Class=Human Interface Device, Driver=usbhid, 1.5M
pi@raspberrypi:/sys/bus/usb/drivers/usb/1-1.3 $

**Comment by JamesH65** [comment]
This is a documentation github, not used for technical support.

Please report your question on the Raspberry Pi forums where it will be seen by many more people.
