### ISSUE TITLE
Access Point config - missing forwarding

### ISSUE THREAD

**Issue by rcastley** [raspberrypi/documentation#717]
In the documentation for creating a wireless access point the enabling of IPv4 forwarding is not documented.

In ```/etc/sysctl.conf``` the line ```net.ipv4.ip_forward=1``` should be uncommented

**Comment by JamesH65** [comment]
Apologies for the delay in responding. 

Is this something that is specifically Stretch related? Would you have time to do a PR for this?

**Comment by JamesH65** [comment]
I believe the latest access point documentation (for Stretch) now works correctly, so closing.
