### ISSUE TITLE
Typo: wpa_password

### ISSUE THREAD

**Issue by tgcentral** [raspberrypi/documentation#721]
Hi,

In wireless-cli.md, the following line seems to be incorrect:

> The wpa_password tool requires a password with between 8 and 63 characters

Not 100% sure, but I believe wpa_password should be replaced with wpa_passphrase?

thanks

**Comment by JamesH65** [comment]
I believe you are correct. Will update.

**Comment by JamesH65** [comment]
Fixed by https://github.com/raspberrypi/documentation/commit/9be053a59e19dae1a6b5915938914973b93266cd#diff-97d8732f57f272935e7c0aca3f958616

 Closing.
