### ISSUE TITLE
SD Formatter Tool no longer has "FORMAT SIZE ADJUSTMENT" option

### ISSUE THREAD

**Issue by woter324** [raspberrypi/documentation#728]
As per above. Scanned documentation and I cannot see a reference to it.

(Windows 7)

**Comment by JamesH65** [comment]
Do you have a link to the docs page where this is a problem?

**Comment by XECDesign** [comment]
This looks like the only occurrence:
https://github.com/raspberrypi/documentation/blob/master/installation/sdxc_formatting.md

**Comment by paul-hammant** [comment]
https://www.raspberrypi.org/documentation/installation/noobs.md is has out of date advice. Find FAT in page.

**Comment by Lukas-J** [comment]
The new tool make the format size adjustment automatically, I think.

**Comment by paul-hammant** [comment]
'The new tool'  ?  URL please..

**Comment by Lukas-J** [comment]
https://www.sdcard.org/downloads/formatter_4/index.html

**Comment by hikarus3j** [comment]
Hello, I have a same question so I ask to helpdesk@sdcard.org about this.
And they send those message to me.

> The SD Formatter does not give an option to select the File System (FAT32 or exFAT): 
> 
> cards 64GB and above, the file system is automatically taken as exFAT
> cards 32GB and below, the file system is automatically taken as FAT32

can this help anyone?

**Comment by paul-hammant** [comment]
Which page do you think those three lines should be added to?  URL pls :)

**Comment by hikarus3j** [comment]
If I don't mistake your words, May be, that should be user Manuals, bottom of this page, I think.
https://www.sdcard.org/jp/downloads/formatter_4/

**Comment by paul-hammant** [comment]
No, I'm asking which raspberrypi page do you think those three lines should be added to, to aid newbies ?

**Comment by hikarus3j** [comment]
Oh... OK I understand, sorry.
but, I don't know about documents for raspberry pi newbies, I'm newbie too.
There is any document page about it ? I have no idea.
I'm afraid to say this, but does anyone answer paul's question?
please write it, I hope.

**Comment by JamesH65** [comment]
I have fixed up the docs to remove the size adjustment reference.
