### ISSUE TITLE
Wireless Interface disapear after config via terminal

### ISSUE THREAD

**Issue by BORNintel** [raspberrypi/documentation#729]
Hi
I followed the instructions on this page:
https://github.com/raspberrypi/documentation/blob/master/configuration/wireless/wireless-cli.md
after which i rebooted and my wireless interface was gone.

How do i fix this?

**Comment by JamesH65** [comment]
This is a github for documentation issues, not technical support which is done on the Raspberry Pi forums. This is probably a Stretch issue, so I suspect the docs may be slightly out of date, I'll check them when time allows.

**Comment by XECDesign** [comment]
That particular doc looks good - wpa_supplicant.conf information is still valid. There's nothing there that would make the interface disappear entirely.

**Comment by JamesH65** [comment]
@BORNintel Please repost on the forums which are a better place for technical support questions.
