### ISSUE TITLE
Documentation translation

### ISSUE THREAD

**Issue by mariobranco** [raspberrypi/documentation#733]
Hi !

I have start to help some people in the Portugueses forum, but a lot of people have problems with the documentation in ingles. There is some way to help translating the documentation ?

Example: 

Raspberry Pi documentation: https://github.com/raspberrypi/documentation/blob/master/configuration/warning-icons.md

My version: https://www.raspberrypi.org/forums/viewtopic.php?f=74&t=185319

**Comment by bennuttall** [comment]
Hi

We appreciate your effort, and it's certainly useful to have that document available in Portugese. Unfortunately, we don't have a way of managing translations at present, so it's not something I want to encourage you to do, not knowing what could be done with the translation.

If you wanted to translate more of the documentation anyway, I could advise you fork this repository and maintain a translation in the fork.

We are currently hiring for a translation manager. This role will mostly focus on our educational materials, but this could be something they look at in future. Keep an eye out for a call for translators in the near future!

Thanks
