### ISSUE TITLE
Raspberry pi booting error

### ISSUE THREAD

**Issue by zo1** [raspberrypi/documentation#737]
![20170926_203538](https://user-images.githubusercontent.com/32304982/30869808-8c578e24-a2fb-11e7-95fd-a78b4fbb3b2e.jpg)
Help! my raspberry pi b+ was working perfectly fine but now it is showing the following errors during booting i.e.
failed to start create volatile files and directories
failed to start avahi mdns/dns-sd stack
failed to start login service. see 'systemctl status systemd-logind.service' for details
after the last error the system halts. what to do??

**Comment by bennuttall** [comment]
Please report your query in the [forums](https://www.raspberrypi.org/forums/). This is for reporting issues with our documentation, not for support queries.
