### ISSUE TITLE
DocUp needed - Playing Audio on the Raspberry PI - 404 error getting example

### ISSUE THREAD

**Issue by juggledad** [raspberrypi/documentation#738]
Attempting to get the example audio file gives a 404. Here is teh results:

pi@skull:~ $ wget https://goo.gl/XJuOUW -O example.mp3 --no-check-certificate
--2017-10-03 07:19:59--  https://goo.gl/XJuOUW
Resolving goo.gl (goo.gl)... 172.217.11.46, 2607:f8b0:4006:815::200e
Connecting to goo.gl (goo.gl)|172.217.11.46|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://raw.githubusercontent.com/raspberrypilearning/burping-jelly-baby/master/sounds/la.mp3 [following]
--2017-10-03 07:20:00--  https://raw.githubusercontent.com/raspberrypilearning/burping-jelly-baby/master/sounds/la.mp3
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2017-10-03 07:20:00 ERROR 404: Not Found.

**Comment by bennuttall** [comment]
Thanks for letting us know. I've created a new short url for it and tested it works.
