### ISSUE TITLE
Application OMXPlayer Is Missing in Contents

### ISSUE THREAD

**Issue by mobluse** [raspberrypi/documentation#741]
On https://github.com/raspberrypi/documentation/blob/master/raspbian/README.md
the Application OMXPlayer is missing in the Contents.

**Comment by bennuttall** [comment]
That's covered in [usage/video](https://github.com/raspberrypi/documentation/blob/master/usage/video/README.md)

**Comment by mobluse** [comment]
I mean, it's missing among the links in the page I mentioned. Now only Camera is under Applications, but OMXPlayer should be there also. The page you just mentioned is a simplified version of https://github.com/raspberrypi/documentation/blob/master/raspbian/applications/omxplayer.md

If you click Applications you get to https://github.com/raspberrypi/documentation/blob/master/raspbian/applications/README.md
but Camera has a direct link from https://github.com/raspberrypi/documentation/blob/master/raspbian/README.md

**Comment by bennuttall** [comment]
Oh, I see. I didn't know that page was there. Thanks!

**Comment by JamesH65** [comment]
This appears to have been fixed.
