### ISSUE TITLE
Netboot configuration stops on the second line when turning on a client

### ISSUE THREAD

**Issue by timelyfiasco** [raspberrypi/documentation#748]
Hi, can someone help me identify what I missed? I am using rasp pi 3, updated up to tonight. I installed Ubuntu mate. I want to try netboot through ethernet. 
the result of vcgencmd otp_dump | grep 17: is 
17:3020000a
I followed every step in https://www.raspberrypi.org/documentation/hardware/raspberrypi/bootmodes/net_tutorial.md except that dhcpcd is already disabled. chattr doesnt work so I used DNSMASQ_EXCEPT=lo in /etc/defaults/dnsmasq
The result of sudo tcpdump -i eth0 port bootpc is 
`tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on enxb827eb196700, link-type EN10MB (Ethernet), capture size 262144 bytes`
`23:52:46.178653 IP 0.0.0.0.bootpc > 255.255.255.255.bootps: BOOTP/DHCP, Request from b8:27:eb:d9:c1:89 (oui Unknown), length 320`
`23:52:46.179883 IP 192.168.1.170.bootps > 255.255.255.255.bootpc: BOOTP/DHCP, Reply, length 317
`
The client rasp pi 's ethernet port is blinking. I am guessing there is a problem with DCHP? But I need help on how to troubleshoot this.
my ./etc/network/interfaces is
`auto  enxb827eb196700`
`iface enxb827eb196700 inet static`
 `       address 192.168.1.170`
  `      netmask 255.255.255.0`
   `     gateway 192.168.1.1`
    `    broadcast 192.168.1.255`
     `   nameserver 192.168.1.1`
 `       dns-nameservers 8.8.8.8 8.8.4.4 192.168.1.1`

**Comment by JamesH65** [comment]
Only just seen this. This is not a documentation issues, but should be handled on the forums, so closing.
