### ISSUE TITLE
please clarify location for ssh file as /boot

### ISSUE THREAD

**Issue by quixand** [raspberrypi/documentation#749]
i've just spent 30 minutes of my life trying to enable ssh using the ssh file, because i was putting it in / rather than /boot

I can't be the only person making this mistake (I hope im not!)
thanks

**Comment by quixand** [comment]
ive made the changes that would have helped me in a fork here https://github.com/quixand/documentation/commit/b730253d539c1b0325bb8aa7529cbb9958e7c609 I can submit a pull request but which branch would you like me to use?

**Comment by XECDesign** [comment]
If you say /boot, people will put it either in the /boot directory of the boot partition or the /boot directory of the root partition and neither is the right location.

The instructions right now are correct, but it may be worth clarifying terminology and explaining how a directory differs from a partition and what a mountpoint is.

**Comment by XECDesign** [comment]
Also, how would you run `touch /boot/ssh` on a headless pi without ssh enabled already?

**Comment by quixand** [comment]
I think you are confusing a booted pi from using the sd card in another machine. I just booted the pi with a monitor and keyboard and did "sudo touch /boot/ssh"

It may not be clear to others that the root partition is not the boot partition.

**Comment by XECDesign** [comment]
That's not quite headless setup then is it? Normally you'd enable ssh using `systemctl enable ssh` or `raspi-config`. The boot partition mechanism is there specifically for headless setup.

I am all for clarifying how it works and where the file needs to go. I'd just prefer to do it in a way that doesn't conflate mountpoints, partitions and directories, which would only add ambiguity to where the file should actually go.

**Comment by quixand** [comment]
ok, I have corrected my branch based on your comments.
https://github.com/quixand/documentation/commit/e841a23e8b6cd6db79873f5243995024490efd72#diff-3022880829cc73a6f254762d548329ec

**Comment by XECDesign** [comment]
Looks good

**Comment by JamesH65** [comment]
Can you submit this as a PR please, on the master branch.

**Comment by quixand** [comment]
done
