### ISSUE TITLE
Apply Laura's Mathematica Fixes

### ISSUE THREAD

**Issue by bennuttall** [raspberrypi/documentation#75]
[mathematica](https://github.com/raspberrypi/documentation/tree/master/usage/mathematica)

Apply @lauraclay's Mathematica usage guide fixes from commit [e4468fe](https://github.com/raspberrypilearning/getting-started-with-mathematica/commit/e4468feefd7f84f78801644e81769ef0948232d8) in [raspberrypilearning](https://github.com/raspberrypilearning/getting-started-with-mathematica)

**Comment by ebenupton** [comment]
@bennuttall is this still valid?
