### ISSUE TITLE
omxplayer audio output bluetooth

### ISSUE THREAD

**Issue by at0022t** [raspberrypi/documentation#751]
When my audio output choice from the desktop is Fugoo Speaker,  VLC uses this choice, but omxplayer does not.  Setup: Rpi0W. Jessie. PWM audio outputs rerouted to GPIO12,13. 
 How do I force omxplayer audio output to go to bluetooth?

**Comment by JamesH65** [comment]
Please post technical support questions on the forum, this tracker is for documentation issues.
