### ISSUE TITLE
Pi3 not booting with USB

### ISSUE THREAD

**Issue by scargill** [raspberrypi/documentation#759]
No matter what I do - my Pi3 will not boot under USB. I've tried a hard drive, a USB stick, a USB adaptor with the very image that when transferred to the uSD sockwet will work.  I've checked that USB flag to make sure it is set - it is....

I've tried different USB sockets....

**Comment by david-kohen** [comment]
I had a similar problem - turned out to be a not-very-bad cable: as soon as the USB power went on the red power light went out for a second, then came back, but too late to complete the boot.

**Comment by JamesH65** [comment]
This is a Issue tracker for documentation problems, not technical support. Please direct questions to the forum.
