### ISSUE TITLE
Suggesting that add the method of how to install Caddy on Raspberry Pi

### ISSUE THREAD

**Issue by reechang** [raspberrypi/documentation#761]
Caddy is is an open source, HTTP/2-enabled web server written in Go.
It's very light , and easy to dispose.
But the information about how to install it in the Raspberry is very limiting.

**Comment by bennuttall** [comment]
Are you offering to write it or asking us to write it? If you can write it, or have a tutorial you can link to, we'll consider adding it. But I can't see anyone here finding the time to do this - we tend to cover majority use case documentation. We wrote the Apache page, and accepted a PR adding the nginx page.

**Comment by JamesH65** [comment]
As Ben implies, we do not have time to add entirely new documentation pages for relatively low use cases, but if you write some docs  we do have time to technical check and copy edit them.

**Comment by JamesH65** [comment]
No response, closing. If you wish to write a PR for this, we are happy to look at it for inclusion.
