### ISSUE TITLE
driver=nl80211 line causes error on Pi Zero W and does not work

### ISSUE THREAD

**Issue by steviebald** [raspberrypi/documentation#775]
I tried following the instructions on a Pi Zero W and could not get it to work.  A Linux sysadmin at work helped me track down the issue to the driver=nl80211 line as there was an error saying driver not found.  When we removed that line it worked perfectly.

**Comment by JamesH65** [comment]
Can you indicate which instructions you were using that had this error?

**Comment by steviebald** [comment]
https://github.com/raspberrypi/documentation/blob/master/configuration/wireless/access-point.md

for setting up pi as a standalone access point

**Comment by JamesH65** [comment]
In the final section there is the following...

> The access point setup is almost the same as that shown in the previous section. Follow the instructions above to set up the hostapd.conf file, but add bridge=br0 below the interface=wlan0 line, and remove or comment out the driver line.
> 
> interface=wlan0
> bridge=br0
> #driver=nl80211
> ...

**Comment by steviebald** [comment]
I stopped at the end of the first section as I wasn't trying to set it up to share internet access, just as an access point so I can connect to and control a robot.

**Comment by JamesH65** [comment]
Odd. When I wrote that page, I needed to have that line in there. However, we have moved on to Stretch, which has changed quite a lot of things that need to be updated in that document. Perhaps this is one of them.

**Comment by steviebald** [comment]
I was trying it on a Pi Zero W, not sure if that is any different.  Apart from that, the instructions were great, keep up the good work!

**Comment by aallan** [comment]
Open since 2017. Still relevant? If not can we close?

**Comment by JamesH65** [comment]
That page has been completely changed now, so closing.
