### ISSUE TITLE
wpa_supplicant.conf

### ISSUE THREAD

**Issue by ribbox** [raspberrypi/documentation#791]
The instruction to create a wpa_supplicant need to be updated to reflect changes in Stretch. 

The following need to be added to the start of the file;

```
country=US
ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
update_config=1
```

Where country code relates to the country you use the RPi in. #790

**Comment by JamesH65** [comment]
Sorry about the delay. Can you post a link to the specific page that you think needs correcting?

**Comment by philwilkinson40** [comment]
https://www.raspberrypi.org/documentation/configuration/wireless/wireless-cli.md

**Comment by JamesH65** [comment]
@philwilkinson40 I made some changes to specify the country code setting on the page you linked - do you think it's now OK or is more work required?

**Comment by JamesH65** [comment]
Closing this issue as questions answered/issue resolved.
