### ISSUE TITLE
WIRELESS-CLI reconnecting?

### ISSUE THREAD

**Issue by simonmeusel** [raspberrypi/documentation#794]
After following the [WIRELESS-CLI](https://www.raspberrypi.org/documentation/configuration/wireless/wireless-cli.md) guide, will your raspberry pi automatically reconnect to a network after connection is lost? If so, i will create a PR to add a note describing this behavior. If not, could you please add instructions on how to do that?

And also, thanks for the great guides!

**Comment by XECDesign** [comment]
Yes, it will reconnect when it sees the AP again. Is there any reason to believe it wouldn't?

**Comment by simonmeusel** [comment]
I've just seen some youtube videos where they needed to setup reconnection "manually". But I've tested it, and it does automatically reconnect
