### ISSUE TITLE
Documentation issue re PHP install

### ISSUE THREAD

**Issue by wleddy** [raspberrypi/documentation#796]
In the document at ‘documentation/remote-access/web-server/apache.md’ the instructions are:
`sudo apt-get install php ...`
That package does not seem to be available to my Zero Wireless. (E: could not locate). Installing php5 did work.

**Comment by bennuttall** [comment]
Needs updating for Stretch. Try the `php7` equivalent of the package.

TODO

**Comment by bennuttall** [comment]
This has been fixed - it was `php5` on jessie, and is now just `php` on stretch.
