### ISSUE TITLE
It's worth to mention standard "Startup Disk Creator" on Ubuntu

### ISSUE THREAD

**Issue by madneon** [raspberrypi/documentation#802]
On the documentation page ["Instaling Operating System Images"](https://www.raspberrypi.org/documentation/installation/installing-images/README.md) or ["Installing operating system images on Linux"](https://www.raspberrypi.org/documentation/installation/installing-images/linux.md) I think its worth to mention about "Startup Disk Creator" (usb-creator-gtk) which can be used to write OS images. It comes with standard installation on every version of Desktop Ubuntu.

**Comment by JamesH65** [comment]
We try not to add distro specific instructions, and since SDC is only on Ubuntu, that is a bit too specific.
