### ISSUE TITLE
config-txt isn't really BIOS as documentation says

### ISSUE THREAD

**Issue by DG12** [raspberrypi/documentation#813]
documentation/configuration/config-txt//README.md says:
"... instead of the BIOS you would expect to find on a conventional PC...."
wikipedia's BIOS entry says:
"... firmware used to perform hardware initialization during the booting process (power-on startup), and to provide runtime services ..."

Why mention a comparison to something people new to computers and people used to micro systems who would not "expect to find".
Perhaps it would be better to replace the first two sentences with:
The Raspberry Pi uses a configuration file to store system configurations parameters in an optional text file named `config.txt.`. 

2) Should initialised be spelled initialized? 
3) "accessible part of the card." should be "accessible partition of the card."
4) Should "commented out" be changed to "changed to a comment"
5) Should "alongside bootcode.bin and start.elf" be "along with bootcode.bin and start.elf"

**Comment by JamesH65** [comment]
My thoughts.
1. BIOS is a very well known phrase in PC land, so having it as a comparison seems fair enough to me. Pi is more comparable to a desktop PC than a microcontroller.
2. No. UK company, UK spelling.
3. Possibly, but that would imply that people are aware on the concept of partitions on a drive, whereas using the word part doesn't require that loevel of knowledge.
4. Could be either.
5. No, but could be either.

So on the whole, I think the page is OK enough as is.
