### ISSUE TITLE
no snd-usb-hiface.ko module under Raspbian

### ISSUE THREAD

**Issue by calabuig** [raspberrypi/documentation#817]
I would like to use m2tech Hiface Evo with my Raspberry pi 3, but under Raspbian I can't find the snd-usb-hiface.ko module.
Is there any way to make it work?

**Comment by lurch** [comment]
I suspect that's a question / request for the https://github.com/raspberrypi/linux repo rather than the documentation repo?

**Comment by JamesH65** [comment]
Indeed. Nothing to do with this documentation repo. In fact, rather than adding an issue to the linux repo, you shoud ask the question on the forums, you are much more likely to get a response. Getting other random HW working on the Pi is not a priority.
