### ISSUE TITLE
How to Network Boot from ipxe?

### ISSUE THREAD

**Issue by 2devnull** [raspberrypi/documentation#818]
Surprised there isn't anything out there about using iPXE. Is there a reason it wouldn't work with that?

**Comment by lurch** [comment]
I just did a quick google, and it seems that iPXE is actually firmware designed for flashing to a NIC? The "NIC" on the Raspberry Pi (the LAN9514) doesn't have a boot ROM that can be flashed.

Are you actually looking for https://www.raspberrypi.org/documentation/hardware/raspberrypi/bootmodes/net.md ? And see also https://www.raspberrypi.org/blog/piserver/

**Comment by 2devnull** [comment]
Upon further research, it also looks like iPXE doesn't support ARM devices.

**Comment by JamesH65** [comment]
Can you close please if there is no furthur action requried.
