### ISSUE TITLE
Incorrect Diagram for Sense HAT Description

### ISSUE THREAD

**Issue by billyauhk** [raspberrypi/documentation#821]
In documentation/hardware/sense-hat/images/sense-overview.png, the pressure sensor should be LPS25H

**Comment by XECDesign** [comment]
You're right, but given that nobody has noticed, it's probably best to just remove that image and replace it with an appropriate table. I'll send a PR later.

**Comment by JamesH65** [comment]
Do we need a table - could just remove the diagram - doesn't seem to add much.

**Comment by XECDesign** [comment]
Yup, I am happy for it to be removed. PR sent.
