### ISSUE TITLE
Cant connect from Mac SSH

### ISSUE THREAD

**Issue by Duggy252** [raspberrypi/documentation#823]
Hi 

I've just setup a new raspberry pi with NOOBS. 
Trying to connect from my MacBook via SSH in terminal. Getting the following error. 
The IP address I believe is right. 

ssh pi@<192.168.0.23>
-bash: syntax error near unexpected token `newline'

**Comment by JamesH65** [comment]
This is not a documentation issue. Please post your problem on the forums

https://www.raspberrypi.org/forums/

Although remove the < > from around the IP address to see if that helps.
