### ISSUE TITLE
Incorrect pin number on 

### ISSUE THREAD

**Issue by xigulor** [raspberrypi/documentation#825]
Hello,

On this page https://github.com/raspberrypi/documentation/blob/master/usage/gpio/README.md there is an error in the GPIO pins numbers : 

The GPIO port number 27 on diags must be read as 21 (it's logical, there are only 26 pins on the B model). I wasted one hour trying to figure why my code was not working ! ;-)

@clivebeale can you please correct your diagrams ? 

Thank you

**Comment by lurch** [comment]
Nope, that diagram is perfectly correct - it just depends whether you're using the "BCM" or "BOARD" addressing scheme. See https://github.com/raspberrypi/documentation/blob/master/usage/gpio/README.md#gpio-numbering and https://pinout.xyz/ for more info.

FYI [GPIO Zero](https://gpiozero.readthedocs.io/en/stable/) _only_ supports the "BCM" addressing scheme.

P.S. That pin is GPIO21 only on very early revisions of the original Model B Pi https://pinout.xyz/pinout/pin13_gpio27 (which obviously make up a _very_ small proportion of the total number of Raspberry Pis).
