### ISSUE TITLE
Set default shell for new users

### ISSUE THREAD

**Issue by sertal70** [raspberrypi/documentation#843]
The [Securing your Raspberry PI](https://github.com/raspberrypi/documentation/blob/master/configuration/security.md#securing-your-raspberry-pi) document, in "Change your username" paragraph  should specify that after having aded a new user it is required to set the default shell using the command:

`sudo usermod -s /bin/bash fred`

Failing to do so lead the new user to strange behaviors, like terminal windows showing only the menu bar and title bar.

**Comment by XECDesign** [comment]
Is that true once https://github.com/raspberrypi/documentation/issues/779 is fixed?

**Comment by sertal70** [comment]
No, actually when #779 will be fixed this issue is fixed, too. I'm going to close it, thanks!

**Comment by XECDesign** [comment]
Thanks for checking.
