### ISSUE TITLE
[0.416592] bcm2835-aux=uart 20215040.serial : could not get clk: -517

### ISSUE THREAD

**Issue by hupo376787** [raspberrypi/documentation#845]
I bought a pi zero wh, and flash a img following https://www.raspberrypi.org/documentation/installation/installing-images/README.md

When install the tf card, it shows
[0.416592] bcm2835-aux=uart 20215040.serial : could not get clk: -517

![_20180313185613](https://user-images.githubusercontent.com/14960168/37337787-4de2606e-26f0-11e8-9d95-a31537b3675e.jpg)

**Comment by JamesH65** [comment]
This has nothing to do with this docs repo, please ask on the forum.
