### ISSUE TITLE
'useradd' not friendly for noobs like me

### ISSUE THREAD

**Issue by MaxVMH** [raspberrypi/documentation#861]
May I suggest to change 'useradd' it to 'adduser' in configuration/security.md?

I'm a complete Linux noob and this just makes more sense to me. I used 'useradd' but then the prompt changes completely (no more username@hostname, no more arrow up functionality etc. ...), for more information see my topic on the Raspberry forums: https://www.raspberrypi.org/forums/viewtopic.php?f=66&t=208614

Sorry if this is a really stupid proposal for some kind of reason I don't understand (yet).

(PS: I will try making a pull request when I get to my desktop - unless someone told me it's a really stupid idea by then)

**Comment by JamesH65** [comment]
Thanks for the report, your instincts are correct! However we actually already have an issue dealing with the exact same thing here #779, which hopefully will mean the docs are updated soon.
