### ISSUE TITLE
Complete wireless configuration

### ISSUE THREAD

**Issue by bennuttall** [raspberrypi/documentation#87]
The [wireless](https://github.com/raspberrypi/documentation/tree/master/configuration/wireless) section contains empty files and the index just links to external documentation.

These need to be written internally and verified as the _right way_.

**Comment by ebenupton** [comment]
Simon - can you put together some docs for your WiFi utility (and the audio stuff for that matter) when you're done?

**Comment by spl237** [comment]
Yes - happy to do that when it's all done.

**Comment by JamesH65** [comment]
@spl237 Was this ever completed?

**Comment by spl237** [comment]
Errr - no.

That said, it's pretty self-explanatory now. I'll stick it on the list of things to do...

**Comment by XECDesign** [comment]
It looks like this has been done already https://github.com/raspberrypi/documentation/tree/master/configuration/wireless. Or does more need to be added?

**Comment by JamesH65** [comment]
I'm happy with that top page, and the cli subpage, I think the rest of the sub pages can be removed, and the off site links deleted. I'll do a PR.

**Comment by JamesH65** [comment]
Will be fixed by #562

**Comment by JamesH65** [comment]
562 now merged so closing
