### ISSUE TITLE
users.md  encourage users to change their password from the default.

### ISSUE THREAD

**Issue by niftyhacking** [raspberrypi/documentation#878]
In users.md and other places it would be good to change:
  "When logged in as the pi user, you can change your password with the passwd command."
to
  "When logged in as the pi user, you should change your password with the passwd command."
i.e.  s/can/should/

Despite looking for and blocking these I see enough of these in log files to ponder the word "must" or "strongly encouraged".
   www sshd[13875]: Failed password for invalid user pi from ...... 

Thank you.

**Comment by JamesH65** [comment]
Fixed by #915
