### ISSUE TITLE
Move FAQ in to the docs github repo.

### ISSUE THREAD

**Issue by JamesH65** [raspberrypi/documentation#881]
Currently the FAQ is in Wordpress, will be much easier to deal with if moved in to the docs github and auto updated to the website from there.

**Comment by JamesH65** [comment]
There is a branch here that has started this...

https://github.com/raspberrypi/documentation/tree/faqs

**Comment by JamesH65** [comment]
@bennuttall I think this can now go live. Not had any negative response to the move. @LizUpton Any thoughts?

**Comment by JamesH65** [comment]
Update. Current FAQ has been moved to github, and joined by a technical FAQ. These are currently being merged, andthe original FAQ is being trimmed to remove out of date entries.

**Comment by JaninaPi** [comment]
I have done the merging and trimming and @LizUpton has signed the changes off: https://github.com/raspberrypi/documentation/blob/master/faqs/README.md
However, in the process I've messed up some of the internal links: the ToC headings from 'Performance' through to 'SD cards', as well as 'Troubleshooting', don't go to the main text, and I can't figure out why. It must be something really easy to fix, but I can't spot the problem.

**Comment by bennuttall** [comment]
Oh that's because GitHub makes its own anchor links based on header text. The version on our site doesn't do that. But to work on both versions, make sure links are unique, i.e. not the exact same as the header.

**Comment by JamesH65** [comment]
IIRC, you need to set the link text to exactly match the header text, so if you changed the header you need to change the link to match.

**Comment by JamesH65** [comment]
Where are we with this? Would be good to get it live.

**Comment by JaninaPi** [comment]
I've changed the header links now so that they do not match the heading text exactly, but do match the anchors, so at least on GH, all of them do send you to the right section now. So this should be all good to go.

**Comment by bennuttall** [comment]
Ping @dtt101

**Comment by dtt101** [comment]
Just let me know what needs to be updated in the footer. Can we just update the copy on the old site with a message?

**Comment by JamesH65** [comment]
This sort of message "This has moved to here"?

The link to change is in the footer, FAQ, which will need to now link to this new document at "documentation/faqs/README.md"

**Comment by bennuttall** [comment]
Actually we don't need the footer changing, just a redirect adding:

https://www.raspberrypi.org/help/faqs/ -> https://www.raspberrypi.org/documentation/faqs/

**Comment by bennuttall** [comment]
I mean the link in the footer can change to be the canonical one, but that's not vital once the redirect's in place.

**Comment by damienh** [comment]
@bennuttall @JamesH65 I have done the redirection via the wordpress plugin. I will leave this issue open so that it can eventually be changed in the footer itself, but for now its ok.

**Comment by JamesH65** [comment]
Now live, and the redirection means the footer goes straight to the new page, so closing since the footer change is actually not a docs issue.
