### ISSUE TITLE
SPI Readme is just a bit out of date.

### ISSUE THREAD

**Issue by DougieLawson** [raspberrypi/documentation#922]
The SPI readme at: https://www.raspberrypi.org/documentation/hardware/raspberrypi/spi/README.md
is a bit old and tired and may not be quite true.

It still has a reference to spi-bcm2708.c in the 3.12 kernel.

We've moved on a bit to spi-bcm2835.c in 4.14.
https://github.com/raspberrypi/linux/blob/9d2ad143e40c38d34be86578840499a976c0a5b0/drivers/spi/spi-bcm2835.c

**Comment by JamesH65** [comment]
@pelwell Is this something you'll need to update? I have no idea what is current and what isn't.

**Comment by pelwell** [comment]
Yes, I'll put it on the list for a rainy day. Unless Dougie wants to submit a PR?

**Comment by DougieLawson** [comment]
Rainy day works for me.
