### ISSUE TITLE
Add Samba usage page

### ISSUE THREAD

**Issue by JamesH65** [raspberrypi/documentation#943]
Lots of requests for decent Samba docs, from the forum and elsewhere, and we have no page in the docs relating to this at all. Worthwhile adding.

**Comment by bennuttall** [comment]
Would be good :+1:

**Comment by JamesH65** [comment]
First draft of this

https://github.com/raspberrypi/documentation/blob/JamesH65-samba/remote-access/samba.md

**Comment by JamesH65** [comment]
That draft has now been updated, and now merged. Closing.

**Comment by JamesH65** [comment]
https://www.raspberrypi.org/documentation/remote-access/samba.md
