### ISSUE TITLE
Could use an HDMI configuration page

### ISSUE THREAD

**Issue by JamesH65** [raspberrypi/documentation#959]
Have the config.txt reference, but some sort of walk through help would be good.

**Comment by adeeb10abbas** [comment]
What kind of HDMI configuration are we talking about here? Could you possibly elaborate a bit more?

**Comment by JamesH65** [comment]
I was thinking of more detailed insturctions on setting up custom HDMI modes etc.

**Comment by adeeb10abbas** [comment]
Gotcha will post something as soon as I have time

**Comment by JamesH65** [comment]
I've started this, current incarnation on this branch https://github.com/raspberrypi/documentation/tree/JamesH65-patch-hdmi-config

**Comment by JamesH65** [comment]
Now merged.
