### ISSUE TITLE
OMXPlayer usage page

### ISSUE THREAD

**Issue by JamesH65** [raspberrypi/documentation#960]
Turns out there doesn't appear to be a page dedicated to OMXplayer, which seems rather a omission. Couple of pages "How to play audio" and "how to play video" but both very short and sweet.

**Comment by bennuttall** [comment]
Pasted from email:

One reason I'd keep them separate is the titles are pretty much answers to questions someone might google, e.g. "how to play audio on raspberry pi" - if they don't know what omxplayer is they're not going to include it in their search terms.

An option could be to leave those pages up and say "play audio with omxplayer - see <link>".

**Comment by JamesH65** [comment]
Started this here https://github.com/raspberrypi/documentation/tree/JamesH65-omxplayer/usage/omxplayer

**Comment by bennuttall** [comment]
Can we put this in Raspbian as it's more documentation of a Raspbian application than usage which is supposed to be just getting started

**Comment by JamesH65** [comment]
Of course, still a work in progress, can go anywhere. I do think we may need to add some more top level categories at some point.

**Comment by JamesH65** [comment]
Any idea how I move the location of a file in a PR in the github UI?

**Comment by bennuttall** [comment]
Interestingly I've just found that you can...

Edit the file you want to move. Edit the filename to simply rename it:

![screenshot from 2018-08-31 14-18-12](https://user-images.githubusercontent.com/1609725/44914718-f5dd0580-ad28-11e8-803d-d72ebc990691.png)

Add `/something/` at the beginning to nest it within a directory:

![screenshot from 2018-08-31 14-22-52](https://user-images.githubusercontent.com/1609725/44914938-86b3e100-ad29-11e8-8a54-07ecb7d2eae5.png)

after you add the slash:

![screenshot from 2018-08-31 14-23-01](https://user-images.githubusercontent.com/1609725/44914954-8e738580-ad29-11e8-98df-0ff55bd10ce2.png)

Add `../` at the beginning and it actually drops the current directory from the path:

![screenshot from 2018-08-31 14-26-11](https://user-images.githubusercontent.com/1609725/44915056-e1e5d380-ad29-11e8-8900-bc61288abd46.png)

after you add the slash:

![screenshot from 2018-08-31 14-26-20](https://user-images.githubusercontent.com/1609725/44915061-e6aa8780-ad29-11e8-8a90-bc1fc0f5cccd.png)

Add the intended directory name to set the new location:

![screenshot from 2018-08-31 14-29-07](https://user-images.githubusercontent.com/1609725/44915198-45700100-ad2a-11e8-866a-8f20663e8205.png)

after you add the slash:

![screenshot from 2018-08-31 14-28-12](https://user-images.githubusercontent.com/1609725/44915132-1d809d80-ad2a-11e8-8d30-5795a056917b.png)

**Comment by JamesH65** [comment]
I knew I had seen it done, but hadn't realised you needed to be editing it to move it!

**Comment by JamesH65** [comment]
So it turns out there is already an OMXplayer page, which has almost exactly the same content as I produced here. I cannot figure out how I missed it....

https://www.raspberrypi.org/documentation/raspbian/applications/omxplayer.md

**Comment by bennuttall** [comment]
Oh... I wonder who wrote it... https://github.com/raspberrypi/documentation/commits/master/raspbian/applications/omxplayer.md

I think you need a holiday, James

**Comment by JamesH65** [comment]
After being on holiday with the family, I do need a holiday. Closing.
