### ISSUE TITLE
MicroSD card writes are extremely slow.

### ISSUE THREAD

**Issue by gooddosh** [raspberrypi/documentation#963]
I have a SanDisk Ultra 128GB microSDXC UHS-I Class 10 Card installed. The disk write speed appears to average 1.2 to 1.6 MB/s, which is excruciatingly slow.

**Comment by gooddosh** [comment]
Disregard earlier references to apt-get. It worked. It was just REALLY slow due to the write speed problem.

**Comment by bennuttall** [comment]
Please do not report Pi troubleshooting questions here. This is for reporting issues with the documentation contents. We provide forums for getting technical help: https://www.raspberrypi.org/forums/
