### ISSUE TITLE
config.txt - video: section 'hdmi timings' not rendered correctly

### ISSUE THREAD

**Issue by DirkUK** [raspberrypi/documentation#967]
See https://www.raspberrypi.org/documentation/configuration/config-txt/video.md section 'HDMI Timings'.
This is not rendered correctly. It looks as if this is interpreted as html; everything enclosed in '<>' is seen as an (invalid) html tag and removed. It makes the text unreadable and useless.

Source is at https://github.com/raspberrypi/documentation/blob/master/configuration/config-txt/video.md#hdmi_timings

**Comment by JamesH65** [comment]
Yes, aware of this but am on holiday, will sort when I get back. It's a
problem on converting github markdown to html.

**Comment by lurch** [comment]
@bennuttall I guess #965 should be closed then? :confused:
