### ISSUE TITLE
Audio config page need updating

### ISSUE THREAD

**Issue by chexbox** [raspberrypi/documentation#980]
You can no longer right-click on the speaker icon to change audio output.

**Comment by JamesH65** [comment]
Just tried this on the current release and it worked fine, got the option of Analog or HDMI come up. Sounds like something else is up with your system.

**Comment by JamesH65** [comment]
Closing as a Won't Fix. This means that although the issue is acknowledged, it is felt that no further action is likely. This may be down to a bad benefit vs cost analysis, or it may actually not be possible to fix.
