### ISSUE TITLE
Could probably do with some NFS docs

### ISSUE THREAD

**Issue by JamesH65** [raspberrypi/documentation#986]
How to connect to an NFS server and how to set up an NFS server on a Pi.

Might be there already but not found anything.

**Comment by bennuttall** [comment]
I did this recently on Ubuntu Server following their guide: https://help.ubuntu.com/community/SettingUpNFSHowTo

If I get chance I'll have a go on a Pi and write it up. But if you want to do it, go ahead.

**Comment by JamesH65** [comment]
Community effort started here https://github.com/raspberrypi/documentation/pull/1010

**Comment by aallan** [comment]
Looks like #1010 got merged. Close?

**Comment by JamesH65** [comment]
Good spot, closing.
