### ISSUE TITLE
CM descriptions for camera and display adapters need to state they are not interchangeable

### ISSUE THREAD

**Issue by 6by9** [raspberrypi/documentation#996]
From https://www.raspberrypi.org/forums/viewtopic.php?f=98&t=123896&start=25

RS CM dev kits are not coming with the display or camera adapters so people are trying to use the Pi Zero camera cable that looks identical. This doesn't work as the wiring is different between the camera and display.

CM camera pages ought to be updated to state that Pi Zero camera cables can be used in lieu of the camera adapter
CM display pages ought to be updated to state that the RPI-DISPLAY adapter (or equivalent) must be used.

(Farnell kits contain the adapters, and RS do sell them independently if people know they need them).

**Comment by JamesH65** [comment]
Closing this issue as questions answered/issue resolved.
