### ISSUE TITLE
net_tutorial.md under-specifies the files needed in the tftproot

### ISSUE THREAD

**Issue by zbrozek** [raspberrypi/documentation#997]
The documentation claims that only bootcode.bin and start.elf are required, but this is incorrect. When booting many more files are requested - some which exist and some which do not - but if you haven't copied everything you haven't satisfied the requirements.

The documentation should include the complete manifest of required files, or clearly state that all of the boot folder is required.

**Comment by JamesH65** [comment]
Can you provide a link to the documentation you believe is incorrect please?

**Comment by zbrozek** [comment]
Certainly!

https://www.raspberrypi.org/documentation/hardware/raspberrypi/bootmodes/net_tutorial.md

**Comment by JamesH65** [comment]
fixed by #999

**Comment by JamesH65** [comment]
Closing this issue as questions answered/issue resolved.
